ComixWall ISG Administration Interface: Spamassassin Class Reference
Spamassassin Class Reference
Public Member Functions
Spamassassin ()
GetVersion ()
Gets software version string.
Stop ()
Stops module process(es).
GetCurrentLocale ()
Gets current locale.
GetLocales ()
Gets locale files.
ChangeLocal ($locale)
Change local.cf link.
ParseLogLine ($logline, &$cols)
Log parser.
GetFileLineCount ($file, $re= '')
Gets line count of file.
GetLogs ($file, $end, $count, $re= '')
Gets lines in file.
GetLiveLogs ($file, $count, $re= '')
Gets logs for live logs pages.
Spamassassin ()
Public Attributes
$Name = 'spamassassin'
$User = 'root|_spamdaemon'
$NVPS = '\h'
$ConfFile = '/etc/mail/spamassassin/local.cf'
$LogFile = '/var/log/maillog'
$VersionCmd = 'unset LC_ALL; unset LANG; /usr/local/bin/spamd -V'
Have to unset LC_ALL and LANG, otherwise perl complains.
$PidFile = '/var/run/spamassassin.pid'
$StartCmd = 'unset LC_ALL; unset LANG; /usr/local/bin/spamd -L -d -x -u _spamdaemon -r /var/run/spamassassin.pid'
$Model = 'spamassassin'
$Layout = 'spamassassin'
Detailed Description
Definition at line 38 of file spamassassin.php.
Member Function Documentation
Spamassassin::Spamassassin ()
Definition at line 57 of file spamassassin.php.
References $TmpFile, ChangeLocal(), GetCurrentLocale(), GetLocales(), and Model.
    {
        global $TmpFile;
        parent::Model();
        $this->Proc= 'spamd';
        $this->StartCmd= "unset LC_ALL; unset LANG; /usr/local/bin/spamd -L -d -x -u _spamdaemon -r /var/run/spamassassin.pid > $TmpFile 2>&1 &";
        $this->Commands= array_merge(
            $this->Commands,
            array(
                'GetCurrentLocale'  => array(
                    'argv'  => array(),
                    'desc'  => _('Get current locale'),
                    ),
                'GetLocales'    => array(
                    'argv'  => array(),
                    'desc'  => _('Get locales'),
                    ),
                'ChangeLocal'   => array(
                    'argv'  => array(NAME),
                    'desc'  => _('Change spamassassin local'),
                    ),
                )
            );
    }
Spamassassin::GetVersion ()
Gets software version string.
Reimplemented from Model.
Definition at line 88 of file spamassassin.php.
References Model::RunShellCommand().
    {
        return $this->RunShellCommand($this->VersionCmd.' | /usr/bin/head -2');
    }
Spamassassin::Stop ()
Stops module process(es).
Tries PROC_STAT_TIMEOUT times.
Returns:
boolean TRUE if the process killed successfully
Todo:
Actually should stop retrying on some error conditions?
Reimplemented from Model.
Definition at line 93 of file spamassassin.php.
References Model::Kill().
    {
        return $this->Kill();
    }
Spamassassin::GetCurrentLocale ()
Gets current locale.
Definition at line 100 of file spamassassin.php.
Referenced by Spamassassin().
    {
        $localcf= $this->confDir.'/local.cf';
        if (is_link($localcf) && ($linkedfile= readlink($localcf))) {
            if (preg_match($this->re_LcSuffix, $linkedfile, $match)) {
                return $match[1];
            }
        }
        return FALSE;
    }
Spamassassin::GetLocales ()
Gets locale files.
Definition at line 114 of file spamassassin.php.
References $file, and Model::GetFiles().
Referenced by Spamassassin().
    {
        $files= $this->GetFiles($this->confDir.'/local-*.cf');
        $files= explode("\n", $files);
        $locales= array();
        foreach ($files as $file) {
            if (!is_dir($file) && !preg_match('/.*\.(bak|orig)$/', $file)) {
                if (preg_match($this->re_LcSuffix, $file, $match)) {
                    $locales[]= $match[1];
                }
            }
        }
        return implode("\n", $locales);
    }
Spamassassin::ChangeLocal ($ locale)
Change local.cf link.
Definition at line 132 of file spamassassin.php.
References Model::RunShellCommand().
Referenced by Spamassassin().
    {
        return $this->RunShellCommand("cd $this->confDir; /bin/ln -sf local-$locale.cf local.cf");
    }
Spamassassin::ParseLogLine ($ logline, &$ cols)
Log parser.
Parameters:
[in] $logline string Log line
[out] $cols array Parsed fields
Returns:
TRUE if log line is parsed
Reimplemented from Model.
Definition at line 137 of file spamassassin.php.
References Model::ParseSyslogLine().
Referenced by GetLiveLogs(), and GetLogs().
    {
        if ($this->ParseSyslogLine($logline, $cols)) {
            if (stripos($cols['Log'], 'clean message ') !== FALSE) {
                $cols['Ham']= 1;
            }
            else if (stripos($cols['Log'], 'identified spam ') !== FALSE) {
                $cols['Spam']= 1;
            }
            $re= '/^.* for (\S+):\S+ in (\d+\.\d+) seconds, (\d+) bytes\.$/';
            if (preg_match($re, $logline, $match)) {
                $cols['User']= $match[1];
                $cols['Seconds']= $match[2];
                $cols['Bytes']= $match[3];
            }
            return TRUE;
        }
        return FALSE;
    }
Spamassassin::GetFileLineCount ($ file, $ re = '')
Gets line count of file.
Parameters:
[in] $file string Log file pathname
[in] $re string Regexp to get count of a restricted result set
Returns:
int Line count
Warning:
Input redirection is necessary, otherwise wc adds file name to its output too
Reimplemented from Model.
Definition at line 158 of file spamassassin.php.
References Model::RunShellCommand().
    {
        $cmd= "/usr/bin/grep -a ' spamd\[' $file";
        if ($re !== '') {
            $re= escapeshellarg($re);
            $cmd.= " | /usr/bin/grep -a $re";
        }
        $cmd.= ' | /usr/bin/wc -l';
        // OpenBSD wc returns with leading blanks
        return trim($this->RunShellCommand($cmd));
    }
Spamassassin::GetLogs ($ file, $ end, $ count, $ re = '')
Gets lines in file.
Parameters:
[in] $file string Log file pathname
[in] $end int Head option, start line
[in] $count int Tail option, page line count
[in] $re string Regexp to restrict the result set
Returns:
serialized Log lines
Reimplemented from Model.
Definition at line 171 of file spamassassin.php.
References $logs, ParseLogLine(), and Model::RunShellCommand().
    {
        $cmd= "/usr/bin/grep -a ' spamd\[' $file";
        if ($re !== '') {
            $re= escapeshellarg($re);
            $cmd.= " | /usr/bin/grep -a $re";
        }
        $cmd.= " | /usr/bin/head -$end | /usr/bin/tail -$count";
        $lines= explode("\n", $this->RunShellCommand($cmd));
        $logs= array();
        foreach ($lines as $line) {
            unset($cols);
            if ($this->ParseLogLine($line, $cols)) {
                $logs[]= $cols;
            }
        }
        return serialize($logs);
    }
Spamassassin::GetLiveLogs ($ file, $ count, $ re = '')
Gets logs for live logs pages.
Used to extract lines in last section of the log file or of the lines grep'd.
Difference from the archives method is that this one always gets the tail of the log or grepped lines.
Parameters:
[in] $file string Log file
[in] $count int Tail lenght, page line count
[in] $re string Regexp to restrict the result set
Returns:
serialized Log lines
Reimplemented from Model.
Definition at line 192 of file spamassassin.php.
References $logs, ParseLogLine(), and Model::RunShellCommand().
    {
        $cmd= "/usr/bin/grep -a ' spamd\[' $file";
        if ($re !== '') {
            $re= escapeshellarg($re);
            $cmd.= " | /usr/bin/grep -a $re";
        }
        $cmd.= " | /usr/bin/tail -$count";
        $lines= explode("\n", $this->RunShellCommand($cmd));
        $logs= array();
        foreach ($lines as $line) {
            if ($this->ParseLogLine($line, $cols)) {
                $logs[]= $cols;
            }
        }
        return serialize($logs);
    }
Spamassassin::Spamassassin ()
Definition at line 44 of file include.php.
References _HELPBOX2(), _HELPWINDOW(), _TITLE2(), ConfHelpMsg, Config, and GraphHelpMsg.
    {
        $this->LogsHelpMsg= _HELPWINDOW('Detailed results of spam content scans are recorded by SpamAssassin, such as spam scores and their reasons.');
        $this->GraphHelpMsg= _HELPWINDOW('SpamAssassin is a perl process. These graphs display data from all perl processes.');
        $this->ConfHelpMsg= _HELPWINDOW('An important setting may be the rewrite header which is used on the subject line of an e-mail identified as spam. Note that spam identification is a guess based on statistical calculations, hence there may be false positives.');
        $this->Config = array(
            'rewrite_header Subject' => array(
                'title' => _TITLE2('Rewrite header'),
                'info' => _HELPBOX2('Add *****SPAM***** to the Subject header of spam e-mails'),
                ),
            'report_safe' => array(
                'title' => _TITLE2('Report safe'),
                'info' => _HELPBOX2('Save spam messages as a message/rfc822 MIME attachment instead of modifying the original message (0: off, 2: use text/plain instead)'),
                ),
            'trusted_networks' => array(
                'title' => _TITLE2('Trusted networks'),
                'info' => _HELPBOX2('Set which networks or hosts are considered \'trusted\' by your mail server (i.e. not spammers)'),
                ),
            'required_score' => array(
                'title' => _TITLE2('Required score'),
                'info' => _HELPBOX2('Set the threshold at which a message is considered spam (default: 5.0)'),
                ),
            'use_bayes' => array(
                'title' => _TITLE2('Use bayes'),
                'info' => _HELPBOX2('Use Bayesian classifier (default: 1)'),
                ),
            'bayes_auto_learn' => array(
                'title' => _TITLE2('Bayes auto learn'),
                'info' => _HELPBOX2('Bayesian classifier auto-learning (default: 1)'),
                ),
            'bayes_ignore_header X-Bogosity' => array(
                'title' => _TITLE2('X-Bogosity'),
                'info' => _HELPBOX2('Set headers which may provide inappropriate cues to the Bayesian classifier'),
                ),
            'bayes_ignore_header X-Spam-Flag' => array(
                'title' => _TITLE2('X-Spam-Flag'),
                ),
            'bayes_ignore_header X-Spam-Status' => array(
                'title' => _TITLE2('X-Spam-Status'),
                ),
        );
    }
Member Data Documentation
Spamassassin::$Name = 'spamassassin'
Reimplemented from Model.
Definition at line 40 of file spamassassin.php.
Spamassassin::$User = 'root|_spamdaemon'
Reimplemented from Model.
Definition at line 41 of file spamassassin.php.
Spamassassin::$NVPS = '\h'
Reimplemented from Model.
Definition at line 46 of file spamassassin.php.
Spamassassin::$ConfFile = '/etc/mail/spamassassin/local.cf'
Reimplemented from Model.
Definition at line 47 of file spamassassin.php.
Spamassassin::$LogFile = '/var/log/maillog'
Reimplemented from Model.
Definition at line 48 of file spamassassin.php.
Spamassassin::$VersionCmd = 'unset LC_ALL; unset LANG; /usr/local/bin/spamd -V'
Have to unset LC_ALL and LANG, otherwise perl complains.
Reimplemented from Model.
Definition at line 51 of file spamassassin.php.
Spamassassin::$PidFile = '/var/run/spamassassin.pid'
Reimplemented from Model.
Definition at line 53 of file spamassassin.php.
Spamassassin::$StartCmd = 'unset LC_ALL; unset LANG; /usr/local/bin/spamd -L -d -x -u _spamdaemon -r /var/run/spamassassin.pid'
Reimplemented from Model.
Definition at line 55 of file spamassassin.php.
Spamassassin::$Model = 'spamassassin'
Reimplemented from View.
Definition at line 41 of file include.php.
Spamassassin::$Layout = 'spamassassin'
Reimplemented from View.
Definition at line 42 of file include.php.
The documentation for this class was generated from the following files:
Model/spamassassin.php
View/spamassassin/include.php