ComixWall ISG Administration Interface: Pmacct Class Reference
Pmacct Class Reference
Public Member Functions
Pmacct ()
GetVersion ()
Gets software version string.
Start ()
Start module process(es).
SetIf ($if)
SetNet ($net)
Public Attributes
$Name = 'pmacctd'
$User = 'root'
$VersionCmd = '/usr/local/sbin/pmacctd -v 2>&1'
Detailed Description
Definition at line 42 of file pmacct.php.
Member Function Documentation
Pmacct::Pmacct ()
Definition at line 49 of file pmacct.php.
References $TmpFile, Model, SetIf(), and SetNet().
    {
        global $TmpFile;
        parent::Model();
        $this->Commands= array_merge(
            $this->Commands,
            array(
                'SetIf'=>   array(
                    'argv'  =>  array(NAME),
                    'desc'  =>  _('Set pmacct if'),
                    ),
                'SetNet'=>  array(
                    'argv'  =>  array(IPRANGE),
                    'desc'  =>  _('Set pmacct net'),
                    ),
                )
            );
    }
Pmacct::GetVersion ()
Gets software version string.
Reimplemented from Model.
Definition at line 71 of file pmacct.php.
References Model::RunShellCommand().
    {
        return $this->RunShellCommand($this->VersionCmd.' | /usr/bin/head -2 | /usr/bin/tail -1');
    }
Pmacct::Start ()
Start module process(es).
Tries PROC_STAT_TIMEOUT times.
Returns:
boolean TRUE if the process starts
Todo:
Actually should stop retying on some error conditions?
Todo:
Check $TmpFile for error messages, if so break out instead
Reimplemented from Model.
Definition at line 76 of file pmacct.php.
References $TmpFile, Model::GetFile(), and ViewError().
    {
        global $TmpFile;
        $this->StartCmd= "/usr/local/sbin/pmacctd -f /etc/pmacct/pmacctd-pnrg.conf > $TmpFile 2>&1 &";
        $retval_pnrg= parent::Start();
        $this->StartCmd= "/usr/local/sbin/pmacctd -f /etc/pmacct/pmacctd-protograph.conf > $TmpFile 2>&1 &";
        $retval_protograph= parent::Start();
        // Second Start() needs special treatment due to pmacct not reporting conf file in ps output
        if ($retval_protograph) {
            $errout= $this->GetFile($TmpFile, '');
            ViewError($errout);
        }
        return ($retval_pnrg & $retval_protograph) && ($errout === '');
    }
Pmacct::SetIf ($ if)
Definition at line 97 of file pmacct.php.
References $retval, and Model::ReplaceRegexp().
Referenced by Pmacct().
    {
        $re= '|^(\s*interface:\s*)(\w+\d+)(\s+)|ms';
        $retval=  $this->ReplaceRegexp('/etc/pmacct/pmacctd-pnrg.conf', $re, '${1}'.$if.'${3}');
        $retval&= $this->ReplaceRegexp('/etc/pmacct/pmacctd-protograph.conf', $re, '${1}'.$if.'${3}');
        return $retval;
    }
Pmacct::SetNet ($ net)
Definition at line 106 of file pmacct.php.
References $Re_Net, and $retval.
Referenced by Pmacct().
    {
        global $Re_Net;
        $re= "|(\s+src\s+net\s+)($Re_Net)(\s+)|ms";
        $retval=  $this->ReplaceRegexp('/etc/pmacct/pmacctd-pnrg.conf', $re, '${1}'.$net.'${3}');
        $re= "|(\s+dst\s+net\s+)($Re_Net)(\s+)|ms";
        $retval&= $this->ReplaceRegexp('/etc/pmacct/pmacctd-pnrg.conf', $re, '${1}'.$net.'${3}');
        return $retval;
    }
Member Data Documentation
Pmacct::$Name = 'pmacctd'
Reimplemented from Model.
Definition at line 44 of file pmacct.php.
Pmacct::$User = 'root'
Reimplemented from Model.
Definition at line 45 of file pmacct.php.
Pmacct::$VersionCmd = '/usr/local/sbin/pmacctd -v 2>&1'
Reimplemented from Model.
Definition at line 47 of file pmacct.php.
The documentation for this class was generated from the following file:
Model/pmacct.php