ComixWall ISG Administration Interface: Dansguardian Class Reference
Dansguardian Class Reference
Public Member Functions
Dansguardian ()
GetConfFile ($confname, $group)
Returns configuration file of the module.
SetConfig ($confname)
Sets configuration file based on config type provided.
GetAuthIpList ($list)
Returns the list of ips in exception or banned lists.
GetIps ($file)
Reads the list of IPs.
AddIp ($list, $ip)
DelIp ($list, $ip)
GetListFilePath ($list)
AddSiteList ($file, $site)
AddUrlList ($file, $url)
DisableExtMime ($group, $list, $type, $item)
DisableExt ($file, $ext)
EnableExtMime ($group, $list, $type, $item)
EnableExt ($file, $ext)
AddExt ($file, $ext, $cmt)
DelExt ($file, $ext)
DelSiteList ($file, $site)
DelUrlList ($file, $url)
GetCats ($file, $cat= '[^#\s]+', $subcat= '[^#\s]+')
Gets the list of DG categories and subcats.
GetFilterConfFilePath ($file, $name)
Reads DG configuration file pathname setting.
GetOffCats ($file, $cat= '[^#\s]+', $subcat= '[^#\s]+')
Gets the list off (commented) DG cats/subcats.
GetSiteList ($file, $site= '[^.#\s]+[^\s]*')
Checks if site exists or gets the list of sites.
GetUrlList ($file, $url= '[^.#\s]+[^\s]*')
Checks if url exists or gets the list of urls.
GetExts ($file)
Gets the list of extensions.
GetFuncCats ($func, $group, $list, $type)
Gets the list of enabled or disabled categories.
TurnOffCats ($group, $list, $type, $cat, $subcat)
TurnOnCats ($group, $list, $type, $cat, $subcat)
FuncTurnCats ($func, $group, $list, $type, $cat, $subcat)
Enables or disables the given category.
TurnOnCat ($file, $cat, $subcat= '[^#\s]+')
Turns on (uncomments) DG cat/subcat.
TurnOffCat ($file, $cat, $subcat= '[^#\s]+')
Turns off (comments out) DG cat/subcat.
GetList ($group, $list, $type)
GetExtMimeList ($group, $list, $type)
GetFuncList ($func, $group, $list, $type)
Gets the list of sites or urls.
DelSiteUrl ($group, $list, $type, $item)
AddSiteUrl ($group, $list, $type, $item)
FuncSiteUrl ($func, $group, $list, $type, $item)
Adds or deletes the given site or url.
DelExtMime ($group, $list, $type, $item)
AddExtMime ($group, $list, $type, $item, $comment)
GetEnabledCats ($group, $list, $type)
GetDisabledCats ($group, $list, $type)
GetGroupIpList ($group)
Gets ips listed in group.
GetGrpIps ($file, $group= '[^#\s]+')
Gets the list of group IPs.
GetIpgroupsFilePath ()
Gets the ip.conf file pathname from master file.
SetIpFilterGrp ($group, $ip)
Adds IP and filter group pair.
DelIpFilterGrp ($ip, $group= '[^#\s]+')
Deletes IP and filter group pair.
GetGroupFile ($group, $list, $type)
GetMetaFile ($group, $list)
Returns meta file for the given group or list.
GetGroupCount ()
Gets number of groups.
GroupExists ($group)
Checks if the meta file exists for the given group.
CreateNewGroup ($group)
Creates a new web filter group.
SetTemplateIps ($ip)
Updates template files with the given ip.
Dansguardian ()
SetSessionFilterGroup ()
Sets the DG filter group for the current session.
PrintFilterGroupForm ()
Displays an edit box and a botton to change current group.
Public Attributes
$Name = 'dansguardian'
$User = 'root|_dansguardian'
$NVPS = '='
$ConfFile = '/etc/dansguardian/dansguardian.conf'
$LogFile = '/var/log/dansguardian/dansguardian.log'
$VersionCmd = '/usr/local/sbin/dansguardian -v'
$PidFile = '/var/run/dansguardian.pid'
$Model = 'dansguardian'
$Layout = 'dansguardian'
Protected Attributes
$confDir = '/etc/dansguardian/'
Detailed Description
Definition at line 38 of file dansguardian.php.
Member Function Documentation
Dansguardian::Dansguardian ()
Todo:
EXT|MIME accepts ext for mime or visa versa, fix this
Is there any pattern or size for comment, 5th param?
Definition at line 61 of file dansguardian.php.
References $Re_Ip, $TmpFile, AddExtMime(), AddIp(), AddSiteList(), AddSiteUrl(), AddUrlList(), CreateNewGroup(), DelExtMime(), DelIp(), DelIpFilterGrp(), DelSiteList(), DelSiteUrl(), DelUrlList(), DisableExtMime(), EnableExtMime(), GetAuthIpList(), GetDisabledCats(), GetEnabledCats(), GetExtMimeList(), GetGroupCount(), GetGroupIpList(), GetList(), GetSiteList(), GetUrlList(), GroupExists(), Model, SetIpFilterGrp(), SetTemplateIps(), TurnOffCats(), and TurnOnCats().
    {
        global $TmpFile, $Re_Ip;
        parent::Model();
        $this->StartCmd= "/usr/local/sbin/dansguardian > $TmpFile 2>&1 &";
        $this->re_DgNet= "$Re_Ip\/$Re_Ip";
        $this->re_DgRange= "$Re_Ip-$Re_Ip";
        $this->ipLists= array(
                'exceptionlist' => 'exceptioniplist',
                'bannedlist'    => 'bannediplist',
            );
        $this->listConfig= array(
            'sites'         => array(
                'exception'         => 'exceptionsitelist',
                'gray'              => 'greysitelist',
                'banned'            => 'bannedsitelist',
                'GetFunc'           => 'GetSiteList',
                'DelFunc'           => 'DelSiteList',
                'AddFunc'           => 'AddSiteList',
                ),
            'urls'          =>  array(
                'exception'         => 'exceptionurllist',
                'gray'              => 'greyurllist',
                'banned'            => 'bannedurllist',
                'GetFunc'           => 'GetUrlList',
                'DelFunc'           => 'DelUrlList',
                'AddFunc'           => 'AddUrlList',
                ),
            'exts'          =>  array(
                'exception'         => 'exceptionextensionlist',
                'gray'              => 'greyextensionlist',
                'banned'            => 'bannedextensionlist',
                ),
            'mimes'         =>  array(
                'exception'         => 'exceptionmimetypelist',
                'gray'              => 'greymimetypelist',
                'banned'            => 'bannedmimetypelist',
                ),
            'dm_exts'       =>  array(
                'MetaConfigFile'    => $this->confDir.'downloadmanagers/fancy.conf',
                'exception'         => 'managedextensionlist',
                ),
            'dm_mimes'      =>  array(
                'MetaConfigFile'    => $this->confDir.'downloadmanagers/fancy.conf',
                'exception'         => 'managedmimetypelist',
                ),
            'virus_sites'   =>  array(
                'MetaConfigFile'    => $this->confDir.'contentscanners/clamdscan.conf',
                'exception'         => 'exceptionvirussitelist',
                'GetFunc'           => 'GetSiteList',
                'DelFunc'           => 'DelSiteList',
                'AddFunc'           => 'AddSiteList',
                ),
            'virus_urls'    =>  array(
                'MetaConfigFile'    => $this->confDir.'contentscanners/clamdscan.conf',
                'exception'         => 'exceptionvirusurllist',
                'GetFunc'           => 'GetUrlList',
                'DelFunc'           => 'DelUrlList',
                'AddFunc'           => 'AddUrlList',
                ),
            'virus_exts'    =>  array(
                'MetaConfigFile'    => $this->confDir.'contentscanners/clamdscan.conf',
                'exception'         => 'exceptionvirusextensionlist',
                ),
            'virus_mimes'   =>  array(
                'MetaConfigFile'    => $this->confDir.'contentscanners/clamdscan.conf',
                'exception'         => 'exceptionvirusmimetypelist',
                ),
            // Used by Cats only
            'phrases'       =>  array(
                'exception'         => 'exceptionphraselist',
                'banned'            => 'bannedphraselist',
                'weighted'          => 'weightedphraselist',
                ),
            );
        $this->Commands= array_merge(
            $this->Commands,
            array(
                'DelIpFilterGrp'=>  array(
                    'argv'  =>  array(IPADR|DGIPRANGE),
                    'desc'  =>  _('Delete filter group IP'),
                    ),
                'SetIpFilterGrp'=>  array(
                    'argv'  =>  array(NUM, IPADR|DGIPRANGE),
                    'desc'  =>  _('Add filter group IP'),
                    ),
                'DelIp'     =>  array(
                    'argv'  =>  array(NAME, IPADR|DGIPRANGE),
                    'desc'  =>  _('Delete IP'),
                    ),
                'AddIp'     =>  array(
                    'argv'  =>  array(NAME, IPADR|DGIPRANGE),
                    'desc'  =>  _('Add IP'),
                    ),
                'CreateNewGroup'=>  array(
                    'argv'  =>  array(NUM),
                    'desc'  =>  _('Create new group'),
                    ),
                'GetGroupCount'=>   array(
                    'argv'  =>  array(),
                    'desc'  =>  _('Get group count'),
                    ),
                'GetGroupIpList'=>  array(
                    'argv'  =>  array(NUM),
                    'desc'  =>  _('Get group ip list'),
                    ),
                'GetAuthIpList'=>   array(
                    'argv'  =>  array(NAME),
                    'desc'  =>  _('Get auth ip list'),
                    ),
                'GetList'       =>  array(
                    'argv'  =>  array(NUM, NAME, NAME),
                    'desc'  =>  _('Get list'),
                    ),
                'GetExtMimeList'=>  array(
                    'argv'  =>  array(NUM, NAME, NAME),
                    'desc'  =>  _('Get ext/mime list'),
                    ),
                'DelSiteUrl'    =>  array(
                    'argv'  =>  array(NUM, NAME, NAME, URL),
                    'desc'  =>  _('Delete list item'),
                    ),
                'AddSiteUrl'    =>  array(
                    'argv'  =>  array(NUM, NAME, NAME, URL),
                    'desc'  =>  _('Add list item'),
                    ),
                'DisableExtMime'    =>  array(
                    'argv'  =>  array(NUM, NAME, NAME, EXT|MIME),
                    'desc'  =>  _('Disable ext/mime'),
                    ),
                'EnableExtMime' =>  array(
                    'argv'  =>  array(NUM, NAME, NAME, EXT|MIME),
                    'desc'  =>  _('Enable ext/mime'),
                    ),
                'DelExtMime'    =>  array(
                    'argv'  =>  array(NUM, NAME, NAME, EXT|MIME),
                    'desc'  =>  _('Delete ext/mime'),
                    ),
                'AddExtMime'    =>  array(
                    'argv'  =>  array(NUM, NAME, NAME, EXT|MIME, STR),
                    'desc'  =>  _('Add ext/mime'),
                    ),
                'GetEnabledCats'=>  array(
                    'argv'  =>  array(NUM, NAME, NAME),
                    'desc'  =>  _('Get active cats'),
                    ),
                'GetDisabledCats'=> array(
                    'argv'  =>  array(NUM, NAME, NAME),
                    'desc'  =>  _('Get inactive cats'),
                    ),
                'TurnOnCats'    =>  array(
                    'argv'  =>  array(NUM, NAME, NAME, NAME, NAME),
                    'desc'  =>  _('Turn on cats'),
                    ),
                'TurnOffCats'   =>  array(
                    'argv'  =>  array(NUM, NAME, NAME, NAME, NAME),
                    'desc'  =>  _('Turn off cats'),
                    ),
                'GroupExists'   =>  array(
                    'argv'  =>  array(NUM),
                    'desc'  =>  _('Group exists'),
                    ),
                'SetTemplateIps'    =>  array(
                    'argv'  =>  array(IPADR),
                    'desc'  =>  _('Set template ips'),
                    ),
                )
            );
    }
Dansguardian::GetConfFile ($ conf, $ group)
Returns configuration file of the module.
Certain modules have configuration divided into multiple pages/files, hence they override this method.
Parameters:
[in] $conf string Config type
[in] $group int Dansguardian group
Returns:
Config file pathname
Reimplemented from Model.
Definition at line 270 of file dansguardian.php.
References $file, Config, and GetGroupFile().
    {
        if ($confname === 'GeneraldownloadsConfig') {
            $file= $this->confDir.'downloadmanagers/fancy.conf';
        }
        else if ($confname == 'blanketConfig') {
            $file= $this->GetGroupFile($group, 'sites', 'banned');
        }
        else if (preg_match('/^General.*Config$/', $confname)) {
            $file= $this->ConfFile;
        }
        else {
            $file= $this->confDir.'dansguardianf'.$group.'.conf';
        }
        return $file;
    }
Dansguardian::SetConfig ($ confname)
Sets configuration file based on config type provided.
Certain modules have configuration divided into multiple pages/files, hence they override this method.
Parameters:
[in] $confname string Config type
Reimplemented from Model.
Definition at line 287 of file dansguardian.php.
References $basicConfig, $blanketConfig, $bypassConfig, $emailConfig, $GeneraladvancedConfig, $GeneralbasicConfig, $GeneraldownloadsConfig, $GeneralfilterConfig, $GenerallogsConfig, $GeneralscanConfig, $scanConfig, and Config.
    {
        global $GeneralbasicConfig, $GeneralfilterConfig, $GeneralscanConfig, $GenerallogsConfig, $GeneraldownloadsConfig, $GeneraladvancedConfig,
            $blanketConfig, $basicConfig, $scanConfig, $bypassConfig, $emailConfig;
        if ($confname !== '') {
            $this->Config= ${$confname};
        }
    }
Dansguardian::GetAuthIpList ($ list)
Returns the list of ips in exception or banned lists.
Definition at line 299 of file dansguardian.php.
References GetIps(), and GetListFilePath().
Referenced by Dansguardian().
    {
        if ($filepath= $this->GetListFilePath($list)) {
            return $this->GetIps($filepath);
        }
        return FALSE;
    }
Dansguardian::GetIps ($ file)
Reads the list of IPs.
Parameters:
[in] $file Config file pathname.
Returns:
List of IPs.
Definition at line 312 of file dansguardian.php.
References $file, $Re_Ip, and Model::SearchFileAll().
Referenced by GetAuthIpList().
    {
        global $Re_Ip;
        return $this->SearchFileAll($file, "/^\h*($Re_Ip|$this->re_DgNet|$this->re_DgRange)\b\h*(|$this->COMC.*)$/m");
    }
Dansguardian::AddIp ($ list, $ ip)
Definition at line 319 of file dansguardian.php.
References Model::AppendToFile(), DelIp(), and GetListFilePath().
Referenced by Dansguardian().
    {
        if ($filepath= $this->GetListFilePath($list)) {
            $this->DelIp($list, $ip);
            return $this->AppendToFile($filepath, $ip);
        }
        return FALSE;
    }
Dansguardian::DelIp ($ list, $ ip)
Definition at line 328 of file dansguardian.php.
References Escape(), GetListFilePath(), and Model::ReplaceRegexp().
Referenced by AddIp(), and Dansguardian().
    {
        if ($filepath= $this->GetListFilePath($list)) {
            $ip= Escape($ip, '/.');
            return $this->ReplaceRegexp($filepath, "/^(\h*$ip\b.*(\s|))/m", '');
        }
        return FALSE;
    }
Dansguardian::GetListFilePath ($ list)
Definition at line 337 of file dansguardian.php.
References GetFilterConfFilePath(), and ViewError().
Referenced by AddIp(), DelIp(), and GetAuthIpList().
    {
        if ($filepath= $this->GetFilterConfFilePath($this->confDir.'dansguardian.conf', $this->ipLists[$list])) {
            return $filepath;
        }
        else {
            ViewError(_('Cannot read config').": $list");
        }
        return FALSE;
    }
Dansguardian::AddSiteList ($ file, $ site)
Definition at line 348 of file dansguardian.php.
References $file, Model::AppendToFile(), and DelSiteList().
Referenced by Dansguardian().
    {
        $this->DelSiteList($file, $site);
        return $this->AppendToFile($file, $site);
    }
Dansguardian::AddUrlList ($ file, $ url)
Definition at line 354 of file dansguardian.php.
References $file, Model::AppendToFile(), and DelUrlList().
Referenced by Dansguardian().
    {
        $this->DelUrlList($file, $url);
        return $this->AppendToFile($file, $url);
    }
Dansguardian::DisableExtMime ($ group, $ list, $ type, $ item)
Definition at line 360 of file dansguardian.php.
References DisableExt(), and GetGroupFile().
Referenced by Dansguardian().
    {
        if (($groupfile= $this->GetGroupFile($group, $list, $type)) !== FALSE) {
            return $this->DisableExt($groupfile, $item);
        }
        return FALSE;
    }
Dansguardian::DisableExt ($ file, $ ext)
Definition at line 368 of file dansguardian.php.
References $file, Escape(), and Model::ReplaceRegexp().
Referenced by DisableExtMime().
    {
        $ext= Escape($ext, './');
        return $this->ReplaceRegexp($file, "/^(\h*$ext(\h*$this->COMC.*|\h*))$/m", $this->COMC.'${1}');
    }
Dansguardian::EnableExtMime ($ group, $ list, $ type, $ item)
Definition at line 374 of file dansguardian.php.
Referenced by Dansguardian().
    {
        if (($groupfile= $this->GetGroupFile($group, $list, $type)) !== FALSE) {
            return $this->EnableExt($groupfile, $item);
        }
        return FALSE;
    }
Dansguardian::EnableExt ($ file, $ ext)
Definition at line 382 of file dansguardian.php.
References $file, and Escape().
    {
        $ext= Escape($ext, './');
        return $this->ReplaceRegexp($file, "/^\h*$this->COMC(\h*$ext(\h*$this->COMC.*|\h*))$/m", '${1}');
    }
Dansguardian::AddExt ($ file, $ ext, $ cmt)
Definition at line 388 of file dansguardian.php.
References $file.
    {
        $this->DelExt($file, $ext);
        return $this->AppendToFile($file, "$ext $this->COMC $cmt");
    }
Dansguardian::DelExt ($ file, $ ext)
Definition at line 394 of file dansguardian.php.
References $file, and Escape().
    {
        // Both extensions and mime types are deleted by this method
        $ext= Escape($ext, './');
        return $this->ReplaceRegexp($file, "/^(\h*($this->COMC\h*|)$ext\b.*(\s|))/m", '');
    }
Dansguardian::DelSiteList ($ file, $ site)
Definition at line 401 of file dansguardian.php.
References $file, and Escape().
Referenced by AddSiteList(), and Dansguardian().
    {
        $site= Escape($site, '/.');
        return $this->ReplaceRegexp($file, "/^(\h*$site\b.*(\s|))/m", '');
    }
Dansguardian::DelUrlList ($ file, $ url)
Definition at line 407 of file dansguardian.php.
References $file, and Escape().
Referenced by AddUrlList(), and Dansguardian().
    {
        $url= Escape($url, '/.');
        return $this->ReplaceRegexp($file, "/^(\h*$url\b.*(\s|))/m", '');
    }
Dansguardian::GetCats ($ file, $ cat = '[^#\s]+', $ subcat = '[^#\s]+')
Gets the list of DG categories and subcats.
Returns a list of all cats or subcats if those args are not provided.
Parameters:
[in] $file Config file pathname.
[in] $cat Category to get. Assumes all categories if not provided.
[in] $subcat SubCategory to get. Assumes all subcats if not provided.
Returns:
List of cats/subcats.
Definition at line 422 of file dansguardian.php.
References $file.
    {
        return $this->SearchFileAll($file, "/^\h*\.Include.*lists\/($cat\/$subcat)>.*$/m");
    }
Dansguardian::GetFilterConfFilePath ($ file, $ name)
Reads DG configuration file pathname setting.
Parameters:
[in] $file Config file pathname.
[in] $name Name of the NVP.
Returns:
Value of the setting, file pathname.
Definition at line 433 of file dansguardian.php.
References $file.
Referenced by GetListFilePath().
    {
        return $this->GetNVP($file, $name, "'");
    }
Dansguardian::GetOffCats ($ file, $ cat = '[^#\s]+', $ subcat = '[^#\s]+')
Gets the list off (commented) DG cats/subcats.
Parameters:
[in] $file Config file pathname.
[in] $cat Category to get. Assumes all categories if not provided.
[in] $subcat SubCategory to get. Assumes all subcats if not provided.
Returns:
List of off cats/subcats.
Definition at line 445 of file dansguardian.php.
References $file.
    {
        return $this->SearchFileAll($file, "/^\h*$this->COMC\h*\.Include.*lists\/($cat\/$subcat)>.*$/m");
    }
Dansguardian::GetSiteList ($ file, $ site = '[^.#\s]+[^\s]*')
Checks if site exists or gets the list of sites.
Parameters:
[in] $file Config file pathname.
[in] $site Site to get. Assumes all sites if not provided.
Returns:
Site name (i.e. site exits) or list of sites.
Definition at line 456 of file dansguardian.php.
References $file, and Escape().
Referenced by Dansguardian().
    {
        $site= Escape($site, '/.');
        return $this->SearchFileAll($file, "/^\h*($site)\b.*\v*$/m");
    }
Dansguardian::GetUrlList ($ file, $ url = '[^.#\s]+[^\s]*')
Checks if url exists or gets the list of urls.
Definition at line 464 of file dansguardian.php.
References $file, and Escape().
Referenced by Dansguardian().
    {
        $url= Escape($url, '/.');
        return $this->SearchFileAll($file, "/^\h*($url)\b.*\v*$/m");
    }
Dansguardian::GetExts ($ file)
Gets the list of extensions.
Parameters:
[in] $file Config file pathname.
Returns:
List of extensions.
Definition at line 475 of file dansguardian.php.
References $file, and $result.
    {
        $re_ext= '\.[a-z0-9A-Z][a-z0-9A-Z_.]{0,10}';
        $re_mime= '[a-zA-Z][a-z0-9A-Z_-]{0,20}\/[a-z0-9A-Z_.-]{0,20}';
        $result= array();
        $contents= file_get_contents($file);
        $re= "($re_ext|$re_mime)\b\h*(|$this->COMC.*)";
        if (preg_match_all("/^\h*($re)$/m", $contents, $match)) {
            $output= array_values($match[1]);
            foreach ($output as $line) {
                if (preg_match("/^$re$/", $line, $match)) {
                    $result[$match[1]]= array(
                        'Comment'   => $match[2],
                        'Enabled'   => TRUE,
                    );
                }
            }
        }
        if (preg_match_all("/^\h*$this->COMC\h*($re)$/m", $contents, $match)) {
            $output= array_values($match[1]);
            foreach ($output as $line) {
                if (preg_match("/^$re$/", $line, $match)) {
                    $result[$match[1]]= array(
                        'Comment'   => $match[2],
                        'Enabled'   => FALSE,
                    );
                }
            }
        }
        return serialize($result);
    }
Dansguardian::GetFuncCats ($ func, $ group, $ list, $ type)
Gets the list of enabled or disabled categories.
Definition at line 513 of file dansguardian.php.
    {
        if (($groupfile= $this->GetGroupFile($group, $list, $type)) !== FALSE) {
            if (($output= $this->$func($groupfile)) !== FALSE) {
                return $output;
            }
            else {
                return '';
            }
        }
        return FALSE;
    }
Dansguardian::TurnOffCats ($ group, $ list, $ type, $ cat, $ subcat)
Definition at line 526 of file dansguardian.php.
Referenced by Dansguardian().
    {
        return $this->FuncTurnCats('TurnOffCat', $group, $list, $type, $cat, $subcat);
    }
Dansguardian::TurnOnCats ($ group, $ list, $ type, $ cat, $ subcat)
Definition at line 531 of file dansguardian.php.
Referenced by Dansguardian().
    {
        return $this->FuncTurnCats('TurnOnCat', $group, $list, $type, $cat, $subcat);
    }
Dansguardian::FuncTurnCats ($ func, $ group, $ list, $ type, $ cat, $ subcat)
Enables or disables the given category.
Definition at line 538 of file dansguardian.php.
    {
        if (($groupfile= $this->GetGroupFile($group, $list, $type)) !== FALSE) {
            if (($output= $this->$func($groupfile, $cat, $subcat)) !== FALSE) {
                return $output;
            }
            else {
                return '';
            }
        }
        return FALSE;
    }
Dansguardian::TurnOnCat ($ file, $ cat, $ subcat = '[^#\s]+')
Turns on (uncomments) DG cat/subcat.
Parameters:
[in] $file Config file pathname.
[in] $cat Category.
[in] $subcat SubCategory. Assumes all subcats if not provided.
Todo:
No need to send CAT and SUBCAT separately, escape slashes in PHP and send
Definition at line 557 of file dansguardian.php.
References $file.
    {
        return $this->ReplaceRegexp($file, "/^\h*$this->COMC(\s*\.Include.*lists\/$cat\/$subcat>.*)$/m", '${1}');
    }
Dansguardian::TurnOffCat ($ file, $ cat, $ subcat = '[^#\s]+')
Turns off (comments out) DG cat/subcat.
Parameters:
[in] $file Config file pathname.
[in] $cat Category.
[in] $subcat SubCategory. Assumes all subcats if not provided.
Todo:
No need to send CAT and SUBCAT separately, escape slashes in View and send here
Definition at line 569 of file dansguardian.php.
References $file.
    {
        return $this->ReplaceRegexp($file, "/^(\h*\.Include.*lists\/$cat\/$subcat>.*)$/m", $this->COMC.'${1}');
    }
Dansguardian::GetList ($ group, $ list, $ type)
Definition at line 575 of file dansguardian.php.
Referenced by Dansguardian().
    {
        return $this->GetFuncList($this->listConfig[$list]['GetFunc'], $group, $list, $type);
    }
Dansguardian::GetExtMimeList ($ group, $ list, $ type)
Definition at line 580 of file dansguardian.php.
Referenced by Dansguardian().
    {
        return $this->GetFuncList('GetExts', $group, $list, $type);
    }
Dansguardian::GetFuncList ($ func, $ group, $ list, $ type)
Gets the list of sites or urls.
Definition at line 587 of file dansguardian.php.
    {
        if (($groupfile= $this->GetGroupFile($group, $list, $type)) !== FALSE) {
            if (($output= $this->$func($groupfile)) !== FALSE) {
                return $output;
            }
            else {
                return '';
            }
        }
        return FALSE;
    }
Dansguardian::DelSiteUrl ($ group, $ list, $ type, $ item)
Definition at line 600 of file dansguardian.php.
Referenced by Dansguardian().
    {
        return $this->FuncSiteUrl($this->listConfig[$list]['DelFunc'], $group, $list, $type, $item);
    }
Dansguardian::AddSiteUrl ($ group, $ list, $ type, $ item)
Definition at line 605 of file dansguardian.php.
Referenced by Dansguardian().
    {
        return $this->FuncSiteUrl($this->listConfig[$list]['AddFunc'], $group, $list, $type, $item);
    }
Dansguardian::FuncSiteUrl ($ func, $ group, $ list, $ type, $ item)
Adds or deletes the given site or url.
Definition at line 612 of file dansguardian.php.
    {
        if (($groupfile= $this->GetGroupFile($group, $list, $type)) !== FALSE) {
            return $this->$func($groupfile, $item);
        }
        return FALSE;
    }
Dansguardian::DelExtMime ($ group, $ list, $ type, $ item)
Definition at line 620 of file dansguardian.php.
Referenced by Dansguardian().
    {
        if (($groupfile= $this->GetGroupFile($group, $list, $type)) !== FALSE) {
            return $this->DelExt($groupfile, $item);
        }
        return FALSE;
    }
Dansguardian::AddExtMime ($ group, $ list, $ type, $ item, $ comment)
Definition at line 628 of file dansguardian.php.
Referenced by Dansguardian().
    {
        if (($groupfile= $this->GetGroupFile($group, $list, $type)) !== FALSE) {
            return $this->AddExt($groupfile, $item, $comment);
        }
        return FALSE;
    }
Dansguardian::GetEnabledCats ($ group, $ list, $ type)
Definition at line 636 of file dansguardian.php.
Referenced by Dansguardian().
    {
        return $this->GetFuncCats('GetCats', $group, $list, $type);
    }
Dansguardian::GetDisabledCats ($ group, $ list, $ type)
Definition at line 641 of file dansguardian.php.
Referenced by Dansguardian().
    {
        return $this->GetFuncCats('GetOffCats', $group, $list, $type);
    }
Dansguardian::GetGroupIpList ($ group)
Gets ips listed in group.
Definition at line 648 of file dansguardian.php.
Referenced by Dansguardian().
    {
        if ($filepath= $this->GetIpgroupsFilePath()) {
            return $this->GetGrpIps($filepath, $group);
        }
        return FALSE;
    }
Dansguardian::GetGrpIps ($ file, $ group = '[^#\s]+')
Gets the list of group IPs.
Parameters:
[in] $file Config file pathname.
[in] $group DG group.
Returns:
List of IPs.
Definition at line 662 of file dansguardian.php.
References $file, and $Re_Ip.
    {
        global $Re_Ip;
        return $this->SearchFileAll($file, "/^\h*($Re_Ip|$this->re_DgNet|$this->re_DgRange)\h*$this->NVPS\h*filter$group\b\h*(|$this->COMC.*)$/m");
    }
Dansguardian::GetIpgroupsFilePath ()
Gets the ip.conf file pathname from master file.
Definition at line 671 of file dansguardian.php.
References ViewError().
    {
        if ($conffile= $this->GetFilterConfFilePath($this->confDir.'dansguardian.conf', 'authplugin')) {
            if ($filepath= $this->GetFilterConfFilePath($conffile, 'ipgroups')) {
                return $filepath;
            }
            else {
                ViewError(_('Cannot read config').': ipgroups');
            }
        }
        else {
            ViewError(_('Cannot read config').': authplugin');
        }
        return FALSE;
    }
Dansguardian::SetIpFilterGrp ($ group, $ ip)
Adds IP and filter group pair.
Parameters:
[in] $group Group to add IP to.
[in] $ip IP to add.
Todo:
Arg order differ from DelIpFilterGrp().
Definition at line 693 of file dansguardian.php.
References $file.
Referenced by Dansguardian().
    {
        if ($file= $this->GetIpgroupsFilePath()) {
            $this->DelIpFilterGrp($ip, $group);
            $this->DelIpFilterGrp($ip, '.*');
            return $this->AppendToFile($file, "$ip = filter$group");
        }
        return FALSE;
    }
Dansguardian::DelIpFilterGrp ($ ip, $ group = '[^#\s]+')
Deletes IP and filter group pair.
Parameters:
[in] $ip IP to delete.
[in] $group Group to delete IP from.
Definition at line 708 of file dansguardian.php.
References $file, and Escape().
Referenced by Dansguardian().
    {
        if ($file= $this->GetIpgroupsFilePath()) {
            $ip= Escape($ip, '/.');
            return $this->ReplaceRegexp($file, "/^(\h*$ip\b\h*$this->NVPS\h*filter$group\b\h*.*(\s|))/m", '');
        }
        return FALSE;
    }
Dansguardian::GetGroupFile ($ group, $ list, $ type)
Definition at line 717 of file dansguardian.php.
References $filename, and ViewError().
Referenced by DisableExtMime(), and GetConfFile().
    {
        $metafile= $this->GetMetaFile($group, $list);
        $filename= $this->listConfig[$list][$type];
        if (($groupfile= $this->GetFilterConfFilePath($metafile, $filename)) !== FALSE) {
            return $groupfile;
        }
        ViewError(_('Cannot find group configuration file').": $type $list");
        return FALSE;
    }
Dansguardian::GetMetaFile ($ group, $ list)
Returns meta file for the given group or list.
Dansguardian configuration is divided into many files, both group meta files and lists for groups.
Parameters:
[in] $group int Group
[in] $list string List name used as array index: sites, ext, etc.
Definition at line 737 of file dansguardian.php.
    {
        if (isset($this->listConfig[$list]['MetaConfigFile'])) {
            $metafile= $this->listConfig[$list]['MetaConfigFile'];
        }
        else {
            $metafile= $this->confDir.'dansguardianf'.$group.'.conf';
        }
        return $metafile;
    }
Dansguardian::GetGroupCount ()
Gets number of groups.
Definition at line 750 of file dansguardian.php.
Referenced by Dansguardian().
    {
        return $this->GetNVP($this->confDir.'dansguardian.conf', 'filtergroups');
    }
Dansguardian::GroupExists ($ group)
Checks if the meta file exists for the given group.
Definition at line 757 of file dansguardian.php.
Referenced by Dansguardian(), and SetSessionFilterGroup().
    {
        return file_exists($this->confDir.'dansguardianf'.$group.'.conf');
    }
Dansguardian::CreateNewGroup ($ group)
Creates a new web filter group.
Creates a new web filter group based on the active group for the current session.
Makes a copy of some of the configuration files listed in $filenames array. Missing files cause warnings, but are not fatal, so that restricted and privileged groups can be copied too.
Parameters:
[in] $group int Group to copy
Definition at line 773 of file dansguardian.php.
References $result, $retval, cwc_syslog(), and ViewError().
Referenced by Dansguardian().
    {
        $filenames= array(
            'bannedphraselist',
            'weightedphraselist',
            'exceptionphraselist',
            'bannedsitelist',
            'greysitelist',
            'exceptionsitelist',
            'bannedurllist',
            'greyurllist',
            'exceptionurllist',
            //'exceptionregexpurllist',
            //'bannedregexpurllist',
            //'picsfile',
            //'contentregexplist',
            //'urlregexplist',
            'bannedextensionlist',
            'bannedmimetypelist',
            'exceptionfilesitelist',
            'exceptionfileurllist',
            //'headerregexplist',
            //'bannedregexpheaderlist'
            );
        $result= TRUE;
        $fatal= FALSE;
        $info= "GetNVP: $this->ConfFile: filtergroups";
        if (($output= $this->GetNVP($this->ConfFile, 'filtergroups')) !== FALSE) {
            ViewError(_('SUCCESS').": $info");
            cwc_syslog(LOG_NOTICE, __FILE__, __FUNCTION__, __LINE__, "SUCCESS: $info");
            $newgroup= $output + 1;
            $conffile= $this->confDir."dansguardianf$group.conf";
            $newconffile= $this->confDir."dansguardianf$newgroup.conf";
            $info= 'File exists check: '.$newconffile;
            if (!file_exists($newconffile)) {
                ViewError(_('SUCCESS').": $info");
                cwc_syslog(LOG_NOTICE, __FILE__, __FUNCTION__, __LINE__, "SUCCESS: $info");
                $info= "File copy: $conffile $newconffile";
                exec("/bin/cp -p $conffile $newconffile 2>&1", $output, $retval);
                if ($retval === 0) {
                    ViewError(_('SUCCESS').": $info");
                    cwc_syslog(LOG_NOTICE, __FILE__, __FUNCTION__, __LINE__, "SUCCESS: $info");
                    foreach ($filenames as $Name) {
                        $info= "GetNVP: $conffile: $Name";
                        if (($output= $this->GetNVP($conffile, $Name)) !== FALSE) {
                            ViewError(_('SUCCESS').": $info");
                            cwc_syslog(LOG_NOTICE, __FILE__, __FUNCTION__, __LINE__, "SUCCESS: $info");
                            $groupfile= rtrim(trim($output, "'"), $group);
                            $newgroupfile= $groupfile.$newgroup;
                            $info= "File exists check: $newgroupfile";
                            if (!file_exists($newgroupfile)) {
                                ViewError(_('SUCCESS').": $info");
                                cwc_syslog(LOG_NOTICE, __FILE__, __FUNCTION__, __LINE__, "SUCCESS: $info");
                                $info= "File copy: $groupfile $newgroupfile";
                                exec("/bin/cp -p $groupfile $newgroupfile 2>&1", $output, $retval);
                                if ($retval === 0) {
                                    ViewError(_('SUCCESS').": $info");
                                    cwc_syslog(LOG_NOTICE, __FILE__, __FUNCTION__, __LINE__, "SUCCESS: $info");
                                    $info= "SetNVP: $newconffile: $Name= $newgroupfile";
                                    if ($this->SetNVP($newconffile, $Name, "'$newgroupfile'")) {
                                        ViewError(_('SUCCESS').": $info");
                                        cwc_syslog(LOG_NOTICE, __FILE__, __FUNCTION__, __LINE__, "SUCCESS: $info");
                                    }
                                    else {
                                        $result= FALSE;
                                        $fatal= TRUE;
                                        ViewError(_('FAILED').": $info");
                                        cwc_syslog(LOG_ERR, __FILE__, __FUNCTION__, __LINE__, "FAILED: $info");
                                    }
                                }
                                else {
                                    $result= FALSE;
                                    $fatal= TRUE;
                                    ViewError(_('FAILED').": $info ".implode("\n", $output));
                                    cwc_syslog(LOG_ERR, __FILE__, __FUNCTION__, __LINE__, "FAILED: $info ".implode("\n", $output));
                                }
                            }
                            else {
                                $result= FALSE;
                                ViewError(_('FAILED').": $info");
                                cwc_syslog(LOG_WARNING, __FILE__, __FUNCTION__, __LINE__, "FAILED: $info");
                            }
                        }
                        else {
                            $result= FALSE;
                            ViewError(_('FAILED').": $info");
                            cwc_syslog(LOG_WARNING, __FILE__, __FUNCTION__, __LINE__, "FAILED: $info");
                        }
                    }
                }
                else {
                    $result= FALSE;
                    $fatal= TRUE;
                    ViewError(_('FAILED').": $info ".implode("\n", $output));
                    cwc_syslog(LOG_ERR, __FILE__, __FUNCTION__, __LINE__, "FAILED: $info ".implode("\n", $output));
                }
            }
            else {
                $result= FALSE;
                $error= _('FAILED').": $info";
                ViewError(_('FAILED').": $info");
                cwc_syslog(LOG_ERR, __FILE__, __FUNCTION__, __LINE__, "FAILED: $info");
            }
        }
        else {
            $result= FALSE;
            $fatal= TRUE;
            ViewError(_('FAILED').": $info");
            cwc_syslog(LOG_ERR, __FILE__, __FUNCTION__, __LINE__, "FAILED: $info");
        }
        if (!$fatal) {
            $info= "SetNVP: $this->ConfFile: filtergroups $newgroup";
            if ($this->SetNVP($this->ConfFile, 'filtergroups', $newgroup)) {
                    ViewError(_('SUCCESS').": $info");
                    cwc_syslog(LOG_NOTICE, __FILE__, __FUNCTION__, __LINE__, "SUCCESS: $info");
            }
            else {
                $result= FALSE;
                $fatal= TRUE;
                ViewError(_('FAILED').": $info");
                cwc_syslog(LOG_ERR, __FILE__, __FUNCTION__, __LINE__, "FAILED: $info");
            }
            if (!$result) {
                ViewError("\n"._("One or more actions failed while creating new group\nExamine the report above to make sure this is the intended result!"));
            }
            else {
                ViewError("\n"._('Group created successfully').": $newgroup");
            }
        }
        if ($fatal) {
            ViewError("\n"._('FATAL ERRORS in creating new group'));
        }
        return !$fatal && $result;
    }
Dansguardian::SetTemplateIps ($ ip)
Updates template files with the given ip.
Used by installer or when system interface configuration is modified.
Definition at line 925 of file dansguardian.php.
References $Re_Ip, and $retval.
Referenced by Dansguardian().
    {
        global $Re_Ip;
        $langpath= '/usr/local/share/dansguardian/languages/';
        $re= "|(http://)($Re_Ip)(/images/comix.png)|m";
        $retval=  $this->ReplaceRegexp($langpath.'ukenglish/fancydmtemplate.html', $re, '${1}'.$ip.'${3}');
        $retval&= $this->ReplaceRegexp($langpath.'ukenglish/template.html', $re, '${1}'.$ip.'${3}');
        $retval&= $this->ReplaceRegexp($langpath.'ukenglish/template_nobypass.html', $re, '${1}'.$ip.'${3}');
        $retval&= $this->ReplaceRegexp($langpath.'turkish/fancydmtemplate.html', $re, '${1}'.$ip.'${3}');
        $retval&= $this->ReplaceRegexp($langpath.'turkish/template.html', $re, '${1}'.$ip.'${3}');
        $retval&= $this->ReplaceRegexp($langpath.'turkish/template_nobypass.html', $re, '${1}'.$ip.'${3}');
        $re= "|(http://)($Re_Ip)(/images/info.png)|m";
        $retval&= $this->ReplaceRegexp($langpath.'ukenglish/fancydmtemplate.html', $re, '${1}'.$ip.'${3}');
        $retval&= $this->ReplaceRegexp($langpath.'turkish/fancydmtemplate.html', $re, '${1}'.$ip.'${3}');
        $re= "|(http://)($Re_Ip)(/images/error.png)|m";
        $retval&= $this->ReplaceRegexp($langpath.'ukenglish/template.html', $re, '${1}'.$ip.'${3}');
        $retval&= $this->ReplaceRegexp($langpath.'ukenglish/template_nobypass.html', $re, '${1}'.$ip.'${3}');
        $retval&= $this->ReplaceRegexp($langpath.'turkish/template.html', $re, '${1}'.$ip.'${3}');
        $retval&= $this->ReplaceRegexp($langpath.'turkish/template_nobypass.html', $re, '${1}'.$ip.'${3}');
        return $retval;
    }
Dansguardian::Dansguardian ()
Definition at line 44 of file include.php.
References _HELPWINDOW().
    {
        $this->LogsHelpMsg= _HELPWINDOW('These logs may be important for diagnosing web filter related problems.');
    }
Dansguardian::SetSessionFilterGroup ()
Sets the DG filter group for the current session.
Warning:
Group file should probably be checked only for $_POST method. But there is no guarantie that session group will exist forever, or that Group 1 exists.
Definition at line 54 of file include.php.
References $_SESSION, _NOTICE(), GroupExists(), and PrintHelpWindow().
    {
        if ($_POST['Group']) {
            $group= $_POST['Group'];
        }
        else if ($_SESSION[$this->Model]['Group']) {
            $group= $_SESSION[$this->Model]['Group'];
        }
        else {
            $group= '1';
        }
        if ($this->Controller($output, 'GroupExists', $group)) {
            $_SESSION[$this->Model]['Group']= $group;
        }
        else {
            PrintHelpWindow(_NOTICE('Filter group not found').': '.$group, 'auto', 'ERROR');
        }
    }
Dansguardian::PrintFilterGroupForm ()
Displays an edit box and a botton to change current group.
Definition at line 76 of file include.php.
References $_SESSION, _HELPBOX2(), _TITLE(), action, maxlength, method, and PrintHelpBox().
    {
        // Print the group form even if group not found, so user can change it
        ?>
        <table>
            <tr>
                <td>
                    <form action="<?php echo $_SERVER['PHP_SELF'] ?>" method="post">
                        <?php echo _TITLE('Group').':' ?>
                        <input type="text" name="Group" style="width: 20px;" maxlength="2" value=<?php echo $_SESSION[$this->Model]['Group'] ?> />
                        <input type="submit" name="ApplyGroup" value="<?php echo _CONTROL('Apply') ?>"/>
                    </form>
                </td>
                <td>
                    <?php
                    PrintHelpBox(_HELPBOX2('This shows the active group for this page. Use this form to change the active group.'), 400);
                    ?>
                </td>
            </tr>
        </table>
        <?php
    }
Member Data Documentation
Dansguardian::$Name = 'dansguardian'
Reimplemented from Model.
Reimplemented in Blacklists, and Dansguardianlogs.
Definition at line 40 of file dansguardian.php.
Dansguardian::$User = 'root|_dansguardian'
Reimplemented from Model.
Definition at line 42 of file dansguardian.php.
Dansguardian::$NVPS = '='
Reimplemented from Model.
Definition at line 47 of file dansguardian.php.
Dansguardian::$ConfFile = '/etc/dansguardian/dansguardian.conf'
Reimplemented from Model.
Definition at line 48 of file dansguardian.php.
Dansguardian::$confDir = '/etc/dansguardian/' [protected]
Reimplemented from Model.
Definition at line 50 of file dansguardian.php.
Dansguardian::$LogFile = '/var/log/dansguardian/dansguardian.log'
Reimplemented from Model.
Reimplemented in Blacklists, and Dansguardianlogs.
Definition at line 55 of file dansguardian.php.
Dansguardian::$VersionCmd = '/usr/local/sbin/dansguardian -v'
Reimplemented from Model.
Definition at line 57 of file dansguardian.php.
Dansguardian::$PidFile = '/var/run/dansguardian.pid'
Reimplemented from Model.
Definition at line 59 of file dansguardian.php.
Dansguardian::$Model = 'dansguardian'
Reimplemented from View.
Reimplemented in Blacklists, and Dansguardianlogs.
Definition at line 41 of file include.php.
Dansguardian::$Layout = 'dansguardian'
Reimplemented from View.
Definition at line 42 of file include.php.
The documentation for this class was generated from the following files:
Model/dansguardian.php
View/dansguardian/include.php