ComixWall ISG Administration Interface: Squid Class Reference
Squid Class Reference
Public Member Functions
Squid ()
AddIpPort ($if)
Adds IP:port to squid config file.
DelIpPort ($if)
Deletes IP:port from squid config file.
GetIpPort ()
Extract all http IP:ports which squid listens to.
ParseLogLine ($logline, &$cols)
Log parser.
Squid ()
PrintLogLine ($cols, $linenum)
Public Attributes
$Name = 'squid'
$User = 'root|_squid'
$NVPS = '\h'
$ConfFile = '/etc/squid/squid.conf'
$LogFile = '/var/squid/logs/access.log'
$VersionCmd = '/usr/local/sbin/squid -v'
$PidFile = '/var/squid/logs/squid.pid'
$Model = 'squid'
$Layout = 'squid'
Detailed Description
Definition at line 42 of file squid.php.
Member Function Documentation
Squid::Squid ()
Definition at line 55 of file squid.php.
References $TmpFile, AddIpPort(), DelIpPort(), GetIpPort(), and Model.
    {
        global $TmpFile;
        parent::Model();
        $this->StartCmd= "/usr/local/sbin/squid -D > $TmpFile 2>&1 &";
        $this->Commands= array_merge(
            $this->Commands,
            array(
                'GetIpPort' => array(
                    'argv'  => array(),
                    'desc'  => _('Get HTTP proxy IP:port'),
                    ),
                'DelIpPort' => array(
                    'argv'  => array(IPPORT),
                    'desc'  => _('Delete HTTP proxy IP:port'),
                    ),
                'AddIpPort' => array(
                    'argv'  => array(IPPORT),
                    'desc'  => _('Add HTTP proxy IP:port'),
                    ),
                )
            );
    }
Squid::AddIpPort ($ if)
Adds IP:port to squid config file.
Adds the line above https_port TAG. Cleans up duplicates first
Parameters:
[in] $if string Interface IP:port.
Definition at line 91 of file squid.php.
References DelIpPort(), and Model::ReplaceRegexp().
Referenced by Squid().
    {
        $this->DelIpPort($if);
        return $this->ReplaceRegexp($this->ConfFile, "/(\h*#\h*TAG:\h*https_port.*)/m", "http_port $if\n".'${1}');
    }
Squid::DelIpPort ($ if)
Deletes IP:port from squid config file.
Warning:
If port is not provided, deletes all ports with that IP.
Parameters:
[in] $if string Interface IP:port.
Definition at line 103 of file squid.php.
References Escape(), and Model::ReplaceRegexp().
Referenced by AddIpPort(), and Squid().
    {
        $if= Escape($if, '.');
        return $this->ReplaceRegexp($this->ConfFile, "/^(\h*http_port\h*$if\b.*(\s|))/m", '');
    }
Squid::GetIpPort ()
Extract all http IP:ports which squid listens to.
Definition at line 111 of file squid.php.
References $Re_IpPort, and Model::SearchFileAll().
Referenced by Squid().
    {
        global $Re_IpPort;
        return $this->SearchFileAll($this->ConfFile, "/^\h*http_port\h*($Re_IpPort)\b.*\h*$/m");
    }
Squid::ParseLogLine ($ logline, &$ cols)
Log parser.
Parameters:
[in] $logline string Log line
[out] $cols array Parsed fields
Returns:
TRUE if log line is parsed
Reimplemented from Model.
Definition at line 118 of file squid.php.
References $Re_Ip, and Model::ParseSyslogLine().
    {
        global $Re_Ip;
        //1253140814.385  11463 127.0.0.1 TCP_MISS/200 6796 GET http://openbsd.org/images/cd45-s.gif - DIRECT/199.185.137.3 image/gif
        //1251968551.489      0 127.0.0.1 TCP_HIT/302 823 GET http://fxfeeds.mozilla.com/firefox/headlines.xml - NONE/- text/html
        $re_datetime= '(\d+\.\d+)';
        $re_size= '(\d+)';
        $re_clientip= "($Re_Ip|-)";
        $re_cache= '(\S+)';
        $re_code= '(\d+)';
        $re_mtd= '(GET|POST|\S+)';
        $re_link= '(\S+)';
        $re_direct= '(\S+)';
        $re_targetip= "($Re_Ip|\S+|-)";
        $re_type= '(\S+)';
        $re= "/^$re_datetime\s+\d+\s+$re_clientip\s+$re_cache\/$re_code\s+$re_size\s+$re_mtd\s+$re_link.*\s+$re_direct\/$re_targetip\s+$re_type$/";
        if (preg_match($re, $logline, $match)) {
            $day= sprintf('% 2d', date("j", $match[1]));
            $cols['Date']= date("M", $match[1]).' '.$day;
            $cols['Time']= date("H:i:s", $match[1]);
            $cols['DateTime']= $cols['Date'].' '.$cols['Time'];
            $cols['ClientIP']= $match[2];
            $cols['Cache']= $match[3];
            $cols['Code']= $match[4];
            $cols['Size']= $match[5];
            $cols['Mtd']= $match[6];
            $cols['Link']= $match[7];
            $cols['Direct']= $match[8];
            $cols['Target']= $match[9];
            $cols['Type']= $match[10];
            return TRUE;
        }
        else if ($this->ParseSyslogLine($logline, $cols)) {
            $cols['DateTime']= $cols['Date'].' '.$cols['Time'];
            return TRUE;
        }
        return FALSE;
    }
Squid::Squid ()
Definition at line 44 of file include.php.
References _HELPBOX2(), _HELPWINDOW(), _TITLE2(), cache, ConfHelpMsg, and Config.
    {
        $this->LogsHelpMsg= _HELPWINDOW('Source IP of all the requests on this page is the loopback interface, i.e. 127.0.0.1, hence not listed here. If the HTTP proxy is configured as non-caching proxy, you should see TCP_MISS on the Cache column.');
        $this->ConfHelpMsg= _HELPWINDOW('By default, the Web Filter connects to the HTTP proxy over the loopback interface and at port 3128. If you do not want to use the Web Filter, you can change this Proxy IP:Port setting to the internal IP address of the system and port 8080. When you stop the Web Filter, all requests from the internal network should be directed to the HTTP proxy.');
        $this->Config = array(
            'no_cache deny localhost' => array(
                'title' => _TITLE2('No cache'),
                'info' => _HELPBOX2('Enable ComixWall as a non-caching proxy for the local network.'),
                ),
            'log_ip_on_direct' => array(
                'title' => _TITLE2('Log ip on direct'),
                'info' => _HELPBOX2('Log the destination IP address in the hierarchy log tag when going direct. Earlier Squid versions logged the hostname here. If you prefer the old way set this to off.'),
                ),
            'debug_options' => array(
                'title' => _TITLE2('Debug options'),
                'info' => _HELPBOX2('Logging options are set as section,level where each source file is assigned a unique section.  Lower levels result in less output,  Full debugging (level 9) can result in a very large log file, so be careful.  The magic word "ALL" sets debugging levels for all sections.  We recommend normally running with "ALL,1".'),
                ),
            'log_fqdn' => array(
                'title' => _TITLE2('Log fqdn'),
                'info' => _HELPBOX2('Turn this on if you wish to log fully qualified domain names in the access.log. To do this Squid does a DNS lookup of all IP\'s connecting to it. This can (in some situations) increase latency, which makes your cache seem slower for interactive browsing.'),
                ),
            'client_netmask' => array(
                'title' => _TITLE2('Client netmask'),
                'info' => _HELPBOX2('A netmask for client addresses in logfiles and cachemgr output.
        Change this to protect the privacy of your cache clients.
        A netmask of 255.255.255.0 will log all IP\'s in that range with the last digit set to \'0\'.'),
                ),
            'http_access allow localhost' => array(
                'title' => _TITLE2('Allow localhost'),
                ),
            'http_access deny all' => array(
                'title' => _TITLE2('Deny others'),
                'info' => _HELPBOX2('And finally deny all other access to this proxy'),
                ),
            'cache_mgr' => array(
                'title' => _TITLE2('Cache mgr'),
                'info' => _HELPBOX2('Email-address of local cache manager who will receive mail if the cache dies. The default is "webmaster".'),
                ),
        );
    }
Squid::PrintLogLine ($ cols, $ linenum)
Definition at line 86 of file include.php.
    {
        $this->PrintLogLineClass($cols['Cache']);
        PrintLogCols($linenum, $cols);
        echo '</tr>';
    }
Member Data Documentation
Squid::$Name = 'squid'
Reimplemented from Model.
Definition at line 44 of file squid.php.
Squid::$User = 'root|_squid'
Reimplemented from Model.
Definition at line 45 of file squid.php.
Squid::$NVPS = '\h'
Reimplemented from Model.
Definition at line 47 of file squid.php.
Squid::$ConfFile = '/etc/squid/squid.conf'
Reimplemented from Model.
Definition at line 48 of file squid.php.
Squid::$LogFile = '/var/squid/logs/access.log'
Reimplemented from Model.
Definition at line 49 of file squid.php.
Squid::$VersionCmd = '/usr/local/sbin/squid -v'
Reimplemented from Model.
Definition at line 51 of file squid.php.
Squid::$PidFile = '/var/squid/logs/squid.pid'
Reimplemented from Model.
Definition at line 53 of file squid.php.
Squid::$Model = 'squid'
Reimplemented from View.
Definition at line 41 of file include.php.
Squid::$Layout = 'squid'
Reimplemented from View.
Definition at line 42 of file include.php.
The documentation for this class was generated from the following files:
Model/squid.php
View/squid/include.php