ComixWall ISG Administration Interface: Cache Class Reference
Cache Class Reference
Public Member Functions
Cache ()
_load ()
_cache ($filename)
_iscached ($filename)
_get ($filename)
Public Attributes
$db
$timestamp
Detailed Description
Definition at line 55 of file class_cache.inc.
Member Function Documentation
Cache::Cache ()
Definition at line 59 of file class_cache.inc.
References $symon, and _load().
                     {
    global $symon;
    if (!isset($symon["cache_duration"])) {
        config_error("cache_duration", "is not set");
        return 0;
    }
    if (!isset($symon["cache_dir"])) {
        config_error("cache_dir", "is not set");
        return 0;
    }
    if (!is_dir($symon["cache_dir"])) {
        config_error("cache_dir", "does not point to a directory");
        return 0;
    }
    return $this->_load();
    }
Cache::_load ()
Definition at line 78 of file class_cache.inc.
References $file, $symon, and _cache().
Referenced by Cache().
                     {
    global $symon;
    $ts = time();
    $this->timestamp = $ts - ($ts % $symon["cache_duration"]);
    $dir = dir($symon["cache_dir"]);
    while ($file = $dir->read()) {
        if ($file == '.' || $file == '..') {
        continue;
        }
        if (!is_file($symon["cache_dir"].'/'.$file)) {
        runtime_error("'".$file."' is not a cache file");
        return 0;
        }
        $this->_cache($file);
    }
    }
Cache::_cache ($ filename)
Definition at line 98 of file class_cache.inc.
References $filename, and $symon.
Referenced by _load().
{
    global $symon;
    if (preg_match("/^([0-9]+)_([0-9a-f]+)(\.[a-z]+)?$/i",
               $filename, $match)) {
        $this->db[$match[2]] = $filename;
        if (($this->timestamp > $match[1]) &&
        (!isset($symon['cache_keepstale']))) {
        $this->expire_key($match[2]);
        }
    } else {
        runtime_error("'".$filename."' is not a cache file");
        return 0;
    }
    }
Cache::_iscached ($ filename)
Definition at line 114 of file class_cache.inc.
References $filename.
{
    if (preg_match("/^([0-9]+)_([0-9a-f]+)(\.[a-z]+)?$/i",
               $filename, $match)) {
        return isset($this->db[$match[2]]);
    } else {
        if (preg_match("/^([0-9a-f]+)(\.[a-z]+)?$/i",
               $filename, $match)) {
        return isset($this->db[$match[1]]);
        } else {
        return isset($this->db[$filename]);
        }
    }
    }
Cache::_get ($ filename)
Definition at line 128 of file class_cache.inc.
References $filename.
{
    if (preg_match("/^([0-9]+)_([0-9a-f]+)(\.[a-z]+)?$/i",
               $filename, $match)) {
        if (isset($this->db[$match[2]])) {
        return $this->db[$match[2]];
        }
    } else {
        if (preg_match("/^([0-9a-f]+)(\.[a-z]+)?$/i",
               $filename, $match)) {
        if (isset($this->db[$match[1]])) {
            return $this->db[$match[1]];
        }
        } else {
        if (isset($this->db[$filename])) {
            return $this->db[$filename];
        }
        }
    }
    return undef;
    }
Member Data Documentation
Cache::$db
Definition at line 56 of file class_cache.inc.
Cache::$timestamp
Definition at line 57 of file class_cache.inc.
The documentation for this class was generated from the following file:
View/symon/class_cache.inc