ComixWall ISG Administration Interface: pfw Class Reference
pfw Class Reference
Public Member Functions
pfw ()
read_from_file ($filename)
parseRulebase ($rulebase_string)
generate ($lines=false, $generate_header=true)
writeFile ($filename)
printRules ()
Public Attributes
$filter
$nat
$macro
$options
$scrub
$altq
$queue
$table
$anchor
Detailed Description
Definition at line 34 of file pfw.class.php.
Member Function Documentation
pfw::pfw ()
Definition at line 46 of file pfw.class.php.
    {
        $this->filter =   new filter();
        $this->nat =        new nat();
        $this->macro =    new macro();
        $this->scrub =    new scrub();
        $this->table =    new table();
        $this->altq =       new altq();
        $this->queue =    new queue();
        $this->options =  new options();
        $this->anchor =   new anchor();
    }
pfw::read_from_file ($ filename)
Definition at line 59 of file pfw.class.php.
References $filename, and parseRulebase().
    {
        $this->parseRulebase(file_get_contents ($filename));
    }
pfw::parseRulebase ($ rulebase_string)
Definition at line 64 of file pfw.class.php.
References $rule.
Referenced by read_from_file().
    {
        if (preg_match("/pf ruleset generated at/", $rulebase_string)) {
            $rulebase_string = substr($rulebase_string, strpos($rulebase_string, "#\n\n") + '3');
        }
        $rulebase_string = preg_replace  ("/\n#/", "\n# ", $rulebase_string);
        $rulebase_string = str_replace ("\\\n", "", $rulebase_string);
        foreach (preg_split("/\n/", $rulebase_string, '-1', PREG_SPLIT_NO_EMPTY) as $rule) {
            $this->rulebase[] = trim($rule);
        }
        foreach ($this->rulebase as $rule) {
            $keywords = preg_split("/[\s,\t]+/", $rule, '-1', PREG_SPLIT_NO_EMPTY);
            if (preg_match("/match.*\bscrub\b/", $rule)) {
                $keywords[0] = 'scrub';
            }
            switch ($keywords['0']) {
            case "":
                break;
            case "#":
                if (!isset($_comment)) {
                    $_comment = trim(substr($rule, '1'));
                } else {
                    $_comment .= "\n". trim(substr($rule, '1'));
                }
                break;
            case "anchor":
            case "pass":
            case "block":
            case "match":
            case "antispoof":
                $this->filter->addComment($_comment);
                unset($_comment);
                $this->filter->rules[] = $this->filter->parse($rule);
                break;
            case "no":
            case "rdr":
            case "nat":
            case "binat":
            case "nat-anchor":
            case "rdr-anchor":
            case "binat-anchor":
                if (isset($_comment)) {
                    $data['type'] = "comment";
                    $data['comment'] = $_comment;
                    $this->nat->rules[] = $data;
                    unset ($_comment);
                }
                $this->nat->rules[] = $this->nat->parse($rule);
                break;
            case "set":
                $this->options->addComment($_comment);
                unset ($_comment);
                $this->options->parse($rule);
                break;
            case "scrub":
                if (isset($_comment)) {
                    $data['type'] = "comment";
                    $data['comment'] = $_comment;
                    $this->scrub->rules[] = $data;
                    unset ($_comment);
                }
                $this->scrub->rules[] = $this->scrub->parse($rule);
                unset ($_comment);
                break;
            case "table":
                if (isset($_comment)) {
                    $data['type'] = "comment";
                    $data['comment'] = $_comment;
                    $this->table->rules[] = $data;
                    unset ($_comment);
                }
                $this->table->rules[] = $this->table->parse($rule);
                unset ($_comment);
                break;
            case "altq":
                if (isset($_comment)) {
                    $data['type'] = "comment";
                    $data['comment'] = $_comment;
                    $this->altq->rules[] = $data;
                    unset ($_comment);
                }
                $this->altq->rules[] = $this->altq->parse($rule);
                break;
            case "queue":
                if (isset($_comment)) {
                    $data['type'] = "comment";
                    $data['comment'] = $_comment;
                    $this->queue->rules[] = $data;
                    unset ($_comment);
                }
                $this->queue->rules[] = $this->queue->parse($rule);
                break;
            case "load":
            if (isset($_comment)) {
                $data['type'] = "comment";
                $data['comment'] = $_comment;
                $this->anchor->rules[] = $data;
                unset ($_comment);
            }
            $this->anchor->rules[] = $this->anchor->parse($rule);
            break;
            default:
                if (isset($_comment)) {
                    $data['type'] = "comment";
                    $data['comment'] = $_comment;
                    $this->macro->rules[] = $data;
                    unset ($_comment);
                }
                $this->macro->rules[] = $this->macro->parse($rule);
                break;
            }
        }
        $this->rulebase = $rules;
    }
pfw::generate ($ lines = false, $ generate_header = true)
Definition at line 180 of file pfw.class.php.
Referenced by writeFile().
    {
      if ($generate_header) {
          $data = "#\n# pf ruleset generated at ". date("Y-m-d H:m:s"). "\n#\n# ruleset automatically generated by pfw\n#\n\n";
        }
        $data .= $this->macro->generate();
        $data .= $this->table->generate();
        $data .= $this->options->generate();
        $data .= $this->scrub->generate();
        $data .= $this->altq->generate();
        $data .= $this->queue->generate();
        $data .= $this->nat->generate();
        $data .= $this->filter->generate();
        $data .= $this->anchor->generate();
    if ($generate_header) {
          $data .= "\n# End of Ruleset\n";
        }
        if ($lines) {
            $linenumber='1';
            foreach (explode("\n", $data) as $line) {
                $_data .= $linenumber++. ": $line\n";
            }
            $data = $_data;
        }
        return $data;
    }
pfw::writeFile ($ filename)
Definition at line 209 of file pfw.class.php.
References $filename, $handle, exit, generate(), and print.
    {
        if (!$handle = fopen($filename, 'w')) {
            print "Cannot open file: $filename";
            exit;
        }
        // Write $somecontent to our opened file.
        if (fwrite($handle, $this->generate()) === FALSE) {
            print "Cannot write to file ($filename)";
            exit;
        }
        fclose ($handle);
    }
pfw::printRules ()
Definition at line 225 of file pfw.class.php.
    {
        print_r ($this->rulebase);
    }
Member Data Documentation
pfw::$filter
Definition at line 36 of file pfw.class.php.
pfw::$nat
Definition at line 37 of file pfw.class.php.
pfw::$macro
Definition at line 38 of file pfw.class.php.
pfw::$options
Definition at line 39 of file pfw.class.php.
pfw::$scrub
Definition at line 40 of file pfw.class.php.
pfw::$altq
Definition at line 41 of file pfw.class.php.
pfw::$queue
Definition at line 42 of file pfw.class.php.
pfw::$table
Definition at line 43 of file pfw.class.php.
pfw::$anchor
Definition at line 44 of file pfw.class.php.
The documentation for this class was generated from the following file:
View/pf/lib/packetfilter/pfw.class.php