ComixWall ISG Administration Interface: Openvpn Class Reference
Openvpn Class Reference
Public Member Functions
Openvpn ()
GetConfFile ($conf, $group)
Attention:
PHP does not allow parameter overriding, method signature should be the same, hence this redundant $group arg
SetConfig ($confname)
Sets configuration file based on config type provided.
StopProcess ($conffile)
Stops openvpn process started with the given conf file.
Restart ($conffile)
Starts module process(es).
IsClientConf ($file)
Determines if the given conf file contains Client configuration.
FindPid ($conffile)
Finds the pid of openvpn process started with the given conf file.
GetConfs ()
Gets files with conf ext.
DeleteConf ($Conf)
CopyConf ($file, $newfile)
Copies file.
Openvpn ()
SetConfig ($file)
Sets session config file, ModelConfig and ModelConfigName params.
ConfSelectForm ($module)
General form for selecting, deleting, and copying an OpenVPN conf file.
ConfStartStopForm ()
General form for selecting an OpenVPN conf file to run.
Public Attributes
$Name = 'openvpn'
$User = '\S+'
$NVPS = '\h'
$LogFile = '/var/log/openvpn.log'
$VersionCmd = '/usr/local/sbin/openvpn --version 2>&1'
$Model = 'openvpn'
$Layout = 'openvpn'
Detailed Description
Definition at line 38 of file openvpn.php.
Member Function Documentation
Openvpn::Openvpn ()
Definition at line 50 of file openvpn.php.
References CopyConf(), DeleteConf(), GetConfs(), IsClientConf(), Model, Model::Restart(), Model::Start(), Model::Stop(), and StopProcess().
    {
        parent::Model();
        $this->Commands= array_merge(
            $this->Commands,
            array(
                'Restart'   => array(
                    'argv'  => array(NAME),
                    'desc'  => _('Start OpenVPN process'),
                    ),
                'StopProcess'=> array(
                    'argv'  => array(NAME),
                    'desc'  => _('Stop OpenVPN instance'),
                    ),
                'IsClientConf'=> array(
                    'argv'  => array(NAME),
                    'desc'  => _('If client conf'),
                    ),
                'CopyConf'  => array(
                    'argv'  => array(NAME, NAME),
                    'desc'  => _('Copy conf'),
                    ),
                'GetConfs'  => array(
                    'argv'  => array(),
                    'desc'  => _('Get confs'),
                    ),
                'DeleteConf'=> array(
                    'argv'  => array(NAME),
                    'desc'  => _('Delete conf'),
                    ),
                )
            );
    }
Openvpn::GetConfFile ($ conf, $ group)
Attention:
PHP does not allow parameter overriding, method signature should be the same, hence this redundant $group arg
Reimplemented from Model.
Definition at line 91 of file openvpn.php.
    {
        return '/etc/openvpn/'.$conf;
    }
Openvpn::SetConfig ($ confname)
Sets configuration file based on config type provided.
Certain modules have configuration divided into multiple pages/files, hence they override this method.
Parameters:
[in] $confname string Config type
Reimplemented from Model.
Definition at line 96 of file openvpn.php.
References $ClientConfig, $ServerConfig, Config, and IsClientConf().
Referenced by ConfSelectForm().
    {
        global $ClientConfig, $ServerConfig;
        if ($this->IsClientConf($confname)) {
            $this->Config= $ClientConfig;
        }
        else {
            $this->Config= $ServerConfig;
        }
    }
Openvpn::StopProcess ($ conffile)
Stops openvpn process started with the given conf file.
Parameters:
[in] $conffile Conf file name.
Definition at line 112 of file openvpn.php.
References FindPid(), and Model::KillPid().
Referenced by Openvpn(), and Restart().
    {
        $pid= $this->FindPid($conffile);
        if ($pid > -1) {
            return $this->KillPid($pid);
        }
        return TRUE;
    }
Openvpn::Restart ($ conffile)
Starts module process(es).
Tries PROC_STAT_TIMEOUT times.
Todo:
Actually should stop retying on some error conditions?
Start command is redirected to tmp file
Definition at line 127 of file openvpn.php.
References $TmpFile, cwc_syslog(), FindPid(), Model::RunShellCommand(), StopProcess(), and ViewError().
    {
        global $TmpFile;
        if ($this->StopProcess($conffile)) {
            $count= 0;
            while ($count++ < self::PROC_STAT_TIMEOUT) {
                if ($this->FindPid($conffile) > -1) {
                    return TRUE;
                }
                $cmd= "/usr/local/sbin/openvpn --config /etc/openvpn/$conffile --daemon --status /var/log/openvpn-status.log 5 > $TmpFile";
                $this->RunShellCommand($cmd);
                exec('/bin/sleep .1');
            }
            $output= file_get_contents($TmpFile);
            ViewError($output);
            cwc_syslog(LOG_ERR, __FILE__, __FUNCTION__, __LINE__, "Restart failed with: $output");
            // Check one last time due to the last sleep in the loop
            return $this->FindPid($conffile) > -1;
        }
        return FALSE;
    }
Openvpn::IsClientConf ($ file)
Determines if the given conf file contains Client configuration.
Used by config page to use the right configuration array
Parameters:
[in] $file string Conf file name.
Definition at line 160 of file openvpn.php.
References Model::GetName().
Referenced by Openvpn(), and SetConfig().
    {
        if (($this->GetName($this->confDir.$file, 'client') !== FALSE) ||
            ($this->GetName($this->confDir.$file, 'tls-client') !== FALSE)) {
            return TRUE;
        }
        return FALSE;
    }
Openvpn::FindPid ($ conffile)
Finds the pid of openvpn process started with the given conf file.
Parameters:
[in] $conffile string Conf file name.
Definition at line 173 of file openvpn.php.
References $file, and Model::RunShellCommand().
Referenced by Restart(), and StopProcess().
    {
        $re= '/^(.*)\.conf$/';
        if (preg_match($re, $conffile, $match)) {
            $file= $match[1].'.conf';
            $pidcmd= "/bin/ps arwwx | /usr/bin/grep openvpn | /usr/bin/grep '$file' | /usr/bin/grep -v -e cwc.php -e grep";
            $output= $this->RunShellCommand($pidcmd);
            $re= '/^\s*(\d+)\s+/m';
            if (preg_match($re, $output, $match)) {
                if ($match[1] !== '') {
                    return $match[1];
                }
            }
        }
        return -1;
    }
Openvpn::GetConfs ()
Gets files with conf ext.
Definition at line 194 of file openvpn.php.
References Model::GetFiles().
Referenced by ConfSelectForm(), ConfStartStopForm(), and Openvpn().
    {
        return $this->GetFiles($this->confDir.'*.conf');
    }
Openvpn::DeleteConf ($ Conf)
Definition at line 199 of file openvpn.php.
References Model::DeleteFile().
Referenced by Openvpn().
    {
        return $this->DeleteFile($this->confDir.$Conf);
    }
Openvpn::CopyConf ($ file, $ newfile)
Copies file.
Parameters:
[in] $file File.
[in] $newfile New file.
Definition at line 209 of file openvpn.php.
References cwc_syslog().
Referenced by Openvpn().
    {
        if (!file_exists($this->confDir.$newfile)) {
            // copy() returns TRUE on success or FALSE on failure
            return copy($this->confDir.$file, $this->confDir.$newfile);
        }
        cwc_syslog(LOG_DEBUG, __FILE__, __FUNCTION__, __LINE__, 'Dest file already exists '.$this->confDir.$newfile);
        return FALSE;
    }
Openvpn::Openvpn ()
Definition at line 44 of file include.php.
References _HELPWINDOW(), and ConfHelpMsg.
    {
        $this->LogsHelpMsg= _HELPWINDOW('Messages from all OpenVPN processes are recorded in the same log file.');
        $this->ConfHelpMsg= _HELPWINDOW('Sample client and server configuration are provided to get you started. You may want to replace the default SSL certificates with yours.');
    }
Openvpn::SetConfig ($ file)
Sets session config file, ModelConfig and ModelConfigName params.
Parameters:
[in] $file string Config file
Reimplemented from Model.
Definition at line 54 of file include.php.
References $_SERVER, $_SESSION, $ClientConfig, $file, $ServerConfig, $ViewConfigName, Config, and IsClientConf().
    {
        global $ViewConfigName, $ClientConfig, $ServerConfig;
        if (isset($file)) {
            $_SESSION[$this->Model][basename($_SERVER['PHP_SELF'])]['ConfFile']= $file;
            if ($this->Controller($output, 'IsClientConf', $file)) {
                $this->Config= $ClientConfig;
            }
            else {
                $this->Config= $ServerConfig;
            }
            $ViewConfigName= $file;
        }
    }
Openvpn::ConfSelectForm ($ module)
General form for selecting, deleting, and copying an OpenVPN conf file.
Parameters:
[in] $module string Module name, the caller
Definition at line 75 of file include.php.
References $file, $selected, _NOTICE(), action, GetConfs(), maxlength, method, and SetConfig().
    {
        global $ConfigFile;
        $deleteconfirm= _NOTICE('Are you sure you want to delete the configuration?');
        if ($this->Controller($conffiles, 'GetConfs')) {
            ?>
            <form action="<?php echo $_SERVER['PHP_SELF'] ?>" method="post">
                <select name="ConfFile">
                <?php
                $conffileexists= FALSE;
                foreach ($conffiles as $file) {
                    $selected= '';
                    if ($ConfigFile === basename($file)) {
                        $selected= ' selected';
                        $conffileexists= TRUE;
                    }
                    ?>
                    <option value="<?php echo basename($file) ?>"<?php echo $selected ?>><?php echo basename($file) ?></option>
                    <?php
                }
                if (!$conffileexists && (count($conffiles) > 0)) {
                    $ConfigFile= basename($conffiles[0]);
                    $this->SetConfig($ConfigFile);
                }
                ?>
                </select>
                <input type="submit" name="Select" value="<?php echo _CONTROL('Select') ?>"/>
                <br />
                <input type="submit" name="Delete" value="<?php echo _CONTROL('Delete') ?>" onclick="return confirm('<?php echo $deleteconfirm ?>')"/>
                <br />
                <input type="text" name="CopyTo" style="width: 150px;" maxlength="100" value="<?php echo basename($ConfigFile) ?>"/>
                <input type="submit" name="Copy" value="<?php echo _CONTROL('Copy') ?>"/>
            </form>
            <?php
        }
    }
Openvpn::ConfStartStopForm ()
General form for selecting an OpenVPN conf file to run.
Definition at line 117 of file include.php.
References $file, $Modules, _NOTICE(), action, GetConfs(), and method.
    {
        global $Modules;
        $startconfirm= _NOTICE('Are you sure you want to start the <NAME>?');
        $startconfirm= preg_replace('/<NAME>/', _($Modules[$this->Model]['Name']), $startconfirm);
        $stopconfirm= _NOTICE('Are you sure you want to stop the <NAME>?');
        $stopconfirm= preg_replace('/<NAME>/', _($Modules[$this->Model]['Name']), $stopconfirm);
        if ($this->Controller($conffiles, 'GetConfs')) {
            ?>
            <form action="<?php echo $_SERVER['PHP_SELF'] ?>" method="post">
                <select name="ConfFiles[]" multiple style="width: 150px; height: 100px;">
                    <?php
                    foreach ($conffiles as $file) {
                        ?>
                        <option value="<?php echo basename($file) ?>"><?php echo basename($file) ?></option>
                        <?php
                    }
                    ?>
                </select>
                <br />
                <input type="submit" name="Start" value="<?php echo _CONTROL('Start') ?>" onclick="return confirm('<?php echo $startconfirm ?>')"/>
                <input type="submit" name="Stop" value="<?php echo _CONTROL('Stop') ?>" onclick="return confirm('<?php echo $stopconfirm ?>')"/>
            </form>
            <?php
        }
    }
Member Data Documentation
Openvpn::$Name = 'openvpn'
Reimplemented from Model.
Definition at line 40 of file openvpn.php.
Openvpn::$User = '\S+'
Reimplemented from Model.
Definition at line 41 of file openvpn.php.
Openvpn::$NVPS = '\h'
Reimplemented from Model.
Definition at line 43 of file openvpn.php.
Openvpn::$LogFile = '/var/log/openvpn.log'
Reimplemented from Model.
Definition at line 46 of file openvpn.php.
Openvpn::$VersionCmd = '/usr/local/sbin/openvpn --version 2>&1'
Reimplemented from Model.
Definition at line 48 of file openvpn.php.
Openvpn::$Model = 'openvpn'
Reimplemented from View.
Definition at line 41 of file include.php.
Openvpn::$Layout = 'openvpn'
Reimplemented from View.
Definition at line 42 of file include.php.
The documentation for this class was generated from the following files:
Model/openvpn.php
View/openvpn/include.php