ComixWall ISG Administration Interface: Smtpgated Class Reference
Smtpgated Class Reference
Public Member Functions
Smtpgated ()
GetVersion ()
Gets software version string.
ParseLogLine ($logline, &$cols)
Log parser.
Smtpgated ()
Public Attributes
$Name = 'smtp-gated'
$User = '_smtp-gated'
$NVPS = '\h'
$ConfFile = '/etc/smtp-gated.conf'
$LogFile = '/var/log/smtp-gated.log'
$VersionCmd = '/usr/local/sbin/smtp-gated -v'
$PidFile = '/var/run/smtp-gated/smtp-gated.pid'
$Model = 'smtp-gated'
$Layout = 'smtp-gated'
Detailed Description
Definition at line 38 of file smtp-gated.php.
Member Function Documentation
Smtpgated::Smtpgated ()
Definition at line 51 of file smtp-gated.php.
References $TmpFile, and Model.
    {
        global $TmpFile;
        parent::Model();
        $this->StartCmd= "/usr/local/sbin/smtp-gated /etc/smtp-gated.conf > $TmpFile 2>&1 &";
    }
Smtpgated::GetVersion ()
Gets software version string.
Reimplemented from Model.
Definition at line 60 of file smtp-gated.php.
References Model::RunShellCommand().
    {
        $version= explode("\n", $this->RunShellCommand($this->VersionCmd.' | /usr/bin/head -4'));
        return $version[1]."\n".$version[3];
    }
Smtpgated::ParseLogLine ($ logline, &$ cols)
Log parser.
Parameters:
[in] $logline string Log line
[out] $cols array Parsed fields
Returns:
TRUE if log line is parsed
Reimplemented from Model.
Definition at line 66 of file smtp-gated.php.
References $Re_Ip, and Model::ParseSyslogLine().
    {
        global $Re_Ip;
        if ($this->ParseSyslogLine($logline, $cols)) {
            $re_scanner= '(SCAN|SPAM)';
            $re_result= '(\S+)';
            $re_nonempty= '(\S+)';
            $re_num= '(\d+)';
            $re_srcip= "($Re_Ip)";
            $re_result= '(.*|)';
            //SCAN:CLEAN size=1639, time=0, src=192.168.1.1, ident=
            //SPAM:CLEAN size=337, time=0, src=192.168.1.1, ident=, score=2.900000
            //SCAN:VIRUS size=1065, time=0, src=192.168.1.1, ident=, virus=Eicar-Test-Signature
            $re= "/$re_scanner:$re_result\s+size=$re_num,\s+time=$re_num,\s+src=$re_srcip,\s+ident=.*$/";
            if (preg_match($re, $logline, $match)) {
                $cols['Scanner']= $match[1];
                $cols['Result']= $match[2];
                $cols['Bytes']= $match[3];
                $cols['ScanSrcIP']= $match[5];
            }
            $re= "/$re_scanner:$re_result\s+size=$re_num,\s+src=$re_srcip,\s+ident=.*$/";
            if (preg_match($re, $logline, $match)) {
                $cols['Scanner']= $match[1];
                $cols['Result']= $match[2];
                $cols['Bytes']= $match[3];
                $cols['ScanSrcIP']= $match[4];
            }
            //CLOSE by=server, rcv=442/286, trns=1, rcpts=1, auth=0, time=140183437574146, src=192.168.1.1, ident=
            $re= "/CLOSE\s+by=$re_nonempty,\s+rcv=$re_num\/$re_num,\s+trns=$re_num,\s+rcpts=$re_num,\s+auth=$re_num,\s+time=$re_num,\s+src=$re_srcip,\s+ident=.*$/";
            if (preg_match($re, $logline, $match)) {
                $cols['ClosedBy']= $match[1];
                $cols['Xmted']= $match[2];
                $cols['Rcved']= $match[3];
                $cols['Trns']= $match[4];
                $cols['Rcpts']= $match[5];
                $cols['Seconds']= $match[7];
                $cols['SrcIP']= $match[8];
            }
            //SESSION TAKEOVER: src=192.168.1.1, ident=, trns=1, reason=Malware found (Eicar-Test-Signature)
            $re= "/SESSION\s+TAKEOVER:\s+src=$re_srcip,\s+\S+,\s+\S+,\s+reason=$re_result$/";
            if (preg_match($re, $logline, $match)) {
                $cols['SrcIP']= $match[1];
                $cols['STReason']= $match[2];
                $cols['ClosedBy']= 'proxy';
            }
            //LOCK:LOCKED src=192.168.1.1, ident=-
            $re= "/LOCK:LOCKED\s+src=$re_srcip,.*$/";
            if (preg_match($re, $logline, $match)) {
                $cols['SrcIP']= $match[1];
                $cols['LockedIP']= $cols['SrcIP'];
                $cols['STReason']= 'Locked';
                $cols['ClosedBy']= 'proxy';
            }
            $re_result= '(RCPT\s+TO:|rejected)';
            $re_sender= '(<\S*>|)';
            $re_recipient= '(<\S*>|)';
            $re_retcode= '(\[\d+\]|\d+)';
            //MAIL FROM <soner@comixwall.org> RCPT TO: 250<soner@comixwall.org>
            $re= "/MAIL\s+FROM\s+$re_sender\s+$re_result\s+$re_retcode$re_recipient$/";
            if (preg_match($re, $logline, $match)) {
                $cols['Sender']= trim($match[1], '<>');
                $cols['RResult']= $match[2].' '.$match[3];
                $cols['Recipient']= trim($match[4], '<>');
            }
            $re= "/^$re_result\s+$re_retcode$re_recipient.*$/";
            if (preg_match($re, $cols['Log'], $match)) {
                $cols['RResult']= $match[1].' '.$match[2];
                $cols['Recipient']= trim($match[3], '<>');
            }
            return TRUE;
        }
        return FALSE;
    }
Smtpgated::Smtpgated ()
Definition at line 44 of file include.php.
References _HELPWINDOW(), _TITLE2(), ConfHelpMsg, and Config.
    {
        $this->LogsHelpMsg= _HELPWINDOW('You may want to watch these logs carefully to determine infected clients in the internal network.');
        $this->ConfHelpMsg= _HELPWINDOW('If an outgoing e-mail is determined to be infected or identified as spam, the client trying to send that e-mail is blocked from sending any e-mails for a period of time defined by lock duration. You can enter your e-mail address in report e-mail option.');
        $this->Config = array(
            'lock_on' => array(
                'title' => _TITLE2('Lock on'),
                ),
            'lock_duration' => array(
                'title' => _TITLE2('Lock duration'),
                ),
            'abuse' => array(
                'title' => _TITLE2('Report e-mail'),
                ),
            'priority' => array(
                'title' => _TITLE2('Priority'),
                ),
            'max_connections' => array(
                'title' => _TITLE2('Maximum connections'),
                ),
            'max_per_host' => array(
                'title' => _TITLE2('Maximum connections per host'),
                ),
            'max_load' => array(
                'title' => _TITLE2('Maximum load'),
                ),
            'scan_max_size' => array(
                'title' => _TITLE2('Maximum virus scan size'),
                ),
            'spam_max_size' => array(
                'title' => _TITLE2('Maximum spam scan size'),
                ),
            'spam_max_load' => array(
                'title' => _TITLE2('Maximum spam load'),
                ),
            'spam_threshold' => array(
                'title' => _TITLE2('Spam threshold'),
                ),
            'ignore_errors' => array(
                'title' => _TITLE2('Ignore errors'),
                ),
            'spool_leave_on' => array(
                'title' => _TITLE2('Leave spool on'),
                ),
            'log_helo' => array(
                'title' => _TITLE2('Log helo'),
                ),
            'log_mail_from' => array(
                'title' => _TITLE2('Log mail from'),
                ),
            'log_rcpt_to' => array(
                'title' => _TITLE2('Log rcpt to'),
                ),
            'log_level' => array(
                'title' => _TITLE2('Log level'),
                ),
            'nat_header_type' => array(
                'title' => _TITLE2('NAT header type'),
                ),
            'locale' => array(
                'title' => _TITLE2('Locale'),
                ),
        );
    }
Member Data Documentation
Smtpgated::$Name = 'smtp-gated'
Reimplemented from Model.
Definition at line 40 of file smtp-gated.php.
Smtpgated::$User = '_smtp-gated'
Reimplemented from Model.
Definition at line 41 of file smtp-gated.php.
Smtpgated::$NVPS = '\h'
Reimplemented from Model.
Definition at line 43 of file smtp-gated.php.
Smtpgated::$ConfFile = '/etc/smtp-gated.conf'
Reimplemented from Model.
Definition at line 44 of file smtp-gated.php.
Smtpgated::$LogFile = '/var/log/smtp-gated.log'
Reimplemented from Model.
Definition at line 45 of file smtp-gated.php.
Smtpgated::$VersionCmd = '/usr/local/sbin/smtp-gated -v'
Reimplemented from Model.
Definition at line 47 of file smtp-gated.php.
Smtpgated::$PidFile = '/var/run/smtp-gated/smtp-gated.pid'
Reimplemented from Model.
Definition at line 49 of file smtp-gated.php.
Smtpgated::$Model = 'smtp-gated'
Reimplemented from View.
Definition at line 41 of file include.php.
Smtpgated::$Layout = 'smtp-gated'
Reimplemented from View.
Definition at line 42 of file include.php.
The documentation for this class was generated from the following files:
Model/smtp-gated.php
View/smtp-gated/include.php