ComixWall ISG Administration Interface: Imlogs Class Reference
Imlogs Class Reference
Public Member Functions
Imlogs ()
ImGetFiles ($proto= '', $localuser= '', $remoteuser= '')
GetDirs ($proto= '', $localuser= '')
GetProtocols ()
GetLocalUsers ($proto)
GetRemoteUsers ($proto, $localuser)
GetSessions ($proto, $localuser, $remoteuser)
GetImLogFile ($proto, $localuser, $remoteuser, $session)
ParseLogLine ($logline, &$cols)
Log parser.
PrintLogLine ($cols, $linenum)
Public Attributes
$Model = 'imlogs'
Detailed Description
Definition at line 42 of file imlogs.php.
Member Function Documentation
Imlogs::Imlogs ()
Todo:
Is there any pattern or size for localuser, 2nd param?
Todo:
Is there any pattern or size for localuser and remoteuser, 2nd and 3rd param?
Todo:
Is there any pattern or size for localuser and remoteuser, 2nd and 3rd param?
Definition at line 46 of file imlogs.php.
References GetImLogFile(), GetLocalUsers(), GetProtocols(), GetRemoteUsers(), GetSessions(), and Model.
    {
        parent::Model();
        $this->Commands= array_merge(
            $this->Commands,
            array(
                'GetProtocols'=>    array(
                    'argv'  =>  array(),
                    'desc'  =>  _('Get protocols'),
                    ),
                'GetLocalUsers'=>   array(
                    'argv'  =>  array(NAME),
                    'desc'  =>  _('Get local users'),
                    ),
                'GetRemoteUsers'=>  array(
                    'argv'  =>  array(NAME, STR),
                    'desc'  =>  _('Get remote users'),
                    ),
                'GetSessions'=> array(
                    'argv'  =>  array(NAME, STR, STR),
                    'desc'  =>  _('Get sessions'),
                    ),
                'GetImLogFile'=>    array(
                    'argv'  =>  array(NAME, STR, STR, NAME),
                    'desc'  =>  _('Get im log file'),
                    ),
                )
            );
    }
Imlogs::ImGetFiles ($ proto = '', $ localuser = '', $ remoteuser = '')
Todo:
Name clash with the Model method GetFiles(), but PHP overloading does not allow redeclaration with different signature
Attention:
Double quotes is necessary for group chats, which contain curly braces in the path names
Definition at line 86 of file imlogs.php.
References Model::GetFiles().
Referenced by GetSessions().
    {
        return $this->GetFiles('"'.$this->logsDir.$proto.$localuser.$remoteuser.'"');
    }
Imlogs::GetDirs ($ proto = '', $ localuser = '')
Attention:
Double quotes is necessary for group chats, which contain curly braces in the path names
Definition at line 92 of file imlogs.php.
References $file, and Model::GetFiles().
Referenced by GetLocalUsers(), GetProtocols(), and GetRemoteUsers().
    {
        $path= $proto.$localuser;
        $files= $this->GetFiles('"'.$this->logsDir.$path.'"');
        $files= explode("\n", $files);
        $dirs= array();
        foreach ($files as $file) {
            if (is_dir($this->logsDir."$path/$file")) {
                $dirs[]= $file;
            }
        }
        return implode("\n", $dirs);
    }
Imlogs::GetProtocols ()
Definition at line 108 of file imlogs.php.
References GetDirs().
Referenced by Imlogs().
    {
        return $this->GetDirs();
    }
Imlogs::GetLocalUsers ($ proto)
Definition at line 113 of file imlogs.php.
References GetDirs().
Referenced by Imlogs().
    {
        return $this->GetDirs("/$proto");
    }
Imlogs::GetRemoteUsers ($ proto, $ localuser)
Definition at line 118 of file imlogs.php.
References GetDirs().
Referenced by Imlogs().
    {
        return $this->GetDirs("/$proto", "/$localuser");
    }
Imlogs::GetSessions ($ proto, $ localuser, $ remoteuser)
Definition at line 123 of file imlogs.php.
References ImGetFiles().
Referenced by Imlogs().
    {
        return $this->ImGetFiles("/$proto", "/$localuser", "/$remoteuser");
    }
Imlogs::GetImLogFile ($ proto, $ localuser, $ remoteuser, $ session)
Definition at line 128 of file imlogs.php.
Referenced by Imlogs().
    {
        return $this->logsDir."/$proto/$localuser/$remoteuser/$session";
    }
Imlogs::ParseLogLine ($ logline, &$ cols)
Log parser.
Parameters:
[in] $logline string Log line
[out] $cols array Parsed fields
Returns:
TRUE if log line is parsed
Reimplemented from Model.
Definition at line 133 of file imlogs.php.
    {
        $re_ip= '\d{1,3}\.\d{1,3}\.\d{1,3}\.\d{1,3}';
        $re_port= '\d{1,5}';
        $re_ipport= "($re_ip:$re_port)";
        $re_datetime= '(\d+)';
        $re_num= '(\d+|)';
        $re_rest= '(.*)';
        $re= "/^$re_ipport,$re_datetime,$re_num,$re_num,$re_num,$re_num,$re_rest$/";
        if (preg_match($re, $logline, $match)) {
            $cols['IPPort']= $match[1];
            $cols['Date']= date("Y.m.d", $match[2]);
            $cols['Time']= date("H:i:s", $match[2]);
            //$cols['User']= $match[3];
            $cols['User']= $match[3] + 1;
            $cols['Log']= $match[7];
            return TRUE;
        }
        else {
            $re= "/^$re_ipport,$re_datetime,$re_num,$re_num,$re_rest$/";
            if (preg_match($re, $logline, $match)) {
                $cols['IPPort']= $match[1];
                $cols['Date']= date("Y.m.d", $match[2]);
                $cols['Time']= date("H:i:s", $match[2]);
                $cols['User']= $match[3];
                $cols['Log']= $match[5];
                return TRUE;
            }
        }
        return FALSE;
    }
Imlogs::PrintLogLine ($ cols, $ linenum)
Definition at line 43 of file imlogs.php.
    {
        $this->PrintLogLineClass($cols['User']);
        PrintLogCols($linenum, $cols);
        echo '</tr>';
    }
Member Data Documentation
Imlogs::$Model = 'imlogs'
Reimplemented from View.
Definition at line 41 of file imlogs.php.
The documentation for this class was generated from the following files:
Model/imlogs.php
View/imspector/imlogs.php