ComixWall ISG Administration Interface: Dhcpd Class Reference
Dhcpd Class Reference
Public Member Functions
Dhcpd ()
Start ()
Start module process(es).
GetIfs ()
Provides the list of dhcpd interfaces.
AddIf ($if)
Adds a dhcpd interface.
DelIf ($if)
Deletes a dhcpd interface.
SetIfs ($ifs)
Sets ifs.
GetOption ($option)
Reads a dhcpd option.
GetRange ()
Reads dhcpd range option.
SetOptions ($dns, $router, $mask, $bc, $lr, $ur)
Set dhcpd configuration.
SetOption ($option, $value)
Changes a dhcpd option.
SetRange ($lower, $upper)
Changes dhcpd range option.
SetDhcpdConf ($lanip, $lanmask, $lannet, $lanbc, $lanmin, $lanmax)
GetArpTable ()
Get arp table.
GetLeases ()
Dhcpd ()
Public Attributes
$Name = 'dhcpd'
$User = '_dhcp'
$ConfFile = '/etc/dhcpd.conf'
$LogFile = '/var/log/dhcpd.log'
$Model = 'dhcpd'
$Layout = 'dhcpd'
Detailed Description
Definition at line 38 of file dhcpd.php.
Member Function Documentation
Dhcpd::Dhcpd ()
Definition at line 50 of file dhcpd.php.
References AddIf(), DelIf(), GetArpTable(), GetIfs(), GetLeases(), GetOption(), GetRange(), Model, SetDhcpdConf(), and SetOptions().
    {
        parent::Model();
        $this->Commands= array_merge(
            $this->Commands,
            array(
                'GetIfs'    => array(
                    'argv'  => array(),
                    'desc'  => _('Get DHCP interfaces'),
                    ),
                'GetOption' => array(
                    'argv'  => array(NAME),
                    'desc'  => _('Get DHCP option'),
                    ),
                'GetRange'  =>  array(
                    'argv'  => array(),
                    'desc'  => _('Get DHCP IP range'),
                    ),
                'AddIf' =>  array(
                    'argv'  => array(NAME),
                    'desc'  => _('Add DHCP interface'),
                    ),
                'DelIf' =>  array(
                    'argv'  => array(NAME),
                    'desc'  => _('Delete DHCP interface'),
                    ),
                'GetArpTable'   =>  array(
                    'argv'  => array(),
                    'desc'  => _('Get arp table'),
                    ),
                'GetLeases' =>  array(
                    'argv'  => array(),
                    'desc'  => _('Get dhcp leases'),
                    ),
                'SetOptions'=>  array(
                    'argv'  => array(IPADR, IPADR, IPADR, IPADR, IPADR, IPADR),
                    'desc'  => _('Set configuration'),
                    ),
                'SetDhcpdConf'  =>  array(
                    'argv'  => array(IPADR, IPADR, IPADR, IPADR, IPADR, IPADR),
                    'desc'  => _('Set dhcpd conf'),
                    ),
                )
            );
    }
Dhcpd::Start ()
Start module process(es).
Tries PROC_STAT_TIMEOUT times.
Returns:
boolean TRUE if the process starts
Todo:
Actually should stop retying on some error conditions?
Todo:
Check $TmpFile for error messages, if so break out instead
Reimplemented from Model.
Definition at line 105 of file dhcpd.php.
References GetIfs(), and Model::RunShellCommand().
    {
        if (($ifs= $this->GetIfs()) !== FALSE) {
            $ifs= explode("\n", $ifs);
            $ifs= implode(' ', $ifs);
            return $this->RunShellCommand("/usr/sbin/dhcpd $ifs");
        }
        return FALSE;
    }
Dhcpd::GetIfs ()
Provides the list of dhcpd interfaces.
Returns:
List of interfaces.
Definition at line 119 of file dhcpd.php.
References Model::SearchFile().
Referenced by AddIf(), DelIf(), Dhcpd(), and Start().
    {
        $ifs= $this->SearchFile($this->rcConfLocal, '/^\h*#*\h*dhcpd_flags\h*=\h*("[^#"]*"|)(\h*|\h*#.*)$/m', 1, '"');
        return implode ("\n", preg_split('/\h+/', $ifs));
    }
Dhcpd::AddIf ($ if)
Adds a dhcpd interface.
Cleans up duplicates first
Parameters:
[in] $if Interface name.
Definition at line 131 of file dhcpd.php.
References DelIf(), GetIfs(), and SetIfs().
Referenced by Dhcpd().
    {
        $this->DelIf($if);
        if (($ifs= $this->GetIfs()) !== FALSE) {
            $ifs= explode("\n", $ifs);
            $ifs= trim(implode(' ', $ifs)." $if");
            return $this->SetIfs($ifs);
        }
        return FALSE;
    }
Dhcpd::DelIf ($ if)
Deletes a dhcpd interface.
Parameters:
[in] $if Interface name.
Definition at line 146 of file dhcpd.php.
References GetIfs(), and SetIfs().
Referenced by AddIf(), and Dhcpd().
    {
        if (($ifs= $this->GetIfs()) !== FALSE) {
            $ifs= explode("\n", $ifs);
            // Don't use: unset($ifs[array_search($if, $ifs)]), check strictly
            if (($key= array_search($if, $ifs)) !== FALSE) {
                echo array_search($if, $ifs)."\n";
                unset($ifs[$key]);
                $ifs= implode(' ', $ifs);
                return $this->SetIfs($ifs);
            }
        }
        return FALSE;
    }
Dhcpd::SetIfs ($ ifs)
Sets ifs.
Parameters:
[in] $ifs List of ifs.
Definition at line 166 of file dhcpd.php.
References Model::ReplaceRegexp().
Referenced by AddIf(), and DelIf().
    {
        return $this->ReplaceRegexp($this->rcConfLocal, '/^(\h*#*\h*dhcpd_flags\h*=\h*)("[^#"]*"|)(\h*|\h*#.*)$/m', '${1}"'.$ifs.'"${3}');
    }
Dhcpd::GetOption ($ option)
Reads a dhcpd option.
DHCP server options are usually IPs. Range is read by GetRange().
Parameters:
[in] $option Option name to get value of.
Returns:
Option value.
Definition at line 178 of file dhcpd.php.
Referenced by Dhcpd().
    {
        return $this->SearchFile($this->ConfFile, "/^\h*option\h*$option\h*([^#;]*)\h*\;\h*$/m");
    }
Dhcpd::GetRange ()
Reads dhcpd range option.
Returns:
IP range.
Definition at line 187 of file dhcpd.php.
Referenced by Dhcpd().
    {
        global $Re_Ip;
        $re= "/^\h*range\h*(($Re_Ip)\h*($Re_Ip))\h*\;\h*$/m";
        if (($output= $this->SearchFile($this->ConfFile, $re)) !== FALSE) {
            return preg_replace("/\s+/", "\n", $output);
        }
        return FALSE;
    }
Dhcpd::SetOptions ($ dns, $ router, $ mask, $ bc, $ lr, $ ur)
Set dhcpd configuration.
Parameters:
[in] $dns DNS server.
[in] $router Gateway.
[in] $mask Netmask.
[in] $bc Broadcast address.
[in] $lr Lower IP range.
[in] $ur Upper IP range.
Returns:
TRUE on success.
Definition at line 208 of file dhcpd.php.
Referenced by Dhcpd().
    {
        $retval=  $this->SetOption('domain-name-servers', $dns);
        $retval&= $this->SetOption('routers', $router);
        $retval&= $this->SetOption('subnet-mask', $mask);
        $retval&= $this->SetOption('broadcast-address', $bc);
        $retval&= $this->SetRange($lr, $ur);
        return $retval;
    }
Dhcpd::SetOption ($ option, $ value)
Changes a dhcpd option.
Parameters:
[in] $option Option name to get value of.
[in] $value Option value to set.
Returns:
Option value.
Definition at line 224 of file dhcpd.php.
    {
        global $Re_Ip;
        return $this->ReplaceRegexp($this->ConfFile, "/^(\h*option\h*$option\b\h*)($Re_Ip)(\h*\;\h*)$/m", '${1}'.$value.'${3}');
    }
Dhcpd::SetRange ($ lower, $ upper)
Changes dhcpd range option.
Parameters:
[in] $lower Lower limit of IP range.
[in] $upper Upper limit of IP range.
Definition at line 236 of file dhcpd.php.
    {
        global $Re_Ip;
        return $this->ReplaceRegexp($this->ConfFile, "/^(\h*range\h*)($Re_Ip)(\h+)($Re_Ip)(\h*\;\h*)$/m", '${1}'.$lower.'${3}'.$upper.'${5}');
    }
Dhcpd::SetDhcpdConf ($ lanip, $ lanmask, $ lannet, $ lanbc, $ lanmin, $ lanmax)
Definition at line 243 of file dhcpd.php.
References $Re_Ip.
Referenced by Dhcpd().
    {
        global $Re_Ip;
        $retval=  $this->ReplaceRegexp($this->ConfFile, "/^(\h*subnet\h+)($Re_Ip)(\h+netmask\h+$Re_Ip\h*\{.*)/m", '${1}'.$lannet.'${3}');
        $retval&= $this->ReplaceRegexp($this->ConfFile, "/^(\h*subnet\h+$Re_Ip\h+netmask\h+)($Re_Ip)(\h*\{.*)/m", '${1}'.$lanmask.'${3}');
        $retval&= $this->SetOptions($lanip, $lanip, $lanmask, $lanbc, $lanmin, $lanmax);
        return $retval;
    }
Dhcpd::GetArpTable ()
Get arp table.
Definition at line 255 of file dhcpd.php.
Referenced by Dhcpd().
    {
        $lines= $this->RunShellCommand('/usr/sbin/arp -an');
        // ? (10.0.0.2) at 00:d0:da:51:d3:c0 on em1
        $re_arp= "/^\? \((.*)\) at (.*) on (.*)$/m";
        $logs= array();
        if (preg_match_all($re_arp, $lines, $match, PREG_SET_ORDER)) {
            foreach ($match as $fields) {
                $cols['IP']= $fields[1];
                $cols['MAC']= $fields[2];
                $cols['Interface']= $fields[3];
                $logs[]= $cols;
            }
        }
        return serialize($logs);
    }
Dhcpd::GetLeases ()
Definition at line 274 of file dhcpd.php.
Referenced by Dhcpd().
    {
        global $Re_Ip;
        // lease 192.168.1.1 {
        //         starts 2 2009/09/08 17:52:36;
        //         ends 3 2009/09/09 05:52:36;
        //         hardware ethernet 00:1f:e2:61:96:9a;
        //         client-hostname "phenom";
        // }
        // lease 192.168.1.2 {
        //         starts 4 2009/09/10 21:26:28;
        //         ends 5 2009/09/11 09:26:28;
        //         hardware ethernet 00:00:f0:76:85:9e;
        //         uid 01:00:00:f0:76:85:9e;
        //         client-hostname "laptop";
        $re_starts= '\s*starts\s+(\d+)\s+(\d+\/\d+\/\d+)\s+(\d+:\d+:\d+)\s*';
        $re_ends= '\s*ends\s+(\d+)\s+(\d+\/\d+\/\d+)\s+(\d+:\d+:\d+)\s*';
        $re_mac= '\s*hardware\s+\w+\s+(\w+:\w+:\w+:\w+:\w+:\w+)\s*';
        $re_uid= '\s*uid\s+(.+)\s*';
        $re_host= '\s*(client-hostname|hostname)\s+"(.+)"\s*';
        $re_abandoned= '(\s*(abandoned);\s*|)';
        $re_lease= "/\s*lease\s+($Re_Ip)\s*\{$re_starts;$re_ends;$re_mac;($re_uid;|)$re_host;$re_abandoned\s*\}\s*/m";
        $lines= $this->GetFile($this->leasesFile);
        $logs= array();
        if (preg_match_all($re_lease, $lines, $match, PREG_SET_ORDER)) {
            foreach ($match as $fields) {
                $cols['IP']= $fields[1];
                $cols['Starts (GMT)']= "$fields[3] $fields[4]";
                $cols['Ends (GMT)']= "$fields[6] $fields[7]";
                $cols['MAC']= $fields[8];
                $cols['Host']= "$fields[12]";
                $cols['Status']= $fields[14];
                $logs[]= $cols;
            }
        }
        return serialize($logs);
    }
Dhcpd::Dhcpd ()
Definition at line 44 of file include.php.
References _HELPWINDOW().
    {
        $this->LogsHelpMsg= _HELPWINDOW('DHCP server logs the details of communications with DHCP clients.');
    }
Member Data Documentation
Dhcpd::$Name = 'dhcpd'
Reimplemented from Model.
Definition at line 40 of file dhcpd.php.
Dhcpd::$User = '_dhcp'
Reimplemented from Model.
Definition at line 41 of file dhcpd.php.
Dhcpd::$ConfFile = '/etc/dhcpd.conf'
Reimplemented from Model.
Definition at line 46 of file dhcpd.php.
Dhcpd::$LogFile = '/var/log/dhcpd.log'
Reimplemented from Model.
Definition at line 48 of file dhcpd.php.
Dhcpd::$Model = 'dhcpd'
Reimplemented from View.
Definition at line 41 of file include.php.
Dhcpd::$Layout = 'dhcpd'
Reimplemented from View.
Definition at line 42 of file include.php.
The documentation for this class was generated from the following files:
Model/dhcpd.php
View/dhcpd/include.php