ComixWall ISG Administration Interface: Lexer Class Reference
Lexer Class Reference
Public Member Functions
Lexer ()
is_eof ()
load ($filename= '')
next_token ()
parse_error ($errorstring, $lineno=0)
parse_semicolon ()
unget ($token)
_get_chr ()
_get_chr_and_nl ()
_get_next_line ()
_next_token ()
_get_quoted_string ($quote)
_unget_chr ($ch)
_display ()
_test ()
Public Attributes
$filename
$lineno
$lineitems
$line
$buffer
$token
$unget
$keywordchrs
Detailed Description
Definition at line 38 of file class_lexer.inc.
Member Function Documentation
Lexer::Lexer ()
Definition at line 48 of file class_lexer.inc.
References unget().
                     {
    $this->filename = '';
    $this->lineno = 0;
    $this->buffer = array();
    $this->line = array();
    $this->eof = 0;
    $this->token = '';
    $this->unget = array();
    $this->keywordchrs = '/ABCDEFGHIJKLMNOPQRSTUVWXYZabcdefghijklmnopqrstuvwxyz0123456789-_.';
    }
Lexer::is_eof ()
Definition at line 59 of file class_lexer.inc.
                      {
    return $this->eof;
    }
Lexer::load ($ filename = '')
Definition at line 63 of file class_lexer.inc.
References $buffer, $filename, $symon, and layout.
Referenced by _test().
{
    global $symon;
    if ($filename == '') {
        runtime_error('layout parser: no file to load');
    }
    $filename = normalise_filename($filename);
    $filename = $symon['layout_dir'].'/'.normalise_filename($filename).'.layout';
    $this->filename = $filename;
    $buffer = load($filename);
    $this->buffer = preg_split("/\n/", $buffer);
    }
Lexer::next_token ()
Definition at line 76 of file class_lexer.inc.
References $symon, $token, _display(), and _next_token().
Referenced by _next_token(), _test(), and parse_semicolon().
{
    global $symon;
    $token = $this->_next_token();
    if (isset($symon['lexer_debug'])) {
        $this->_display();
    }
    return $token;
    }
Lexer::parse_error ($ errorstring, $ lineno = 0)
Definition at line 88 of file class_lexer.inc.
References $lineno.
Referenced by _get_quoted_string(), and parse_semicolon().
{
    if ($lineno == 0) {
        $lineno = $this->lineno;
    }
    runtime_error("parse error: $this->filename : $lineno : '$this->token' : $errorstring");
    }
Lexer::parse_semicolon ()
Definition at line 96 of file class_lexer.inc.
References $token, next_token(), and parse_error().
{
    if ($this->eof) {
        $this->parse_error('Expected ;');
    }
    $token = $this->next_token();
    if ($token != ';') {
        $this->parse_error('Expected ;');
    }
    }
Lexer::unget ($ token)
Definition at line 106 of file class_lexer.inc.
References _unget_chr().
Referenced by _display(), _get_chr_and_nl(), _unget_chr(), and Lexer().
{
    $items = preg_split('//', $token, -1, PREG_SPLIT_NO_EMPTY);
    foreach ($items as $k => $item) {
        $this->_unget_chr($item);
    }
    }
Lexer::_get_chr ()
Definition at line 113 of file class_lexer.inc.
References _get_chr_and_nl().
Referenced by _next_token().
{
    $item = $this->_get_chr_and_nl();
    if ($item == "\n") {
        $item = ' ';
    }
    return $item;
    }
Lexer::_get_chr_and_nl ()
Definition at line 121 of file class_lexer.inc.
References _get_next_line(), and unget().
Referenced by _get_chr(), and _get_quoted_string().
{
    if ($this->eof) {
        runtime_error('internal: trying to get_chr while eof has been signalled');
    }
    if (count($this->unget)) {
        return array_shift($this->unget);
    }
    $item = '';
    while ($item == '') {
        if (count($this->lineitems) == 0) {
        $this->_get_next_line();
        if ($this->eof) {
            return;
        }
        return "\n";
        }
        $item = array_shift($this->lineitems);
    }
    return $item;
    }
Lexer::_get_next_line ()
Definition at line 142 of file class_lexer.inc.
Referenced by _get_chr_and_nl(), and _next_token().
{
    if ($this->eof) {
        runtime_error('internal: trying to get_next_line while eof has been signalled');
    }
    if (count($this->buffer) == 0) {
        $this->eof = 1;
        return;
    }
    $this->line = array_shift($this->buffer);
    $this->lineno += 1;
    $this->lineitems = preg_split('//', $this->line, -1, PREG_SPLIT_NO_EMPTY);
    }
Lexer::_next_token ()
Definition at line 155 of file class_lexer.inc.
References _get_chr(), _get_next_line(), _get_quoted_string(), _unget_chr(), and next_token().
Referenced by next_token().
{
    if ($this->eof) {
        runtime_error('internal: trying next_token while eof has been signalled');
    }
    $this->token = '';
    $ch = $this->_get_chr();
    while ($this->eof || !(strpos(" \t\r\n#", $ch) === FALSE)) {
        if ($this->eof) {
        return;
        }
        if ($ch == '#') {
        $this->_get_next_line();
        }
        $ch = $this->_get_chr();
    }
    if ($this->eof) {
        $this->token = '';
        return $this->token;
    }
    if ($ch == '"') {
        $this->token = $this->_get_quoted_string('"');
        return $this->token;
    }
    if ($ch == "'") {
        $this->token = $this->_get_quoted_string("'");
        return $this->token;
    }
    if (!(strpos($this->keywordchrs, $ch) === FALSE)) {
        $this->token = '';
        while (!(strpos($this->keywordchrs, $ch) === FALSE) || $this->eof) {
        $this->token .= $ch;
        $ch = $this->_get_chr();
        }
        if (!$this->eof) {
        $this->_unget_chr($ch);
        }
        return $this->token;
    }
    $this->token = $ch;
    return $this->token;
    }
Lexer::_get_quoted_string ($ quote)
Definition at line 201 of file class_lexer.inc.
References _get_chr_and_nl(), and parse_error().
Referenced by _next_token().
{
    $start_lineno = $this->lineno;
    $this->token = '';
    $delimited = 0;
    $ch = $this->_get_chr_and_nl();
    while ($ch != $quote) {
        if ($this->eof) {
        $this->parse_error("starting $quote without closing $quote", $start_lineno);
        return;
        }
        if ($ch == "\\" && $quote == '"') {
        $ch = $this->_get_chr_and_nl();
        }
        $this->token .= $ch;
        $ch = $this->_get_chr_and_nl();
    }
    return $this->token;
    }
Lexer::_unget_chr ($ ch)
Definition at line 222 of file class_lexer.inc.
References unget().
Referenced by _next_token(), and unget().
{
    $this->unget[] = $ch;
    }
Lexer::_display ()
Definition at line 226 of file class_lexer.inc.
References print, and unget().
Referenced by next_token().
{
    print "<pre>\xa -- token = $this->token";
    print "\xa lexing $this->filename:$this->lineno";
    print "\xa line = $this->line";
    print "\xa items = ";
    if (count($this->lineitems)) {
        foreach ($this->lineitems as $k => $item) {
        print $item. '|';
        }
    }
    print "\xa unget = ";
    if (count($this->unget) > 0) {
        foreach ($this->unget as $item) {
        print $item. '|';
        }
    }
    print "\xa eof = $this->eof </pre>";
    }
Lexer::_test ()
Definition at line 245 of file class_lexer.inc.
References $symon, $token, load(), and next_token().
                     {
    global $symon;
    $this->load('hifn_test.layout');
    while(!$this->eof) {
        $token = $this->next_token();
    }
    }
Member Data Documentation
Lexer::$filename
Definition at line 39 of file class_lexer.inc.
Referenced by load().
Lexer::$lineno
Definition at line 40 of file class_lexer.inc.
Referenced by parse_error().
Lexer::$lineitems
Definition at line 41 of file class_lexer.inc.
Lexer::$line
Definition at line 42 of file class_lexer.inc.
Lexer::$buffer
Definition at line 43 of file class_lexer.inc.
Referenced by load().
Lexer::$token
Definition at line 44 of file class_lexer.inc.
Referenced by _test(), next_token(), and parse_semicolon().
Lexer::$unget
Definition at line 45 of file class_lexer.inc.
Lexer::$keywordchrs
Definition at line 46 of file class_lexer.inc.
The documentation for this class was generated from the following file:
View/symon/class_lexer.inc