ComixWall ISG Administration Interface: Openssh Class Reference
Openssh Class Reference
Public Member Functions
Openssh ()
ParseLogLine ($logline, &$cols)
Log parser.
GetFileLineCount ($file, $re= '')
Gets line count of file.
GetLogs ($file, $end, $count, $re= '')
Gets lines in file.
GetLiveLogs ($file, $count, $re= '')
Gets logs for live logs pages.
Openssh ()
Public Attributes
$Name = 'openssh'
$User = 'root'
$NVPS = '\h'
$ConfFile = '/etc/ssh/sshd_config'
$LogFile = '/var/log/authlog'
$VersionCmd = '/usr/bin/ssh -V 2>&1'
$PidFile = '/var/run/sshd.pid'
$Model = 'openssh'
$Layout = 'sshd'
Detailed Description
Definition at line 38 of file openssh.php.
Member Function Documentation
Openssh::Openssh ()
Definition at line 51 of file openssh.php.
References $TmpFile, and Model.
    {
        global $TmpFile;
        parent::Model();
        $this->Proc= 'sshd';
        $this->StartCmd= "/usr/sbin/sshd > $TmpFile 2>&1 &";
    }
Openssh::ParseLogLine ($ logline, &$ cols)
Log parser.
Parameters:
[in] $logline string Log line
[out] $cols array Parsed fields
Returns:
TRUE if log line is parsed
Reimplemented from Model.
Definition at line 61 of file openssh.php.
References $Re_Ip, and Model::ParseSyslogLine().
Referenced by GetLiveLogs(), and GetLogs().
    {
        global $Re_Ip;
        if ($this->ParseSyslogLine($logline, $cols)) {
            $re_user= '((invalid user\s+|)(\S+))';
            $re_clientip= "($Re_Ip)";
            $re_num= '(\d+)';
            $re_type= '(.*)';
            // Failed password for invalid user soner from 81.215.105.114 port 27836 ssh2
            // Failed password for root from 81.215.105.114 port 29782 ssh2
            // Failed none for invalid user soner from 81.215.105.114 port 40401 ssh2
            $re= "/Failed\s+(.*)\s+for\s+$re_user\s+from\s+$re_clientip\s+port\s+$re_num\s+$re_type$/";
            if (preg_match($re, $logline, $match)) {
                $cols['Reason']= $match[1];
                $cols['User']= $match[4];
                $cols['IP']= $match[5];
                $cols['Type']= $match[7];
            }
            else {
                // Accepted password for root from 81.215.105.114 port 47179 ssh2
                // Accepted publickey for root from 81.215.105.114 port 58402 ssh2
                $re= "/Accepted\s+(.*)\s+for\s+$re_user\s+from\s+$re_clientip\s+port\s+$re_num\s+$re_type$/";
                if (preg_match($re, $logline, $match)) {
                    $cols['User']= $match[4];
                    $cols['IP']= $match[5];
                    $cols['Type']= $match[7];
                }
            }
            return TRUE;
        }
        return FALSE;
    }
Openssh::GetFileLineCount ($ file, $ re = '')
Gets line count of file.
Parameters:
[in] $file string Log file pathname
[in] $re string Regexp to get count of a restricted result set
Returns:
int Line count
Warning:
Input redirection is necessary, otherwise wc adds file name to its output too
Reimplemented from Model.
Definition at line 96 of file openssh.php.
References Model::RunShellCommand().
    {
        $cmd= "/usr/bin/grep -a ' sshd\[' $file";
        if ($re !== '') {
            $re= escapeshellarg($re);
            $cmd.= " | /usr/bin/grep -a $re";
        }
        $cmd.= ' | /usr/bin/wc -l';
        // OpenBSD wc returns with leading blanks
        return trim($this->RunShellCommand($cmd));
    }
Openssh::GetLogs ($ file, $ end, $ count, $ re = '')
Gets lines in file.
Parameters:
[in] $file string Log file pathname
[in] $end int Head option, start line
[in] $count int Tail option, page line count
[in] $re string Regexp to restrict the result set
Returns:
serialized Log lines
Reimplemented from Model.
Definition at line 109 of file openssh.php.
References $logs, ParseLogLine(), and Model::RunShellCommand().
    {
        $cmd= "/usr/bin/grep -a ' sshd\[' $file";
        if ($re !== '') {
            $re= escapeshellarg($re);
            $cmd.= " | /usr/bin/grep -a $re";
        }
        $cmd.= " | /usr/bin/head -$end | /usr/bin/tail -$count";
        $lines= explode("\n", $this->RunShellCommand($cmd));
        $logs= array();
        foreach ($lines as $line) {
            unset($cols);
            if ($this->ParseLogLine($line, $cols)) {
                $logs[]= $cols;
            }
        }
        return serialize($logs);
    }
Openssh::GetLiveLogs ($ file, $ count, $ re = '')
Gets logs for live logs pages.
Used to extract lines in last section of the log file or of the lines grep'd.
Difference from the archives method is that this one always gets the tail of the log or grepped lines.
Parameters:
[in] $file string Log file
[in] $count int Tail lenght, page line count
[in] $re string Regexp to restrict the result set
Returns:
serialized Log lines
Reimplemented from Model.
Definition at line 130 of file openssh.php.
References $logs, ParseLogLine(), and Model::RunShellCommand().
    {
        $cmd= "/usr/bin/grep -a ' sshd\[' $file";
        if ($re !== '') {
            $re= escapeshellarg($re);
            $cmd.= " | /usr/bin/grep -a $re";
        }
        $cmd.= " | /usr/bin/tail -$count";
        $lines= explode("\n", $this->RunShellCommand($cmd));
        $logs= array();
        foreach ($lines as $line) {
            if ($this->ParseLogLine($line, $cols)) {
                $logs[]= $cols;
            }
        }
        return serialize($logs);
    }
Openssh::Openssh ()
Definition at line 44 of file include.php.
References _HELPBOX2(), _HELPWINDOW(), _TITLE2(), ConfHelpMsg, and Config.
    {
        $this->LogsHelpMsg= _HELPWINDOW('OpenSSH logs detailed information on all connections, successful logins and failures. Also provided are warnings based on reverse DNS lookups.');
        $this->ConfHelpMsg= _HELPWINDOW('Thanks to OpenSSH, remote root login to the system is permitted by default. TCP Keep Alive and Use DNS options may help you resolve some issues.');
        $this->Config = array(
            'Port' => array(
                'title' => _TITLE2('Port'),
                'info' => _HELPBOX2('The strategy used for options in the default sshd_config shipped with OpenSSH is to specify options with their default value where possible, but leave them commented.  Uncommented options change a default value.'),
                ),
            'Protocol' => array(
                'title' => _TITLE2('Protocol'),
                ),
            'AddressFamily' => array(
                'title' => _TITLE2('Address Family'),
                ),
            'ListenAddress' => array(
                'title' => _TITLE2('Listen Address'),
                ),
            'ServerKeyBits' => array(
                'title' => _TITLE2('Server Key Bits'),
                ),
            'SyslogFacility' => array(
                'title' => _TITLE2('Syslog Facility'),
                'info' => _HELPBOX2('Obsoletes QuietMode and FascistLogging'),
                ),
            'LogLevel' => array(
                'title' => _TITLE2('Log Level'),
                ),
            'LoginGraceTime' => array(
                'title' => _TITLE2('Login Grace Time'),
                ),
            'PermitRootLogin' => array(
                'title' => _TITLE2('Permit Root Login'),
                ),
            'MaxAuthTries' => array(
                'title' => _TITLE2('Max Auth Tries'),
                ),
            'PermitEmptyPasswords' => array(
                'title' => _TITLE2('Permit Empty Passwords'),
                ),
            'PrintMotd' => array(
                'title' => _TITLE2('Print Motd'),
                ),
            'PrintLastLog' => array(
                'title' => _TITLE2('Print Last Log'),
                ),
            'TCPKeepAlive' => array(
                'title' => _TITLE2('TCP Keep Alive'),
                ),
            'UseDNS' => array(
                'title' => _TITLE2('Use DNS'),
                ),
            'MaxStartups' => array(
                'title' => _TITLE2('MaxStartups'),
                ),
            'Banner' => array(
                'title' => _TITLE2('Banner'),
                'info' => _HELPBOX2('No default banner path'),
                ),
            'Subsystem\s+sftp' => array(
                'title' => _TITLE2('Subsystem sftp'),
                'info' => _HELPBOX2('Override default of no subsystems'),
                ),
        );
    }
Member Data Documentation
Openssh::$Name = 'openssh'
Reimplemented from Model.
Definition at line 40 of file openssh.php.
Openssh::$User = 'root'
Reimplemented from Model.
Definition at line 41 of file openssh.php.
Openssh::$NVPS = '\h'
Reimplemented from Model.
Definition at line 43 of file openssh.php.
Openssh::$ConfFile = '/etc/ssh/sshd_config'
Reimplemented from Model.
Definition at line 44 of file openssh.php.
Openssh::$LogFile = '/var/log/authlog'
Reimplemented from Model.
Definition at line 45 of file openssh.php.
Openssh::$VersionCmd = '/usr/bin/ssh -V 2>&1'
Reimplemented from Model.
Definition at line 47 of file openssh.php.
Openssh::$PidFile = '/var/run/sshd.pid'
Reimplemented from Model.
Definition at line 49 of file openssh.php.
Openssh::$Model = 'openssh'
Reimplemented from View.
Definition at line 41 of file include.php.
Openssh::$Layout = 'sshd'
Reimplemented from View.
Definition at line 42 of file include.php.
The documentation for this class was generated from the following files:
Model/openssh.php
View/openssh/include.php