ComixWall ISG Administration Interface: Imspector Class Reference
Imspector Class Reference
Public Member Functions
Imspector ()
GetVersion ()
Gets software version string.
SetConfig ($confname)
Sets configuration file based on config type provided.
GetBadwords ()
AddBadword ($badword)
DelBadword ($badword)
GetAcl ()
AddAcl ($acl)
DelAcl ($acl)
MoveAclUp ($acl)
MoveAclDown ($acl)
Imspector ()
Public Attributes
$Name = 'imspector'
$User = '_imspector'
$ConfFile = '/etc/imspector/imspector.conf'
$LogFile = '/var/log/imspector.log'
$PidFile = '/var/run/imspector.pid'
$Model = 'imspector'
$Layout = 'imspector'
Detailed Description
Definition at line 42 of file imspector.php.
Member Function Documentation
Imspector::Imspector ()
Definition at line 55 of file imspector.php.
References $TmpFile, AddAcl(), AddBadword(), DelAcl(), DelBadword(), GetAcl(), GetBadwords(), Model, MoveAclDown(), and MoveAclUp().
    {
        global $TmpFile;
        parent::Model();
        $this->StartCmd= "/usr/local/sbin/imspector -c $this->ConfFile > $TmpFile 2>&1 &";
        $this->Commands= array_merge(
            $this->Commands,
            array(
                'GetBadwords'=> array(
                    'argv'  =>  array(),
                    'desc'  =>  _('Get badwords'),
                    ),
                'AddBadword'=>  array(
                    'argv'  =>  array(STR),
                    'desc'  =>  _('Add badword'),
                    ),
                'DelBadword'=>  array(
                    'argv'  =>  array(STR),
                    'desc'  =>  _('Delete badword'),
                    ),
                'GetAcl'=>  array(
                    'argv'  =>  array(),
                    'desc'  =>  _('Get ACL'),
                    ),
                'AddAcl'=>  array(
                    'argv'  =>  array(STR),
                    'desc'  =>  _('Add ACL'),
                    ),
                'DelAcl'=>  array(
                    'argv'  =>  array(STR),
                    'desc'  =>  _('Delete ACL'),
                    ),
                'MoveAclUp'=>   array(
                    'argv'  =>  array(STR),
                    'desc'  =>  _('Move ACL Up'),
                    ),
                'MoveAclDown'=> array(
                    'argv'  =>  array(STR),
                    'desc'  =>  _('Move ACL Down'),
                    ),
                )
            );
    }
Imspector::GetVersion ()
Gets software version string.
Reimplemented from Model.
Definition at line 109 of file imspector.php.
    {
        return 'IMSpector 0.9';
    }
Imspector::SetConfig ($ confname)
Sets configuration file based on config type provided.
Certain modules have configuration divided into multiple pages/files, hence they override this method.
Parameters:
[in] $confname string Config type
Reimplemented from Model.
Definition at line 114 of file imspector.php.
References $aclConfig, $badwordsConfig, $basicConfig, and Config.
    {
        global $basicConfig, $badwordsConfig, $aclConfig;
        $this->Config= ${$confname};
    }
Imspector::GetBadwords ()
Definition at line 121 of file imspector.php.
References Model::GetFile().
Referenced by Imspector().
    {
        return $this->GetFile($this->badwordsFile);
    }
Imspector::AddBadword ($ badword)
Definition at line 126 of file imspector.php.
References Model::AppendToFile(), and DelBadword().
Referenced by Imspector().
    {
        $this->DelBadword($badword);
        return $this->AppendToFile($this->badwordsFile, $badword);
    }
Imspector::DelBadword ($ badword)
Definition at line 132 of file imspector.php.
References Escape(), and Model::ReplaceRegexp().
Referenced by AddBadword(), and Imspector().
    {
        $badword= Escape($badword, '/.');
        return $this->ReplaceRegexp($this->badwordsFile, "/^($badword\s)/m", '');
    }
Imspector::GetAcl ()
Definition at line 138 of file imspector.php.
References Model::SearchFileAll().
Referenced by Imspector().
    {
        return $this->SearchFileAll($this->aclFile, "/^\h*((allow|deny)\h+[^\n]+)$/m", 1);
    }
Imspector::AddAcl ($ acl)
Definition at line 143 of file imspector.php.
References Model::AppendToFile(), and DelAcl().
Referenced by Imspector().
    {
        $this->DelAcl($acl);
        return $this->AppendToFile($this->aclFile, $acl);
    }
Imspector::DelAcl ($ acl)
Definition at line 149 of file imspector.php.
References Escape(), and Model::ReplaceRegexp().
Referenced by AddAcl(), and Imspector().
    {
        $acl= Escape($acl, '/.');
        return $this->ReplaceRegexp($this->aclFile, "/^($acl\n)/m", '');
    }
Imspector::MoveAclUp ($ acl)
Definition at line 155 of file imspector.php.
References Escape(), and Model::ReplaceRegexp().
Referenced by Imspector().
    {
        $acl= Escape($acl, '/.');
        return $this->ReplaceRegexp($this->aclFile, "/^\h*((allow|deny)\h+[^\n]+)\n+\h*($acl)\n/m", '${3}'."\n".'${1}'."\n");
    }
Imspector::MoveAclDown ($ acl)
Definition at line 161 of file imspector.php.
References Escape(), and Model::ReplaceRegexp().
Referenced by Imspector().
    {
        $acl= Escape($acl, '/.');
        return $this->ReplaceRegexp($this->aclFile, "/^\h*($acl)\n+\h*((allow|deny)\h+[^\n]+)\n/m", '${2}'."\n".'${1}'."\n");
    }
Imspector::Imspector ()
Definition at line 44 of file include.php.
References _HELPWINDOW().
    {
        $this->LogsHelpMsg= _HELPWINDOW('IM proxy logs contain process errors and notices.');
    }
Member Data Documentation
Imspector::$Name = 'imspector'
Reimplemented from Model.
Definition at line 44 of file imspector.php.
Imspector::$User = '_imspector'
Reimplemented from Model.
Definition at line 45 of file imspector.php.
Imspector::$ConfFile = '/etc/imspector/imspector.conf'
Reimplemented from Model.
Definition at line 47 of file imspector.php.
Imspector::$LogFile = '/var/log/imspector.log'
Reimplemented from Model.
Definition at line 48 of file imspector.php.
Imspector::$PidFile = '/var/run/imspector.pid'
Reimplemented from Model.
Definition at line 53 of file imspector.php.
Imspector::$Model = 'imspector'
Reimplemented from View.
Definition at line 41 of file include.php.
Imspector::$Layout = 'imspector'
Reimplemented from View.
Definition at line 42 of file include.php.
The documentation for this class was generated from the following files:
Model/imspector.php
View/imspector/include.php