ComixWall ISG Administration Interface: Snort Class Reference
Snort Class Reference
Public Member Functions
Snort ()
GetVersion ()
Gets software version string.
Start ($if)
Stop ()
Stops module process(es).
StopProcess ($if)
Stops snort process started with the given interface.
FindPid ($if)
Finds the pid of snort process started with the given inf.
IsInstanceRunning ($if)
Checks if the process(es) is running.
SetConfig ($confname)
Sets configuration file based on config type provided.
GetRules ()
Get list of enabled/uncommented rules.
GetDisabledRules ()
Gets list of disabled/commented rules.
EnableRule ($rule)
DisableRule ($rule)
MoveRuleUp ($rule)
MoveRuleDown ($rule)
SetStartupIfs ($lanif, $wanif)
Snort ()
Public Attributes
$Name = 'snort'
$User = '_snort'
$NVPS = '\h'
$ConfFile = '/etc/snort/snort.conf'
$LogFile = '/var/log/snort/snort.log'
$VersionCmd = '/usr/local/bin/snort -V 2>&1'
$Model = 'snort'
$Layout = 'snort'
Detailed Description
Definition at line 38 of file snort.php.
Member Function Documentation
Snort::Snort ()
Definition at line 51 of file snort.php.
References DisableRule(), EnableRule(), GetDisabledRules(), GetRules(), Model, MoveRuleDown(), MoveRuleUp(), SetStartupIfs(), Model::Start(), Stop(), and StopProcess().
    {
        parent::Model();
        $this->Commands= array_merge(
            $this->Commands,
            array(
                'Start'=>   array(
                    'argv'  =>  array(NAME),
                    'desc'  =>  _('Start snort'),
                    ),
                'StopProcess'=> array(
                    'argv'  => array(NAME),
                    'desc'  => _('Stop Snort instance'),
                    ),
                'GetRules'      =>  array(
                    'argv'  =>  array(),
                    'desc'  =>  _('Get rules'),
                    ),
                'GetDisabledRules'=>    array(
                    'argv'  =>  array(),
                    'desc'  =>  _('Get disabled rules'),
                    ),
                'DisableRule'   =>  array(
                    'argv'  =>  array(NAME),
                    'desc'  =>  _('Disable rule'),
                    ),
                'EnableRule'    =>  array(
                    'argv'  =>  array(NAME),
                    'desc'  =>  _('Enable rule'),
                    ),
                'MoveRuleUp'=>  array(
                    'argv'  =>  array(NAME),
                    'desc'  =>  _('Move rule up'),
                    ),
                'MoveRuleDown'=>    array(
                    'argv'  =>  array(NAME),
                    'desc'  =>  _('Move rule down'),
                    ),
                'SetStartupIfs' =>  array(
                    'argv'  =>  array(NAME, NAME),
                    'desc'  =>  _('Set startup ifs'),
                    ),
                )
            );
    }
Snort::GetVersion ()
Gets software version string.
Reimplemented from Model.
Definition at line 106 of file snort.php.
References Model::RunShellCommand().
    {
        return $this->RunShellCommand($this->VersionCmd.' | /usr/bin/head -3 | /usr/bin/tail -2');
    }
Snort::Start ($ if)
Todo:
Check $TmpFile for error messages, if so break out instead
Start command is redirected to tmp file
Definition at line 111 of file snort.php.
References $TmpFile, cwc_syslog(), IsInstanceRunning(), Model::RunShellCommand(), and ViewError().
    {
        global $TmpFile;
        $cmd= "/usr/local/bin/snort -i $if -D -d -c $this->ConfFile -u _snort -g _snort -b -l /var/snort/log";
        $count= 0;
        while ($count++ < self::PROC_STAT_TIMEOUT) {
            if ($this->IsInstanceRunning($if)) {
                return TRUE;
            }
            $this->RunShellCommand("$cmd > $TmpFile 2>&1");
            exec('/bin/sleep .1');
        }
        $output= file_get_contents($TmpFile);
        ViewError($output);
        cwc_syslog(LOG_ERR, __FILE__, __FUNCTION__, __LINE__, "Start failed with: $output");
        // Check one last time due to the last sleep in the loop
        return $this->IsInstanceRunning($if);
    }
Snort::Stop ()
Stops module process(es).
Tries PROC_STAT_TIMEOUT times.
Returns:
boolean TRUE if the process killed successfully
Todo:
Actually should stop retrying on some error conditions?
Reimplemented from Model.
Definition at line 135 of file snort.php.
References $TmpFile, cwc_syslog(), IsInstanceRunning(), Model::RunShellCommand(), and ViewError().
Referenced by Snort().
    {
        global $TmpFile;
        $cmd= '/usr/bin/pkill -U_snort';
        $count= 0;
        while ($count++ < self::PROC_STAT_TIMEOUT) {
            if (!$this->IsInstanceRunning('\w+')) {
                return TRUE;
            }
            $this->RunShellCommand("$cmd > $TmpFile 2>&1");
            exec('/bin/sleep .1');
        }
        $output= file_get_contents($TmpFile);
        ViewError($output);
        cwc_syslog(LOG_ERR, __FILE__, __FUNCTION__, __LINE__, "Kill failed with: $output");
        // Check one last time due to the last sleep in the loop
        return !$this->IsInstanceRunning('\w+');
    }
Snort::StopProcess ($ if)
Stops snort process started with the given interface.
Parameters:
[in] $if string Interface name.
Definition at line 164 of file snort.php.
References FindPid(), and Model::KillPid().
Referenced by Snort().
    {
        $pid= $this->FindPid($if);
        if ($pid > -1) {
            return $this->KillPid($pid);
        }
        return TRUE;
    }
Snort::FindPid ($ if)
Finds the pid of snort process started with the given inf.
Parameters:
[in] $if string Interface name.
Returns:
int Pid or -1 if not running
Definition at line 178 of file snort.php.
References $retval.
Referenced by StopProcess().
    {
        $pidcmd= "/bin/ps arwwx | /usr/bin/grep snort | /usr/bin/grep '$if' | /usr/bin/grep -v -e cwc.php -e grep";
        exec($pidcmd, $output, $retval);
        foreach ($output as $psline) {
            $re= '/\h+-i\h+(\w+)\b/';
            if (preg_match($re, $psline)) {
                $re= '/^\s*(\d+)\s+/';
                if (preg_match($re, $psline, $match)) {
                    if ($match[1] !== '') {
                        return $match[1];
                    }
                }
            }
        }
        return -1;
    }
Snort::IsInstanceRunning ($ if)
Checks if the process(es) is running.
Uses ps with -U option.
Parameters:
[in] $if string Interface name
Returns:
boolean TRUE if running
Definition at line 204 of file snort.php.
References Model::RunShellCommand().
Referenced by Start(), and Stop().
    {
        $re= "\/usr\/local\/bin\/snort\s+[^\n]*-i\s+$if\s+[^\n]*";
        $output= $this->RunShellCommand('/bin/ps arwwx -U_snort');
        if (preg_match("/$re/m", $output)) {
            return TRUE;
        }
        return FALSE;
    }
Snort::SetConfig ($ confname)
Sets configuration file based on config type provided.
Certain modules have configuration divided into multiple pages/files, hence they override this method.
Parameters:
[in] $confname string Config type
Reimplemented from Model.
Definition at line 215 of file snort.php.
References $advancedConfig, $basicConfig, and Config.
    {
        global $basicConfig, $advancedConfig;
        $this->Config= ${$confname};
    }
Snort::GetRules ()
Get list of enabled/uncommented rules.
Returns:
Rule or list of rules.
Definition at line 225 of file snort.php.
References Model::SearchFileAll().
Referenced by Snort().
    {
        return $this->SearchFileAll($this->ConfFile, "/^\h*$this->re_RulePrefix([^#\s]+)\h*$/m", 2);
    }
Snort::GetDisabledRules ()
Gets list of disabled/commented rules.
Returns:
Rule or list of rules.
Definition at line 233 of file snort.php.
References Model::SearchFileAll().
Referenced by Snort().
    {
        return $this->SearchFileAll($this->ConfFile, "/^\h*$this->COMC\h*$this->re_RulePrefix([^#\s]+)\b\h*$/m", 2);
    }
Snort::EnableRule ($ rule)
Definition at line 238 of file snort.php.
References Model::EnableName().
Referenced by Snort().
    {
        return $this->EnableName($this->ConfFile, "$this->re_RulePrefix$rule");
    }
Snort::DisableRule ($ rule)
Definition at line 243 of file snort.php.
References Model::DisableName().
Referenced by Snort().
    {
        return $this->DisableName($this->ConfFile, "$this->re_RulePrefix$rule");
    }
Snort::MoveRuleUp ($ rule)
Definition at line 248 of file snort.php.
References $rule, Escape(), and Model::ReplaceRegexp().
Referenced by Snort().
    {
        $rule= Escape($rule, '/.');
        return $this->ReplaceRegexp($this->ConfFile, "/^\h*(($this->re_RulePrefix[^\n]+)\n+($this->COMC\h*$this->re_RulePrefix[^\n]+\n+)*)\h*($this->re_RulePrefix$rule)\n/m", '${6}'."\n".'${1}');
    }
Snort::MoveRuleDown ($ rule)
Definition at line 254 of file snort.php.
References $rule, Escape(), and Model::ReplaceRegexp().
Referenced by Snort().
    {
        $rule= Escape($rule, '/.');
        return $this->ReplaceRegexp($this->ConfFile, "/^\h*($this->re_RulePrefix$rule)\n+\h*(($this->COMC\h*$this->re_RulePrefix[^\n]+\n+)*($this->re_RulePrefix[^\n]+)\n+)/m", '${3}'.'${1}'."\n");
    }
Snort::SetStartupIfs ($ lanif, $ wanif)
Definition at line 260 of file snort.php.
References Model::ReplaceRegexp().
Referenced by Snort().
    {
        $re= '|(\h*/usr/local/bin/snort\h+.*-i\h+)(\w+\d+)(\h+.*\h+/usr/local/bin/snort\h+.*-i\h+)(\w+\d+)(\h+.*)|ms';
        return $this->ReplaceRegexp('/etc/rc.local', $re, '${1}'.$lanif.'${3}'.$wanif.'${5}');
    }
Snort::Snort ()
Definition at line 44 of file include.php.
References _HELPWINDOW().
    {
        $this->LogsHelpMsg= _HELPWINDOW('These logs contain messages from all IDS process. Alerts are duplicated here as well.');
    }
Member Data Documentation
Snort::$Name = 'snort'
Reimplemented from Model.
Reimplemented in Snortalerts.
Definition at line 40 of file snort.php.
Snort::$User = '_snort'
Reimplemented from Model.
Definition at line 41 of file snort.php.
Snort::$NVPS = '\h'
Reimplemented from Model.
Definition at line 43 of file snort.php.
Snort::$ConfFile = '/etc/snort/snort.conf'
Reimplemented from Model.
Definition at line 44 of file snort.php.
Snort::$LogFile = '/var/log/snort/snort.log'
Reimplemented from Model.
Reimplemented in Snortalerts.
Definition at line 45 of file snort.php.
Snort::$VersionCmd = '/usr/local/bin/snort -V 2>&1'
Reimplemented from Model.
Definition at line 47 of file snort.php.
Snort::$Model = 'snort'
Reimplemented from View.
Reimplemented in Snortalerts.
Definition at line 41 of file include.php.
Snort::$Layout = 'snort'
Reimplemented from View.
Definition at line 42 of file include.php.
The documentation for this class was generated from the following files:
Model/snort.php
View/snort/include.php