ComixWall ISG Administration Interface: Symon Class Reference
Symon Class Reference
Public Member Functions
Symon ()
SetCpus ()
SetIfs ($lanif, $wanif)
SetSensors ()
SetPartitions ()
SetConf ($lanif, $wanif)
Public Attributes
$Name = 'symon'
$User = '_symon'
$VersionCmd = '/usr/local/libexec/symon -v 2>&1'
Detailed Description
Definition at line 42 of file symon.php.
Member Function Documentation
Symon::Symon ()
Definition at line 52 of file symon.php.
References $TmpFile, Model, SetConf(), SetCpus(), SetIfs(), SetPartitions(), and SetSensors().
    {
        global $TmpFile;
        parent::Model();
        $this->StartCmd= "/usr/local/libexec/symon > $TmpFile 2>&1 &";
        $this->Commands= array_merge(
            $this->Commands,
            array(
                'SetCpus'=> array(
                    'argv'  =>  array(),
                    'desc'  =>  _('Set symon cpus'),
                    ),
                'SetIfs'=>  array(
                    'argv'  =>  array(NAME, NAME),
                    'desc'  =>  _('Set symon ifs'),
                    ),
                'SetSensors'=>  array(
                    'argv'  =>  array(),
                    'desc'  =>  _('Set symon sensors'),
                    ),
                'SetPartitions'=>   array(
                    'argv'  =>  array(),
                    'desc'  =>  _('Set symon partitions'),
                    ),
                'SetConf'=> array(
                    'argv'  =>  array(NAME, NAME),
                    'desc'  =>  _('Set symon conf'),
                    ),
                )
            );
    }
Symon::SetCpus ()
Definition at line 91 of file symon.php.
References $layout, Model::GetSysCtl(), and Model::ReplaceRegexp().
Referenced by Symon().
    {
        $ncpu= 1;
        if (($hwncpu= $this->GetSysCtl('hw.ncpu')) !== FALSE) {
            if (preg_match('|^hw.ncpu=(\d+)$|ms', $hwncpu, $match)) {
                $ncpu= $match[1];
            }
        }
        $layout= '';
        for ($c= 0; $c < $ncpu; $c++) {
            $layout.= "graph    rrdfile=$this->rrdsPath/cpu$c.rrd, title=\"CPU $c\";\n";
        }
        $re= '|(\s*group\h+name\h*=\h*"CPU\h+Load";\s*)(.*)|ms';
        return $this->ReplaceRegexp($this->layoutsPath.'/cpus.layout', $re, '${1}'.$layout);
    }
Symon::SetIfs ($ lanif, $ wanif)
Definition at line 109 of file symon.php.
References $retval.
Referenced by Symon().
    {
        $re= '|^(\s*graph\s+rrdfile\s*=\s*[\w/]+/if_)(\w+\d+)(\.rrd\s*,\s*title\s*=\s*"Internal Interface\s+\()(\w+\d+)(\)\s*"\s*;)|ms';
        $retval=  $this->ReplaceRegexp($this->layoutsPath.'/ifs.layout', $re, '${1}'.$lanif.'${3}'.$lanif.'${5}');
        $re= '|^(\s*graph\s+rrdfile\s*=\s*[\w/]+/if_)(\w+\d+)(\.rrd\s*,\s*title\s*=\s*"External Interface\s+\()(\w+\d+)(\)\s*"\s*;)|ms';
        $retval&= $this->ReplaceRegexp($this->layoutsPath.'/ifs.layout', $re, '${1}'.$wanif.'${3}'.$wanif.'${5}');
        $re= '|(\s+lan_rrd\s*=\s*[\w/]+/if_)(\w+\d+)(\.rrd\s*,\s*)|ms';
        $retval&= $this->ReplaceRegexp($this->layoutsPath.'/states.layout', $re, '${1}'.$lanif.'${3}');
        $re= '|(\s+wan_rrd\s*=\s*[\w/]+/if_)(\w+\d+)(\.rrd\s*,\s*)|ms';
        $retval&= $this->ReplaceRegexp($this->layoutsPath.'/states.layout', $re, '${1}'.$wanif.'${3}');
        return $retval;
    }
Symon::SetSensors ()
Definition at line 126 of file symon.php.
References $layout.
Referenced by Symon().
    {
        if (($sensorslist= $this->GetSensors()) !== FALSE) {
            $layout= '';
            if (isset($sensorslist['temp']) && count($sensorslist['temp']) > 0) {
                foreach ($sensorslist['temp'] as $s) {
                    $layout.= "graph    rrdfile=$this->rrdsPath/sensor_$s.rrd, title=\"Temperature ($s)\";\n";
                }
            }
            $layout.= 'group    name="Fan";'."\n";
            if (isset($sensorslist['fan']) && count($sensorslist['fan']) > 0) {
                foreach ($sensorslist['fan'] as $s) {
                    $layout.= "graph    rrdfile=$this->rrdsPath/sensor_$s.rrd, title=\"Fan ($s)\";\n";
                }
            }
            $re= '|(\s*group\h+name\h*=\h*"Temperature";\s*)(.*)|ms';
            return $this->ReplaceRegexp($this->layoutsPath.'/sensors.layout', $re, '${1}'.$layout);
        }
        return FALSE;
    }
Symon::SetPartitions ()
Definition at line 149 of file symon.php.
References $layout, and $retval.
Referenced by Symon().
    {
        $partitions= $this->GetPartitions();
        $layout= '';
        $disks= array();
        foreach ($partitions as $part => $mdir) {
            if (preg_match('|/dev/((\w+\d+)[a-z]+)|', $part, $match)) {
                $p= $match[1];
                $layout.= "graph    rrdfile=$this->rrdsPath/df_$p.rrd, title=\"Partition $p ($mdir)\";\n";
                if (!in_array($match[2], $disks)) {
                    $disks[]= $match[2];
                }
            }
        }
        $re= '|(\s*group\h+name\h*=\h*"Partitions\h+Usages";\s*)(.*)|ms';
        $retval=  $this->ReplaceRegexp($this->layoutsPath.'/partitions.layout', $re, '${1}'.$layout);
        $layout= '';
        foreach ($disks as $d) {
            $layout.= "graph    rrdfile=$this->rrdsPath/io_$d.rrd, title=\"Disk $d\";\n";
        }
        $re= '|(\s*group\h+name\h*=\h*"Disk\h+I/O";\s*)(.*)|ms';
        $retval&= $this->ReplaceRegexp($this->layoutsPath.'/disks.layout', $re, '${1}'.$layout);
        return $retval;
    }
Symon::SetConf ($ lanif, $ wanif)
Todo:
See the new OpenBSD installer to get this and sensors paths
Definition at line 180 of file symon.php.
References $retval.
Referenced by Symon().
    {
        $ncpu= 1;
        if (($hwncpu= $this->GetSysCtl('hw.ncpu')) !== FALSE) {
            if (preg_match('|^hw.ncpu=(\d+)$|ms', $hwncpu, $match)) {
                $ncpu= $match[1];
            }
        }
        $cpus= '';
        for ($i= 0; $i < $ncpu; $i++) {
            $cpus.= "   cpu($i),\n";
        }
        $others= "  mem,\n  pf,\n   mbuf,\n";
        $ifs= " if(lo0),\n  if($lanif),\n   if($wanif),\n";
        $partitions= $this->GetPartitions();
        $parts= '';
        $disks= array();
        foreach ($partitions as $part => $mdir) {
            if (preg_match('|/dev/((\w+\d+)[a-z]+)|', $part, $match)) {
                $parts.= '  df('.$match[1]."),\n";
                if (!in_array($match[2], $disks)) {
                    $disks[]= $match[2];
                }
            }
        }
        $ios= '';
        foreach ($disks as $io) {
            $ios.= "    io($io),\n";
        }
        $sensors= '';
        if (($sensorslist= $this->GetSensors()) !== FALSE) {
            if (isset($sensorslist['temp']) && count($sensorslist['temp']) > 0) {
                foreach ($sensorslist['temp'] as $s) {
                    $sensors.= "    sensor($s),\n";
                }
            }
            if (isset($sensorslist['fan']) && count($sensorslist['fan']) > 0) {
                foreach ($sensorslist['fan'] as $s) {
                    $sensors.= "    sensor($s),\n";
                }
            }
        }
        $proclist= array(
            'httpd',
            'dansguardian',
            'snort',
            'clamd',
            'p3scan',
            'perl',
            'sshd',
            'squid',
            'smtp-gated',
            'named',
            'dhcpd',
            'sockd',
            'imspector',
            'ftp-proxy',
            'openvpn',
        );
        $procs= '';
        foreach ($proclist as $p) {
            $procs.= "  proc($p),\n";
        }
        $conf= "\n".$cpus.$others.$ifs.$ios.$parts.$sensors.$procs;
        $re= '|(\s*monitor\s*\{\h*)([^\}]*)(\s*\})|ms';
        $retval=  $this->ReplaceRegexp('/etc/symon.conf', $re, '${1}'.$conf.'${3}');
        $conf= preg_replace('/( )/ms', '        ', $conf);
        $re= '|(\s*source\s*127\.0\.0\.1\s*\{\s*accept\s*\{\h*)([^\}]*)(\h*\})|ms';
        $retval&= $this->ReplaceRegexp('/etc/symux.conf', $re, '${1}'.$conf.'   ${3}');
        return $retval;
    }
Member Data Documentation
Symon::$Name = 'symon'
Reimplemented from Model.
Definition at line 44 of file symon.php.
Symon::$User = '_symon'
Reimplemented from Model.
Definition at line 45 of file symon.php.
Symon::$VersionCmd = '/usr/local/libexec/symon -v 2>&1'
Reimplemented from Model.
Definition at line 47 of file symon.php.
The documentation for this class was generated from the following file:
Model/symon.php