ComixWall ISG Administration Interface: Freshclam Class Reference
Freshclam Class Reference
Public Member Functions
Freshclam ()
ParseLogLine ($logline, &$cols)
GetMirrors ()
AddMirror ($mirror)
DelMirror ($mirror)
Freshclam ()
Public Attributes
$Name = 'freshclam'
$User = '_clamav'
$NVPS = '\h'
$ConfFile = '/etc/freshclam.conf'
$LogFile = '/var/log/freshclam.log'
$PidFile = '/var/run/clamav/freshclam.pid'
$Model = 'freshclam'
Detailed Description
Definition at line 42 of file freshclam.php.
Member Function Documentation
Freshclam::Freshclam ()
Definition at line 53 of file freshclam.php.
References $TmpFile, AddMirror(), DelMirror(), GetMirrors(), and Model.
    {
        global $TmpFile;
        parent::Model();
        $this->StartCmd= "/usr/local/bin/freshclam -d > $TmpFile 2>&1 &";
        $this->Commands= array_merge(
            $this->Commands,
            array(
                'GetMirrors'=>  array(
                    'argv'  =>  array(),
                    'desc'  =>  _('Get database mirrors'),
                    ),
                'AddMirror'=>   array(
                    'argv'  =>  array(URL),
                    'desc'  =>  _('Add database mirror'),
                    ),
                'DelMirror'=>   array(
                    'argv'  =>  array(URL),
                    'desc'  =>  _('Delete database mirror'),
                    ),
                )
            );
    }
Freshclam::ParseLogLine ($ logline, &$ cols)
Todo:
clamd and freshclam log lines contain number of virus defs.
Reimplemented from Model.
Definition at line 83 of file freshclam.php.
References Model::ParseSyslogLine().
    {
        // Mon Oct 26 05:23:56 2009 -> ClamAV update process started at Mon Oct 26 05:23:56 2009
        $re_datetime= '\w+\s+(\w+\s+\d+)\s+(\d+:\d+:\d+)\s+\d+';
        $re_rest= '(.*)';
        $re= "/^$re_datetime\s+->\s+$re_rest$/";
        if (preg_match($re, $logline, $match)) {
            $cols['Date']= $match[1];
            $cols['Time']= $match[2];
            $cols['DateTime']= $cols['Date'].' '.$cols['Time'];
            $cols['Log']= $match[3];
            return TRUE;
        }
        else if ($this->ParseSyslogLine($logline, $cols)) {
            $cols['DateTime']= $cols['Date'].' '.$cols['Time'];
            return TRUE;
        }
        else {
            $cols['Log']= $logline;
            return TRUE;
        }
        return FALSE;
    }
Freshclam::GetMirrors ()
Definition at line 108 of file freshclam.php.
References Model::SearchFileAll().
Referenced by Freshclam().
    {
        $mirrors= $this->SearchFileAll($this->ConfFile, "/^\h*DatabaseMirror\h*([\w.]+)\b.*\h*$/m");
        // Do not list the main server
        return preg_replace('/^(\s*database\.clamav\.net\s*)/m', '', $mirrors);
    }
Freshclam::AddMirror ($ mirror)
Definition at line 115 of file freshclam.php.
References DelMirror(), and Model::ReplaceRegexp().
Referenced by Freshclam().
    {
        $this->DelMirror($mirror);
        return $this->ReplaceRegexp($this->ConfFile, "/(\h*DatabaseMirror\h+database\.clamav\.net.*)/m", "DatabaseMirror $mirror\n".'${1}');
    }
Freshclam::DelMirror ($ mirror)
Definition at line 121 of file freshclam.php.
References Escape(), Model::ReplaceRegexp(), and ViewError().
Referenced by AddMirror(), and Freshclam().
    {
        // Do not delete the main server
        if ($mirror !== 'database.clamav.net') {
            $mirror= Escape($mirror, '.');
            return $this->ReplaceRegexp($this->ConfFile, "/^(\h*DatabaseMirror\h+$mirror\b.*(\s|))/m", '');
        }
        ViewError(_("Won't delete database.clamav.net entry."));
        return FALSE;
    }
Freshclam::Freshclam ()
Definition at line 43 of file include.freshclam.php.
References _HELPBOX2(), _HELPWINDOW(), _TITLE2(), ConfHelpMsg, Config, reload(), and session.
    {
        $this->LogsHelpMsg= _HELPWINDOW('Freshclam logs details of each virus update session. Version warnings may not be critical as mentioned in the logs as well.');
        $this->ConfHelpMsg= _HELPWINDOW('You may want to customize the frequency of database checks. Also make sure you have chosen a database mirror close to you.');
        $this->Config = array(
            'Checks' => array(
                'title' => _TITLE2('Database Checks'),
                'info' => _HELPBOX2('Number of database checks per day.
        Default: 12 (every two hours)'),
                ),
            'MaxAttempts' => array(
                'title' => _TITLE2('Max Attempts'),
                'info' => _HELPBOX2('How many attempts to make before giving up.
        Default: 3 (per mirror)'),
                ),
            'SafeBrowsing' => array(
                'title' => _TITLE2('Safe Browsing'),
                'info' => _HELPBOX2('This option enables support for Google Safe Browsing. When activated for the first time, freshclam will download a new database file (safebrowsing.cvd) which will be automatically loaded by clamd and clamscan during the next reload, provided that the heuristic phishing detection is turned on. This database includes information about websites that may be phishing sites or possible sources of malware. When using this option, it\'s mandatory to run freshclam at least every 30 minutes.
        Default: disabled'),
                ),
            'LogVerbose' => array(
                'title' => _TITLE2('Log Verbose'),
                'info' => _HELPBOX2('Enable verbose logging.
        Default: disabled'),
                ),
            'DNSDatabaseInfo' => array(
                'title' => _TITLE2('DNS Database Info'),
                'info' => _HELPBOX2('Use DNS to verify virus database version. Freshclam uses DNS TXT records to verify database and software versions. With this directive you can change the database verification domain.
        Default: enabled, pointing to current.cvd.clamav.net'),
                ),
            'HTTPProxyServer' => array(
                'title' => _TITLE2('HTTP Proxy Server'),
                'info' => _HELPBOX2('Proxy settings
        Default: disabled'),
                ),
            'HTTPProxyPort' => array(
                'title' => _TITLE2('HTTP Proxy Port'),
                ),
            'HTTPProxyUsername' => array(
                'title' => _TITLE2('HTTP Proxy Username'),
                ),
            'HTTPProxyPassword' => array(
                'title' => _TITLE2('HTTP Proxy Password'),
                ),
            'LocalIPAddress' => array(
                'title' => _TITLE2('Local IP Address'),
                'info' => _HELPBOX2('Use aaa.bbb.ccc.ddd as client address for downloading databases. Useful for multi-homed systems.
        Default: Use OS\'es default outgoing IP address.'),
                ),
            'Debug' => array(
                'title' => _TITLE2('Debug'),
                'info' => _HELPBOX2('Enable debug messages in libclamav.
        Default: disabled'),
                ),
        );
    }
Member Data Documentation
Freshclam::$Name = 'freshclam'
Reimplemented from Model.
Definition at line 44 of file freshclam.php.
Freshclam::$User = '_clamav'
Reimplemented from Model.
Definition at line 45 of file freshclam.php.
Freshclam::$NVPS = '\h'
Reimplemented from Model.
Definition at line 47 of file freshclam.php.
Freshclam::$ConfFile = '/etc/freshclam.conf'
Reimplemented from Model.
Definition at line 48 of file freshclam.php.
Freshclam::$LogFile = '/var/log/freshclam.log'
Reimplemented from Model.
Definition at line 49 of file freshclam.php.
Freshclam::$PidFile = '/var/run/clamav/freshclam.pid'
Reimplemented from Model.
Definition at line 51 of file freshclam.php.
Freshclam::$Model = 'freshclam'
Reimplemented from View.
Definition at line 41 of file include.freshclam.php.
The documentation for this class was generated from the following files:
Model/freshclam.php
View/clamav/include.freshclam.php