ComixWall ISG Administration Interface: View Class Reference
View Class Reference
Public Member Functions
Restart ()
Stops and restarts module process(es).
Stop ()
Stops module process(es).
Start ()
Starts module process(es).
FormatDate ($date)
Generic date array to string formatter.
FormatDateArray ($datestr, &$date)
Date string to array formatter.
IsDateRange ($date)
Checks if the date array contains a range, meaning an empty string.
Public Attributes
$Model = 'model'
$LogsHelpMsg = ''
$GraphHelpMsg = ''
$Layout = ''
$ConfHelpMsg = ''
$Config = array()
Configuration.
Detailed Description
Definition at line 40 of file view.php.
Member Function Documentation
View::Restart ()
Stops and restarts module process(es).
Reimplemented in Apache, and System.
Definition at line 62 of file view.php.
References Start(), and Stop().
    {
        if ($this->Stop()) {
            return $this->Start();
        }
        return FALSE;
    }
View::Stop ()
Stops module process(es).
Reimplemented in Apache, Pf, Snort, Snortips, Spamassassin, and Spamd.
Definition at line 72 of file view.php.
Referenced by Restart().
    {
        if ($this->Controller($output, 'Stop')) {
            return TRUE;
        }
        return FALSE;
    }
View::Start ()
Starts module process(es).
Reimplemented in Dhcpd, Pf, and Spamd.
Definition at line 82 of file view.php.
Referenced by Restart().
    {
        if ($this->Controller($output, 'Start')) {
            return TRUE;
        }
        return FALSE;
    }
View::FormatDate ($ date)
Generic date array to string formatter.
Assumes standard syslog date format for the output string.
Parameters:
[in] $date array Datetime struct
Returns:
string Date string
Reimplemented in Apachelogs, Dansguardianlogs, and Pf.
Definition at line 97 of file view.php.
References $MonthNames.
    {
        global $MonthNames;
        return $MonthNames[$date['Month']].' '.sprintf('% 2d', $date['Day']);
    }
View::FormatDateArray ($ datestr, &$ date)
Date string to array formatter.
Assumes standard syslog date format for the output string. Does the opposite of FormatDate().
Parameters:
[in] $datestr string Date as string
[out] $date array Datetime output
Todo:
Check if empty Year is ok around new year's day
Reimplemented in Apachelogs, and Dansguardianlogs.
Definition at line 114 of file view.php.
References $MonthNumbers.
    {
        global $MonthNumbers;
        if (preg_match('/(\d+)\s+(\d+)/', $datestr, $match)) {
            $date['Month']= $match[1];
            $date['Day']= sprintf('%02d', $match[2]);
            return TRUE;
        }
        else if (preg_match('/(\w+)\s+(\d+)/', $datestr, $match)) {
            if (array_key_exists($match[1], $MonthNumbers)) {
                $date['Month']= $MonthNumbers[$match[1]];
                $date['Day']= sprintf('%02d', $match[2]);
                return TRUE;
            }
        }
        return FALSE;
    }
View::IsDateRange ($ date)
Checks if the date array contains a range, meaning an empty string.
Assumes standard syslog date format for the output string.
Parameters:
[in] $date array Datetime struct
Returns:
TRUE if a range
Definition at line 140 of file view.php.
    {
        return ($date['Month'] == '') || ($date['Day'] == '');
    }
Member Data Documentation
View::$Model = 'model'
Reimplemented in Cwc, Cwwui, Apachelogs, Apache, Clamd, Freshclam, Blacklists, Dansguardianlogs, Dansguardian, Dante, Dhcpd, Ftpproxy, Imlogs, Imspector, Docs, Monitoring, Named, Openssh, Openvpn, P3scan, Pf, Smtpgated, Snortalerts, Snort, Snortips, Spamassassin, Spamd, Squid, and System.
Definition at line 42 of file view.php.
View::$LogsHelpMsg = ''
Definition at line 44 of file view.php.
View::$GraphHelpMsg = ''
Definition at line 46 of file view.php.
View::$Layout = ''
Reimplemented in Apache, Clamd, Dansguardian, Dante, Dhcpd, Ftpproxy, Imspector, Named, Openssh, Openvpn, P3scan, Smtpgated, Snort, Snortips, Spamassassin, Spamd, Squid, and System.
Definition at line 47 of file view.php.
View::$ConfHelpMsg = ''
Definition at line 49 of file view.php.
View::$Config = array()
Configuration.
If title field is missing, index string is used as title.
Parameters:
title Configuration title displayed.
info Info text displayed in help box on the right.
Definition at line 58 of file view.php.
The documentation for this class was generated from the following file:
View/lib/view.php