ComixWall ISG Administration Interface: System Class Reference
System Class Reference
Public Member Functions
System ()
AddHost ($host)
Adds host line to hosts file.
DelHost ($host)
Deletes host from hosts file.
GetHosts ()
Reads hosts file contents.
GetStaticGateway ()
Reads gateway address.
GetMyName ()
Reads hostname.
GetNameServer ()
Reads nameserver setting.
GetRootEmail ()
Reads root e-mail address.
GetIfConfig ($if)
GetDynamicGateway ()
Gets the default gateway from routing table.
GetConfig ()
SystemMakeStaticGateway ()
SystemMakeDynamicGateway ()
SetMyGate ($mygate)
Sets system gateway.
SetMyName ($myname)
Sets system hostname.
SetIf ($if, $type, $ip, $mask, $bc, $opt)
Sets system interface configuration.
DeleteIf ($if)
Unconfigures interface by deleting its hostname file.
SetNameServer ($nameserver)
Changes nameserver.
SetRootEmail ($emailaddr)
Change root e-mail address.
SetManCgiHome ($ip)
Set int_net.
SetDateTime ($datetime)
Sets system clock.
UpdateMailAliases ()
Update mail aliases.
AutoConfig ()
Runs installer with automatic configuration option.
InitGraphs ()
Delete all graph files, and recreate if necessary.
DeleteStats ()
Delete files under /var/tmp/comixwall.
Shutdown ()
Shut down.
Restart ()
Restart module processes.
GetPartitionsPfw ()
Gets pfw partition list.
GetSystemInfo ()
Gets system information.
DisplayRemoteTime ($timeserver)
Displays datetime from time server.
SetRemoteTime ($timeserver)
Sets datetime from time server.
GetRemoteTime ()
GetServiceStartStatus ()
Gets service start stati.
GetServiceStatRcConfLocal ($file, $service)
Gets service startup status in rc.conf.local.
GetServiceStatRcLocal ($file, $service)
Gets service startup status in rc.local.
DisableService ($service)
Turn off (disable) service startup.
EnableService ($service)
Turn on (enable) service startup.
DisableServiceRcConfLocal ($service)
Turn off (disable) service startup in rc.conf.local.
DisableServiceRcLocal ($service)
Turn off (disable) service startup in rc.local.
EnableServiceRcConfLocal ($service)
Turn on (enable) service startup in rc.conf.local.
EnableServiceRcLocal ($service)
Turn on (enable) service startup in rc.local.
GetLogsConfig ()
Get logs configuration.
SetLogsConfig ($model, $file, $count, $size, $when)
Set logs configuration.
RotateLogFile ($file)
Calls forked rotation function.
DaemonizedRotateLogFile ($file)
Rotate log file via newsyslog.
RotateAllLogFiles ()
Calls forked full rotation function.
DaemonizedRotateAllLogFiles ()
Rotate all log files via newsyslog.
DaemonizeFunc ($func, $param= '')
Daemonizes to run the given function.
SetPassword ($user, $passwd)
Sets user's password in htpasswd file.
SetLocale ($locale)
SetLogLevel ($level)
SetHelpBoxes ($bool)
SetReloadRate ($rate)
SetSessionTimeout ($timeout)
NetStart ()
SelectProcesses ($psout)
Returns all processes from ps output.
System ()
Public Attributes
$Name = 'system'
$User = '\S+'
$LogFile = '/var/log/messages'
$Model = 'system'
$Layout = 'system'
Detailed Description
Definition at line 42 of file system.php.
Member Function Documentation
System::System ()
rc.local module search strings and descriptions
rc.local file should have lines like the following:
 if [ -x /usr/local/libexec/symon ]; then
     echo -n ' symon';
     /usr/local/libexec/symon
 fi
Indeces of this array are used to comment or uncomment the lines like the 3rd one above.
rc.conf.local module search strings and descriptions
Todo:
Is there any pattern or size for options, 6th param?
Definition at line 53 of file system.php.
References AddHost(), AutoConfig(), DeleteIf(), DeleteStats(), DelHost(), DisableService(), DisplayRemoteTime(), EnableService(), GetConfig(), GetDynamicGateway(), GetHosts(), GetIfConfig(), GetLogsConfig(), GetMyName(), GetNameServer(), GetPartitionsPfw(), GetRemoteTime(), GetRootEmail(), GetServiceStartStatus(), GetStaticGateway(), GetSystemInfo(), InitGraphs(), Model, NetStart(), reload(), Restart(), RotateAllLogFiles(), RotateLogFile(), session, SetDateTime(), SetHelpBoxes(), SetIf(), SetLocale(), SetLogLevel(), SetLogsConfig(), SetManCgiHome(), SetMyGate(), SetMyName(), SetNameServer(), SetPassword(), SetReloadRate(), SetRemoteTime(), SetRootEmail(), SetSessionTimeout(), Shutdown(), SystemMakeDynamicGateway(), SystemMakeStaticGateway(), and UpdateMailAliases().
    {
        parent::Model();
        $this->Proc= '.';
        $this->rcLocalServices= array(
            '/usr/local/sbin/dansguardian',
            '/usr/local/sbin/squid',
            '/usr/local/bin/snort',
            '/usr/local/sbin/snortips',
            '/usr/local/sbin/clamd',
            '/usr/local/bin/freshclam',
            '/usr/local/bin/spamd',
            '/usr/local/sbin/p3scan',
            '/usr/local/sbin/smtp-gated',
            '/usr/local/sbin/imspector',
            '/usr/local/sbin/sockd',
            '/usr/local/libexec/symux',
            '/usr/local/libexec/symon',
            '/usr/local/sbin/pmacctd',
            );
        $this->rcConfLocalServices= array(
            'pf',
            'dhcpd_flags',
            'named_flags',
            'ftpproxy_flags',
            'httpd_flags',
            'ntpd_flags',
            'spamd_flags',
            'spamd_grey',
            'spamlogd_flags',
            'apmd_flags',
            );
        $this->Commands= array_merge(
            $this->Commands,
            array(
                'GetMyName'     =>  array(
                    'argv'  =>  array(),
                    'desc'  =>  _('Read system hostname'),
                    ),
                'GetRootEmail'  =>  array(
                    'argv'  =>  array(),
                    'desc'  =>  _('Get system admin e-mail address'),
                    ),
                'GetIfConfig'       =>  array(
                    'argv'  =>  array(NAME),
                    'desc'  =>  _('Get if config'),
                    ),
                'GetStaticGateway'      =>  array(
                    'argv'  =>  array(),
                    'desc'  =>  _('Read system gateway'),
                    ),
                'GetHosts'      =>  array(
                    'argv'  =>  array(),
                    'desc'  =>  _('List hosts'),
                    ),
                'GetNameServer' =>  array(
                    'argv'  =>  array(),
                    'desc'  =>  _('Read system nameserver'),
                    ),
                'GetConfig'=>   array(
                    'argv'  =>  array(),
                    'desc'  =>  _('Get configuration'),
                    ),
                'SetMyName'     =>  array(
                    'argv'  =>  array(NAME),
                    'desc'  =>  _('Set system hostname'),
                    ),
                'SetRootEmail'  =>  array(
                    'argv'  =>  array(EMAIL),
                    'desc'  =>  _('Set e-mail address'),
                    ),
                'SystemMakeStaticGateway'       =>  array(
                    'argv'  =>  array(),
                    'desc'  =>  _('Make system gateway static'),
                    ),
                'SystemMakeDynamicGateway'      =>  array(
                    'argv'  =>  array(),
                    'desc'  =>  _('Make system gateway dynamic'),
                    ),
                'GetDynamicGateway' =>  array(
                    'argv'  =>  array(),
                    'desc'  =>  _('Get system gateway'),
                    ),
                'SetMyGate'     =>  array(
                    'argv'  =>  array(IPADR),
                    'desc'  =>  _('Set system gateway'),
                    ),
                'SetIf'     =>  array(
                    'argv'  =>  array(NAME, NAME, IPADR|NAME|EMPTYSTR, IPADR|NAME|EMPTYSTR, IPADR|NAME|EMPTYSTR, STR|EMPTYSTR),
                    'desc'  =>  _('Configure an interface'),
                    ),
                'DeleteIf'  =>  array(
                    'argv'  =>  array(NAME),
                    'desc'  =>  _('Unconfigure an interface'),
                    ),
                'SetNameServer' =>  array(
                    'argv'  =>  array(IPADR),
                    'desc'  =>  _('Set system nameserver'),
                    ),
                'AddHost'       =>  array(
                    'argv'  =>  array(HOST),
                    'desc'  =>  _('Add host'),
                    ),
                'DelHost'       =>  array(
                    'argv'  =>  array(HOST),
                    'desc'  =>  _('Delete host'),
                    ),
                'GetServiceStartStatus'=>   array(
                    'argv'  =>  array(),
                    'desc'  =>  _('Get service start status'),
                    ),
                'DisableService'=>  array(
                    'argv'  =>  array(URL),
                    'desc'  =>  _('Turn off service'),
                    ),
                'EnableService'=>   array(
                    'argv'  =>  array(URL),
                    'desc'  =>  _('Turn on service'),
                    ),
                'SetDateTime'       =>  array(
                    'argv'  =>  array(DATETIME),
                    'desc'  =>  _('Set system clock'),
                    ),
                'UpdateMailAliases' =>  array(
                    'argv'  =>  array(),
                    'desc'  =>  _('Update mail aliases'),
                    ),
                'DisplayRemoteTime' =>  array(
                    'argv'  =>  array(URL|IP),
                    'desc'  =>  _('Display remote time'),
                    ),
                'SetRemoteTime' =>  array(
                    'argv'  =>  array(URL|IP),
                    'desc'  =>  _('Set remote time'),
                    ),
                'GetRemoteTime' =>  array(
                    'argv'  =>  array(),
                    'desc'  =>  _('Get remote time'),
                    ),
                'AutoConfig'    =>  array(
                    'argv'  =>  array(),
                    'desc'  =>  _('Automatic configuration'),
                    ),
                'InitGraphs'    =>  array(
                    'argv'  =>  array(),
                    'desc'  =>  _('Init graphs'),
                    ),
                'DeleteStats'   =>  array(
                    'argv'  =>  array(),
                    'desc'  =>  _('Erase statistics files'),
                    ),
                'Shutdown'  =>  array(
                    'argv'  =>  array(),
                    'desc'  =>  _('System shutdown'),
                    ),
                'Restart'   =>  array(
                    'argv'  =>  array(),
                    'desc'  =>  _('System restart'),
                    ),
                'GetPartitionsPfw'  =>  array(
                    'argv'  =>  array(),
                    'desc'  =>  _('Get partition list'),
                    ),
                'GetSystemInfo' =>  array(
                    'argv'  =>  array(),
                    'desc'  =>  _('Get system information'),
                    ),
                'GetLogsConfig'=>   array(
                    'argv'  =>  array(),
                    'desc'  =>  _('Get logs configuration'),
                    ),
                'SetLogsConfig'=>   array(
                    'argv'  =>  array(NAME, FILEPATH, NUM, NUM|ASTERISK, NUM|ASTERISK),
                    'desc'  =>  _('Set logs configuration'),
                    ),
                'RotateLogFile'=>   array(
                    'argv'  =>  array(FILEPATH),
                    'desc'  =>  _('Rotate log file'),
                    ),
                'RotateAllLogFiles'=>   array(
                    'argv'  =>  array(),
                    'desc'  =>  _('Rotate all log files'),
                    ),
                'SetManCgiHome'=>   array(
                    'argv'  =>  array(IPADR),
                    'desc'  =>  _('Set man.cgi home'),
                    ),
                'SetPassword'   =>  array(
                    'argv'  =>  array(NAME, SHA1STR),
                    'desc'  =>  _('Set user password'),
                    ),
                'SetLocale'=>   array(
                    'argv'  =>  array(NAME),
                    'desc'  =>  _('Set locale'),
                    ),
                'SetLogLevel'=> array(
                    'argv'  =>  array(NAME),
                    'desc'  =>  _('Set log level'),
                    ),
                'SetHelpBoxes'=>    array(
                    'argv'  =>  array(NAME),
                    'desc'  =>  _('Set help boxes'),
                    ),
                'SetReloadRate'=>   array(
                    'argv'  =>  array(NUM),
                    'desc'  =>  _('Set reload rate'),
                    ),
                'SetSessionTimeout'=>   array(
                    'argv'  =>  array(NUM),
                    'desc'  =>  _('Set session timeout'),
                    ),
                'NetStart'  =>  array(
                    'argv'  =>  array(),
                    'desc'  =>  _('Restart network'),
                    ),
                )
            );
    }
System::AddHost ($ host)
Adds host line to hosts file.
Parameters:
[in] $host Host definition line.
Definition at line 340 of file system.php.
References Model::AppendToFile(), and DelHost().
Referenced by System().
    {
        $this->DelHost($host);
        return $this->AppendToFile($this->confDir.'hosts', $host);
    }
System::DelHost ($ host)
Deletes host from hosts file.
Parameters:
[in] $host Host definition line.
Definition at line 350 of file system.php.
References Model::ReplaceRegexp().
Referenced by AddHost(), and System().
    {
        return $this->ReplaceRegexp($this->confDir.'hosts', "/^(\h*$host(\s|))/m", '');
    }
System::GetHosts ()
Reads hosts file contents.
Returns:
Hosts file uncommented lines.
Definition at line 359 of file system.php.
References $Re_Ip, and Model::SearchFileAll().
Referenced by System().
    {
        global $Re_Ip;
        return $this->SearchFileAll($this->confDir.'hosts', "/^\h*(($Re_Ip|[:\d]+)\b.*)\h*$/m");
    }
System::GetStaticGateway ()
Reads gateway address.
Returns:
IP of the gateway.
Definition at line 370 of file system.php.
References Model::GetFile().
Referenced by GetConfig(), and System().
    {
        return $this->GetFile($this->confDir.'mygate');
    }
System::GetMyName ()
Reads hostname.
Returns:
System name, output of hostname too.
Definition at line 379 of file system.php.
References Model::GetFile().
Referenced by GetConfig(), and System().
    {
        return $this->GetFile($this->confDir.'myname');
    }
System::GetNameServer ()
Reads nameserver setting.
Returns:
ystem-wide nameserver.
Definition at line 388 of file system.php.
References Model::SearchFile().
Referenced by System().
    {
        return $this->SearchFile($this->confDir.'resolv.conf', "/^\h*nameserver\h*([^#]*)\h*$/m");
    }
System::GetRootEmail ()
Reads root e-mail address.
Returns:
oot address.
Definition at line 397 of file system.php.
References Model::SearchFile().
Referenced by System().
    {
        return $this->SearchFile($this->confDir.'mail/aliases', "/^\h*root:\h*([^#]*)\h*$/m");
    }
System::GetIfConfig ($ if)
Definition at line 402 of file system.php.
References $file, and Model::GetFile().
Referenced by GetConfig(), and System().
    {
        $file= $this->confDir."hostname.".$if;
        if (file_exists($file)) {
            if (($contents= $this->GetFile($file)) !== FALSE) {
                $re= '^\s*(inet|dhcp)\s*(\S*)\s*(\S*)\s*(\S*)\s*(\S*)\s*$';
                if (preg_match("/$re/m", $contents, $match)) {
                    return serialize(array_slice($match, 1));
                }
            }
        }
        return FALSE;
    }
System::GetDynamicGateway ()
Gets the default gateway from routing table.
Definition at line 418 of file system.php.
References $Re_Ip, $retval, cwc_syslog(), and ViewError().
Referenced by GetConfig(), System(), and SystemMakeStaticGateway().
    {
        global $Re_Ip;
        $cmd= "/sbin/route -n get default | /usr/bin/grep gateway 2>&1";
        exec($cmd, $output, $retval);
        if ($retval === 0) {
            if (count($output) > 0) {
                #    gateway: 10.0.0.2
                $re= "\s*gateway:\s*($Re_Ip)\s*";
                if (preg_match("/$re/m", $output[0], $match)) {
                    return $match[1];
                }
            }
        }
        else {
            $errout= implode("\n", $output);
            ViewError($errout);
            cwc_syslog(LOG_ERR, __FILE__, __FUNCTION__, __LINE__, "Get dynamic gateway failed: $errout");
        }
        return FALSE;
    }
System::GetConfig ()
Definition at line 441 of file system.php.
References $MODEL_PATH, $ModelFiles, $Models, GetDynamicGateway(), Model::GetExtIf(), GetIfConfig(), Model::GetIntIf(), GetMyName(), Model::GetPhyIfs(), and GetStaticGateway().
Referenced by System().
    {
        global $MODEL_PATH, $ModelFiles, $Models;
        $config= array();
        if (($myname= $this->GetMyName()) !== FALSE) {
            $config['Myname']= trim($myname);
        }
        if (($mygate= $this->GetStaticGateway()) !== FALSE) {
            $config['Mygate']= trim($mygate);
            $config['StaticGateway']= TRUE;
        }
        else if (($mygate= $this->GetDynamicGateway()) !== FALSE) {
            $config['Mygate']= trim($mygate);
            $config['StaticGateway']= FALSE;
        }
        if (($intif= $this->GetIntIf()) !== FALSE) {
            $config['IntIf']= trim($intif, '"');
        }
        if (($extif= $this->GetExtIf()) !== FALSE) {
            $config['ExtIf']= trim($extif, '"');
        }
        if (($ifs= $this->GetPhyIfs()) !== FALSE) {
            $ifs= explode("\n", $ifs);
            foreach ($ifs as $if) {
                $config['Ifs'][$if]= array();
                if (($output= $this->GetIfConfig($if)) !== FALSE) {
                    $config['Ifs'][$if]= unserialize($output);
                }
            }
        }
        return serialize($config);
    }
System::SystemMakeStaticGateway ()
Definition at line 481 of file system.php.
References GetDynamicGateway(), and SetMyGate().
Referenced by System().
    {
        if (($gateway= $this->GetDynamicGateway()) !== FALSE) {
            return $this->SetMyGate($gateway);
        }
        return FALSE;
    }
System::SystemMakeDynamicGateway ()
Definition at line 489 of file system.php.
References Model::DeleteFile().
Referenced by System().
    {
        return $this->DeleteFile($this->confDir.'mygate');
    }
System::SetMyGate ($ mygate)
Sets system gateway.
Parameters:
[in] $mygate Gateway IP.
Definition at line 498 of file system.php.
Referenced by System(), and SystemMakeStaticGateway().
    {
        // If filename does not exist, the file is created. Otherwise, the existing file is overwritten
        return file_put_contents($this->confDir.'mygate', $mygate.PHP_EOL);
    }
System::SetMyName ($ myname)
Sets system hostname.
Parameters:
[in] $myname Hostname.
Definition at line 508 of file system.php.
Referenced by System().
    {
        return file_put_contents($this->confDir.'myname', $myname.PHP_EOL);
    }
System::SetIf ($ if, $ type, $ ip, $ mask, $ bc, $ opt)
Sets system interface configuration.
Parameters:
[in] $if Interface name.
[in] $type inet or dhcp.
[in] $ip IP.
[in] $mask Netmask.
[in] $bc Broadcast address.
[in] $opt Options.
Warning:
Need a new line at the end of a line in hostname.if (otherwise /etc/netstart fails), file_put_contents() removes the last new line
Definition at line 522 of file system.php.
References $Re_Ip, and ViewError().
Referenced by System().
    {
        global $Re_Ip;
        // Trim for whitespace caused by empty strings
        $ifconf= trim("$type $ip $mask $bc $opt");
        // ComixWall supports only these configuration
        if (preg_match("/^inet\s*$Re_Ip\s*$Re_Ip\s*($Re_Ip|).*$/", $ifconf)
            || preg_match('/^dhcp\s*NONE\s*NONE\s*NONE.*$/', $ifconf)
            || preg_match('/^dhcp$/', $ifconf)) {
            return file_put_contents($this->confDir.'hostname.'.$if, $ifconf.PHP_EOL);
        }
        else {
            ViewError(_('Unsupported interface configuration').": $ifconf");
        }
        return FALSE;
    }
System::DeleteIf ($ if)
Unconfigures interface by deleting its hostname file.
Parameters:
[in] $if Interface name.
Definition at line 545 of file system.php.
References Model::DeleteFile().
Referenced by System().
    {
        exec("/sbin/ifconfig $if down");
        exec("/sbin/ifconfig $if delete");
        return $this->DeleteFile($this->confDir.'hostname.'.$if);
    }
System::SetNameServer ($ nameserver)
Changes nameserver.
Parameters:
[in] $nameserver System nameserver IP.
Definition at line 556 of file system.php.
References $Re_Ip, and Model::ReplaceRegexp().
Referenced by System().
    {
        global $Re_Ip;
        return $this->ReplaceRegexp($this->confDir.'resolv.conf', "/^(\h*nameserver\h*)($Re_Ip)(\b.*)$/m", '${1}'.$nameserver.'${3}');
    }
System::SetRootEmail ($ emailaddr)
Change root e-mail address.
Parameters:
[in] $emailaddr E-mail address.
Definition at line 567 of file system.php.
Referenced by System().
    {
        return $this->ReplaceRegexp($this->confDir.'mail/aliases', "/^(\h*root:\h*)([^#\s]*)(.*)$/m", '${1}'.$emailaddr.'${3}');
    }
System::SetManCgiHome ($ ip)
Set int_net.
Definition at line 574 of file system.php.
Referenced by System().
    {
        $re= '|^(\s*\$www\{\'home\'\}\h*=\h*\')(.*)(\'\h*;\h*)$|m';
        return $this->ReplaceRegexp('/var/www/cgi-bin/man.cgi', $re, '${1}'."https://$ip".'${3}');
    }
System::SetDateTime ($ datetime)
Sets system clock.
Parameters:
[in] $datetime string Datetime.
Date returns 2 on locally successful.
Definition at line 584 of file system.php.
References $retval, cwc_syslog(), and ViewError().
Referenced by System().
    {
        exec("/bin/date $datetime 2>&1", $output, $retval);
        if ($retval === 2) {
            return TRUE;
        }
        $errout= implode("\n", $output);
        ViewError($errout);
        cwc_syslog(LOG_ERR, __FILE__, __FUNCTION__, __LINE__, "Set date failed: $errout");
        return FALSE;
    }
System::UpdateMailAliases ()
Update mail aliases.
Definition at line 599 of file system.php.
Referenced by System().
    {
        return $this->RunShellCommand('/usr/bin/newaliases');
    }
System::AutoConfig ()
Runs installer with automatic configuration option.
Definition at line 606 of file system.php.
References $retval, $ROOT, cwc_syslog(), and ViewError().
Referenced by System().
    {
        global $ROOT;
        exec("$ROOT/Installer/install.php -a 2>&1", $output, $retval);
        if ($retval === 0) {
            return TRUE;
        }
        $errout= implode("\n", $output);
        ViewError($errout);
        cwc_syslog(LOG_ERR, __FILE__, __FUNCTION__, __LINE__, "Auto configuration failed: $errout");
        return FALSE;
    }
System::InitGraphs ()
Delete all graph files, and recreate if necessary.
Definition at line 622 of file system.php.
References $retval, $VIEW_PATH, cwc_syslog(), and ViewError().
Referenced by System().
    {
        global $VIEW_PATH;
        $success= TRUE;
        // symon
        exec("/bin/rm -f ${VIEW_PATH}symon/cache/* 2>&1", $output, $retval);
        // Failing to clear the cache dir is not fatal
        exec("/bin/rm -f ${VIEW_PATH}symon/rrds/localhost/*.rrd 2>&1", $output, $retval);
        if ($retval === 0) {
            exec('/bin/sh /usr/local/share/symon/c_smrrds.sh all 2>&1', $output, $retval);
            if ($retval !== 0) {
                $success= FALSE;
            }
        }
        else {
            $success= FALSE;
        }
        // pnrg
        exec("/bin/rm -f ${VIEW_PATH}pmacct/protograph/comixwall.rrd 2>&1", $output, $retval);
        if ($retval === 0) {
            exec("/bin/sh ${VIEW_PATH}pmacct/protograph/createrrd.sh 2>&1", $output, $retval);
            if ($retval !== 0) {
                $success= FALSE;
            }
        }
        else {
            $success= FALSE;
        }
        // protograph
        exec("/bin/rm -f ${VIEW_PATH}pmacct/pnrg/spool/*.{gif,cgi,rrd,desc} 2>&1", $output, $retval);
        if ($retval !== 0) {
            $success= FALSE;
        }
        if (!$success) {
            $errout= implode("\n", $output);
            ViewError($errout);
            cwc_syslog(LOG_ERR, __FILE__, __FUNCTION__, __LINE__, "Failed initializing graphs: $errout");
        }
        return $success;
    }
System::DeleteStats ()
Delete files under /var/tmp/comixwall.
Definition at line 669 of file system.php.
Referenced by System().
    {
        exec('/bin/rm -rf /var/tmp/comixwall/* 2>&1', $output, $retval);
        if ($retval === 0) {
            return TRUE;
        }
        $errout= implode("\n", $output);
        ViewError($errout);
        cwc_syslog(LOG_ERR, __FILE__, __FUNCTION__, __LINE__, "Failed erasing statistics files: $errout");
        return FALSE;
    }
System::Shutdown ()
Shut down.
Definition at line 683 of file system.php.
Referenced by System().
    {
        global $TmpFile;
        $this->RunShellCommand("/sbin/shutdown -h -p now > $TmpFile 2>&1 &");
    }
System::Restart ()
Restart module processes.
Reimplemented from Model.
Definition at line 690 of file system.php.
Referenced by System().
    {
        global $TmpFile;
        $this->RunShellCommand("/sbin/shutdown -r now > $TmpFile 2>&1 &");
    }
System::GetPartitionsPfw ()
Gets pfw partition list.
Definition at line 699 of file system.php.
Referenced by System().
    {
        global $VIEW_PATH;
        return $this->RunShellCommand("${VIEW_PATH}pf/bin/commandwrapper.sh localhost -df");
    }
System::GetSystemInfo ()
Gets system information.
Definition at line 708 of file system.php.
Referenced by System().
    {
        global $VIEW_PATH;
        return $this->RunShellCommand("${VIEW_PATH}pf/bin/commandwrapper.sh localhost -info");
    }
System::DisplayRemoteTime ($ timeserver)
Displays datetime from time server.
Definition at line 717 of file system.php.
Referenced by System().
    {
        global $TmpFile;
        $this->Pkill('rdate');
        return $this->RunShellCommand("/usr/sbin/rdate -p $timeserver > $TmpFile 2>&1 &");
    }
System::SetRemoteTime ($ timeserver)
Sets datetime from time server.
Definition at line 727 of file system.php.
Referenced by System().
    {
        global $TmpFile;
        $this->Pkill('rdate');
        return $this->RunShellCommand("/usr/sbin/rdate $timeserver > $TmpFile 2>&1 &");
    }
System::GetRemoteTime ()
Definition at line 735 of file system.php.
Referenced by System().
    {
        global $TmpFile;
        $count= 0;
        while ($count++ < self::PROC_STAT_TIMEOUT) {
            if (!$this->IsRunning('rdate')) {
                break;
            }
            // shell sleep command seems not affected by changes to clock
            exec('/bin/sleep .1');
        }
        if ($count < self::PROC_STAT_TIMEOUT) {
            if (($output= $this->GetFile($TmpFile)) !== FALSE) {
                $retval= $output;
            }
        }
        else {
            $retval= _('The process is taking too long, thus will run in the background.');
        }
        return $retval;
    }
System::GetServiceStartStatus ()
Gets service start stati.
Definition at line 761 of file system.php.
Referenced by System().
    {
        $output= array();
        foreach ($this->rcConfLocalServices as $service) {
            $stat= $this->GetServiceStatRcConfLocal($this->rcConfLocal, $service);
            if ($stat === '') {
                $output[$service]= TRUE;
            }
            else if ($stat === '#') {
                $output[$service]= FALSE;
            }
        }
        foreach ($this->rcLocalServices as $service) {
            $stat= $this->GetServiceStatRcLocal($this->confDir.'rc.local', $service);
            if ($stat === '') {
                $output[$service]= TRUE;
            }
            else if ($stat === '#') {
                $output[$service]= FALSE;
            }
        }
        return serialize($output);
    }
System::GetServiceStatRcConfLocal ($ file, $ service)
Gets service startup status in rc.conf.local.
Parameters:
[in] $file Config file.
[in] $service Service name in rc.conf.local.
Returns:
Empty if on, # if off.
Definition at line 791 of file system.php.
    {
        return $this->SearchFile($file, "/^\h*(#|)\h*$service\h*=.*$/m");
    }
System::GetServiceStatRcLocal ($ file, $ service)
Gets service startup status in rc.local.
Parameters:
[in] $file Config file.
[in] $service Service name in rc.local.
Returns:
Empty if on, # if off.
Definition at line 802 of file system.php.
    {
        $service= Escape($service, '/');
        return $this->SearchFile($file, "/^\h*(#|)\h*$service\b.*$/m");
    }
System::DisableService ($ service)
Turn off (disable) service startup.
Parameters:
[in] $service Service name.
Definition at line 812 of file system.php.
Referenced by System().
    {
        if (in_array($service, $this->rcConfLocalServices)) {
            return $this->DisableServiceRcConfLocal($service);
        }
        else if (in_array($service, $this->rcLocalServices)) {
            return $this->DisableServiceRcLocal($service);
        }
        else {
            return FALSE;
        }
    }
System::EnableService ($ service)
Turn on (enable) service startup.
Parameters:
[in] $service Service name.
Definition at line 829 of file system.php.
Referenced by System().
    {
        if (in_array($service, $this->rcConfLocalServices)) {
            return $this->EnableServiceRcConfLocal($service);
        }
        else if (in_array($service, $this->rcLocalServices)) {
            return $this->EnableServiceRcLocal($service);
        }
        else {
            return FALSE;
        }
    }
System::DisableServiceRcConfLocal ($ service)
Turn off (disable) service startup in rc.conf.local.
Parameters:
[in] $service Service name in rc.conf.local.
Definition at line 846 of file system.php.
    {
        return $this->ReplaceRegexp($this->rcConfLocal, "/^(\h*$service\h*=.*)$/m", '#${1}');
    }
System::DisableServiceRcLocal ($ service)
Turn off (disable) service startup in rc.local.
Parameters:
[in] $service Service name in rc.local.
Definition at line 855 of file system.php.
    {
        $service= Escape($service, '/');
        return $this->ReplaceRegexp($this->confDir.'rc.local', "/^(\h*$service\b.*)$/m", '#${1}');
    }
System::EnableServiceRcConfLocal ($ service)
Turn on (enable) service startup in rc.conf.local.
Parameters:
[in] $service Service name in rc.conf.local.
Definition at line 865 of file system.php.
    {
        return $this->ReplaceRegexp($this->rcConfLocal, "/^\h*#(\h*$service\h*=.*)$/m", '${1}');
    }
System::EnableServiceRcLocal ($ service)
Turn on (enable) service startup in rc.local.
Parameters:
[in] $service Service name in rc.local.
Definition at line 874 of file system.php.
    {
        $service= Escape($service, '/');
        return $this->ReplaceRegexp($this->confDir.'rc.local', "/^\h*#(\h*$service\b.*)$/m", '${1}');
    }
System::GetLogsConfig ()
Get logs configuration.
Definition at line 882 of file system.php.
Referenced by System().
    {
        global $MODEL_PATH, $ModelFiles, $Models, $ModelsToLogConfig;
        $output= array();
        foreach ($ModelsToLogConfig as $m) {
            if (array_key_exists($m, $ModelFiles)) {
                require_once($MODEL_PATH.$ModelFiles[$m]);
                if (class_exists($Models[$m])) {
                    $model= new $Models[$m]();
                    if (($config= $model->GetNewsyslogConfig($m)) !== FALSE) {
                        $output= array_merge($output, $config);
                    }
                }
                else {
                    cwc_syslog(LOG_NOTICE, __FILE__, __FUNCTION__, __LINE__, "Not in Models: $m");
                }
            }
            else {
                cwc_syslog(LOG_NOTICE, __FILE__, __FUNCTION__, __LINE__, "Not in ModelFiles: $m");
            }
        }
        return serialize($output);
    }
System::SetLogsConfig ($ model, $ file, $ count, $ size, $ when)
Set logs configuration.
Definition at line 910 of file system.php.
Referenced by System().
    {
        global $MODEL_PATH, $ModelFiles, $Models, $ModelsToLogConfig;
        if (array_key_exists($model, $ModelFiles)) {
            require_once($MODEL_PATH.$ModelFiles[$model]);
            if (class_exists($Models[$model])) {
                $model= new $Models[$model]();
                return $model->SetNewsyslogConfig($file, $count, $size, $when);
            }
            else {
                cwc_syslog(LOG_NOTICE, __FILE__, __FUNCTION__, __LINE__, "Not in Models: $model");
            }
        }
        else {
            cwc_syslog(LOG_NOTICE, __FILE__, __FUNCTION__, __LINE__, "Not in ModelFiles: $model");
        }
        return FALSE;
    }
System::RotateLogFile ($ file)
Calls forked rotation function.
Definition at line 933 of file system.php.
Referenced by System().
    {
        return $this->DaemonizeFunc('DaemonizedRotateLogFile', $file);
    }
System::DaemonizedRotateLogFile ($ file)
Rotate log file via newsyslog.
Daemonized, because newsyslog may kill httpd, hence parent.
Definition at line 942 of file system.php.
    {
        global $TmpFile;
        if (($contents= $this->GetFile($this->newSyslogConf)) !== FALSE) {
            $re_filepath= Escape($file, '/');
            $re_owner= '([\w:]+|)';
            $re_mode= '(\d+)';
            $re_count= '(\d+)';
            $re_size= '(\d+|\*)';
            $re_when= '(\d+|\*)';
            $re= "/^(\s*$re_filepath\s+$re_owner\s*$re_mode\s+$re_count\s+$re_size\s+$re_when\s+.*)$/m";
            if (preg_match($re, $contents, $match)) {
                $line= $match[1];
                $cmd= "/bin/echo '$line' | /usr/bin/newsyslog -vF -f -  > $TmpFile 2>&1 &";
                exec($cmd, $output, $retval);
                if ($retval === 0) {
                    return TRUE;
                }
                $errout= implode("\n", $output);
                ViewError($errout);
                cwc_syslog(LOG_ERR, __FILE__, __FUNCTION__, __LINE__, "Log rotation failed: $errout");
            }
        }
        return FALSE;
    }
System::RotateAllLogFiles ()
Calls forked full rotation function.
Definition at line 972 of file system.php.
Referenced by System().
    {
        return $this->DaemonizeFunc('DaemonizedRotateAllLogFiles');
    }
System::DaemonizedRotateAllLogFiles ()
Rotate all log files via newsyslog.
Daemonized, because newsyslog kills httpd, hence parent, stopping rotation in the middle, e.g. before compressing files.
Definition at line 982 of file system.php.
    {
        global $TmpFile;
        $cmd= "/usr/bin/newsyslog -vF -f $this->newSyslogConf > $TmpFile 2>&1 &";
        exec($cmd, $output, $retval);
        if ($retval === 0) {
            return TRUE;
        }
        $errout= implode("\n", $output);
        ViewError($errout);
        cwc_syslog(LOG_ERR, __FILE__, __FUNCTION__, __LINE__, "Log rotation failed: $errout");
        return FALSE;
    }
System::DaemonizeFunc ($ func, $ param = '')
Daemonizes to run the given function.
Definition at line 999 of file system.php.
    {
        $pid= pcntl_fork();
        if ($pid == -1) {
            cwc_syslog(LOG_ERR, __FILE__, __FUNCTION__, __LINE__, 'Cannot fork');
        }
        else if ($pid) {
             // Parent should exit
            return TRUE;
        }
        else {
            // Make the child process a session leader
            $sid= posix_setsid();
            if ($sid < 0) {
                cwc_syslog(LOG_ERR, __FILE__, __FUNCTION__, __LINE__, 'Cannot make the child a session leader');
                // Exit if cannot daemonize completely
                return FALSE;
            }
            // The child is daemonized now, hence survives even if its process group is killed.
            // This is necessary when rotating httpd logs.
            $argv= array();
            if ($param !== '') {
                $argv= array($param);
            }
            return call_user_func_array(array($this, $func), $argv);
        }
    }
System::SetPassword ($ user, $ passwd)
Sets user's password in htpasswd file.
Passwords in htpasswd file are SHA1 encrypted.
Definition at line 1030 of file system.php.
Referenced by System().
    {
        exec("/usr/bin/htpasswd -b -s $this->passwdFile $user $passwd 2>&1", $output, $retval);
        if ($retval === 0) {
            return TRUE;
        }
        $errout= implode("\n", $output);
        ViewError($errout);
        cwc_syslog(LOG_ERR, __FILE__, __FUNCTION__, __LINE__, "Set password failed: $errout");
        return FALSE;
    }
System::SetLocale ($ locale)
Definition at line 1043 of file system.php.
Referenced by System().
    {
        global $ROOT;
        $this->NVPS= '=';
        // Append semi-colon to new value, this setting is a PHP line
        return $this->SetNVP($ROOT.'/lib/setup.php', '\$DefaultLocale', "'$locale';");
    }
System::SetLogLevel ($ level)
Definition at line 1052 of file system.php.
Referenced by System().
    {
        global $ROOT;
        $this->NVPS= '=';
        // Append semi-colon to new value, this setting is a PHP line
        return $this->SetNVP($ROOT.'/lib/setup.php', '\$LOG_LEVEL', $level.';');
    }
System::SetHelpBoxes ($ bool)
Definition at line 1061 of file system.php.
Referenced by System().
    {
        global $VIEW_PATH;
        $this->NVPS= '=';
        // Append semi-colon to new value, this setting is a PHP line
        return $this->SetNVP($VIEW_PATH.'lib/setup.php', '\$ShowHelpBox', $bool.';');
    }
System::SetReloadRate ($ rate)
Definition at line 1070 of file system.php.
Referenced by System().
    {
        global $VIEW_PATH;
        $this->NVPS= '=';
        // Append semi-colon to new value, this setting is a PHP line
        return $this->SetNVP($VIEW_PATH.'lib/setup.php', '\$DefaultReloadRate', $rate.';');
    }
System::SetSessionTimeout ($ timeout)
Definition at line 1079 of file system.php.
Referenced by System().
    {
        global $VIEW_PATH;
        if ($timeout < 10) {
            $timeout= 10;
        }
        $this->NVPS= '=';
        // Append semi-colon to new value, this setting is a PHP line
        return $this->SetNVP($VIEW_PATH.'lib/setup.php', '\$SessionTimeout', $timeout.';');
    }
System::NetStart ()
Definition at line 1092 of file system.php.
Referenced by System().
    {
        // Should refresh pf rules too
        $cmd= "/bin/sh /etc/netstart 2>&1 && /sbin/pfctl -f $this->PfRulesFile 2>&1";
        exec($cmd, $output, $retval);
        if ($retval === 0) {
            return TRUE;
        }
        $errout= implode("\n", $output);
        ViewError($errout);
        cwc_syslog(LOG_ERR, __FILE__, __FUNCTION__, __LINE__, "Netstart failed: $errout");
        return FALSE;
    }
System::SelectProcesses ($ psout)
Returns all processes from ps output.
Used by Processes page, hence lists all processes.
Parameters:
[in] $psout ps output.
Returns:
array Parsed ps output
Reimplemented from Model.
Definition at line 1113 of file system.php.
    {
        //   PID STARTED  %CPU      TIME %MEM   RSS   VSZ STAT  PRI  NI TTY      USER     GROUP    COMMAND
        //     1  5:10PM   0.0   0:00.03  0.0   388   412 Is     10   0 ??       root     wheel    /sbin/init
        $re= '/^\s*(\d+)\s+(\S+)\s+(\S+)\s+(\S+)\s+(\S+)\s+(\d+)\s+(\d+)\s+(\S+)\s+(\d+)\s+(\d+)\s+\S+\s+(\S+)\s+(\S+)\s+(.+)$/';
        $processes= array();
        foreach ($psout as $line) {
            if (preg_match($re, $line, $match)) {
                $processes[]= array(
                    $match[1],
                    $match[2],
                    $match[3],
                    $match[4],
                    $match[5],
                    $match[6],
                    $match[7],
                    $match[8],
                    $match[9],
                    $match[10],
                    $match[11],
                    $match[12],
                    $match[13],
                    );
            }
        }
        return $processes;
    }
System::System ()
Definition at line 44 of file include.php.
References _HELPWINDOW().
    {
        $this->LogsHelpMsg= _HELPWINDOW('This page shows system-wide logs. Most services on ComixWall write to their own log files, but a few processes may log messages to this system file. Pay special attention to error messages.');
    }
Member Data Documentation
System::$Name = 'system'
Reimplemented from Model.
Definition at line 44 of file system.php.
System::$User = '\S+'
Reimplemented from Model.
Definition at line 45 of file system.php.
System::$LogFile = '/var/log/messages'
Reimplemented from Model.
Definition at line 51 of file system.php.
System::$Model = 'system'
Reimplemented from View.
Definition at line 41 of file include.php.
System::$Layout = 'system'
Reimplemented from View.
Definition at line 42 of file include.php.
The documentation for this class was generated from the following files:
Model/system.php
View/system/include.php