ComixWall ISG Administration Interface: Named Class Reference
Named Class Reference
Public Member Functions
Named ()
GetForwarders ()
Gets name server forwarders.
SetForwarders ($forwarders)
Sets name server forwarders.
ParseLogLine ($logline, &$cols)
Log parser.
Named ()
Public Attributes
$Name = 'named'
$User = 'root|named'
$ConfFile = '/var/named/etc/named.conf'
$LogFile = '/var/log/named.log'
$VersionCmd = '/usr/sbin/named -v'
$PidFile = '/var/run/named.pid'
$Model = 'named'
$Layout = 'named'
Detailed Description
Definition at line 38 of file named.php.
Member Function Documentation
Named::Named ()
Definition at line 50 of file named.php.
References $TmpFile, GetForwarders(), Model, and SetForwarders().
    {
        global $TmpFile;
        parent::Model();
        $this->StartCmd= "/usr/sbin/named > $TmpFile 2>&1 &";
        $this->Commands= array_merge(
            $this->Commands,
            array(
                'GetForwarders' => array(
                    'argv'  => array(),
                    'desc'  => _('Get DNS forwarders'),
                    ),
                'SetForwarders' => array(
                    'argv'  => array(IPADRLIST),
                    'desc'  => _('Set DNS forwarders'),
                    ),
                )
            );
    }
Named::GetForwarders ()
Gets name server forwarders.
Returns:
Forwarders IP, semi-colon separated.
Todo:
Is semi-colon separated list fine?
Definition at line 79 of file named.php.
References Model::SearchFile().
Referenced by Named().
    {
        return $this->SearchFile($this->ConfFile, "/^\h*forwarders\h*{\h*(.*)\h*\;\h*}\h*\;\h*$/m");
    }
Named::SetForwarders ($ forwarders)
Sets name server forwarders.
Parameters:
[in] $forwarders string semi-colon seperated list of IPs, forwarders.
Returns:
Replace result.
Definition at line 89 of file named.php.
References Model::ReplaceRegexp().
Referenced by Named().
    {
        return $this->ReplaceRegexp($this->ConfFile, "/^(\h*forwarders\h*{\h*)(.*)(\h*\;\h*}\h*\;\h*)$/m", '${1}'.$forwarders.'${3}');
    }
Named::ParseLogLine ($ logline, &$ cols)
Log parser.
Parameters:
[in] $logline string Log line
[out] $cols array Parsed fields
Returns:
TRUE if log line is parsed
Reimplemented from Model.
Definition at line 94 of file named.php.
References $Re_Ip, and Model::ParseSyslogLine().
    {
        global $Re_Ip;
        if ($this->ParseSyslogLine($logline, $cols)) {
            $re_clientip= "($Re_Ip)";
            $re_num= '(\d+)';
            $re_domain= '(\S+)';
            $re_type= '(.*)';
            // client 127.0.0.1#31874: query: www.openbsd.org IN A +
            $re= "/client\s+$re_clientip#$re_num:\s+query:\s+$re_domain\s+\S+\s+$re_type$/";
            if (preg_match($re, $logline, $match)) {
                $cols['IP']= $match[1];
                $cols['Domain']= $match[3];
                $cols['Type']= $match[4];
            }
            return TRUE;
        }
        return FALSE;
    }
Named::Named ()
Definition at line 44 of file include.php.
References _HELPWINDOW().
    {
        $this->LogsHelpMsg= _HELPWINDOW('DNS server logs all name lookups. You should see many requests from the system itself along with those from internal clients.');
    }
Member Data Documentation
Named::$Name = 'named'
Reimplemented from Model.
Definition at line 40 of file named.php.
Named::$User = 'root|named'
Reimplemented from Model.
Definition at line 41 of file named.php.
Named::$ConfFile = '/var/named/etc/named.conf'
Reimplemented from Model.
Definition at line 43 of file named.php.
Named::$LogFile = '/var/log/named.log'
Reimplemented from Model.
Definition at line 44 of file named.php.
Named::$VersionCmd = '/usr/sbin/named -v'
Reimplemented from Model.
Definition at line 46 of file named.php.
Named::$PidFile = '/var/run/named.pid'
Reimplemented from Model.
Definition at line 48 of file named.php.
Named::$Model = 'named'
Reimplemented from View.
Definition at line 41 of file include.php.
Named::$Layout = 'named'
Reimplemented from View.
Definition at line 42 of file include.php.
The documentation for this class was generated from the following files:
Model/named.php
View/named/include.php