ComixWall ISG Administration Interface: Apache Class Reference
Apache Class Reference
Public Member Functions
Apache ()
GetVersion ()
Gets software version string.
Restart ()
Restart module processes.
Stop ()
Stops module process(es).
ParseLogLine ($logline, &$cols)
Log parser.
SetWebalizerHostname ($ip)
Apache ()
Public Attributes
$Name = 'apache'
$User = 'root|www'
$NVPS = '\h'
$ConfFile = '/var/www/conf/httpd.conf'
$LogFile = '/var/www/logs/error_log'
$VersionCmd = '/usr/sbin/httpd -v'
$Model = 'apache'
$Layout = 'httpd'
Detailed Description
Definition at line 38 of file apache.php.
Member Function Documentation
Apache::Apache ()
Definition at line 50 of file apache.php.
References Model, and SetWebalizerHostname().
    {
        parent::Model();
        $this->Proc= 'httpd';
        $this->Commands= array_merge(
            $this->Commands,
            array(
                'SetWebalizerHostname'=>    array(
                    'argv'  =>  array(IPADR),
                    'desc'  =>  _('Set webalizer hostname'),
                    ),
                )
            );
    }
Apache::GetVersion ()
Gets software version string.
Reimplemented from Model.
Definition at line 67 of file apache.php.
References Model::RunShellCommand().
    {
        return $this->RunShellCommand($this->VersionCmd)."\n".
            $this->RunShellCommand($this->phpVersionCmd.' | /usr/bin/head -1');
    }
Apache::Restart ()
Restart module processes.
Reimplemented from Model.
Definition at line 73 of file apache.php.
References Model::RunShellCommand().
    {
        return $this->RunShellCommand('/usr/sbin/apachectl restart');
    }
Apache::Stop ()
Stops module process(es).
Tries PROC_STAT_TIMEOUT times.
Returns:
boolean TRUE if the process killed successfully
Todo:
Actually should stop retrying on some error conditions?
Reimplemented from Model.
Definition at line 78 of file apache.php.
References Model::RunShellCommand().
    {
        return $this->RunShellCommand('/usr/sbin/apachectl stop');
    }
Apache::ParseLogLine ($ logline, &$ cols)
Log parser.
Parameters:
[in] $logline string Log line
[out] $cols array Parsed fields
Returns:
TRUE if log line is parsed
Reimplemented from Model.
Reimplemented in Apachelogs, and Cwlogs.
Definition at line 83 of file apache.php.
References $retval, and Model::ParseSyslogLine().
    {
        //[Mon Sep 10 22:00:01 2007] [notice] Accept mutex: sysvsem (Default: sysvsem)
        $re_datetime= '\[([a-zA-Z]+)\s+([a-zA-Z]+)\s+(\d+)\s+(\d+:\d+:\d+)\s+(\d+)\]';
        $re_loglevel= '\[([a-zA-Z]+)\]';
        $re_rest= '(.*)';
        $re= "/^$re_datetime\s+$re_loglevel\s+$re_rest$/";
        if (preg_match($re, $logline, $match)) {
            $cols['Date']= "$match[2] $match[3] $match[5]";
            $cols['Time']= $match[4];
            $cols['Level']= $match[6];
            $cols['Log']= $match[7];
        }
        else {
            if ($retval= $this->ParseSyslogLine($logline, $cols)) {
                $cols['DateTime']= $cols['Date'].' '.$cols['Time'];
            }
            else {
                // There are very simple log lines too, e.g. "man: Formatting manual page..."
                // So parser never fails
                $cols['Log']= $logline;
            }
        }
        return TRUE;
    }
Apache::SetWebalizerHostname ($ ip)
Definition at line 110 of file apache.php.
References $Re_Ip, and Model::ReplaceRegexp().
Referenced by Apache().
    {
        global $Re_Ip;
        $re= "/^(\h*HostName\h+)($Re_Ip|[\w\.]+)(\s+.*)/ms";
        return $this->ReplaceRegexp('/etc/webalizer.conf', $re, '${1}'.$ip.'${3}');
    }
Apache::Apache ()
Definition at line 44 of file include.php.
References _HELPBOX2(), _HELPWINDOW(), _TITLE2(), ConfHelpMsg, Config, However, and Model::Start().
    {
        $this->LogsHelpMsg= _HELPWINDOW('These logs may be important for diagnosing web server related problems.');
        $this->ConfHelpMsg= _HELPWINDOW('Since this web administration interface depends on the Apache web server, you should be careful while modifying these options. By default, the web server is configured to serve this web interface only, hence the default values should suffice for most purposes. However, OpenBSD/httpd is a full-featured HTTP server, and you can configure it to serve web sites too.');
        $this->Config= array(
            'ServerAdmin' => array(
                'title' => _TITLE2('Server Admin'),
                'info' => _HELPBOX2('ServerAdmin: Your address, where problems with the server should be e-mailed.
        This address appears on some server-generated pages, such as error documents.'),
                ),
            'HostnameLookups' => array(
                'title' => _TITLE2('Hostname Lookups'),
                'info' => _HELPBOX2('Log the names of clients or just their IP addresses e.g., www.apache.org (on) or 204.62.129.132 (off).
        The default is off because it\'d be overall better for the net if people had to knowingly turn this feature on, since enabling it means that each client request will result in AT LEAST one lookup request to the nameserver.'),
                ),
            'LogLevel' => array(
                'title' => _TITLE2('Log Level'),
                'info' => _HELPBOX2('LogLevel: Control the number of messages logged to the error_log.
        Possible values include: debug, info, notice, warn, error, crit, alert, emerg.'),
                ),
            'Timeout' => array(
                'title' => _TITLE2('Timeout'),
                'info' => _HELPBOX2('The number of seconds before receives and sends time out.'),
                ),
            'KeepAlive' => array(
                'title' => _TITLE2('KeepAlive'),
                'info' => _HELPBOX2('Whether or not to allow persistent connections (more than one request per connection). Set to "Off" to deactivate.'),
                ),
            'MaxKeepAliveRequests' => array(
                'title' => _TITLE2('Max KeepAlive Requests'),
                'info' => _HELPBOX2('The maximum number of requests to allow during a persistent connection. Set to 0 to allow an unlimited amount. We recommend you leave this number high, for maximum performance.'),
                ),
            'KeepAliveTimeout' => array(
                'title' => _TITLE2('KeepAlive Timeout'),
                'info' => _HELPBOX2('Number of seconds to wait for the next request from the same client on the same connection.'),
                ),
            'MinSpareServers' => array(
                'title' => _TITLE2('Min Spare Servers'),
                'info' => _HELPBOX2('Server-pool size regulation.
        Rather than making you guess how many server processes you need, Apache dynamically adapts to the load it sees --- that is, it tries to maintain enough server processes to handle the current load, plus a few spare servers to handle transient load spikes (e.g., multiple simultaneous requests from a single Netscape browser).
        It does this by periodically checking how many servers are waiting for a request.  If there are fewer than MinSpareServers, it creates a new spare.  If there are more than MaxSpareServers, some of the spares die off.  The default values in httpd.conf-dist are probably OK for most sites.'),
                ),
            'MaxSpareServers' => array(
                'title' => _TITLE2('Max Spare Servers'),
                ),
            'StartServers' => array(
                'title' => _TITLE2('Start Servers'),
                'info' => _HELPBOX2('Number of servers to start initially --- should be a reasonable ballpark figure.'),
                ),
            'MaxClients' => array(
                'title' => _TITLE2('Max Clients'),
                'info' => _HELPBOX2('Limit on total number of servers running, i.e., limit on the number of clients who can simultaneously connect --- if this limit is ever reached, clients will be LOCKED OUT, so it should NOT BE SET TOO LOW. It is intended mainly as a brake to keep a runaway server from taking the system with it as it spirals down...'),
                ),
            );
    }
Member Data Documentation
Apache::$Name = 'apache'
Reimplemented from Model.
Reimplemented in Apachelogs.
Definition at line 40 of file apache.php.
Apache::$User = 'root|www'
Reimplemented from Model.
Definition at line 41 of file apache.php.
Apache::$NVPS = '\h'
Reimplemented from Model.
Definition at line 43 of file apache.php.
Apache::$ConfFile = '/var/www/conf/httpd.conf'
Reimplemented from Model.
Definition at line 44 of file apache.php.
Apache::$LogFile = '/var/www/logs/error_log'
Reimplemented from Model.
Reimplemented in Apachelogs, Cwc, and Cwwui.
Definition at line 45 of file apache.php.
Apache::$VersionCmd = '/usr/sbin/httpd -v'
Reimplemented from Model.
Definition at line 47 of file apache.php.
Apache::$Model = 'apache'
Reimplemented from View.
Reimplemented in Cwc, Cwwui, and Apachelogs.
Definition at line 41 of file include.php.
Apache::$Layout = 'httpd'
Reimplemented from View.
Definition at line 42 of file include.php.
The documentation for this class was generated from the following files:
Model/apache.php
View/apache/include.php