ComixWall ISG Administration Interface: RRDTool Class Reference
RRDTool Class Reference
Public Member Functions
RRDTool ()
graph ($filename, $args)
get_error ()
get_output ()
_test ()
exec ($cmdline)
Public Attributes
$cmdline
$error
$output
Detailed Description
Definition at line 40 of file class_rrdtool.inc.
Member Function Documentation
RRDTool::RRDTool ()
Definition at line 45 of file class_rrdtool.inc.
References $symon, and method.
                       {
    global $symon;
    $this->method = '';
    if (isset($symon['rrdtool_path'])) {
        if (!is_executable($symon['rrdtool_path'])) {
        config_error('rrdtool_path', 'is not an executable');
        return 0;
        }
    } else {
        config_error('rrdtool_path', 'is not set');
        return 0;
    }
    return 1;
    }
RRDTool::graph ($ filename, $ args)
Definition at line 63 of file class_rrdtool.inc.
References $cmdline, $filename, $output, $result, $symon, exec(), and get_output().
{
    global $symon;
    if (!is_array($args)) {
        $temp = preg_split("/\n/", $args);
    } else {
        $temp = $args;
    }
    $args = array();
    reset($temp);
    foreach ($temp as $t) {
        if ($t == '') continue;
        if (preg_match("/^\s+$/s", $t)) continue;
        array_push($args, $t);
    }
    $cmdline = $symon['rrdtool_path'] . ' graph '. $filename .
        hash2cmdline($args) . ' 2>&1';
    $result = $this->exec($cmdline);
    if (isset($symon['rrdtool_debug'])) {
        $output = "\xa rrdtool graph debug output \xa cmdline: '$cmdline'\xa errors:'".$this->get_error()."'\xa output:'".$this->get_output()."'";
        error_log($output);
    }
    return $result;
    }
RRDTool::get_error ()
Definition at line 93 of file class_rrdtool.inc.
{
    return $this->error;
    }
RRDTool::get_output ()
Definition at line 97 of file class_rrdtool.inc.
Referenced by _test(), and graph().
{
    return $this->output;
    }
RRDTool::_test ()
Definition at line 101 of file class_rrdtool.inc.
References $cmdline, $symon, exec(), get_output(), and print.
                     {
    global $symon;
    $cmdline = $symon['rrdtool_path'] . ' -v';
    if ($this->exec($cmdline) == 0) {
        runtime_error('apache or php setup faulty: cannot execute '.$symon['rrdtool_path']);
        return 0;
    } else {
        $version_info = $this->get_output();
        if (strlen($version_info) == 0) {
        runtime_error('apache or php setup faulty: can execute '.$symon['rrdtool_path']. ', but no results are returned');
        return 0;
        } else {
        print "\xa rrdtool version: ";
        if (preg_match("/rrdtool\s+(\S+)/i", $version_info, $match)) {
            print $match[1];
        } else {
            print "unknown";
        }
        return 1;
        }
    }
    }
RRDTool::exec ($ cmdline)
Definition at line 125 of file class_rrdtool.inc.
References $cmdline.
Referenced by _test(), and graph().
{
    global $runtime;
    $this->error = '';
    $this->output = '';
    $this->cmdline = $cmdline;
    unset($reta);
    exec($cmdline, $reta, $ret);
    if ($ret != 0) {
        foreach($reta as $key => $value) {
        $this->error .= '<pre>'.$value.'</pre><br>';
        }
        return 0;
    } else {
        foreach($reta as $value) {
        if ($value != "") {
            $this->output .= '<p>'.$value.'</p>';
        }
        }
        if (strstr($this->output, '<p>ERROR:')) {
        return 0;
        }
        return 1;
    }
    return 1;
    }
Member Data Documentation
RRDTool::$cmdline
Definition at line 41 of file class_rrdtool.inc.
Referenced by _test(), exec(), and graph().
RRDTool::$error
Definition at line 42 of file class_rrdtool.inc.
RRDTool::$output
Definition at line 43 of file class_rrdtool.inc.
Referenced by graph().
The documentation for this class was generated from the following file:
View/symon/class_rrdtool.inc