ComixWall ISG Administration Interface: Model Class Reference
Model Class Reference
Public Member Functions
Model ()
GetIntIf ()
Get int_if.
GetExtIf ()
Get ext_if.
Restart ()
Restart module processes.
GetStatsLogLines ($logfile, $tail=-1)
Builds generic grep command to extract log lines.
SearchFile ($file, $re, $set=1, $trimchars= '')
Searches a given file with a given regexp.
SearchFileAll ($file, $re, $set=1)
Multi-searches a given file with a given regexp.
ReplaceRegexp ($file, $matchre, $replacere)
Search and replace.
RunShellCommand ($cmd)
Runs given shell command and returns its output as string.
AppendToFile ($file, $line)
Appends a string to a file.
GetFiles ($filepath)
Returns files with the given filepath pattern.
GetConfigValues ($conf, $group)
Returns all configuration for a given configuration type.
GetValue ($name, $conf, $group)
Returns all enabled configuration for a given configuration type.
GetDisabledValue ($name, $conf, $group)
Returns all disabled configuration for a given configuration type.
GetNVP ($file, $name, $trimchars= '')
Reads value of NVP.
GetDisabledNVP ($file, $name)
Reads value of commented-out NVP.
GetName ($file, $name)
Checks if Name exists.
GetDisabledName ($file, $name)
Checks if commented-out Name exists.
SetConfValue ($name, $newvalue, $conf, $group)
Sets the value of NVP configuration.
SetNVP ($file, $name, $newvalue)
Changes value of NVP.
EnableConf ($name, $conf, $group)
Enables a configuration item in conf file.
DisableConf ($name, $conf, $group)
Disables a configuration item in conf file.
EnableNVP ($file, $name)
Enables an NVP: configuration item with value.
EnableName ($file, $name)
Enables a Name: configuration item without value.
DisableNVP ($file, $name)
Disables an NVP.
DisableName ($file, $name)
Disables a Name.
GetConfFile ($conf, $group)
Returns configuration file of the module.
SetConfig ($confname)
Sets configuration file based on config type provided.
GetIpAddr ($if)
Extracts IP address assigned to an interface.
CheckAuthentication ($user, $passwd)
Checks user's password supplied against the one in htpasswd file.
GetLogStartDate ($file)
Extracts the datetime of the first line in the log file.
GetFileFirstLine ($file)
Gets first line of file.
GetFileLineCount ($file, $re= '')
Gets line count of file.
GetLogs ($file, $end, $count, $re= '')
Gets lines in file.
GetLiveLogs ($file, $count, $re= '')
Gets logs for live logs pages.
Reload ()
Sends HUP to the module pid.
Start ()
Start module process(es).
Stop ()
Stops module process(es).
Pkill ($proc)
Stops the given process.
Kill ()
Stops module's parent process with its pid.
KillPid ($pid)
Kills process with the given pid.
IsModulePidRunning ($pid)
Checks if the pid is running.
IsRunning ($proc= '')
Checks if the process(es) is running.
GetProcList ()
Gets the list of processes running.
SelectProcesses ($psout)
Selects user processes from ps output.
GetVersion ()
Gets software version string.
GetServiceStatus ()
Gets service statuses.
GetProcStatLines ($logfile)
Collects text statistics for the proc stats general page.
CopyLogFileToTmp ($file, $tmpdir)
Uncompresses gzipped log file to tmp dir.
GetFileCvsTag ($file)
Returns ComixWall cvs tag in the given file, if any.
GetSysCtl ($option)
Gets sysctl output for the given arg.
GetFile ($file)
Reads file contents.
GetDefaultLogFile ()
SelectLogFile ($file)
Returns log file under tmp location.
UpdateTmpLogFile ($file)
Copies original log file to tmp location.
GetTmpLogFileName ($file)
Returns the log file name in the tmp location.
GetLogFilesList ()
Gets log files list with start dates.
DeleteFile ($path)
Deletes file or dir.
PutFile ($file, $contents)
Writes contents to file.
GetPhyIfs ()
Extract physical interface names from ifconfig output.
GetAllStats ($logfile, $collecthours= '')
Returns both brief and full statistics.
GetStats ($logfile, $date, $collecthours= '')
Main statistics collector, as module data set.
CountDiffLogLines ($logfile, &$count)
Gets the number of lines added to log files since last tmp update.
UpdateStats ($logfile, &$stats, &$briefstats)
Updates statistics incrementally, both brief and full.
GetDateRegexp ($date)
Generates date regexp to be used by statistics functions.
GetHourRegexp ($date)
Generates hour regexp to be used by statistics functions.
GetSavedStats ($logfile, &$stats, &$briefstats)
Gets saved statistics for the given log file.
IsLogFileModified ($logfile)
Checks if the given log file has been updated.
GetStatsFileInfo ($logfile, &$linecount, &$filestat)
Gets previous line count and stat() from statistics file.
GetStatsFileName ($logfile)
Gets name of the tmp statistics file for the given log file.
GetOrigFileName ($logfile)
Returns the original file name for the given log file.
SaveStats ($logfile, $stats, $briefstats, $linecount)
Saves collected statistics with current line count and stat() output.
CollectDayStats ($statsdefs, $values, $line, &$stats)
Day statistics collector.
CollectHourStats ($statsdefs, $hour, $min, $values, $line, &$daystats)
Hour statistics collector.
IncStats ($line, $values, $statsdefs, &$stats)
Increments stats for the given values.
CollectMinuteStats ($statsdefs, $min, $values, $line, &$hourstats)
Minute statistics collector.
ParseLogLine ($logline, &$cols)
Log parser.
ParseSyslogLine ($logline, &$cols)
Parses standard syslog line.
Public Attributes
$Name = ''
$User = ''
$Proc = ''
Attention:
Should be updated in constructors of children
$NVPS = '='
$COMC = '#'
$ConfFile = ''
$Config = ''
$LogFile = ''
const PROC_STAT_TIMEOUT = 100
Max number of iterations to try while starting or stopping processes.
$CmdLogStart = '/usr/bin/head -1 <LF>'
$VersionCmd = ''
$StartCmd = ''
$PidFile = ''
$TmpLogsDir = ''
$PfRulesFile = '/etc/pf.conf'
$Commands = array()
Argument lists and descriptions of commands.
Protected Attributes
$psCmd = '/bin/ps arwwx -o pid,start,%cpu,time,%mem,rss,vsz,stat,pri,nice,tty,user,group,command | /usr/bin/grep -E <PROC>'
$passwdFile = '/var/www/conf/.htpasswd'
Apache password file pathname.
$newSyslogConf = '/etc/newsyslog.conf'
$rcConfLocal = '/etc/rc.conf.local'
Detailed Description
Definition at line 40 of file model.php.
Member Function Documentation
Model::Model ()
Todo:
Is there any pattern or size for new value, 2nd param?
Definition at line 89 of file model.php.
References $ModelConfig, CheckAuthentication(), Config, DisableConf(), EnableConf(), GetAllStats(), GetConfigValues(), GetDefaultLogFile(), GetExtIf(), GetFileCvsTag(), GetFileLineCount(), GetIntIf(), GetLiveLogs(), GetLogFilesList(), GetLogs(), GetLogStartDate(), GetPhyIfs(), GetProcList(), GetProcStatLines(), GetServiceStatus(), GetStats(), GetSysCtl(), GetVersion(), IsRunning(), Reload(), Restart(), SelectLogFile(), SetConfValue(), Start(), and Stop().
    {
        global $ModelConfig;
        $this->Proc= $this->Name;
        $this->Config= $ModelConfig;
        $this->TmpLogsDir= '/var/tmp/comixwall/logs/'.get_class($this).'/';
        $this->Commands= array_merge(
            $this->Commands,
            array(
                'GetIntIf'=>    array(
                    'argv'  =>  array(),
                    'desc'  =>  _('Get int_if'),
                    ),
                'GetExtIf'=>    array(
                    'argv'  =>  array(),
                    'desc'  =>  _('Get ext_if'),
                    ),
                'GetVersion'    =>  array(
                    'argv'  =>  array(),
                    'desc'  =>  _('Get software version'),
                    ),
                'Reload'    =>  array(
                    'argv'  =>  array(),
                    'desc'  =>  _('Reload '.get_class($this)),
                    ),
                'Start' =>  array(
                    'argv'  =>  array(),
                    'desc'  =>  _('Start '.get_class($this)),
                    ),
                'Restart'   => array(
                    'argv'  => array(),
                    'desc'  => _('Restart '.get_class($this)),
                    ),
                'Stop'  =>  array(
                    'argv'  =>  array(),
                    'desc'  => _('Stop '.get_class($this)),
                    ),
                'IsRunning' =>  array(
                    'argv'  =>  array(),
                    'desc'  =>  _('Check if process running'),
                    ),
                'GetProcList'   =>  array(
                    'argv'  =>  array(),
                    'desc'  =>  _('Get process list'),
                    ),
                'GetServiceStatus'  =>  array(
                    'argv'  =>  array(),
                    'desc'  =>  _('Get service status'),
                    ),
                'GetAllStats'=> array(
                    'argv'  =>  array(FILEPATH, NAME|EMPTYSTR),
                    'desc'  =>  _('Get all stats'),
                    ),
                'GetStats'=>    array(
                    'argv'  =>  array(FILEPATH, SERIALARRAY, NAME|EMPTYSTR),
                    'desc'  =>  _('Get stats'),
                    ),
                'GetPhyIfs'     =>  array(
                    'argv'  =>  array(),
                    'desc'  =>  _('List physical interfaces'),
                    ),
                'GetFileCvsTag'=>   array(
                    'argv'  =>  array(FILEPATH),
                    'desc'  =>  _('Get source file CVS tag'),
                    ),
                'GetDefaultLogFile' =>  array(
                    'argv'  =>  array(),
                    'desc'  =>  _('Get log file'),
                    ),
                'SelectLogFile' =>  array(
                    'argv'  =>  array(FILEPATH|EMPTYSTR),
                    'desc'  =>  _('Select log file'),
                    ),
                'GetLogFilesList'   =>  array(
                    'argv'  =>  array(),
                    'desc'  =>  _('Get log files list'),
                    ),
                'GetProcStatLines'  =>  array(
                    'argv'  =>  array(FILEPATH|NONE),
                    'desc'  =>  _('Get stat lines'),
                    ),
                'GetSysCtl' =>  array(
                    'argv'  =>  array(NAME),
                    'desc'  =>  _('Get sysctl values'),
                    ),
                'CheckAuthentication'   =>  array(
                    'argv'  =>  array(NAME, SHA1STR),
                    'desc'  =>  _('Check authentication'),
                    ),
                'GetConfigValues'   =>  array(
                    'argv'  =>  array(NAME|EMPTYSTR, NUM|EMPTYSTR),
                    'desc'  =>  _('Get config values'),
                    ),
                'SetConfValue'  =>  array(
                    'argv'  =>  array(CONFNAME, STR, NAME|EMPTYSTR, NUM|EMPTYSTR),
                    'desc'  =>  _('Set name value pair'),
                    ),
                'EnableConf'    =>  array(
                    'argv'  =>  array(CONFNAME, NAME|EMPTYSTR, NUM|EMPTYSTR),
                    'desc'  =>  _('Enable config'),
                    ),
                'DisableConf'   =>  array(
                    'argv'  =>  array(CONFNAME, NAME|EMPTYSTR, NUM|EMPTYSTR),
                    'desc'  =>  _('Disable config'),
                    ),
                'GetLogStartDate'   =>  array(
                    'argv'  =>  array(FILEPATH),
                    'desc'  =>  _('Get log start date'),
                    ),
                'GetFileLineCount'  =>  array(
                    'argv'  =>  array(FILEPATH, REGEXP|NONE),
                    'desc'  =>  _('Gets line count'),
                    ),
                'GetLogs'   =>  array(
                    'argv'  =>  array(FILEPATH, NUM, NUM, REGEXP|NONE),
                    'desc'  =>  _('Get lines'),
                    ),
                'GetLiveLogs'   =>  array(
                    'argv'  =>  array(FILEPATH, NUM, REGEXP|NONE),
                    'desc'  =>  _('Get tail'),
                    ),
                'PrepareFileForDownload'    =>  array(
                    'argv'  =>  array(FILEPATH),
                    'desc'  =>  _('Prepare file for download'),
                    ),
                'GetAllowedIps' =>  array(
                    'argv'  =>  array(),
                    'desc'  =>  _('Get PF allowed'),
                    ),
                'AddAllowedIp'  =>  array(
                    'argv'  =>  array(IPADR|IPRANGE),
                    'desc'  =>  _('Set PF allowed'),
                    ),
                'DelAllowedIp'  =>  array(
                    'argv'  =>  array(IPADR|IPRANGE),
                    'desc'  =>  _('Delete PF allowed'),
                    ),
                'GetRestrictedIps'=>    array(
                    'argv'  =>  array(),
                    'desc'  =>  _('Get PF restricted'),
                    ),
                'AddRestrictedIp'=> array(
                    'argv'  =>  array(IPADR|IPRANGE),
                    'desc'  =>  _('Set PF restricted'),
                    ),
                'DelRestrictedIp'=> array(
                    'argv'  =>  array(IPADR|IPRANGE),
                    'desc'  =>  _('Delete PF restricted'),
                    ),
                )
            );
    }
Model::GetIntIf ()
Get int_if.
Definition at line 283 of file model.php.
References GetNVP().
Referenced by System::GetConfig(), and Model().
    {
        return $this->GetNVP($this->PfRulesFile, 'int_if');
    }
Model::GetExtIf ()
Get ext_if.
Definition at line 290 of file model.php.
References GetNVP().
Referenced by System::GetConfig(), and Model().
    {
        return $this->GetNVP($this->PfRulesFile, 'ext_if');
    }
Model::Restart ()
Restart module processes.
Reimplemented in Apache, and System.
Definition at line 297 of file model.php.
Referenced by Model(), and Openvpn::Openvpn().
    {
    }
Model::GetStatsLogLines ($ logfile, $ tail = -1)
Builds generic grep command to extract log lines.
The purpose is to get the lines with dates in $re_datetime.
Parameters:
[in] $logfile string Log file pathname
[in] $tail int Tail len, new log lines to update stats with
Definition at line 308 of file model.php.
References $Modules, and RunShellCommand().
Referenced by UpdateStats().
    {
        global $Modules;
        $cmd= $Modules[$this->Name]['Stats']['Total']['Cmd'];
        if ($tail > -1) {
            $cmd.= " | /usr/bin/tail -$tail";
        }
        $cmd= preg_replace('/<LF>/', $logfile, $cmd);
        return $this->RunShellCommand($cmd);
    }
Model::SearchFile ($ file, $ re, $ set = 1, $ trimchars = '')
Searches a given file with a given regexp.
Parameters:
[in] $file string Config file
[in] $re string Regexp to search the file with, should have end markers
[in] $set int There may be multiple parentheses in $re, which one to return
[in] $trimchars If given, these chars are trimmed
Returns:
String found or FALSE if no match
Todo:
What to do multiple matching NVPs
Definition at line 331 of file model.php.
References $file, and $retval.
Referenced by GetDisabledName(), GetDisabledNVP(), Named::GetForwarders(), Dhcpd::GetIfs(), Snortips::GetIP(), GetName(), System::GetNameServer(), GetNVP(), and System::GetRootEmail().
    {
        if (preg_match($re, file_get_contents($file), $match)) {
            $retval= $match[$set];
            if ($trimchars !== '') {
                $retval= trim($retval, $trimchars);
            }
            return rtrim($retval);
        }
        return FALSE;
    }
Model::SearchFileAll ($ file, $ re, $ set = 1)
Multi-searches a given file with a given regexp.
Parameters:
[in] $file string Config file
[in] $re string Regexp to search the file with, should have end markers
[in] $set int There may be multiple parentheses in $re, which one to return
Returns:
String found or FALSE if no match
Todo:
What to do multiple matching NVPs
Definition at line 351 of file model.php.
References $file.
Referenced by Imspector::GetAcl(), Snort::GetDisabledRules(), System::GetHosts(), Squid::GetIpPort(), Dansguardian::GetIps(), Snortips::GetKeywords(), Snortips::GetListIPs(), Freshclam::GetMirrors(), and Snort::GetRules().
    {
        if (preg_match_all($re, file_get_contents($file), $match)) {
            return implode("\n", array_values($match[$set]));
        }
        return FALSE;
    }
Model::ReplaceRegexp ($ file, $ matchre, $ replacere)
Search and replace.
Parameters:
[in] $file string Config file.
[in] $matchre string Match re.
[in] $replacere string Replace re.
Definition at line 366 of file model.php.
References $file, and cwc_syslog().
Referenced by Squid::AddIpPort(), Freshclam::AddMirror(), Imspector::DelAcl(), Imspector::DelBadword(), System::DelHost(), Dansguardian::DelIp(), Squid::DelIpPort(), Snortips::DelKeyword(), Freshclam::DelMirror(), Dansguardian::DisableExt(), Imspector::MoveAclDown(), Imspector::MoveAclUp(), Snort::MoveRuleDown(), Snort::MoveRuleUp(), Symon::SetCpus(), Named::SetForwarders(), Pmacct::SetIf(), Dhcpd::SetIfs(), Dante::SetIfs(), Dante::SetIntnet(), System::SetNameServer(), Spamd::SetStartupIf(), Snort::SetStartupIfs(), and Apache::SetWebalizerHostname().
    {
        if (copy($file, $file.'.bak')) {
            $contents= preg_replace($matchre, $replacere, file_get_contents($file), 1, $count);
            if ($contents !== NULL && $count === 1) {
                file_put_contents($file, $contents);
                return TRUE;
            }
            else {
                cwc_syslog(LOG_DEBUG, __FILE__, __FUNCTION__, __LINE__, "Cannot replace in $file");
            }
        }
        else {
            cwc_syslog(LOG_ERR, __FILE__, __FUNCTION__, __LINE__, "Cannot copy file $file");
        }
        return FALSE;
    }
Model::RunShellCommand ($ cmd)
Runs given shell command and returns its output as string.
Parameters:
[in] $cmd Command line to run.
Returns:
Command result in a string.
Attention:
Do not use shell_exec() here, because it is disabled when PHP is running in safe_mode
Warning:
Not all shell commands return 0 on success, such as grep, date... Hence, do not check return value
Definition at line 389 of file model.php.
Referenced by Snortips::AddIPToList(), Pf::ApplyPfRules(), Snortips::BlockIP(), Spamassassin::ChangeLocal(), P3scan::ChangeLocal(), Pf::DisableAfterHours(), Pf::EnableAfterHours(), Openvpn::FindPid(), Pf::GetAfterHoursPfRules(), Spamassassin::GetFileLineCount(), Pf::GetFileLineCount(), Openssh::GetFileLineCount(), GetFiles(), Spamd::GetGreylist(), Pf::GetHostGraphsList(), Snortips::GetInfo(), Spamassassin::GetLiveLogs(), Pf::GetLiveLogs(), Openssh::GetLiveLogs(), Spamassassin::GetLogs(), Pf::GetLogs(), Openssh::GetLogs(), Pf::GetPfwCmdWrapperConntest(), Pf::GetPfwCmdWrapperInfo(), Pf::GetPfwCmdWrapperLog(), Pf::GetPfwCmdWrapperPfInfo(), Pf::GetPfwCmdWrapperPfMem(), Pf::GetPfwCmdWrapperPfStates(), Pf::GetPfwCmdWrapperQueues(), Pf::GetPfwPfFileName(), Pf::GetStateCount(), GetStatsFileInfo(), GetStatsLogLines(), Spamassassin::GetVersion(), Snort::GetVersion(), Smtpgated::GetVersion(), Pmacct::GetVersion(), P3scan::GetVersion(), Apache::GetVersion(), Spamd::GetWhitelist(), Snort::IsInstanceRunning(), Pf::IsRunning(), Openvpn::Restart(), Apache::Restart(), Spamd::Start(), Snort::Start(), Pf::Start(), Dhcpd::Start(), Snort::Stop(), Pf::Stop(), Apache::Stop(), Snortips::UnblockAll(), and Snortips::UnblockIPs().
    {
        exec($cmd, $output);
        if (is_array($output)) {
            return implode("\n", $output);
        }
        return '';
    }
Model::AppendToFile ($ file, $ line)
Appends a string to a file.
Parameters:
[in] $file Config file pathname
[in] $line Line to add
Definition at line 406 of file model.php.
References $file, and cwc_syslog().
Referenced by Imspector::AddAcl(), Imspector::AddBadword(), System::AddHost(), Dansguardian::AddIp(), Snortips::AddKeyword(), Dansguardian::AddSiteList(), and Dansguardian::AddUrlList().
    {
        if (copy($file, $file.'.bak')) {
            $contents= file_get_contents($file).$line."\n";
            file_put_contents($file, $contents);
            return TRUE;
        }
        else {
            cwc_syslog(LOG_ERR, __FILE__, __FUNCTION__, __LINE__, "Cannot copy file $file");
        }
        return FALSE;
    }
Model::GetFiles ($ filepath)
Returns files with the given filepath pattern.
$filepath does not have to be just directory path, and may contain wildcards.
Parameters:
[in] $filepath string Pattern
Returns:
List of file names, without path
Definition at line 426 of file model.php.
References RunShellCommand().
Referenced by Openvpn::GetConfs(), Imlogs::GetDirs(), Spamassassin::GetLocales(), P3scan::GetLocales(), and Imlogs::ImGetFiles().
    {
        return $this->RunShellCommand("ls -1 $filepath");
    }
Model::GetConfigValues ($ conf, $ group)
Returns all configuration for a given configuration type.
Parameters:
[in] $conf string Config type
[in] $group int Dansguardian group
Returns:
serialized Array of config items
Definition at line 437 of file model.php.
References Config, GetDisabledValue(), GetValue(), and SetConfig().
Referenced by Model().
    {
        $this->SetConfig($conf);
        $values= array();
        foreach ($this->Config as $name => $config) {
            if (($output= $this->GetValue($name, $conf, $group)) !== FALSE) {
                $values[$name]= array(
                    'Value' => $output,
                    'Enabled' => TRUE,
                    );
            }
            else if (($output= $this->GetDisabledValue($name, $conf, $group)) !== FALSE) {
                $values[$name]= array(
                    'Value' => $output,
                    'Enabled' => FALSE,
                    );
            }
        }
        return serialize($values);
    }
Model::GetValue ($ name, $ conf, $ group)
Returns all enabled configuration for a given configuration type.
Parameters:
[in] $name string Config name
[in] $conf string Config type
[in] $group int Dansguardian group
Returns:
serialized Array of config items
Definition at line 466 of file model.php.
References $file, Config, GetConfFile(), GetName(), and GetNVP().
Referenced by GetConfigValues().
    {
        $file= $this->GetConfFile($conf, $group);
        if ((isset($this->Config[$name]['type'])) && ($this->Config[$name]['type'] === FALSE)) {
            return $this->GetName($file, $name);
        }
        $value= $this->GetNVP($file, $name);
        return $value !== FALSE ? "$name=$value" : $value;
    }
Model::GetDisabledValue ($ name, $ conf, $ group)
Returns all disabled configuration for a given configuration type.
Definition at line 480 of file model.php.
References $file, Config, GetConfFile(), GetDisabledName(), and GetDisabledNVP().
Referenced by GetConfigValues().
    {
        $file= $this->GetConfFile($conf, $group);
        if ((isset($this->Config[$name]['type'])) && ($this->Config[$name]['type'] === FALSE)) {
            return $this->GetDisabledName($file, $name);
        }
        $value= $this->GetDisabledNVP($file, $name);
        return $value !== FALSE ? "$name=$value" : $value;
    }
Model::GetNVP ($ file, $ name, $ trimchars = '')
Reads value of NVP.
Parameters:
[in] $file string Config file
[in] $name string Name of NVP
[in] $trimchars string Chars to trim in the results
Returns:
Value of NVP or NULL on failure
Definition at line 499 of file model.php.
References $file, and SearchFile().
Referenced by GetExtIf(), GetIntIf(), GetValue(), SetNVP(), and Spamd::Start().
    {
        return $this->SearchFile($file, "/^\h*$name\b\h*$this->NVPS\h*([^$this->COMC'\"\n]*|'[^'\n]*'|\"[^\"\n]*\"|[^$this->COMC\n]*)(\h*|\h*$this->COMC.*)$/m", 1, $trimchars);
    }
Model::GetDisabledNVP ($ file, $ name)
Reads value of commented-out NVP.
Parameters:
[in] $file Config file
[in] $name Name of NVP
Returns:
Value of commented NVP or NULL on failure
Definition at line 510 of file model.php.
References $file, and SearchFile().
Referenced by GetDisabledValue(), and Spamd::Start().
    {
        return $this->SearchFile($file, "/^\h*$this->COMC\h*$name\b\h*$this->NVPS\h*([^$this->COMC'\"\n]*|'[^'\n]*'|\"[^\"\n]*\"|[^$this->COMC\n]*)(\h*|\h*$this->COMC.*)$/m");
    }
Model::GetName ($ file, $ name)
Checks if Name exists.
Parameters:
[in] $file Config file
[in] $name Name of NVP
Returns:
Name or NULL on failure
Definition at line 521 of file model.php.
References $file, and SearchFile().
Referenced by GetValue(), and Openvpn::IsClientConf().
    {
        return $this->SearchFile($file, "/^\h*($name)(\h*$this->COMC.*|\h*)$/m");
    }
Model::GetDisabledName ($ file, $ name)
Checks if commented-out Name exists.
Parameters:
[in] $file Config file
[in] $name Name of NVP
Returns:
Commented Name or NULL on failure
Definition at line 532 of file model.php.
References $file, and SearchFile().
Referenced by GetDisabledValue().
    {
        return $this->SearchFile($file, "/^\h*$this->COMC\h*($name)(\h*$this->COMC.*|\h*)$/m");
    }
Model::SetConfValue ($ name, $ newvalue, $ conf, $ group)
Sets the value of NVP configuration.
Parameters:
[in] $name string Config name
[in] $newvalue new Config value
[in] $conf string Config type
[in] $group int Dansguardian group
Definition at line 544 of file model.php.
References $file, Config, cwc_syslog(), GetConfFile(), SetConfig(), SetNVP(), and ViewError().
Referenced by Model().
    {
        $this->SetConfig($conf);
        if (isset($this->Config[$name]['type'])) {
            $re= $this->Config[$name]['type'];
        }
        else {
            $re= '.*';
        }
        if (preg_match("/^($re)$/", $newvalue)) {
            $file= $this->GetConfFile($conf, $group);
            return $this->SetNVP($file, $name, $newvalue);
        }
        ViewError(_('Invalid value').": $name: $newvalue");
        cwc_syslog(LOG_NOTICE, __FILE__, __FUNCTION__, __LINE__, "Configuration change failed, invalid value: $name: $newvalue");
        return FALSE;
    }
Model::SetNVP ($ file, $ name, $ newvalue)
Changes value of NVP.
Parameters:
[in] $file Config file
[in] $name Name of NVP
[in] $newvalue New value to set
Returns:
boolean Success or failure
Warning:
Backslash should be escaped first, or causes double escapes
Definition at line 570 of file model.php.
References $file, Escape(), and GetNVP().
Referenced by Pf::SetAfterhoursIf(), SetConfValue(), Pf::SetIfs(), and Pf::SetIntnet().
    {
        if (copy($file, $file.'.bak')) {
            if (($value= $this->GetNVP($file, $name)) !== FALSE) {
                $value= Escape($value, '\/$^*()."');
                $re= "^(\h*$name\b\h*$this->NVPS\h*)($value)(\h*$this->COMC.*|\h*)$";
                $contents= preg_replace("/$re/m", '${1}'.$newvalue.'${3}', file_get_contents($file), 1, $count);
                if ($contents !== NULL && $count == 1) {
                    file_put_contents($file, $contents);
                    return TRUE;
                }
                else {
                    cwc_syslog(LOG_ERR, __FILE__, __FUNCTION__, __LINE__, "Cannot set new value $file, $name, $newvalue");
                }
            }
            else {
                cwc_syslog(LOG_ERR, __FILE__, __FUNCTION__, __LINE__, "Cannot find NVP: $file, $name");
            }
        }
        else {
            cwc_syslog(LOG_ERR, __FILE__, __FUNCTION__, __LINE__, "Cannot copy file $file");
        }
        return FALSE;
    }
Model::EnableConf ($ name, $ conf, $ group)
Enables a configuration item in conf file.
Certain modules have multiple configuration files, hence they override this method.
Parameters:
[in] $name string Config name
[in] $conf string Config type
[in] $group int Dansguardian group
Returns:
boolean Result of action
Definition at line 607 of file model.php.
Referenced by Model().
    {
        $file= $this->GetConfFile($conf, $group);
        $this->SetConfig($conf);
        if ((isset($this->Config[$name]['type'])) && ($this->Config[$name]['type'] === FALSE)) {
            return $this->EnableName($file, $name);
        }
        return $this->EnableNVP($file, $name);
    }
Model::DisableConf ($ name, $ conf, $ group)
Disables a configuration item in conf file.
Definition at line 620 of file model.php.
Referenced by Model().
    {
        $file= $this->GetConfFile($conf, $group);
        $this->SetConfig($conf);
        if ((isset($this->Config[$name]['type'])) && ($this->Config[$name]['type'] === FALSE)) {
            return $this->DisableName($file, $name);
        }
        return $this->DisableNVP($file, $name);
    }
Model::EnableNVP ($ file, $ name)
Enables an NVP: configuration item with value.
Parameters:
[in] $file string Config file
[in] $name string Config name
Definition at line 636 of file model.php.
    {
        return $this->ReplaceRegexp($file, "/^\h*$this->COMC(\s*$name\b\s*$this->NVPS\s*.*)$/m", '${1}');
    }
Model::EnableName ($ file, $ name)
Enables a Name: configuration item without value.
Definition at line 643 of file model.php.
Referenced by Snort::EnableRule().
    {
        return $this->ReplaceRegexp($file, "/^\h*$this->COMC(\h*$name(\h*$this->COMC.*|\h*))$/m", '${1}');
    }
Model::DisableNVP ($ file, $ name)
Disables an NVP.
Definition at line 650 of file model.php.
    {
        return $this->ReplaceRegexp($file, "/^(\h*$name\b\s*$this->NVPS\s*.*)$/m", $this->COMC.'${1}');
    }
Model::DisableName ($ file, $ name)
Disables a Name.
Definition at line 657 of file model.php.
Referenced by Snort::DisableRule().
    {
        return $this->ReplaceRegexp($file, "/^(\h*$name(\h*$this->COMC.*|\h*))$/m", $this->COMC.'${1}');
    }
Model::GetConfFile ($ conf, $ group)
Returns configuration file of the module.
Certain modules have configuration divided into multiple pages/files, hence they override this method.
Parameters:
[in] $conf string Config type
[in] $group int Dansguardian group
Returns:
Config file pathname
Reimplemented in Dansguardian, and Openvpn.
Definition at line 671 of file model.php.
Referenced by GetDisabledValue(), GetValue(), and SetConfValue().
    {
        return $this->ConfFile;
    }
Model::SetConfig ($ confname)
Sets configuration file based on config type provided.
Certain modules have configuration divided into multiple pages/files, hence they override this method.
Parameters:
[in] $confname string Config type
Reimplemented in Dansguardian, Imspector, Openvpn, Snort, and Openvpn.
Definition at line 683 of file model.php.
Referenced by GetConfigValues(), and SetConfValue().
    {
    }
Model::GetIpAddr ($ if)
Extracts IP address assigned to an interface.
Parameters:
[in] $if Interface name.
Returns:
IP of the interface.
Definition at line 692 of file model.php.
Referenced by Snortips::DelIPFromList().
    {
        global $Re_Ip;
        if (file_exists($this->confDir."hostname.$if")) {
            return $this->SearchFile($this->confDir."hostname.$if", "/^\h*inet\h*($Re_Ip)\h*$Re_Ip\b.*$/m");
        }
        return FALSE;
    }
Model::CheckAuthentication ($ user, $ passwd)
Checks user's password supplied against the one in htpasswd file.
Parameters:
[in] $user User name.
[in] $passwd Password.
Returns:
TRUE if passwd matches, FALSE otherwise.
Warning:
Args should never be empty, htpasswd expects 2 args
Passwords in htpasswd file are SHA encrypted.
Warning:
Have to trim newline chars, or passwds do not match
Definition at line 708 of file model.php.
Referenced by Model().
    {
        $passwd= $passwd == '' ? "''" : $passwd;
        exec("/usr/bin/htpasswd -bn -s '' $passwd 2>&1", $output, $retval);
        if ($retval === 0) {
            $htpasswd= ltrim($output[0], ':');
            $passwdfile= file($this->passwdFile, FILE_IGNORE_NEW_LINES);
            // Do not use preg_match() here. If there is more than one line (passwd) for a user in passwdFile,
            // this array method ensures that only one password apply to each user, the last one in passwdFile.
            // This should never happen actually, but in any case.
            $passwdlist= array();
            foreach ($passwdfile as $nvp) {
                list($u, $p)= explode(':', $nvp, 2);
                $passwdlist[$u]= $p;
            }
            if ($passwdlist[$user] === $htpasswd) {
                return TRUE;
            }
        }
        ViewError(implode("\n", $output));
        return FALSE;
    }
Model::GetLogStartDate ($ file)
Extracts the datetime of the first line in the log file.
Works only on uncompressed log files.
Parameters:
[in] $file string Log file pathname
Returns:
string DateTime or warning if archive is compressed
Definition at line 745 of file model.php.
Referenced by Model().
    {
        if (preg_match('/.*\.gz$/', $file)) {
            $tmpfile= $this->GetTmpLogFileName($file);
            // Log file may have been rotated, shifting compressed archive file numbers,
            // hence modification check
            if (file_exists($tmpfile) && !$this->IsLogFileModified($tmpfile)) {
                $file= $tmpfile;
            }
        }
        if (!preg_match('/.*\.gz$/', $file)) {
            $logline= $this->GetFileFirstLine($file);
            $this->ParseLogLine($logline, $cols);
            return $cols['Date'].' '.$cols['Time'];
        }
        return _CONTROL('Compressed');
    }
Model::GetFileFirstLine ($ file)
Gets first line of file.
Used to get the start date of log files.
Parameters:
[in] $file string Log file pathname
Returns:
int First line in file
Definition at line 772 of file model.php.
    {
        $cmd= preg_replace('/<LF>/', $file, $this->CmdLogStart);
        return $this->RunShellCommand($cmd);
    }
Model::GetFileLineCount ($ file, $ re = '')
Gets line count of file.
Parameters:
[in] $file string Log file pathname
[in] $re string Regexp to get count of a restricted result set
Returns:
int Line count
Warning:
Input redirection is necessary, otherwise wc adds file name to its output too
Reimplemented in Openssh, Pf, and Spamassassin.
Definition at line 784 of file model.php.
Referenced by CountDiffLogLines(), Model(), and UpdateStats().
    {
        if ($re == '') {
            $cmd= "/usr/bin/wc -l < $file";
        }
        else {
            $re= escapeshellarg($re);
            $cmd= "/usr/bin/grep -a -E $re $file | /usr/bin/wc -l";
        }
        // OpenBSD wc returns with leading blanks
        return trim($this->RunShellCommand($cmd));
    }
Model::GetLogs ($ file, $ end, $ count, $ re = '')
Gets lines in file.
Parameters:
[in] $file string Log file pathname
[in] $end int Head option, start line
[in] $count int Tail option, page line count
[in] $re string Regexp to restrict the result set
Returns:
serialized Log lines
Reimplemented in Openssh, Pf, and Spamassassin.
Definition at line 806 of file model.php.
Referenced by Model().
    {
        // Empty $re is not an issue for grep, greps all
        $re= escapeshellarg($re);
        $cmd= "/usr/bin/grep -a -E $re $file | /usr/bin/head -$end | /usr/bin/tail -$count";
        exec($cmd, $output, $retval);
        $logs= array();
        foreach ($output as $line) {
            unset($cols);
            if ($this->ParseLogLine($line, $cols)) {
                $logs[]= $cols;
            }
        }
        return serialize($logs);
    }
Model::GetLiveLogs ($ file, $ count, $ re = '')
Gets logs for live logs pages.
Used to extract lines in last section of the log file or of the lines grep'd.
Difference from the archives method is that this one always gets the tail of the log or grepped lines.
Parameters:
[in] $file string Log file
[in] $count int Tail lenght, page line count
[in] $re string Regexp to restrict the result set
Returns:
serialized Log lines
Reimplemented in Openssh, Pf, and Spamassassin.
Definition at line 837 of file model.php.
Referenced by Model().
    {
        // Empty $re is not an issue for grep, greps all
        $re= escapeshellarg($re);
        $cmd= "/usr/bin/grep -a -E $re $file | /usr/bin/tail -$count";
        exec($cmd, $output, $retval);
        $logs= array();
        foreach ($output as $line) {
            unset($cols);
            if ($this->ParseLogLine($line, $cols)) {
                $logs[]= $cols;
            }
        }
        return serialize($logs);
    }
Model::Reload ()
Sends HUP to the module pid.
Definition at line 857 of file model.php.
Referenced by Model().
    {
        if ($this->PidFile !== '') {
            if (($pid= $this->GetFile($this->PidFile)) !== FALSE) {
                $this->RunShellCommand("/bin/kill -HUP $pid");
                return TRUE;
            }
        }
        ViewError(_('Cannot get pid'));
        return FALSE;
    }
Model::Start ()
Start module process(es).
Tries PROC_STAT_TIMEOUT times.
Returns:
boolean TRUE if the process starts
Todo:
Actually should stop retying on some error conditions?
Todo:
Check $TmpFile for error messages, if so break out instead
Reimplemented in Dhcpd, Pf, Pmacct, and Spamd.
Definition at line 877 of file model.php.
Referenced by Apache::Apache(), Model(), Openvpn::Openvpn(), and Snort::Snort().
    {
        global $TmpFile;
        $this->RunShellCommand($this->StartCmd);
        $count= 0;
        while ($count++ < self::PROC_STAT_TIMEOUT) {
            if ($this->IsRunning()) {
                return TRUE;
            }
            exec('/bin/sleep .1');
        }
        // Check one last time due to the last sleep in the loop
        if ($this->IsRunning()) {
            return TRUE;
        }
        // Start command is redirected to tmp file
        $output= file_get_contents($TmpFile);
        ViewError($output);
        cwc_syslog(LOG_ERR, __FILE__, __FUNCTION__, __LINE__, "Start failed with: $output");
        return FALSE;
    }
Model::Stop ()
Stops module process(es).
Tries PROC_STAT_TIMEOUT times.
Returns:
boolean TRUE if the process killed successfully
Todo:
Actually should stop retrying on some error conditions?
Reimplemented in Apache, Pf, Snort, Snortips, Spamassassin, and Spamd.
Definition at line 912 of file model.php.
Referenced by Model(), and Openvpn::Openvpn().
    {
        return $this->Pkill($this->Proc);
    }
Model::Pkill ($ proc)
Stops the given process.
Used to kill processes without a model definition, hence $proc param.
Parameters:
$proc string Process name
Todo:
Check $TmpFile for error messages, if so break out instead
Definition at line 923 of file model.php.
Referenced by Spamd::Stop().
    {
        global $TmpFile;
        $cmd= '/usr/bin/pkill -x '.$proc;
        $count= 0;
        while ($count++ < self::PROC_STAT_TIMEOUT) {
            if (!$this->IsRunning($proc)) {
                return TRUE;
            }
            $this->RunShellCommand("$cmd > $TmpFile 2>&1");
            exec('/bin/sleep .1');
        }
        // Check one last time due to the last sleep in the loop
        if (!$this->IsRunning($proc)) {
            return TRUE;
        }
        // Pkill command is redirected to tmp file
        $output= file_get_contents($TmpFile);
        ViewError($output);
        cwc_syslog(LOG_ERR, __FILE__, __FUNCTION__, __LINE__, "Pkill failed for $proc with: $output");
        return FALSE;
    }
Model::Kill ()
Stops module's parent process with its pid.
Todo:
Check $TmpFile for error messages, if so break out instead
Attention:
Missing pid file means success, proc is not running anyway
Definition at line 953 of file model.php.
Referenced by Spamassassin::Stop(), and Snortips::Stop().
    {
        global $TmpFile;
        if (($pid= $this->GetFile($this->PidFile)) !== FALSE) {
            $cmd= "/bin/kill $pid";
            $count= 0;
            while ($count++ < self::PROC_STAT_TIMEOUT) {
                if (!$this->IsRunning()) {
                    return TRUE;
                }
                $this->RunShellCommand("$cmd > $TmpFile 2>&1");
                exec('/bin/sleep .1');
            }
            // Check one last time due to the last sleep in the loop
            if (!$this->IsRunning()) {
                return TRUE;
            }
            // Kill command is redirected to tmp file
            $output= file_get_contents($TmpFile);
            ViewError($output);
            cwc_syslog(LOG_ERR, __FILE__, __FUNCTION__, __LINE__, "Kill failed with: $output");
            return FALSE;
        }
        return TRUE;
    }
Model::KillPid ($ pid)
Kills process with the given pid.
Tries PROC_STAT_TIMEOUT times.
Parameters:
[in] $pid int Pid
Returns:
boolean TRUE if the process killed successfully
Todo:
Actually should stop retrying on some error conditions?
Todo:
Check $TmpFile for error messages, if so break out instead
Kill command is redirected to tmp file
Definition at line 994 of file model.php.
Referenced by Snort::StopProcess(), and Openvpn::StopProcess().
    {
        global $TmpFile;
        $cmd= '/bin/kill '.$pid;
        $count= 0;
        while ($count++ < self::PROC_STAT_TIMEOUT) {
            if (!$this->IsModulePidRunning($pid)) {
                return TRUE;
            }
            $this->RunShellCommand("$cmd > $TmpFile 2>&1");
            exec('/bin/sleep .1');
        }
        $output= file_get_contents($TmpFile);
        ViewError($output);
        cwc_syslog(LOG_ERR, __FILE__, __FUNCTION__, __LINE__, "Kill failed with: $output");
        // Check one last time due to the last sleep in the loop
        return !$this->IsModulePidRunning($pid);
    }
Model::IsModulePidRunning ($ pid)
Checks if the pid is running.
Parameters:
[in] $pid int Pid
Returns:
boolean TRUE if process is running
Definition at line 1024 of file model.php.
    {
        $pidcmd= "/bin/ps -o pid -p $pid | /usr/bin/grep '$pid'";
        $output= $this->RunShellCommand($pidcmd);
        return ($output !== '');
    }
Model::IsRunning ($ proc = '')
Checks if the process(es) is running.
Uses ps with grep.
Parameters:
[in] $proc string Module process name
Returns:
boolean TRUE if there is any process running
Todo:
Should use pid files instead of ps, if possible at all
Reimplemented in Clamav, Monitoring, and Pf.
Definition at line 1040 of file model.php.
Referenced by Snortips::GetInfo(), and Model().
    {
        if ($proc == '') {
            $proc= $this->Proc;
        }
        $cmd= preg_replace('/<PROC>/', escapeshellarg($proc), $this->psCmd);
        exec($cmd, $output, $retval);
        if ($retval === 0) {
            return count($this->SelectProcesses($output)) > 0;
        }
        ViewError(implode("\n", $output));
        cwc_syslog(LOG_DEBUG, __FILE__, __FUNCTION__, __LINE__, "No such process: $proc");
        return FALSE;
    }
Model::GetProcList ()
Gets the list of processes running.
Definition at line 1059 of file model.php.
Referenced by Model().
    {
        $cmd= preg_replace('/<PROC>/', escapeshellarg($this->Proc), $this->psCmd);
        exec($cmd, $output, $retval);
        if ($retval === 0) {
            return serialize($this->SelectProcesses($output));
        }
        ViewError(implode("\n", $output));
        cwc_syslog(LOG_DEBUG, __FILE__, __FUNCTION__, __LINE__, "Process list failed for $this->Proc");
        return FALSE;
    }
Model::SelectProcesses ($ psout)
Selects user processes from ps output.
Parameters:
[in] $psout arrary ps output
Returns:
array Parsed ps output of user processes
Reimplemented in System.
Definition at line 1076 of file model.php.
    {
        //   PID STARTED  %CPU      TIME %MEM   RSS   VSZ STAT  PRI  NI TTY      USER     GROUP    COMMAND
        //     1  5:10PM   0.0   0:00.03  0.0   388   412 Is     10   0 ??       root     wheel    /sbin/init
        // Skip processes running on terminals, e.g. vi, tail, man
        // Select based on daemon user
        $re= "/^\s*(\d+)\s+(\S+)\s+(\S+)\s+(\S+)\s+(\S+)\s+(\d+)\s+(\d+)\s+(\S+)\s+(\d+)\s+(\d+)\s+\?\?\s+($this->User)\s+(\S+)\s+(.+)$/";
        $processes= array();
        foreach ($psout as $line) {
            if (preg_match($re, $line, $match)) {
                // Skip processes initiated by this WUI
                if (!preg_match('/\b(cwc\.php|grep|kill|pkill)\b/', $match[13])) {
                    $processes[]= array(
                        $match[1],
                        $match[2],
                        $match[3],
                        $match[4],
                        $match[5],
                        $match[6],
                        $match[7],
                        $match[8],
                        $match[9],
                        $match[10],
                        $match[11],
                        $match[12],
                        $match[13],
                        );
                }
            }
        }
        return $processes;
    }
Model::GetVersion ()
Gets software version string.
Reimplemented in Apache, Imspector, P3scan, Pmacct, Smtpgated, Snort, and Spamassassin.
Definition at line 1112 of file model.php.
Referenced by Model().
    {
        if ($this->VersionCmd !== '') {
            return  $this->RunShellCommand($this->VersionCmd.' | /usr/bin/head -1');
        }
        return FALSE;
    }
Model::GetServiceStatus ()
Gets service statuses.
Definition at line 1122 of file model.php.
Referenced by Model().
    {
        global $MODEL_PATH, $ModelFiles, $Models, $ModelsToStat;
        $output= FALSE;
        foreach ($ModelsToStat as $m) {
            if (array_key_exists($m, $ModelFiles)) {
                require_once($MODEL_PATH.$ModelFiles[$m]);
                if (class_exists($Models[$m])) {
                    $model= new $Models[$m]();
                    if ($model->IsRunning()) {
                        $output.= "$m=R\n";
                    }
                    else {
                        $output.= "$m=S\n";
                    }
                }
                else {
                    cwc_syslog(LOG_NOTICE, __FILE__, __FUNCTION__, __LINE__, "Not in Models: $m");
                }
            }
            else {
                cwc_syslog(LOG_NOTICE, __FILE__, __FUNCTION__, __LINE__, "Not in ModelFiles: $m");
            }
        }
        return $output;
    }
Model::GetProcStatLines ($ logfile)
Collects text statistics for the proc stats general page.
Builds the shell command to count with grep first. Just counts the number of lines in the grep output.
Definition at line 1157 of file model.php.
Referenced by Model().
    {
        global $Modules;
        $stats= array();
        foreach ($Modules[$this->Name]['Stats'] as $stat => $conf) {
            if (isset($conf['Cmd'])) {
                $cmd= $conf['Cmd'];
                if (isset($conf['Needle'])) {
                    $cmd.= ' | /usr/bin/grep -a -E <NDL>';
                    $cmd= preg_replace('/<NDL>/', escapeshellarg($conf['Needle']), $cmd);
                }
                $cmd.= ' | /usr/bin/wc -l';
            }
            else if (isset($conf['Needle'])) {
                $cmd= '/usr/bin/grep -a -E <NDL> <LF> | /usr/bin/wc -l';
                $cmd= preg_replace('/<NDL>/', escapeshellarg($conf['Needle']), $cmd);
            }
            if ($logfile == '') {
                $logfile= $this->LogFile;
            }
            $cmd= preg_replace('/<LF>/', $logfile, $cmd);
            $stats[$conf['Title']]= trim($this->RunShellCommand($cmd));
        }
        return serialize($stats);
    }
Model::CopyLogFileToTmp ($ file, $ tmpdir)
Uncompresses gzipped log file to tmp dir.
Definition at line 1187 of file model.php.
    {
        exec("/bin/mkdir -p $tmpdir 2>&1", $output, $retval);
        if ($retval === 0) {
            exec("/bin/cp $file $tmpdir 2>&1", $output, $retval);
            if ($retval === 0) {
                $tmpfile= $tmpdir.basename($file);
                if (preg_match('/(.*)\.gz$/', $tmpfile, $match)) {
                    // Delete the old uncompressed file, otherwise gunzip fails
                    $this->DeleteFile($match[1]);
                    exec("/usr/bin/gunzip $tmpfile 2>&1", $output, $retval);
                    if ($retval === 0) {
                        return TRUE;
                    }
                    else {
                        cwc_syslog(LOG_ERR, __FILE__, __FUNCTION__, __LINE__, 'gunzip failed: '.$tmpdir.basename($file));
                    }
                }
                else {
                    return TRUE;
                }
            }
            else {
                cwc_syslog(LOG_ERR, __FILE__, __FUNCTION__, __LINE__, 'cp failed: '.$file);
            }
        }
        else {
            cwc_syslog(LOG_ERR, __FILE__, __FUNCTION__, __LINE__, 'mkdir failed: '.$tmpdir);
        }
        ViewError(implode("\n", $output));
        return FALSE;
    }
Model::GetFileCvsTag ($ file)
Returns ComixWall cvs tag in the given file, if any.
Parameters:
[in] $file string File pathname.
Warning:
Don't add $ to ComixWall tag, otherwise CVS changes $re during commit
Definition at line 1225 of file model.php.
Referenced by Model().
    {
        if (($contents= $this->GetFile($file)) !== FALSE) {
            $re= '/ComixWall:\s+(.*\.php,v\s+\d+\.\d+\s+\d+\/\d+\/\d+\s+\d+:\d+:\d+)\s+\S+\s+Exp\s+\$/';
            if (preg_match($re, $contents, $match)) {
                return $match[1];
            }
        }
        return FALSE;
    }
Model::GetSysCtl ($ option)
Gets sysctl output for the given arg.
Parameters:
[in] $option sysctl arg, such as hw.sensors.
Returns:
sysctl output lines.
Definition at line 1242 of file model.php.
Referenced by Model(), and Symon::SetCpus().
    {
        return $this->RunShellCommand("/sbin/sysctl $option");
    }
Model::GetFile ($ file)
Reads file contents.
Parameters:
[in] $file Config file
Returns:
File contents
Definition at line 1252 of file model.php.
Referenced by Imspector::GetBadwords(), System::GetIfConfig(), Snortips::GetInfo(), System::GetMyName(), GetSavedStats(), System::GetStaticGateway(), and Pmacct::Start().
    {
        if (file_exists($file)) {
            return file_get_contents($file);
        }
        return FALSE;
    }
Model::GetDefaultLogFile ()
Definition at line 1260 of file model.php.
Referenced by Model().
    {
        return $this->LogFile;
    }
Model::SelectLogFile ($ file)
Returns log file under tmp location.
Updates the tmp file if original file is modified. Updates the stat info of the file in the tmp statistics file, used to check file modificaton.
Parameters:
[in] $file Original file name
Returns:
File pathname
Definition at line 1274 of file model.php.
Referenced by Model().
    {
        if ($file === '') {
            $file= $this->LogFile;
        }
        $file= $this->GetTmpLogFileName($file);
        if (!file_exists($file) || $this->IsLogFileModified($file)) {
            if ($this->UpdateTmpLogFile($file)) {
                // Update stats to update file stat info only
                $this->UpdateStats($file, $stats, $briefstats);
            }
            else {
                $file= $this->LogFile;
                cwc_syslog(LOG_DEBUG, __FILE__, __FUNCTION__, __LINE__, "Logfile tmp copy update failed, defaulting to: $file");
            }
        }
        return $file;
    }
Model::UpdateTmpLogFile ($ file)
Copies original log file to tmp location.
Parameters:
[in] $file File pathname
Definition at line 1300 of file model.php.
Referenced by GetStats().
    {
        $origfile= $this->GetOrigFileName($file);
        if ($this->CopyLogFileToTmp($origfile, $this->TmpLogsDir)) {
            return TRUE;
        }
        cwc_syslog(LOG_DEBUG, __FILE__, __FUNCTION__, __LINE__, "Copy failed: $file");
        return FALSE;
    }
Model::GetTmpLogFileName ($ file)
Returns the log file name in the tmp location.
Parameters:
[in] $file File pathname
Definition at line 1315 of file model.php.
    {
        if (preg_match('/(.*)\.gz$/', $file, $match)) {
            $file= $this->TmpLogsDir.basename($match[1]);
        }
        else {
            $file= $this->TmpLogsDir.basename($file);
        }
        return $file;
    }
Model::GetLogFilesList ()
Gets log files list with start dates.
Searches the logs directory for all possible archives according to the default file name.
Definition at line 1331 of file model.php.
Referenced by Model().
    {
        $file= $this->LogFile;
        $filelist= explode("\n", $this->GetFiles("$file*"));
        asort($filelist);
        $result= array();
        foreach ($filelist as $filepath) {
            $result[$filepath]= $this->GetLogStartDate($filepath);
        }
        return serialize($result);
    }
Model::DeleteFile ($ path)
Deletes file or dir.
Parameters:
[in] $path string File or dir.
Definition at line 1348 of file model.php.
Referenced by Openvpn::DeleteConf(), System::DeleteIf(), and System::SystemMakeDynamicGateway().
    {
        if (file_exists($path)) {
            exec("/bin/rm -rf $path 2>&1", $output, $retval);
            if ($retval === 0) {
                return TRUE;
            }
            else {
                $errout= implode("\n", $output);
                ViewError($errout);
                cwc_syslog(LOG_DEBUG, __FILE__, __FUNCTION__, __LINE__, "Failed deleting: $path, $errout");
            }
        }
        else {
            cwc_syslog(LOG_DEBUG, __FILE__, __FUNCTION__, __LINE__, "File path does not exist: $path");
        }
        return FALSE;
    }
Model::PutFile ($ file, $ contents)
Writes contents to file.
Parameters:
[in] $file Config file.
[in] $contents Contents to write.
Definition at line 1372 of file model.php.
Referenced by Snortips::GetInfo(), Pf::InstallNewCrontab(), and SaveStats().
    {
        if (file_exists($file)) {
            return file_put_contents($file, $contents, LOCK_EX);
        }
        return FALSE;
    }
Model::GetPhyIfs ()
Extract physical interface names from ifconfig output.
Removes non-physical interfaces from the output
Returns:
Names of physical interfaces.
Definition at line 1385 of file model.php.
Referenced by Snortips::DelIPFromList(), System::GetConfig(), and Model().
    {
        return $this->RunShellCommand("/sbin/ifconfig -a | /usr/bin/grep ': flags=' | /usr/bin/sed 's/: flags=.*//g' | /usr/bin/grep -v -e lo -e pflog -e pfsync -e enc -e tun");
    }
Model::GetAllStats ($ logfile, $ collecthours = '')
Returns both brief and full statistics.
Parameters:
[in] $logfile string Log file pathname
[in] $collecthours boolean Flag to get hour statistics also
Returns:
serialized Statistics in serialized arrays
Attention:
We need $stats return value of GetStats() because of $collecthours constraint
Definition at line 1396 of file model.php.
References $stats, GetSavedStats(), and GetStats().
Referenced by Model().
    {
        $date= serialize(array('Month' => '', 'Day' => ''));
        $stats= $this->GetStats($logfile, $date, $collecthours);
        // Do not get $stats here, just $briefstats
        $this->GetSavedStats($logfile, $dummy, $briefstats);
        $briefstats= serialize($briefstats);
        // Use serialized stats as array elements to prevent otherwise extra unserialize() for $stats,
        // which is already serialized by GetStat() above.
        // They are ordinary strings now, this serialize() should be quite fast
        return serialize(
                array(
                    'stats'     => $stats,
                    'briefstats'=> $briefstats,
                    )
            );
    }
Model::GetStats ($ logfile, $ date, $ collecthours = '')
Main statistics collector, as module data set.
Parameters:
[in] $logfile string Log file pathname
[in] $date array Datetime struct
[in] $collecthours boolean Flag to collect hour statistics also
Returns:
array Statistics data set collected, serialized
Definition at line 1424 of file model.php.
References $Modules, $stats, GetDateRegexp(), GetHourRegexp(), GetSavedStats(), IsLogFileModified(), UpdateStats(), and UpdateTmpLogFile().
Referenced by GetAllStats(), and Model().
    {
        global $Modules;
        $date= unserialize($date);
        $stats= array();
        $briefstats= array();
        $uptodate= FALSE;
        if ($this->IsLogFileModified($logfile)) {
            $this->UpdateTmpLogFile($logfile);
        }
        else {
            $uptodate= $this->GetSavedStats($logfile, $stats, $briefstats);
        }
        if (!$uptodate) {
            $this->UpdateStats($logfile, $stats, $briefstats);
        }
        if (isset($stats['Date'])) {
            if ($collecthours === '') {
                foreach ($stats['Date'] as $day => $daystats) {
                    unset($stats['Date'][$day]['Hours']);
                }
            }
            $re= $this->GetDateRegexp($date);
            foreach ($stats['Date'] as $day => $daystats) {
                if (!preg_match("/$re/", $day)) {
                    unset($stats['Date'][$day]);
                }
            }
            $re= $this->GetHourRegexp($date);
            foreach ($stats['Date'] as $day => $daystats) {
                if (isset($daystats['Hours'])) {
                    foreach ($daystats['Hours'] as $hour => $hourstats) {
                        if (!preg_match("/$re/", $hour)) {
                            unset($stats['Date'][$day]['Hours'][$hour]);
                        }
                    }
                }
            }
        }
        return serialize($stats);
    }
Model::CountDiffLogLines ($ logfile, &$ count)
Gets the number of lines added to log files since last tmp update.
Parameters:
[in] $logfile string Log file pathname
[out] $count int Number of new log lines
Definition at line 1478 of file model.php.
References cwc_syslog(), GetFileLineCount(), GetOrigFileName(), and GetStatsFileInfo().
Referenced by UpdateStats().
    {
        $count= -1;
        if ($this->GetStatsFileInfo($logfile, $oldlinecount, $oldfilestat)) {
            $newlinecount= $this->GetFileLineCount($logfile);
            $origfile= $this->GetOrigFileName($logfile);
            if (($newlinecount >= $oldlinecount) && !preg_match('/\.gz$/', $origfile)) {
                cwc_syslog(LOG_DEBUG, __FILE__, __FUNCTION__, __LINE__, "Logfile modified: $logfile, linecount $oldlinecount->$newlinecount");
                $count= $newlinecount - $oldlinecount;
                cwc_syslog(LOG_DEBUG, __FILE__, __FUNCTION__, __LINE__, "Logfile has grown by $count lines: $logfile");
                return TRUE;
            }
            else {
                // Logs probably rotated, recollect the stats
                // Also stats for compressed files are always recollected on rotation, otherwise stats would be merged with the old stats
                cwc_syslog(LOG_DEBUG, __FILE__, __FUNCTION__, __LINE__, "Assuming log file rotation: $logfile");
            }
        }
        else {
            cwc_syslog(LOG_DEBUG, __FILE__, __FUNCTION__, __LINE__, "Cannot get file info: $logfile");
        }
        return FALSE;
    }
Model::UpdateStats ($ logfile, &$ stats, &$ briefstats)
Updates statistics incrementally, both brief and full.
Parameters:
[in] $logfile string Log file pathname
[out] $stats array Full stats
[out] $briefstats array Brief stats
Definition at line 1513 of file model.php.
References $Modules, $stats, CollectDayStats(), CountDiffLogLines(), GetFileLineCount(), GetSavedStats(), GetStatsLogLines(), ParseLogLine(), and SaveStats().
Referenced by GetStats().
    {
        global $Modules;
        $stats= array();
        $briefstats= array();
        // Line count should be obtained here, see SaveStats() for explanation
        $linecount= $this->GetFileLineCount($logfile);
        if ($this->CountDiffLogLines($logfile, $tail)) {
            $this->GetSavedStats($logfile, $stats, $briefstats);
        }
        $statsdefs= $Modules[$this->Name]['Stats'];
        if (isset($statsdefs)) {
            $lines= $this->GetStatsLogLines($logfile, $tail);
            if ($lines !== '') {
                $lines= explode("\n", $lines);
                foreach ($lines as $line) {
                    unset($values);
                    $this->ParseLogLine($line, $values);
                    // Post-processing modifies link and/or datetime values.
                    $this->PostProcessCols($values);
                    $this->CollectDayStats($statsdefs, $values, $line, $stats);
                    $briefstatsdefs= $statsdefs['Total']['BriefStats'];
                    if (isset($briefstatsdefs)) {
                        if (!isset($briefstatsdefs['Date'])) {
                            // Always collect Date field
                            $briefstatsdefs['Date'] = _('Requests by date');
                        }
                        // Collect the fields listed under BriefStats
                        foreach ($briefstatsdefs as $name => $title) {
                            $value= $values[$name];
                            if (isset($value)) {
                                $briefstats[$name][$value]+= 1;
                            }
                        }
                    }
                }
            }
        }
        $this->SaveStats($logfile, $stats, $briefstats, $linecount);
    }
Model::GetDateRegexp ($ date)
Generates date regexp to be used by statistics functions.
Used to match date indeces of stats array to get stats for date ranges.
Parameters:
[in] $date array Date struct
Returns:
Regexp
Reimplemented in Pf.
Definition at line 1573 of file model.php.
References $MonthNames.
Referenced by GetStats().
    {
        global $MonthNames;
        if ($date['Month'] == '') {
            $re= '.*';
        }
        else {
            $re= $MonthNames[$date['Month']].'\s+';
            if ($date['Day'] == '') {
                $re.= '.*';
            }
            else {
                $re.= sprintf('% 2d', $date['Day']);
            }
        }
        return $re;
    }
Model::GetHourRegexp ($ date)
Generates hour regexp to be used by statistics functions.
Parameters:
[in] $date array Date struct
Returns:
Regexp
Definition at line 1597 of file model.php.
Referenced by GetStats().
    {
        if ($date['Hour'] == '') {
            $re= '.*';
        }
        else {
            $re= $date['Hour'];
        }
        return $re;
    }
Model::GetSavedStats ($ logfile, &$ stats, &$ briefstats)
Gets saved statistics for the given log file.
Parameters:
[in] $logfile string Log file
[out] $stats array Statistics
[out] $briefstats array Brief statistics
Definition at line 1614 of file model.php.
References $stats, cwc_syslog(), GetFile(), and GetStatsFileName().
Referenced by GetAllStats(), GetStats(), and UpdateStats().
    {
        $statsfile= $this->GetStatsFileName($logfile);
        if (($filecontents= $this->GetFile($statsfile)) !== FALSE) {
            if ($serialized_stats= preg_replace("|^(<filestat>.*</filestat>\s)|m", '', $filecontents)) {
                $allstats= unserialize($serialized_stats);
                if (isset($allstats['stats']) && isset($allstats['briefstats'])) {
                    $stats= $allstats['stats'];
                    $briefstats= $allstats['briefstats'];
                    return TRUE;
                }
                else {
                    cwc_syslog(LOG_DEBUG, __FILE__, __FUNCTION__, __LINE__, "Missing stats in file: $statsfile");
                }
            }
            else {
                cwc_syslog(LOG_DEBUG, __FILE__, __FUNCTION__, __LINE__, "filestat removal failed in file: $statsfile");
            }
        }
        return FALSE;
    }
Model::IsLogFileModified ($ logfile)
Checks if the given log file has been updated.
Compares the full stat info, except for last access time, which is updated by the stat() call too.
Parameters:
[in] $logfile string Log file
Definition at line 1643 of file model.php.
References cwc_syslog(), GetOrigFileName(), and GetStatsFileInfo().
Referenced by GetStats().
    {
        $origfile= $this->GetOrigFileName($logfile);
        if ($this->GetStatsFileInfo($logfile, $linecount, $filestat)) {
            if (file_exists($origfile)) {
                $newfilestat= stat($origfile);
                $diff= array_diff($newfilestat, $filestat);
                unset($diff['8']);
                unset($diff['atime']);
                if (count($diff) === 0) {
                    cwc_syslog(LOG_DEBUG, __FILE__, __FUNCTION__, __LINE__, "Logfile not modified: $logfile, linecount $linecount");
                    return FALSE;
                }
            }
        }
        return TRUE;
    }
Model::GetStatsFileInfo ($ logfile, &$ linecount, &$ filestat)
Gets previous line count and stat() from statistics file.
Parameters:
[in] $logfile string Log file
[out] $linecount int Previous line count
[out] $filestat array Previous stat() output
Todo:
Should check file format too, and delete the stats file if corrupted
Definition at line 1669 of file model.php.
References cwc_syslog(), GetStatsFileName(), and RunShellCommand().
Referenced by CountDiffLogLines(), and IsLogFileModified().
    {
        $linecount= 0;
        $filestat= array();
        $statsfile= $this->GetStatsFileName($logfile);
        if (file_exists($statsfile)) {
            $filestatline= $this->RunShellCommand("/usr/bin/head -1 $statsfile");
            if (preg_match('|^<filestat>(.*)</filestat>$|', $filestatline, $match)) {
                $fileinfo= unserialize($match[1]);
                $linecount= $fileinfo['linecount'];
                $filestat= $fileinfo['stat'];
                return TRUE;
            }
            else {
                cwc_syslog(LOG_DEBUG, __FILE__, __FUNCTION__, __LINE__, "filestat missing in: $statsfile");
            }
        }
        else {
            cwc_syslog(LOG_DEBUG, __FILE__, __FUNCTION__, __LINE__, "No such file: $statsfile");
        }
        return FALSE;
    }
Model::GetStatsFileName ($ logfile)
Gets name of the tmp statistics file for the given log file.
Parameters:
[in] $logfile string Log file
Definition at line 1700 of file model.php.
References GetOrigFileName().
Referenced by GetSavedStats(), GetStatsFileInfo(), and SaveStats().
    {
        $origfilename= basename($this->GetOrigFileName($logfile));
        $statsdir= '/var/tmp/comixwall/stats/'.get_class($this);
        $statsfile= "$statsdir/$origfilename";
        return $statsfile;
    }
Model::GetOrigFileName ($ logfile)
Returns the original file name for the given log file.
Parameters:
[in] $logfile string Log file
Definition at line 1714 of file model.php.
Referenced by CountDiffLogLines(), GetStatsFileName(), IsLogFileModified(), and SaveStats().
    {
        $origfilename= basename($logfile);
        if (basename($this->LogFile) !== $origfilename) {
            $origfilename.= '.gz';
        }
        $origfile= dirname($this->LogFile).'/'.$origfilename;
        return $origfile;
    }
Model::SaveStats ($ logfile, $ stats, $ briefstats, $ linecount)
Saves collected statistics with current line count and stat() output.
Warning:
Line count should be get before statistics collection, otherwise new lines appended during stats processing may be skipped, hence the $linecount param.
Parameters:
[in] $logfile string Log file
[in] $stats array Statistics
[in] $briefstats array Brief statistics
[in] $linecount int Line count
Definition at line 1736 of file model.php.
References $stats, cwc_syslog(), GetOrigFileName(), GetStatsFileName(), and PutFile().
Referenced by UpdateStats().
    {
        $origfile= $this->GetOrigFileName($logfile);
        $statsfile= $this->GetStatsFileName($logfile);
        $savestats=
            '<filestat>'.
            serialize(
                array(
                    'linecount' => $linecount,
                    'stat'      => stat($origfile),
                    )
            ).
            '</filestat>'."\n".
            serialize(
                array(
                    'stats'     => $stats,
                    'briefstats'=> $briefstats,
                    )
            );
        $statsdir= dirname($statsfile);
        if (!file_exists($statsdir)) {
            exec('/bin/mkdir -p '.$statsdir);
        }
        exec('/usr/bin/touch '.$statsfile);
        $this->PutFile($statsfile, $savestats);
        cwc_syslog(LOG_DEBUG, __FILE__, __FUNCTION__, __LINE__, "Saved stats to: $statsfile");
    }
Model::CollectDayStats ($ statsdefs, $ values, $ line, &$ stats)
Day statistics collector.
$statsdefs has all the information to collect what data.
If parsed log time does not have an appropriate hour/min, then 12:00 is assumed.
Parameters:
[in] $statsdefs array Module stats section of $Modules
[in] $values array Log fields parsed by caller function
[in] $line string Current log line needed to search for keywords
[out] $stats array Statistics data set collected
Todo:
How is it possible that Time does not have hour/min? Should have a module Time field processor as well?
Definition at line 1781 of file model.php.
References $stats, CollectHourStats(), cwc_syslog(), and IncStats().
Referenced by UpdateStats().
    {
        $re= '/^(\d+):(\d+):(\d+)$/';
        if (preg_match($re, $values['Time'], $match)) {
            $hour= $match[1];
            $min= $match[2];
        }
        else {
            // Should be unreachable
            $hour= '12';
            $min= '00';
            cwc_syslog(LOG_DEBUG, __FILE__, __FUNCTION__, __LINE__, 'There was no Time in log values, defaulting to 12:00');
        }
        $daystats= &$stats['Date'][$values['Date']];
        $this->IncStats($line, $values, $statsdefs, $daystats);
        $this->CollectHourStats($statsdefs, $hour, $min, $values, $line, $daystats);
    }
Model::CollectHourStats ($ statsdefs, $ hour, $ min, $ values, $ line, &$ daystats)
Hour statistics collector.
$statsdefs has all the information to collect what data.
$daystats is the subsection of the main $stats array for the current date.
Parameters:
[in] $statsdefs array Module stats section of $Modules
[in] $hour string Hour to collect stats for
[in] $min string Min to collect stats for, passed to CollectMinuteStats()
[in] $values array Log fields parsed by caller function
[in] $line string Current log line needed to search for keywords
[out] $daystats array Statistics data set collected
Definition at line 1814 of file model.php.
References CollectMinuteStats(), and IncStats().
Referenced by CollectDayStats().
    {
        $hourstats= &$daystats['Hours'][$hour];
        $this->IncStats($line, $values, $statsdefs, $hourstats);
        $this->CollectMinuteStats($statsdefs, $min, $values, $line, $hourstats);
    }
Model::IncStats ($ line, $ values, $ statsdefs, &$ stats)
Increments stats for the given values.
Definition at line 1824 of file model.php.
References $stats.
Referenced by CollectDayStats(), and CollectHourStats().
    {
        $stats['Sum']+= 1;
        if (isset($statsdefs['Total']['Counters'])) {
            foreach ($statsdefs['Total']['Counters'] as $counter => $conf) {
                $value= $values[$conf['Field']];
                if (isset($value)) {
                    $stats[$counter]['Sum']+= $value;
                    foreach ($conf['NVPs'] as $name => $title) {
                        if (isset($values[$name])) {
                            $stats[$counter][$name][$values[$name]]+= $value;
                        }
                    }
                }
            }
        }
        foreach ($statsdefs as $stat => $conf) {
            if (isset($conf['Needle'])) {
                if (preg_match('/'.$conf['Needle'].'/', $line)) {
                    $stats[$stat]['Sum']+= 1;
                    foreach ($conf['NVPs'] as $name => $title) {
                        if (isset($values[$name])) {
                            $stats[$stat][$name][$values[$name]]+= 1;
                        }
                    }
                }
            }
        }
    }
Model::CollectMinuteStats ($ statsdefs, $ min, $ values, $ line, &$ hourstats)
Minute statistics collector.
$statsdefs has all the information to collect what data.
$hourstats is the subsection of the $stats array for the current hour.
Parameters:
[in] $statsdefs array Module stats section of $Modules
[in] $min string Min to collect stats for, passed to CollectMinuteStats()
[in] $values array Log fields parsed by caller function
[in] $line string Current log line needed to search for keywords
[out] $hourstats array Statistics data set collected
Definition at line 1870 of file model.php.
Referenced by CollectHourStats().
    {
        $minstats= &$hourstats['Mins'][$min];
        $minstats['Sum']+= 1;
        if (isset($statsdefs['Total']['Counters'])) {
            foreach ($statsdefs['Total']['Counters'] as $counter => $conf) {
                if (isset($values[$conf['Field']])) {
                    $minstats[$counter]+= $values[$conf['Field']];
                }
            }
        }
        foreach ($statsdefs as $stat => $conf) {
            if (isset($conf['Needle'])) {
                if (preg_match('/'.$conf['Needle'].'/', $line)) {
                    $minstats[$stat]+= 1;
                }
            }
        }
    }
Model::ParseLogLine ($ logline, &$ cols)
Log parser.
Parameters:
[in] $logline string Log line
[out] $cols array Parsed fields
Returns:
TRUE if log line is parsed
Reimplemented in Apache, Apachelogs, Blacklists, Clamd, Cwlogs, Dansguardianlogs, Freshclam, Ftpproxy, Imlogs, Named, Openssh, P3scan, Pf, Smtpgated, Snortalerts, Snortips, Spamassassin, Spamd, and Squid.
Definition at line 1898 of file model.php.
References ParseSyslogLine().
Referenced by UpdateStats().
    {
        return $this->ParseSyslogLine($logline, $cols);
    }
Model::ParseSyslogLine ($ logline, &$ cols)
Parses standard syslog line.
Parameters:
[in] $logline string Log line
[out] $cols array Parsed fields
Returns:
TRUE if log line is a syslog line, thus parsed
Definition at line 1910 of file model.php.
Referenced by Squid::ParseLogLine(), Spamd::ParseLogLine(), Spamassassin::ParseLogLine(), Snortips::ParseLogLine(), Snortalerts::ParseLogLine(), Smtpgated::ParseLogLine(), P3scan::ParseLogLine(), Openssh::ParseLogLine(), Named::ParseLogLine(), ParseLogLine(), Ftpproxy::ParseLogLine(), Freshclam::ParseLogLine(), Dansguardianlogs::ParseLogLine(), Cwlogs::ParseLogLine(), Clamd::ParseLogLine(), Apachelogs::ParseLogLine(), and Apache::ParseLogLine().
    {
        $re_datetime= '(\w+\s+\d+)\s+(\d+:\d+:\d+)';
        $re_proc= '((\S+(\[\d+\]|)):|)';
        $re= "/^$re_datetime\s+(\S+|)\s+$re_proc\s*(.*|)$/";
        if (preg_match($re, $logline, $match)) {
            $cols['Date']= $match[1];
            $cols['Time']= $match[2];
            $cols['Process']= $match[5];
            $cols['Log']= $match[7];
            return TRUE;
        }
        return FALSE;
    }
Member Data Documentation
Model::$Name = ''
Reimplemented in Apache, Apachelogs, Blacklists, Clamd, Dansguardian, Dansguardianlogs, Dante, Dhcpd, Freshclam, Ftpproxy, Imspector, Named, Openssh, Openvpn, P3scan, Pf, Pmacct, Smtpgated, Snort, Snortalerts, Snortips, Spamassassin, Spamd, Squid, Symon, Symux, and System.
Definition at line 42 of file model.php.
Model::$User = ''
Reimplemented in Apache, Clamd, Dansguardian, Dante, Dhcpd, Freshclam, Ftpproxy, Imspector, Named, Openssh, Openvpn, P3scan, Pmacct, Smtpgated, Snort, Snortips, Spamassassin, Spamd, Squid, Symon, Symux, and System.
Definition at line 43 of file model.php.
Model::$Proc = ''
Attention:
Should be updated in constructors of children
Definition at line 46 of file model.php.
Model::$NVPS = '='
Reimplemented in Apache, Clamd, Dansguardian, Freshclam, Openssh, Openvpn, P3scan, Pf, Smtpgated, Snort, Snortips, Spamassassin, and Squid.
Definition at line 48 of file model.php.
Model::$COMC = '#'
Definition at line 49 of file model.php.
Model::$ConfFile = ''
Reimplemented in Apache, Clamd, Dansguardian, Dante, Dhcpd, Freshclam, Imspector, Named, Openssh, P3scan, Pf, Smtpgated, Snort, Snortips, Spamassassin, and Squid.
Definition at line 50 of file model.php.
Model::$Config = ''
Definition at line 51 of file model.php.
Model::$LogFile = ''
Reimplemented in Apache, Apachelogs, Blacklists, Clamd, Cwc, Cwwui, Dansguardian, Dansguardianlogs, Dante, Dhcpd, Docs, Freshclam, Ftpproxy, Imspector, Monitoring, Named, Openssh, Openvpn, P3scan, Pf, Smtpgated, Snort, Snortalerts, Snortips, Spamassassin, Spamd, Squid, and System.
Definition at line 53 of file model.php.
Model::$psCmd = '/bin/ps arwwx -o pid,start,%cpu,time,%mem,rss,vsz,stat,pri,nice,tty,user,group,command | /usr/bin/grep -E <PROC>' [protected]
Definition at line 55 of file model.php.
const Model::PROC_STAT_TIMEOUT = 100
Max number of iterations to try while starting or stopping processes.
Definition at line 58 of file model.php.
Model::$passwdFile = '/var/www/conf/.htpasswd' [protected]
Apache password file pathname.
Definition at line 63 of file model.php.
Model::$CmdLogStart = '/usr/bin/head -1 <LF>'
Definition at line 65 of file model.php.
Model::$VersionCmd = ''
Reimplemented in Apache, Clamd, Dansguardian, Dante, Named, Openssh, Openvpn, P3scan, Pmacct, Smtpgated, Snort, Snortips, Spamassassin, Squid, Symon, and Symux.
Definition at line 67 of file model.php.
Model::$StartCmd = ''
Reimplemented in Spamassassin.
Definition at line 69 of file model.php.
Model::$PidFile = ''
Reimplemented in Clamd, Dansguardian, Dante, Freshclam, Imspector, Named, Openssh, P3scan, Smtpgated, Snortips, Spamassassin, and Squid.
Definition at line 70 of file model.php.
Model::$TmpLogsDir = ''
Definition at line 72 of file model.php.
Model::$newSyslogConf = '/etc/newsyslog.conf' [protected]
Definition at line 74 of file model.php.
Model::$rcConfLocal = '/etc/rc.conf.local' [protected]
Definition at line 75 of file model.php.
Model::$PfRulesFile = '/etc/pf.conf'
Definition at line 78 of file model.php.
Model::$Commands = array()
Argument lists and descriptions of commands.
Parameters:
[out] argv Array of arg types in order
[out] desc Description of the shell function
Todo:
$Commands should be implemented with Interfaces in OOP?
Definition at line 87 of file model.php.
The documentation for this class was generated from the following file:
Model/model.php