ComixWall ISG Administration Interface: P3scan Class Reference
P3scan Class Reference
Public Member Functions
P3scan ()
GetVersion ()
Gets software version string.
GetCurrentLocale ()
Gets current locale.
GetLocales ()
Gets list of locale files.
ChangeLocal ($locale)
Changes local.cf link to given locale.
ParseLogLine ($logline, &$cols)
Log parser.
P3scan ()
Public Attributes
$Name = 'p3scan'
$User = '_p3scan'
const CONFIG_DIR = '/etc/p3scan'
const RE_LC_SUFFIX = '/p3scan-(.*)\.mail$/'
$NVPS = '='
$ConfFile = '/etc/p3scan/p3scan.conf'
$LogFile = '/var/log/p3scan.log'
$VersionCmd = '/usr/local/sbin/p3scan -v'
$PidFile = '/var/run/p3scan/p3scan.pid'
$Model = 'p3scan'
$Layout = 'p3scan'
Detailed Description
Definition at line 38 of file p3scan.php.
Member Function Documentation
P3scan::P3scan ()
Definition at line 54 of file p3scan.php.
References $TmpFile, ChangeLocal(), GetCurrentLocale(), GetLocales(), and Model.
    {
        global $TmpFile;
        parent::Model();
        $this->StartCmd= "/usr/local/sbin/p3scan -f /etc/p3scan/p3scan.conf > $TmpFile 2>&1 &";
        $this->Commands= array_merge(
            $this->Commands,
            array(
                'GetCurrentLocale'  => array(
                    'argv'  => array(),
                    'desc'  => _('Get current locale'),
                    ),
                'GetLocales'    => array(
                    'argv'  => array(),
                    'desc'  => _('Get locales'),
                    ),
                'ChangeLocal'   => array(
                    'argv'  => array(NAME),
                    'desc'  => _('Change p3scan report language'),
                    ),
                )
            );
    }
P3scan::GetVersion ()
Gets software version string.
Reimplemented from Model.
Definition at line 83 of file p3scan.php.
References Model::RunShellCommand().
    {
        return $this->RunShellCommand($this->VersionCmd.' | /usr/bin/head -2 | /usr/bin/tail -1');
    }
P3scan::GetCurrentLocale ()
Gets current locale.
Definition at line 90 of file p3scan.php.
Referenced by P3scan().
    {
        $localcf= self::CONFIG_DIR.'/p3scan.mail';
        if (is_link($localcf) && ($linkedfile= readlink($localcf))) {
            if (preg_match(self::RE_LC_SUFFIX, $linkedfile, $match)) {
                return $match[1];
            }
        }
        return FALSE;
    }
P3scan::GetLocales ()
Gets list of locale files.
Definition at line 104 of file p3scan.php.
References $file, and Model::GetFiles().
Referenced by P3scan().
    {
        $files= $this->GetFiles(self::CONFIG_DIR.'/p3scan-*.mail');
        $files= explode("\n", $files);
        $locales= array();
        foreach ($files as $file) {
            if (!is_dir($file) && !preg_match('/.*\.(bak|orig)$/', $file)) {
                if (preg_match(self::RE_LC_SUFFIX, $file, $match)) {
                    $locales[]= $match[1];
                }
            }
        }
        return implode("\n", $locales);
    }
P3scan::ChangeLocal ($ locale)
Changes local.cf link to given locale.
Parameters:
[in] $locale string Locale name, e.g. Turkish.
Definition at line 124 of file p3scan.php.
References Model::RunShellCommand().
Referenced by P3scan().
    {
        return $this->RunShellCommand('/bin/ln -sf '.self::CONFIG_DIR."/p3scan-$locale.mail ".self::CONFIG_DIR."/p3scan.mail");
    }
P3scan::ParseLogLine ($ logline, &$ cols)
Log parser.
Parameters:
[in] $logline string Log line
[out] $cols array Parsed fields
Returns:
TRUE if log line is parsed
Reimplemented from Model.
Definition at line 129 of file p3scan.php.
References $Re_Ip, and Model::ParseSyslogLine().
    {
        global $Re_Ip;
        if ($this->ParseSyslogLine($logline, $cols)) {
            $re= "/USER '(.*)'$/";
            if (preg_match($re, $logline, $match)) {
                $cols['User']= $match[1];
            }
            else {
                $re_clientip= "($Re_Ip)";
                $re_num= '(\d+)';
                $re= "/Connection from $re_clientip:$re_num$/";
                if (preg_match($re, $logline, $match)) {
                    $cols['SrcIP']= $match[1];
                }
                else {
                    $re= "/Real-server address is $re_clientip:$re_num$/";
                    if (preg_match($re, $logline, $match)) {
                        $cols['DstIP']= $match[1];
                    }
                    else {
                        $re_result= '(.*)';
                        $re= "/Session done \($re_result\). Mails: $re_num Bytes: $re_num$/";
                        if (preg_match($re, $logline, $match)) {
                            $cols['Result']= $match[1];
                            $cols['Mails']= $match[2];
                            $cols['Bytes']= $match[3];
                        }
                        else {
                            // POP3 from 192.168.10.2:47845 to 10.0.0.10:110 from Soner Tari <soner@comixwall.org> to soner@comixwall.org user: soner virus: Eicar-Test-Signature file: /p3scan.8c0Ph
                            $re= "/POP3 from $Re_Ip:\d+ to $Re_Ip:\d+ from (.+) to (.+) user: .+ virus: (.+) file:.*$/";
                            if (preg_match($re, $logline, $match)) {
                                $cols['From']= $match[1];
                                $cols['To']= $match[2];
                                $cols['Virus']= $match[3];
                            }
                        }
                    }
                }
            }
            return TRUE;
        }
        return FALSE;
    }
P3scan::P3scan ()
P3scan configuration.
See Dansguardian $basicConfig for details.
Definition at line 44 of file include.php.
References _HELPBOX2(), _HELPWINDOW(), _TITLE2(), ConfHelpMsg, Config, and exit.
    {
        $this->LogsHelpMsg= _HELPWINDOW('POP3 proxy logs connection information and process exit status.');
        $this->ConfHelpMsg= _HELPWINDOW('You may want to set the report language for your locale. By default, POP3 proxy scans for both spam and viruses.');
        $this->Config = array(
            'checkspam' => array(
                'title' => _TITLE2('Scan Spam'),
                'info' => _HELPBOX2('If enabled, will scan for Spam before scanning for a virus. You should start spamd before running p3scan.'),
                ),
            'justdelete' => array(
                'title' => _TITLE2('Just Delete'),
                'info' => _HELPBOX2('Instead of keeping an infected message in the Virus Directory, delete it after reporting it to the user.
        default: Keep infected messages in Virus Directory'),
                ),
            'maxchilds' => array(
                'title' => _TITLE2('Max Childs'),
                'info' => _HELPBOX2('The maximum number of connections we will handle at once. Any further connections will be dropped. Keep in mind that a number of 10 also means that 10 viruscanner can run at once.'),
                ),
            'bytesfree' => array(
                'title' => _TITLE2('Bytes Free'),
                'info' => _HELPBOX2('The number of KB\'s there must be free before processing any mail. If there is less than this amount, p3scan will terminate any connections until the problem is resolved.
        default: 100MB'),
                ),
            'debug' => array(
                'title' => _TITLE2('Debug'),
                'info' => _HELPBOX2('Turn on debugging.'),
                ),
            'quiet' => array(
                'title' => _TITLE2('Quiet'),
                'info' => _HELPBOX2('Disable reporting of normal operating messages. Only report errors or critical information.
        default: display all except debug info'),
                ),
        );
    }
Member Data Documentation
P3scan::$Name = 'p3scan'
Reimplemented from Model.
Definition at line 40 of file p3scan.php.
P3scan::$User = '_p3scan'
Reimplemented from Model.
Definition at line 41 of file p3scan.php.
const P3scan::CONFIG_DIR = '/etc/p3scan'
Definition at line 43 of file p3scan.php.
const P3scan::RE_LC_SUFFIX = '/p3scan-(.*)\.mail$/'
Definition at line 44 of file p3scan.php.
P3scan::$NVPS = '='
Reimplemented from Model.
Definition at line 46 of file p3scan.php.
P3scan::$ConfFile = '/etc/p3scan/p3scan.conf'
Reimplemented from Model.
Definition at line 47 of file p3scan.php.
P3scan::$LogFile = '/var/log/p3scan.log'
Reimplemented from Model.
Definition at line 48 of file p3scan.php.
P3scan::$VersionCmd = '/usr/local/sbin/p3scan -v'
Reimplemented from Model.
Definition at line 50 of file p3scan.php.
P3scan::$PidFile = '/var/run/p3scan/p3scan.pid'
Reimplemented from Model.
Definition at line 52 of file p3scan.php.
P3scan::$Model = 'p3scan'
Reimplemented from View.
Definition at line 41 of file include.php.
P3scan::$Layout = 'p3scan'
Reimplemented from View.
Definition at line 42 of file include.php.
The documentation for this class was generated from the following files:
Model/p3scan.php
View/p3scan/include.php