ComixWall ISG Administration Interface: Spamd Class Reference
Spamd Class Reference
Public Member Functions
Spamd ()
Stop ()
Stops module process(es).
Start ()
Start module process(es).
SetStartupIf ($if)
GetWhitelist ()
GetGreylist ()
ParseLogLine ($logline, &$cols)
Log parser.
Spamd ()
Public Attributes
$Name = 'spamd'
$User = '_spamd'
$LogFile = '/var/log/spamd.log'
$Model = 'spamd'
$Layout = 'spamd'
Detailed Description
Definition at line 42 of file spamd.php.
Member Function Documentation
Spamd::Spamd ()
Definition at line 49 of file spamd.php.
References $TmpFile, GetGreylist(), GetWhitelist(), Model, and SetStartupIf().
    {
        global $TmpFile;
        parent::Model();
        $this->StartCmd= "/usr/libexec/spamd > $TmpFile 2>&1 &";
        $this->Commands= array_merge(
            $this->Commands,
            array(
                'GetWhitelist'  => array(
                    'argv'  => array(),
                    'desc'  => _('Get spamd whitelist'),
                    ),
                'GetGreylist'   => array(
                    'argv'  => array(),
                    'desc'  => _('Get spamd blacklist'),
                    ),
                'SetStartupIf'  => array(
                    'argv'  => array(NAME),
                    'desc'  => _('Set startup if'),
                    ),
                )
            );
    }
Spamd::Stop ()
Stops module process(es).
Tries PROC_STAT_TIMEOUT times.
Returns:
boolean TRUE if the process killed successfully
Todo:
Actually should stop retrying on some error conditions?
Reimplemented from Model.
Definition at line 78 of file spamd.php.
References Model::Pkill().
    {
        $this->Pkill('spamlogd');
        return parent::Stop();
    }
Spamd::Start ()
Start module process(es).
Tries PROC_STAT_TIMEOUT times.
Returns:
boolean TRUE if the process starts
Todo:
Actually should stop retying on some error conditions?
Todo:
Check $TmpFile for error messages, if so break out instead
Reimplemented from Model.
Definition at line 84 of file spamd.php.
References Model::GetDisabledNVP(), Model::GetNVP(), and Model::RunShellCommand().
    {
        parent::Start();
        // spamlogd_flags="-i em1"
        if (($if= $this->GetNVP($this->rcConfLocal, 'spamlogd_flags', '"')) === FALSE) {
            if (($if= $this->GetDisabledNVP($this->rcConfLocal, 'spamlogd_flags', '"')) === FALSE) {
                return FALSE;
            }
        }
        $this->RunShellCommand("/usr/libexec/spamlogd $if");
    }
Spamd::SetStartupIf ($ if)
Definition at line 98 of file spamd.php.
References Model::ReplaceRegexp().
Referenced by Spamd().
    {
        $re= '/(\h*spamlogd_flags\h*=\h*"\h*-i\h+)(\w+\d+)(".*)/m';
        return $this->ReplaceRegexp($this->rcConfLocal, $re, '${1}'.$if.'${3}');
    }
Spamd::GetWhitelist ()
Definition at line 104 of file spamd.php.
References Model::RunShellCommand().
Referenced by Spamd().
    {
        return $this->RunShellCommand('/usr/sbin/spamdb | grep WHITE');
    }
Spamd::GetGreylist ()
Definition at line 109 of file spamd.php.
References Model::RunShellCommand().
Referenced by Spamd().
    {
        return $this->RunShellCommand('/usr/sbin/spamdb | grep GREY');
    }
Spamd::ParseLogLine ($ logline, &$ cols)
Log parser.
Parameters:
[in] $logline string Log line
[out] $cols array Parsed fields
Returns:
TRUE if log line is parsed
Reimplemented from Model.
Definition at line 114 of file spamd.php.
References $Re_Ip, and Model::ParseSyslogLine().
    {
        global $Re_Ip;
        if ($this->ParseSyslogLine($logline, $cols)) {
            $re_srcip= "($Re_Ip)";
            $re_num= '(\d+)';
            //87.109.52.69: disconnected after 466 seconds.
            $re= "/$re_srcip: disconnected after $re_num seconds\.$/";
            if (preg_match($re, $logline, $match)) {
                $cols['IP']= $match[1];
                $cols['Seconds']= $match[2];
            }
            //122.45.35.135: disconnected after 462 seconds. lists: korea
            $re= "/$re_srcip: disconnected after $re_num seconds\. lists: (.*)$/";
            if (preg_match($re, $logline, $match)) {
                $cols['IP']= $match[1];
                $cols['Seconds']= $match[2];
                $cols['List']= $match[3];
            }
            return TRUE;
        }
        return FALSE;
    }
Spamd::Spamd ()
Definition at line 44 of file include.php.
References _HELPWINDOW().
    {
        $this->LogsHelpMsg= _HELPWINDOW('Spamd logs connections from spam sources and greylisted clients. Also recorded is length of time the client remained connected to spamd.');
    }
Member Data Documentation
Spamd::$Name = 'spamd'
Reimplemented from Model.
Definition at line 44 of file spamd.php.
Spamd::$User = '_spamd'
Reimplemented from Model.
Definition at line 45 of file spamd.php.
Spamd::$LogFile = '/var/log/spamd.log'
Reimplemented from Model.
Definition at line 47 of file spamd.php.
Spamd::$Model = 'spamd'
Reimplemented from View.
Definition at line 41 of file include.php.
Spamd::$Layout = 'spamd'
Reimplemented from View.
Definition at line 42 of file include.php.
The documentation for this class was generated from the following files:
Model/spamd.php
View/spamd/include.php