ComixWall ISG Administration Interface: Blacklists Class Reference
Blacklists Class Reference
Public Member Functions
Blacklists ()
SearchSite ($site)
Searches a given site/url in blacklists.
ParseLogLine ($logline, &$cols)
Search result parser.
Blacklists ()
Public Attributes
$Name = 'blacklists'
$LogFile = '/var/tmp/comixwall/search.out'
$Model = 'blacklists'
Detailed Description
Definition at line 42 of file blacklists.php.
Member Function Documentation
Blacklists::Blacklists ()
Definition at line 50 of file blacklists.php.
References blacklists, lists, Model, and SearchSite().
    {
        parent::Model();
        $this->blacklistsPath= $this->confDir.'lists/blacklists/';
        $this->Commands= array_merge(
            $this->Commands,
            array(
                'SearchSite'=>  array(
                    'argv'  =>  array(REGEXP),
                    'desc'  =>  _('Search site'),
                    ),
                )
            );
    }
Blacklists::SearchSite ($ site)
Searches a given site/url in blacklists.
Skips *.processed files generated by Dansguardian at first startup.
Parameters:
[in] $site string search string
Returns:
File path of search results or FALSE on failure
Definition at line 74 of file blacklists.php.
References $retval.
Referenced by Blacklists().
    {
        $dir= dirname($this->LogFile);
        if (!file_exists($dir)) {
            exec('/bin/mkdir -p '.$dir);
        }
        // Do not list results from domain/url.processed files,
        // *.processed files are generated by dansguardian
        $site= escapeshellarg($site);
        $cmd= "/usr/bin/find $this->blacklistsPath \! -name \"*.processed\" -exec /usr/bin/grep -Io -E $site {} \; > $this->LogFile 2>&1";
        exec($cmd, $output, $retval);
        return $retval <= 1 ? $this->LogFile : FALSE;
    }
Blacklists::ParseLogLine ($ logline, &$ cols)
Search result parser.
This method does what all other ParseLogLine() methods do on log files, except that this works on search results. Function name and signature should be the same, because blacklists search results are displayed by other logs methods.
Reimplemented from Model.
Definition at line 97 of file blacklists.php.
    {
        $re= "|^$this->blacklistsPath(\S+)/(\S+):(.*)$|";
        if (preg_match($re, $logline, $match)) {
            $cols['Category']= ucwords($match[1].' '.$match[2]);
            $cols['Site']= $match[3];
            return TRUE;
        }
        return FALSE;
    }
Blacklists::Blacklists ()
Definition at line 43 of file blacklists.php.
References _HELPWINDOW(), and ConfHelpMsg.
    {
        $this->ConfHelpMsg= _HELPWINDOW('You can search categories on this page.');
    }
Member Data Documentation
Blacklists::$Name = 'blacklists'
Reimplemented from Dansguardian.
Definition at line 44 of file blacklists.php.
Blacklists::$LogFile = '/var/tmp/comixwall/search.out'
Reimplemented from Dansguardian.
Definition at line 46 of file blacklists.php.
Blacklists::$Model = 'blacklists'
Reimplemented from Dansguardian.
Definition at line 41 of file blacklists.php.
The documentation for this class was generated from the following files:
Model/blacklists.php
View/dansguardian/blacklists.php