ComixWall ISG Administration Interface: Pf Class Reference
Pf Class Reference
Public Member Functions
Pf ()
IsRunning ($proc= '')
Checks if the process(es) is running.
Start ()
Enable pf.
Stop ()
Disable pf.
GetStateCount ($re= '')
Gets pf state count.
GetStateList ($end, $count, $re= '')
Gets the pftop output.
ParsePftop ($pftopout)
Parses pftop output.
SetIfs ($lanif, $wanif)
Sets interface names.
SetIntnet ($net)
Sets int_net.
SetAfterhoursIf ($if)
Sets afterhours interface name.
ApplyPfRules ()
Applies pf rules.
GetHostGraphsList ($ip)
Generates host graphs.
EnableAfterHours ()
Enables AfterHours.
DisableAfterHours ()
Disables AfterHours.
GetAfterHoursPfRules ()
Gets pf AfterHour anchor rules.
GetAfterHours ()
Gets pf AfterHour definitions from cron file.
GetCrontab ()
Gets active crontab.
DisableAfterHoursBusinessDays ()
EnableAfterHoursBusinessDays ()
DisableAfterHoursHolidays ()
EnableAfterHoursHolidays ()
ApplyAfterHours ($sh, $sm, $eh, $em, $businessdayslist, $holidayslist)
Sets after hours definitions in cron file.
CommentAfterHoursLine ($re)
Comments the line that matches the give regexp.
UncommentAfterHoursLine ($re)
Uncomments the line that matches the give regexp.
InstallNewCrontab ($contents)
Installs given crontab contents.
CheckAfterHoursOverlap ($contents)
Checks if there is any overlap between business days and holidays in the given file contents.
ParseLogLine ($logline, &$cols)
Log parser.
GetDateRegexp ($date)
Generates date regexp to be used by statistics functions.
GetFileLineCount ($file, $re= '')
Gets line count of file.
GetLogs ($file, $end, $count, $re= '')
Gets lines in file.
GetLiveLogs ($file, $count, $re= '')
Gets logs for live logs pages.
GetPfwCmdWrapperInfo ()
GetPfwCmdWrapperPfInfo ()
GetPfwCmdWrapperPfMem ()
GetPfwCmdWrapperPfStates ($countadjusted, $re)
GetPfwCmdWrapperQueues ($pfhost)
GetPfwCmdWrapperConntest ($pfhost)
GetPfwCmdWrapperLog ($pfhost, $count, $re)
GetPfwPfFileName ($pfhost)
GetPfwPfTest ($pfhost, $file)
GetPfwPfInstall ($pfhost, $file)
Pf ()
FormatDate ($date)
Builds PF (tcpdump) specific string from $date.
Public Attributes
$Name = 'pf'
$LogFile = '/var/log/pflog'
$NVPS = '='
$ConfFile = '/etc/pf.restrictedips'
$AfterHoursFile = '/etc/pf.conf.afterhours'
$Model = 'pf'
Detailed Description
Definition at line 38 of file pf.php.
Member Function Documentation
Pf::Pf ()
Definition at line 69 of file pf.php.
References $TCPDUMP, $VIEW_PATH, ApplyAfterHours(), ApplyPfRules(), DisableAfterHours(), DisableAfterHoursBusinessDays(), DisableAfterHoursHolidays(), EnableAfterHours(), EnableAfterHoursBusinessDays(), EnableAfterHoursHolidays(), GetAfterHours(), GetAfterHoursPfRules(), GetHostGraphsList(), GetPfwCmdWrapperConntest(), GetPfwCmdWrapperInfo(), GetPfwCmdWrapperLog(), GetPfwCmdWrapperPfInfo(), GetPfwCmdWrapperPfMem(), GetPfwCmdWrapperPfStates(), GetPfwCmdWrapperQueues(), GetPfwPfFileName(), GetPfwPfInstall(), GetPfwPfTest(), GetStateCount(), GetStateList(), Model, SetAfterhoursIf(), SetIfs(), and SetIntnet().
    {
        global $VIEW_PATH, $TCPDUMP;
        parent::Model();
        $this->PNRG_IMG_DIR= $VIEW_PATH.'pmacct/pnrg/spool/';
        $this->PF_PATH= $VIEW_PATH.'pf';
        $re_days= '(\*|[0-7,]*)';
        $re_hour= '(\d+)';
        $re_min= '(\d+)';
        $re= "$re_min\s+$re_hour\s+\*\s+\*\s+$re_days\s+\/sbin\/pfctl -a AfterHours -f \/etc\/pf\.conf\.afterhours";
        $this->re_BusinessDays= "^$re$";
        $this->re_DisabledBusinessDays= "^#$re$";
        $re= "$re_min\s+$re_hour\s+\*\s+\*\s+$re_days\s+\/sbin\/pfctl -a AfterHours -Fr";
        $this->re_Flush= "^$re$";
        $this->re_DisabledFlush= "^#$re$";
        $re= "\*\s+\*\s+\*\s+\*\s+$re_days\s+\/sbin\/pfctl -a AfterHours -f \/etc\/pf\.conf\.afterhours";
        $this->re_Holidays= "^$re$";
        $this->re_DisabledHolidays= "^#$re$";
        $this->CmdLogStart= $TCPDUMP.' <LF> | /usr/bin/head -1';
        $this->Commands= array_merge(
            $this->Commands,
            array(
                'SetIfs'=>  array(
                    'argv'  =>  array(NAME, NAME),
                    'desc'  =>  _('Set interfaces'),
                    ),
                'SetIntnet'=>   array(
                    'argv'  =>  array(IPRANGE),
                    'desc'  =>  _('Set internal net'),
                    ),
                'SetAfterhoursIf'=> array(
                    'argv'  =>  array(NAME),
                    'desc'  =>  _('Set afterhours if'),
                    ),
                'GetStateCount' =>  array(
                    'argv'  =>  array(REGEXP|NONE),
                    'desc'  =>  _('Get pf state count'),
                    ),
                'GetStateList'  =>  array(
                    'argv'  =>  array(NUM, NUM, REGEXP|NONE),
                    'desc'  =>  _('Get pf states'),
                    ),
                'ApplyPfRules'  =>  array(
                    'argv'  =>  array(),
                    'desc'  =>  _('Apply pf rules'),
                    ),
                'GetHostGraphsList' =>  array(
                    'argv'  =>  array(IPADR|EMPTYSTR),
                    'desc'  =>  _('Get host graphs'),
                    ),
                'EnableAfterHours'  =>  array(
                    'argv'  =>  array(),
                    'desc'  =>  _('Enable AfterHours'),
                    ),
                'DisableAfterHours'     =>  array(
                    'argv'  =>  array(),
                    'desc'  =>  _('Disable AfterHours'),
                    ),
                'GetAfterHoursPfRules'=>    array(
                    'argv'  =>  array(),
                    'desc'  =>  _('Get AfterHour pf rules'),
                    ),
                'GetAfterHours' =>  array(
                    'argv'  =>  array(),
                    'desc'  =>  _('Get AfterHours'),
                    ),
                'DisableAfterHoursBusinessDays'=>   array(
                    'argv'  =>  array(),
                    'desc'  =>  _('Disable AfterHours business days'),
                    ),
                'EnableAfterHoursBusinessDays'=>    array(
                    'argv'  =>  array(),
                    'desc'  =>  _('Enable AfterHours business days'),
                    ),
                'DisableAfterHoursHolidays'=>   array(
                    'argv'  =>  array(),
                    'desc'  =>  _('Disable AfterHours holidays'),
                    ),
                'EnableAfterHoursHolidays'=>    array(
                    'argv'  =>  array(),
                    'desc'  =>  _('Enable AfterHours holidays'),
                    ),
                'ApplyAfterHours'=> array(
                    'argv'  =>  array(NUM|EMPTYSTR, NUM|EMPTYSTR, NUM|EMPTYSTR, NUM|EMPTYSTR, AFTERHOURS, AFTERHOURS),
                    'desc'  =>  _('Apply AfterHours'),
                    ),
                'GetPfwCmdWrapperInfo'=>    array(
                    'argv'  =>  array(),
                    'desc'  =>  _('Get pfw commandwrapper -info'),
                    ),
                'GetPfwCmdWrapperPfInfo'=>  array(
                    'argv'  =>  array(),
                    'desc'  =>  _('Get pfw commandwrapper -pfinfo'),
                    ),
                'GetPfwCmdWrapperPfMem'=>   array(
                    'argv'  =>  array(),
                    'desc'  =>  _('Get pfw commandwrapper -pfmem'),
                    ),
                'GetPfwCmdWrapperPfStates'=>    array(
                    'argv'  =>  array(NUM, REGEXP),
                    'desc'  =>  _('Get pfw commandwrapper -pfstates'),
                    ),
                'GetPfwCmdWrapperQueues'=>  array(
                    'argv'  =>  array(NAME),
                    'desc'  =>  _('Get pfw commandwrapper -queues'),
                    ),
                'GetPfwCmdWrapperConntest'=>    array(
                    'argv'  =>  array(NAME),
                    'desc'  =>  _('Get pfw commandwrapper -conntest'),
                    ),
                'GetPfwCmdWrapperLog'=> array(
                    'argv'  =>  array(NAME, NUM, REGEXP),
                    'desc'  =>  _('Get pfw commandwrapper -log'),
                    ),
                'GetPfwPfFileName'=>    array(
                    'argv'  =>  array(NAME),
                    'desc'  =>  _('Get pfw packetfilter -r'),
                    ),
                'GetPfwPfTest'=>    array(
                    'argv'  =>  array(NAME, FILEPATH),
                    'desc'  =>  _('Get pfw packetfilter -t'),
                    ),
                'GetPfwPfInstall'=> array(
                    'argv'  =>  array(NAME, FILEPATH),
                    'desc'  =>  _('Get pfw packetfilter -i'),
                    ),
                )
            );
    }
Pf::IsRunning ($ proc = '')
Checks if the process(es) is running.
Uses ps with grep.
Parameters:
[in] $proc string Module process name
Returns:
boolean TRUE if there is any process running
Todo:
Should use pid files instead of ps, if possible at all
Reimplemented from Model.
Definition at line 233 of file pf.php.
References Model::RunShellCommand().
    {
        $output= $this->RunShellCommand('/sbin/pfctl -s info');
        if (preg_match('/Status:\s*(Enabled|Disabled)\s*/', $output, $match)) {
            return ($match[1] == 'Enabled');
        }
        return FALSE;
    }
Pf::Start ()
Enable pf.
Reimplemented from Model.
Definition at line 244 of file pf.php.
References Model::RunShellCommand().
    {
        return $this->RunShellCommand('/sbin/pfctl -e');
    }
Pf::Stop ()
Disable pf.
Reimplemented from Model.
Definition at line 251 of file pf.php.
References Model::RunShellCommand().
    {
        return $this->RunShellCommand('/sbin/pfctl -d');
    }
Pf::GetStateCount ($ re = '')
Gets pf state count.
Parameters:
[in] $re string Regexp to get count of a restricted result set
Returns:
int Line count
Definition at line 261 of file pf.php.
References $retval, and Model::RunShellCommand().
Referenced by Pf().
    {
        // Skip header lines by grepping for In or Out
        // Empty $re is not an issue for grep, greps all
        $cmd= "$this->pftopCmd | /usr/bin/egrep -a 'In|Out'";
        if ($re !== '') {
            $re= escapeshellarg($re);
            $cmd.= " | /usr/bin/grep -a -E $re";
        }
        $cmd.= ' | /usr/bin/wc -l';
        exec($cmd, $output, $retval);
        // OpenBSD wc returns with leading blanks
        return trim($this->RunShellCommand($cmd));
    }
Pf::GetStateList ($ end, $ count, $ re = '')
Gets the pftop output.
Parameters:
[in] $end int Head option, start line
[in] $count int Tail option, page line count
[in] $re string Regexp to restrict the result set
Returns:
serialized Lines
Definition at line 283 of file pf.php.
References $retval, cwc_syslog(), ParsePftop(), and ViewError().
Referenced by Pf().
    {
        // Skip header lines by grepping for In or Out
        // Empty $re is not an issue for grep, greps all
        $re= escapeshellarg($re);
        $cmd= "$this->pftopCmd | /usr/bin/egrep -a 'In|Out' | /usr/bin/grep -a -E $re | /usr/bin/head -$end | /usr/bin/tail -$count";
        exec($cmd, $output, $retval);
        if ($retval === 0) {
            return serialize($this->ParsePftop($output));
        }
        ViewError(implode("\n", $output));
        cwc_syslog(LOG_DEBUG, __FILE__, __FUNCTION__, __LINE__, 'Failed running pftop');
        return FALSE;
    }
Pf::ParsePftop ($ pftopout)
Parses pftop output.
Parameters:
[in] $pftopout arrary pftop output
Returns:
array States
Definition at line 303 of file pf.php.
Referenced by GetStateList().
    {
        $states= array();
        foreach ($pftopout as $line) {
            if (preg_match($this->re_Pftop, $line, $match)) {
                $states[]= array(
                    $match[1],
                    $match[2],
                    $match[3],
                    $match[4],
                    $match[5],
                    $match[6],
                    $match[7],
                    $match[8],
                    $match[9],
                    );
            }
        }
        return $states;
    }
Pf::SetIfs ($ lanif, $ wanif)
Sets interface names.
Definition at line 326 of file pf.php.
References $retval, and Model::SetNVP().
Referenced by Pf().
    {
        $retval= $this->SetNVP($this->PfRulesFile, 'int_if', '"'.$lanif.'"');
        $retval&= $this->SetNVP($this->PfRulesFile, 'ext_if', '"'.$wanif.'"');
        $retval&= $this->SetNVP($this->PfRulesFile, 'proxy', '"'.$wanif.'"');
        return $retval;
    }
Pf::SetIntnet ($ net)
Sets int_net.
Definition at line 336 of file pf.php.
References Model::SetNVP().
Referenced by Pf().
    {
        return $this->SetNVP($this->PfRulesFile, 'int_net', '"'.$net.'"');
    }
Pf::SetAfterhoursIf ($ if)
Sets afterhours interface name.
Definition at line 343 of file pf.php.
References Model::SetNVP().
Referenced by Pf().
    {
        return $this->SetNVP($this->AfterHoursFile, 'int_if', '"'.$if.'"');
    }
Pf::ApplyPfRules ()
Applies pf rules.
Definition at line 350 of file pf.php.
References Model::RunShellCommand().
Referenced by Pf().
    {
        return $this->RunShellCommand("/sbin/pfctl -f $this->PfRulesFile");
    }
Pf::GetHostGraphsList ($ ip)
Generates host graphs.
Definition at line 357 of file pf.php.
References $dh, $filename, $Re_Ip, and Model::RunShellCommand().
Referenced by Pf().
    {
        global $Re_Ip;
        $iplist= array();
        $dh= opendir($this->PNRG_IMG_DIR);
        while (FALSE !== ($filename= readdir($dh))) {
            if (preg_match("/^($Re_Ip)\.cgi$/", $filename, $match)) {
                $iplist[]= $match[1];
            }
        }
        closedir($dh);
        sort($iplist);
        if (in_array($ip, $iplist)) {
            $this->RunShellCommand($this->PNRG_IMG_DIR.$ip.'.cgi');
        }
        else if (count($iplist) > 0) {
            $this->RunShellCommand($this->PNRG_IMG_DIR.$iplist[0].'.cgi');
        }
        return implode("\n", $iplist);
    }
Pf::EnableAfterHours ()
Enables AfterHours.
Definition at line 385 of file pf.php.
References Model::RunShellCommand().
Referenced by Pf().
    {
        return $this->RunShellCommand('/sbin/pfctl -a AfterHours -f /etc/pf.conf.afterhours');
    }
Pf::DisableAfterHours ()
Disables AfterHours.
Definition at line 392 of file pf.php.
References Model::RunShellCommand().
Referenced by Pf().
    {
        return $this->RunShellCommand('/sbin/pfctl -a AfterHours -Fr');
    }
Pf::GetAfterHoursPfRules ()
Gets pf AfterHour anchor rules.
Definition at line 399 of file pf.php.
References Model::RunShellCommand().
Referenced by Pf().
    {
        return $this->RunShellCommand('/sbin/pfctl -a AfterHours -sr');
    }
Pf::GetAfterHours ()
Gets pf AfterHour definitions from cron file.
Definition at line 406 of file pf.php.
References GetCrontab().
Referenced by Pf().
    {
        if (($contents= $this->GetCrontab()) !== FALSE) {
            if (preg_match("/$this->re_BusinessDays/ms", $contents, $match)) {
                $businessdaysdisabled= FALSE;
            }
            else if (preg_match("/$this->re_DisabledBusinessDays/ms", $contents, $match)) {
                $businessdaysdisabled= TRUE;
            }
            $endmin= sprintf('%02d', $match[1]);
            $endhour= sprintf('%02d', $match[2]);
            $businessdays= explode(',', $match[3]);
            if (preg_match("/$this->re_Holidays/ms", $contents, $match)) {
                $holidaysdisabled= FALSE;
            }
            else if (preg_match("/$this->re_DisabledHolidays/ms", $contents, $match)) {
                $holidaysdisabled= TRUE;
            }
            $holidays= explode(',', $match[1]);
            if (preg_match("/$this->re_Flush/ms", $contents, $match)) {
                $flushdisabled= FALSE;
            }
            else if (preg_match("/$this->re_DisabledFlush/ms", $contents, $match)) {
                $flushdisabled= TRUE;
            }
            $startmin= sprintf('%02d', $match[1]);
            $starthour= sprintf('%02d', $match[2]);
            $flushdays= explode(',', $match[3]);
            return serialize(array($businessdaysdisabled, $holidaysdisabled, $flushdisabled,
                $startmin, $starthour, $endmin, $endhour, $businessdays, $holidays, $flushdays));
        }
        return FALSE;
    }
Pf::GetCrontab ()
Gets active crontab.
Do not read root's crontab file directly, it has header comment lines.
Definition at line 447 of file pf.php.
References $retval, cwc_syslog(), and ViewError().
Referenced by ApplyAfterHours(), CommentAfterHoursLine(), GetAfterHours(), and UncommentAfterHoursLine().
    {
        exec('/usr/bin/crontab -l', $output, $retval);
        if ($retval === 0) {
            return implode("\n", $output);
        }
        ViewError(implode("\n", $output));
        cwc_syslog(LOG_ERR, __FILE__, __FUNCTION__, __LINE__, 'Failed listing crontab');
        return FALSE;
    }
Pf::DisableAfterHoursBusinessDays ()
Flush line should be in sync with business hours line.
Definition at line 458 of file pf.php.
References CommentAfterHoursLine().
Referenced by Pf().
    {
        if ($this->CommentAfterHoursLine($this->re_BusinessDays)) {
            return $this->CommentAfterHoursLine($this->re_Flush);
        }
        return FALSE;
    }
Pf::EnableAfterHoursBusinessDays ()
Flush line should be in sync with business hours line.
Definition at line 467 of file pf.php.
References UncommentAfterHoursLine().
Referenced by Pf().
    {
        if ($this->UncommentAfterHoursLine($this->re_DisabledBusinessDays)) {
            return $this->UncommentAfterHoursLine($this->re_DisabledFlush);
        }
        return FALSE;
    }
Pf::DisableAfterHoursHolidays ()
Definition at line 476 of file pf.php.
References CommentAfterHoursLine().
Referenced by Pf().
    {
        return $this->CommentAfterHoursLine($this->re_Holidays);
    }
Pf::EnableAfterHoursHolidays ()
Definition at line 481 of file pf.php.
References UncommentAfterHoursLine().
Referenced by Pf().
    {
        return $this->UncommentAfterHoursLine($this->re_DisabledHolidays);
    }
Pf::ApplyAfterHours ($ sh, $ sm, $ eh, $ em, $ businessdayslist, $ holidayslist)
Sets after hours definitions in cron file.
Parameters:
[in] $sh string Start hour.
[in] $sm string Start minute.
[in] $eh string End hour.
[in] $em string End minute.
[in] $businessdayslist string Comma separated business days.
[in] $holidayslist string Comma separated holidays.
Definition at line 495 of file pf.php.
References CheckAfterHoursOverlap(), GetCrontab(), and InstallNewCrontab().
Referenced by Pf().
    {
        if (($contents= $this->GetCrontab()) !== FALSE) {
            // Remove leading zeros
            $starthour= $sh + 0;
            $startmin= $sm + 0;
            $endhour= $eh + 0;
            $endmin= $em + 0;
            $re_replace= "$endmin   $endhour    *   *   $businessdayslist   /sbin/pfctl -a AfterHours -f /etc/pf.conf.afterhours";
            if ($newcontents= preg_replace("/$this->re_BusinessDays/ms", $re_replace, $contents)) {
                $contents= $newcontents;
            }
            $re_replace= "* *   *   *   $holidayslist   /sbin/pfctl -a AfterHours -f /etc/pf.conf.afterhours";
            if ($newcontents= preg_replace("/$this->re_Holidays/ms", $re_replace, $contents)) {
                $contents= $newcontents;
            }
            $re_replace= "$startmin $starthour  *   *   $businessdayslist   /sbin/pfctl -a AfterHours -Fr";
            if ($newcontents= preg_replace("/$this->re_Flush/ms", $re_replace, $contents)) {
                $contents= $newcontents;
            }
            if ($this->CheckAfterHoursOverlap($contents)) {
                return $this->InstallNewCrontab($contents);
            }
        }
        return FALSE;
    }
Pf::CommentAfterHoursLine ($ re)
Comments the line that matches the give regexp.
Parameters:
[in] $re string RE of the line to comment.
Definition at line 530 of file pf.php.
References GetCrontab(), and InstallNewCrontab().
Referenced by DisableAfterHoursBusinessDays(), and DisableAfterHoursHolidays().
    {
        if (($contents= $this->GetCrontab()) !== FALSE) {
            if (preg_match("/$re/ms", $contents, $match)) {
                if ($contents= preg_replace("/$re/ms", '#'.$match[0], $contents)) {
                    return $this->InstallNewCrontab($contents);
                }
            }
        }
        return FALSE;
    }
Pf::UncommentAfterHoursLine ($ re)
Uncomments the line that matches the give regexp.
Parameters:
[in] $re string RE of the line to uncomment.
Definition at line 546 of file pf.php.
References CheckAfterHoursOverlap(), GetCrontab(), and InstallNewCrontab().
Referenced by EnableAfterHoursBusinessDays(), and EnableAfterHoursHolidays().
    {
        if (($contents= $this->GetCrontab()) !== FALSE) {
            if (preg_match("/$re/ms", $contents, $match)) {
                if ($contents= preg_replace("/$re/ms", substr($match[0], 1), $contents)) {
                    if ($this->CheckAfterHoursOverlap($contents)) {
                        return $this->InstallNewCrontab($contents);
                    }
                }
            }
        }
        return FALSE;
    }
Pf::InstallNewCrontab ($ contents)
Installs given crontab contents.
Crontab contents should be installed by running crontab, otherwise they are not activated just by directly editing crontab files.
Parameters:
[in] $contents string Crontab contents.
Definition at line 567 of file pf.php.
References $retval, cwc_syslog(), Model::PutFile(), and ViewError().
Referenced by ApplyAfterHours(), CommentAfterHoursLine(), and UncommentAfterHoursLine().
    {
        // PutFile() does not create the file if it does not exist already
        exec("/usr/bin/touch $this->tmpCrontab");
        // crontab complains without newline at the end of last line
        if ($this->PutFile($this->tmpCrontab, $contents.PHP_EOL)) {
            exec("/usr/bin/crontab $this->tmpCrontab", $output, $retval);
            if ($retval === 0) {
                return TRUE;
            }
            ViewError(implode("\n", $output));
        }
        cwc_syslog(LOG_ERR, __FILE__, __FUNCTION__, __LINE__, 'Failed installing new crontab');
        return FALSE;
    }
Pf::CheckAfterHoursOverlap ($ contents)
Checks if there is any overlap between business days and holidays in the given file contents.
Parameters:
[in] $contents string Cron file contents to check.
Returns:
TRUE if no overlap.
Definition at line 589 of file pf.php.
References ViewError().
Referenced by ApplyAfterHours(), and UncommentAfterHoursLine().
    {
        $businessdays= array();
        if (preg_match("/$this->re_BusinessDays/ms", $contents, $match)) {
            $businessdays= explode(',', $match[3]);
        }
        $holidays= array();
        if (preg_match("/$this->re_Holidays/ms", $contents, $match)) {
            $holidays= explode(',', $match[1]);
        }
        if (count(array_intersect($businessdays, $holidays)) > 0) {
            ViewError(_('Business days and holidays cannot overlap.'));
            return FALSE;
        }
        return TRUE;
    }
Pf::ParseLogLine ($ logline, &$ cols)
Log parser.
Parameters:
[in] $logline string Log line
[out] $cols array Parsed fields
Returns:
TRUE if log line is parsed
Reimplemented from Model.
Definition at line 607 of file pf.php.
References $Re_Ip.
Referenced by GetLiveLogs(), and GetLogs().
    {
        global $Re_Ip;
        // Sep 28 03:50:22.683986 rule 39/(match) pass in on em1: 10.0.0.11.40284 > 10.0.0.13.443: S 3537547021:3537547021(0) win 5840 <mss 1460,sackOK,timestamp 6440374[|tcp]> (DF)
        // Sep 27 14:32:21.715363 rule 37/(match) pass in on em1: 10.0.0.11.40546 > 10.0.0.13.22: S 2853072521:2853072521(0) win 5840 <mss 1460,sackOK,timestamp 3609332[|tcp]> (DF)
        // Sep 28 02:57:36.888668 rule 47/(match) pass out on em1: 10.0.0.13.16227 > 194.27.110.130.123: v4 client strat 0 poll 0 prec 0 [tos 0x10]
        //
        // Sep 26 14:26:28.605638 rule 11/(match) block in on em1: 10.0.0.11.59299 > 239.255.255.250.1900: udp 132 (DF) [ttl 1]
        //
        // Sep 28 03:50:20.124951 rule 11/(match) block in on em1: 10.0.0.11 > 224.0.0.22: igmp-2 [v2] (DF) [tos 0xc0] [ttl 1]
        //
        // Sep 28 03:50:16.900084 rule 11/(match) block in on em1: 10.0.0.11.5353 > 224.0.0.251.5353: 0*- [0q] 7/0/0[|domain] (DF)
        // Sep 28 03:30:02.676705 rule 47/(match) pass out on em1: 10.0.0.13.41578 > 10.0.0.2.53: 61952+% [1au][|domain]
        //
        // Sep 28 03:50:03.858844 rule 11/(match) block in on em0: 10.0.0.2.67 > 255.255.255.255.68: xid:0xf2ed6079 flags:0x8000 [|bootp] (DF)
        // Sep 28 03:50:03.858828 rule 11/(match) block in on em0: 0.0.0.0.68 > 255.255.255.255.67: xid:0xf2ed6079 [|bootp] [tos 0x10]
        //
        // Sep 28 03:50:03.749086 rule 11/(match) block in on em1: fe80::21f:e2ff:fe61:969a > ff02::2: icmp6: router solicitation
        // Sep 28 03:49:54.705294 rule 11/(match) block in on em0: :: > ff02::1:ff61:969a: [|icmp6]
        // Sep 26 17:46:27.631418 rule 11/(match) block in on em0: :: > ff02::16: HBH icmp6: type-#143 [hlim 1]
        // Oct 18 05:16:52.230791 rule 11/(match) block in on em1: fe80::a00:27ff:fe4f:2af9.546 > ff02::1:2.547:dhcp6 solicit [hlim 1]
        $re_datetime= '(\w+\s+\d+)\s+(\d+:\d+:\d+)\.\d+';
        $re_rule= 'rule\s+([\w\.]+)\/\S+';
        $re_action= '(block|pass|match)';
        $re_direction= '(in|out)';
        $re_if= 'on\s+(\w+\d+):';
        $re_srcipport= "($Re_Ip|[\w:]+)(.(\d+)|)";
        $re_dstipport= "($Re_Ip|[\w:]+)(.(\d+)|)";
        $re_rest= '(.*)';
        $re= "/^$re_datetime\s+$re_rule\s+$re_action\s+$re_direction\s+$re_if\s+$re_srcipport\s+>\s+$re_dstipport:\s*$re_rest$/";
        if (preg_match($re, $logline, $match)) {
            $cols['Date']= $match[1];
            $cols['Time']= $match[2];
            $cols['Rule']= $match[3];
            $cols['Act']= $match[4];
            $cols['Dir']= $match[5];
            $cols['If']= $match[6];
            $cols['SrcIP']= $match[7];
            $cols['SPort']= $match[9];
            $cols['DstIP']= $match[10];
            $cols['DPort']= $match[12];
            $rest= $match[13];
            $re= '/(tcp|udp|domain|icmp6|icmp\b|igmp\-2|igmp\b|bootp|\back\b|v4|dhcp\d*)/';
            if (preg_match($re, $rest, $match)) {
                $cols['Type']= $match[1];
            }
            else {
                $cols['Type']= 'other';
            }
            $cols['Log']= $rest;
            return TRUE;
        }
        return FALSE;
    }
Pf::GetDateRegexp ($ date)
Generates date regexp to be used by statistics functions.
Used to match date indeces of stats array to get stats for date ranges.
Parameters:
[in] $date array Date struct
Returns:
Regexp
Reimplemented from Model.
Definition at line 667 of file pf.php.
References $MonthNames.
    {
        global $MonthNames;
        if ($date['Month'] == '') {
            $re= '.*';
        }
        else {
            $re= $MonthNames[$date['Month']].'\s+';
            if ($date['Day'] == '') {
                $re.= '.*';
            }
            else {
                $re.= sprintf('%02d', $date['Day']);
            }
        }
        return $re;
    }
Pf::GetFileLineCount ($ file, $ re = '')
Gets line count of file.
Parameters:
[in] $file string Log file pathname
[in] $re string Regexp to get count of a restricted result set
Returns:
int Line count
Warning:
Input redirection is necessary, otherwise wc adds file name to its output too
Reimplemented from Model.
Definition at line 686 of file pf.php.
References $TCPDUMP, and Model::RunShellCommand().
    {
        global $TCPDUMP;
        $cmd= "$TCPDUMP $file";
        if ($re !== '') {
            $re= escapeshellarg($re);
            $cmd.= " | /usr/bin/grep -a -E $re";
        }
        $cmd.= ' | /usr/bin/wc -l';
        // OpenBSD wc returns with leading blanks
        return trim($this->RunShellCommand($cmd));
    }
Pf::GetLogs ($ file, $ end, $ count, $ re = '')
Gets lines in file.
Parameters:
[in] $file string Log file pathname
[in] $end int Head option, start line
[in] $count int Tail option, page line count
[in] $re string Regexp to restrict the result set
Returns:
serialized Log lines
Reimplemented from Model.
Definition at line 701 of file pf.php.
References $logs, $TCPDUMP, ParseLogLine(), and Model::RunShellCommand().
    {
        global $TCPDUMP;
        $cmd= "$TCPDUMP $file";
        if ($re !== '') {
            $re= escapeshellarg($re);
            $cmd.= " | /usr/bin/grep -a -E $re";
        }
        $cmd.= " | /usr/bin/head -$end | /usr/bin/tail -$count";
        $lines= explode("\n", $this->RunShellCommand($cmd));
        $logs= array();
        foreach ($lines as $line) {
            unset($Cols);
            if ($this->ParseLogLine($line, $Cols)) {
                $logs[]= $Cols;
            }
        }
        return serialize($logs);
    }
Pf::GetLiveLogs ($ file, $ count, $ re = '')
Gets logs for live logs pages.
Used to extract lines in last section of the log file or of the lines grep'd.
Difference from the archives method is that this one always gets the tail of the log or grepped lines.
Parameters:
[in] $file string Log file
[in] $count int Tail lenght, page line count
[in] $re string Regexp to restrict the result set
Returns:
serialized Log lines
Reimplemented from Model.
Definition at line 724 of file pf.php.
References $logs, $TCPDUMP, ParseLogLine(), and Model::RunShellCommand().
    {
        global $TCPDUMP;
        $cmd= "$TCPDUMP $file";
        if ($re !== '') {
            $re= escapeshellarg($re);
            $cmd.= " | /usr/bin/grep -a -E $re";
        }
        $cmd.= " | /usr/bin/tail -$count";
        $lines= explode("\n", $this->RunShellCommand($cmd));
        $logs= array();
        foreach ($lines as $line) {
            if ($this->ParseLogLine($line, $Cols)) {
                $logs[]= $Cols;
            }
        }
        return serialize($logs);
    }
Pf::GetPfwCmdWrapperInfo ()
Definition at line 746 of file pf.php.
References Model::RunShellCommand().
Referenced by Pf().
    {
        return $this->RunShellCommand("$this->PF_PATH/bin/commandwrapper.sh localhost -info");
    }
Pf::GetPfwCmdWrapperPfInfo ()
Definition at line 751 of file pf.php.
References Model::RunShellCommand().
Referenced by Pf().
    {
        return $this->RunShellCommand("$this->PF_PATH/bin/commandwrapper.sh localhost -pfinfo");
    }
Pf::GetPfwCmdWrapperPfMem ()
Definition at line 756 of file pf.php.
References Model::RunShellCommand().
Referenced by Pf().
    {
        return $this->RunShellCommand("$this->PF_PATH/bin/commandwrapper.sh localhost -pfmem");
    }
Pf::GetPfwCmdWrapperPfStates ($ countadjusted, $ re)
Definition at line 761 of file pf.php.
References Model::RunShellCommand().
Referenced by Pf().
    {
        $re= escapeshellarg($re);
        return $this->RunShellCommand("$this->PF_PATH/bin/commandwrapper.sh localhost -pfstates $countadjusted $re");
    }
Pf::GetPfwCmdWrapperQueues ($ pfhost)
Definition at line 767 of file pf.php.
References Model::RunShellCommand().
Referenced by Pf().
    {
        return $this->RunShellCommand("$this->PF_PATH/bin/commandwrapper.sh $pfhost -queues");
    }
Pf::GetPfwCmdWrapperConntest ($ pfhost)
Definition at line 772 of file pf.php.
References Model::RunShellCommand().
Referenced by Pf().
    {
        return $this->RunShellCommand("$this->PF_PATH/bin/commandwrapper.sh $pfhost -conntest");
    }
Pf::GetPfwCmdWrapperLog ($ pfhost, $ count, $ re)
Definition at line 777 of file pf.php.
References Model::RunShellCommand().
Referenced by Pf().
    {
        $re= escapeshellarg($re);
        return $this->RunShellCommand("$this->PF_PATH/bin/commandwrapper.sh $pfhost -log -$count $re");
    }
Pf::GetPfwPfFileName ($ pfhost)
Definition at line 783 of file pf.php.
References Model::RunShellCommand().
Referenced by Pf().
    {
        return $this->RunShellCommand("$this->PF_PATH/bin/packetfilter.sh $pfhost -r");
    }
Pf::GetPfwPfTest ($ pfhost, $ file)
Definition at line 788 of file pf.php.
References $retval.
Referenced by Pf().
    {
        exec("$this->PF_PATH/bin/packetfilter.sh $pfhost -t $file", $output, $retval);
        // Return value of this shell script is not 0, do not use $retval === 0 here
        if ($retval) {
            return implode("\n", $output);
        }
        return FALSE;
    }
Pf::GetPfwPfInstall ($ pfhost, $ file)
Definition at line 798 of file pf.php.
References $retval.
Referenced by Pf().
    {
        exec("$this->PF_PATH/bin/packetfilter.sh $pfhost -i $file", $output, $retval);
        // Return value of this shell script is not 0, do not use $retval === 0 here
        if ($retval) {
            return implode("\n", $output);
        }
        return FALSE;
    }
Pf::Pf ()
Definition at line 43 of file include.php.
References _HELPWINDOW().
    {
        $this->LogsHelpMsg= _HELPWINDOW('What is recorded in packet filter logs is determined by pf rules you can configure under Rules tab.');
    }
Pf::FormatDate ($ date)
Builds PF (tcpdump) specific string from $date.
Parameters:
[in] $date array Datetime struct
Reimplemented from View.
Definition at line 52 of file include.php.
References $MonthNames.
    {
        global $MonthNames;
        return $MonthNames[$date['Month']].' '.$date['Day'];
    }
Member Data Documentation
Pf::$Name = 'pf'
Reimplemented from Model.
Definition at line 40 of file pf.php.
Pf::$LogFile = '/var/log/pflog'
Reimplemented from Model.
Definition at line 42 of file pf.php.
Pf::$NVPS = '='
Reimplemented from Model.
Definition at line 44 of file pf.php.
Pf::$ConfFile = '/etc/pf.restrictedips'
Reimplemented from Model.
Definition at line 45 of file pf.php.
Pf::$AfterHoursFile = '/etc/pf.conf.afterhours'
Definition at line 47 of file pf.php.
Pf::$Model = 'pf'
Reimplemented from View.
Definition at line 41 of file include.php.
The documentation for this class was generated from the following files:
Model/pf.php
View/pf/include.php