ComixWall ISG Administration Interface: rules Class Reference
rules Class Reference
pfw's parent rule class.
Public Member Functions
rules ()
The class constructor function.
up ($rulenumber)
Moves a rule in a ruleset up.
down ($rulenumber)
Moves a rule in a ruleset down.
del ($rulenumber)
Deletes a rule in the ruleset.
addRule ($rulenumber=false)
Adds a rule to the ruleset.
addComment ($comment=false)
Adds a comment-rule to the ruleset.
addEntity ($type, $rulenumber, $data)
Adds a ruleset entity to a rule, used for things that can hold more than one thing.
delEntity ($type, $rulenumber, $data)
Deletes a ruleset entity from a rule, used for things that can hold more than one thing.
parseString ($rules, $i)
Deletes a ruleset entity from a rule, used for things that can hold more than one thing.
parseItem ($rules, $i, $delimiter_pre="{", $delimiter_post="}")
parsePortItem ($rules, $i)
generateItem ($items, $heading)
Generates output from either an array of items or a single item into a joined output string.
Public Attributes
$rules = array()
Detailed Description
pfw's parent rule class.
All the pfw ruleset classes are extensions of this class.
Definition at line 38 of file rules.class.php.
Member Function Documentation
rules::rules ()
The class constructor function.
Definition at line 49 of file rules.class.php.
{}
rules::up ($ rulenumber)
Moves a rule in a ruleset up.
Parameters:
int $rulenumber The number of the rule to move up in the ruleset.
Returns:
void
Definition at line 57 of file rules.class.php.
References $rulenumber, and $rules.
    {
        $rules = array();
        for ($i = '0'; $i < count($this->rules); $i++) {
            if ($i == ($rulenumber - '1')) {
                $rules[] = $this->rules[$i+'1'];
                $rules[] = $this->rules[$i];
            } else if ($i != $rulenumber) {
                $rules[] = $this->rules[$i];
            }
        }
        $this->rules = $rules;
    }
rules::down ($ rulenumber)
Moves a rule in a ruleset down.
Parameters:
int $rulenumber The number of the rule to move down in the ruleset.
Returns:
void
Definition at line 77 of file rules.class.php.
References $rulenumber, and $rules.
    {
        $rules = array();
        for ($i = '0'; $i < count($this->rules); $i++) {
            if ($i == $rulenumber) {
                $rules[] = $this->rules[$i+'1'];
                $rules[] = $this->rules[$i];
            } else if ($i != ($rulenumber + '1')) {
                $rules[] = $this->rules[$i];
            }
        }
        $this->rules = $rules;
    }
rules::del ($ rulenumber)
Deletes a rule in the ruleset.
Parameters:
int $rulenumber The number of the rule to delete
Returns:
void
Definition at line 97 of file rules.class.php.
References $rulenumber, and $rules.
    {
        $rules = array();
        for ($i = '0'; $i < count($this->rules); $i++) {
            if ($i != $rulenumber) {
                $rules[] = $this->rules[$i];
            }
        }
        $this->rules = $rules;
    }
rules::addRule ($ rulenumber = false)
Adds a rule to the ruleset.
Parameters:
int $rulenumber The number in the rulebase where you want to insert the rule, if not specified, it will be the last rule.
Returns:
int The number of the inserted rule in the ruleset
Definition at line 114 of file rules.class.php.
References $rulenumber.
    {
        if (!$rulenumber || ($rulenumber > count($this->rules))) {
            $this->rules[] = array();
            return (count($this->rules) - '1');
        } else {
            for ($i = '0'; $i < count($this->rules); $i++) {
                if ($i == $rulenumber) {
                    $_new_rulebase[] = array();
                }
                $_new_rulebase[] = $this->rules[$i];
            }
            $this->rules = $_new_rulebase;
            return $rulenumber;
        }
    }
rules::addComment ($ comment = false)
Adds a comment-rule to the ruleset.
Parameters:
string $comment The comment to be added.
Returns:
void
Reimplemented in options.
Definition at line 137 of file rules.class.php.
    {
        if ($comment) {
            $_data['type'] = "comment";
            $_data['comment'] = $comment;
            $this->rules[] = $_data;
        }
    }
rules::addEntity ($ type, $ rulenumber, $ data)
Adds a ruleset entity to a rule, used for things that can hold more than one thing.
Parameters:
string $type What we are adding the entity to.
int $rulenumber The rulenumber to which we want to add the entity to.
string $data The data to add to the $type.
Returns:
int The number of the inserted rule in the ruleset
Definition at line 154 of file rules.class.php.
References $rulenumber.
    {
        if (!isset($this->rules[$rulenumber][$type])) {
            $this->rules[$rulenumber][$type] = $data;
        } else if (!is_array($this->rules[$rulenumber][$type])) {
            $_temp = $this->rules[$rulenumber][$type];
            unset($this->rules[$rulenumber][$type]);
            $this->rules[$rulenumber][$type][] = $_temp;
            $this->rules[$rulenumber][$type][] = $data;
            $this->rules[$rulenumber][$type] = array_unique ($this->rules[$rulenumber][$type]);
        } else {
            $this->rules[$rulenumber][$type][] = $data;
            $this->rules[$rulenumber][$type] = array_unique ($this->rules[$rulenumber][$type]);
        }
    }
rules::delEntity ($ type, $ rulenumber, $ data)
Deletes a ruleset entity from a rule, used for things that can hold more than one thing.
Parameters:
string $type What we are deleting the entity from.
int $rulenumber The rulenumber to which we want to delete the entity from.
string $data The data to delete from the $type.
Returns:
void
Definition at line 178 of file rules.class.php.
References $rulenumber.
    {
        if (is_array($this->rules[$rulenumber][$type])) {
            foreach ($this->rules[$rulenumber][$type] as $entity) {
                if ($entity != $data) {
                    $_new_data[] = $entity;
                }
            }
            if (count($_new_data) == '1') {
                $this->rules[$rulenumber][$type] = $_new_data['0'];
            } else {
                $this->rules[$rulenumber][$type] = $_new_data;
            }
        } else {
            unset($this->rules[$rulenumber][$type]);
        }
    }
rules::parseString ($ rules, $ i)
Deletes a ruleset entity from a rule, used for things that can hold more than one thing.
Parameters:
array $rules The entire ruleset.
int $i The pointer to where in the ruleset the parsing is at.
Returns:
array $data,$i The parsed string and the new pointer.
Definition at line 203 of file rules.class.php.
References $rules.
Referenced by filter::parse().
    {
      $i++;
      if ($rules[$i] == "\"") {
        $data = $rules[++$i];
        while ($rules[++$i] != "\"") {
          $data .= " ". $rules[$i];
        }
      } else {
        $data = $rules[$i];
      }
      return Array($data, $i);
    }
rules::parseItem ($ rules, $ i, $ delimiter_pre = "{", $ delimiter_post = "}")
Definition at line 217 of file rules.class.php.
References $rules.
Referenced by options::parse(), nat::parse(), and filter::parse().
                                                    {", $delimiter_post = "}")
  {
    $i++;
    //
    // Check if the rule is negated (! { $item1, $item2})
    // If it is, replace with ({ !$item1, !$item2})
    //
    if ($rules[$i] == "!") {
          $ii = ++$i; // Need a new iterator for this loop
        while (preg_replace("/[\s,]+/", "", $rules[++$ii]) != $delimiter_post) {
            if (($rules[$ii] != $delimiter_pre) and ($rules[$ii] != $delimiter_post)) {
              if ($rules[$ii]{0} == "!") {
                //Delete Double negations
                $rules[$ii] = substr($rules[$ii], 1);
              } else {
                $rules[$ii] = "!". $rules[$ii];
              }
        }
        }
    }
        if (($rules[$i] == $delimiter_pre)) {
          while (preg_replace("/[\s,]+/", "", $rules[++$i]) != $delimiter_post) {
            if (($rules[$i] != $delimiter_pre) and ($rules[$i] != $delimiter_post)) {
          if($rules[$i] == "\("){
              while($rules[++$i] != "\)"){
                  $data2[] = $rules[$i];
              }
              $data[] = "(" . join(" ", $data2) . ")";
              unset($data2);
          }
          else{
              $data[] = $rules[$i];
          }
            }
          }
        } else {
          //
          // Check if we have for instance ($ext_if) that by now has been
          // translated to \( $ext_if \)
          //
          if ($rules[$i] == "\(") {
        while($rules[++$i] != "\)"){
            $data2[] = $rules[$i];
        }
        $data[] = "(" . join(" ", $data2) . ")";
        unset($data2);
          } else {
            $data = $rules[$i];
          }
        }
        return Array($data, $i);
  }
rules::parsePortItem ($ rules, $ i)
Definition at line 270 of file rules.class.php.
References $rules.
Referenced by filter::parse().
  {
    $i++;
    //
    // Check if the rule is negated (! { $item1, $item2})
    // If it is, replace with ({ !$item1, !$item2})
    //
    if ($rules[$i] == "!") {
      $ii = ++$i; // Need a new iterator for this loop
        while (preg_replace("/[\s,]+/", "", $rules[++$ii]) != "}") {
            if (($rules[$ii] != "{") and ($rules[$ii] != "}")) {
              if ($rules[$ii]{0} == "!") {
                //Delete Double negations
                $rules[$ii] = substr($rules[$ii], 1);
              } else {
                $rules[$ii] = "!". $rules[$ii];
              }
        }
        }
    }
    if ($rules[$i] == "{") {
      while (preg_replace("/[\s,]+/", "", $rules[++$i]) != "}") {
        $rules[$i] = preg_replace("/[\s,]+/", "", $rules[$i]);
        switch ($rules[$i]) {
        case "}":
            break;
        case "=":
            $data[] = $rules[++$i];
            break;
        case "!=":
        case "<":
        case "<=":
        case ">":
        case ">=":
            $data[] = $rules[$i]. " ". $rules[++$i];
            break;
        default:
            switch (preg_replace("/[\s,]+/", "", $rules[$i+1])) {
            case "<>":
            case "><":
            case ":":
                $data[] = $rules[$i]. " ". $rules[++$i]. " ". $rules[++$i];
                break;
            default:
                $data[] = $rules[$i];
                break;
            }
            break;
        }
      }
    } else {
      switch ($rules[$i]) {
      case "=":
        $data = $rules[++$i];
        break;
      case "!=":
      case "<":
      case "<=":
      case ">":
      case ">=":
        $data = $rules[$i]. " ". $rules[++$i];
        break;
      default:
        switch (preg_replace("/[\s,]+/", "", $rules[$i+1])) {
        case "<>":
        case "><":
        case ":":
            $data = $rules[$i]. " ". $rules[++$i]. " ". $rules[++$i];
            break;
        default:
            $data = $rules[$i];
            break;
        }
        break;
        }
    }
    return Array($data, $i);
  }
rules::generateItem ($ items, $ heading)
Generates output from either an array of items or a single item into a joined output string.
Parameters:
array $items The item or items that should be generated
string $heading The heading for this particular item list
Returns:
string $data The parsed output with the rulestring.
Definition at line 357 of file rules.class.php.
Referenced by nat::generate(), and filter::generate().
    {
    if (is_array($items)) {
      return " ". trim($heading). " { ". join($items, " "). " }";
    } else {
      return " ". trim($heading). " ". $items;
    }
    }
Member Data Documentation
rules::$rules = array()
Reimplemented in options.
Definition at line 44 of file rules.class.php.
Referenced by del(), down(), table::parse(), scrub::parse(), queue::parse(), nat::parse(), macro::parse(), filter::parse(), anchor::parse(), altq::parse(), filter::parseAnchor(), parseItem(), parsePortItem(), parseString(), and up().
The documentation for this class was generated from the following file:
View/pf/lib/packetfilter/rules.class.php