ComixWall ISG Administration Interface: Clamd Class Reference
Clamd Class Reference
Public Member Functions
Clamd ()
ParseLogLine ($logline, &$cols)
Clamd ()
Public Attributes
$Name = 'clamd'
$User = '_clamav'
$NVPS = '\h'
$ConfFile = '/etc/clamd.conf'
$LogFile = '/var/log/clamd.log'
$VersionCmd = '/usr/local/sbin/clamd -V'
$PidFile = '/var/run/clamav/clamd.pid'
$Model = 'clamd'
$Layout = 'clamd'
Detailed Description
Definition at line 38 of file clamd.php.
Member Function Documentation
Clamd::Clamd ()
Definition at line 51 of file clamd.php.
References $TmpFile, and Model.
    {
        global $TmpFile;
        parent::Model();
        $this->StartCmd= "/usr/local/sbin/clamd -c /etc/clamd.conf > $TmpFile 2>&1 &";
    }
Clamd::ParseLogLine ($ logline, &$ cols)
Todo:
clamd and freshclam log lines contain the number of virus defs.
Reimplemented from Model.
Definition at line 61 of file clamd.php.
References Model::ParseSyslogLine().
    {
        //Thu Sep 24 14:20:02 2009 -> SelfCheck: Database status OK.
        $re_datetime= '\w+\s+(\w+\s+\d+)\s+(\d+:\d+:\d+)\s+\d+';
        $re_rest= '(.*)';
        $re= "/^$re_datetime\s+->\s+$re_rest$/";
        if (preg_match($re, $logline, $match)) {
            $cols['Date']= $match[1];
            $cols['Time']= $match[2];
            $cols['DateTime']= $cols['Date'].' '.$cols['Time'];
            $cols['Log']= $match[3];
            return TRUE;
        }
        else if ($this->ParseSyslogLine($logline, $cols)) {
            $cols['DateTime']= $cols['Date'].' '.$cols['Time'];
            return TRUE;
        }
        return FALSE;
    }
Clamd::Clamd ()
Definition at line 45 of file include.clamd.php.
References _HELPBOX2(), _HELPWINDOW(), _TITLE2(), ConfHelpMsg, Config, and GraphHelpMsg.
    {
        $this->LogsHelpMsg= _HELPWINDOW('Clamd logs virus scan results, virus database checks, and database reloads.');
        $this->GraphHelpMsg= _HELPWINDOW('Since Freshclam wakes up periodically, this page displays graphs for Clamd process only.');
        $this->ConfHelpMsg= _HELPWINDOW('By default, Clamd accepts virus scan requests from processes running on the system only, such as the web filter. Default settings should be suitable for most purposes.');
        $this->Config = array(
            'LogClean' => array(
                'title' => _TITLE2('Log Clean'),
                'info' => _HELPBOX2('Also log clean files. Useful in debugging but drastically increases the log size.
        Default: disabled'),
                ),
            'LogVerbose' => array(
                'title' => _TITLE2('Log Verbose'),
                'info' => _HELPBOX2('Enable verbose logging.
        Default: disabled'),
                ),
            'MaxThreads' => array(
                'title' => _TITLE2('Max Threads'),
                'info' => _HELPBOX2('Maximal number of threads running at the same time.
        Default: 10'),
                ),
            'MaxDirectoryRecursion' => array(
                'title' => _TITLE2('Max Directory Recursion'),
                'info' => _HELPBOX2('Maximal depth directories are scanned at.
        Default: 15'),
                ),
            'FollowDirectorySymlinks' => array(
                'title' => _TITLE2('Follow Directory Symlinks'),
                'info' => _HELPBOX2('Follow directory symlinks.
        Default: disabled'),
                ),
            'FollowFileSymlinks' => array(
                'title' => _TITLE2('Follow File Symlinks'),
                'info' => _HELPBOX2('Follow regular file symlinks.
        Default: disabled'),
                ),
            'SelfCheck' => array(
                'title' => _TITLE2('Self Check'),
                'info' => _HELPBOX2('Perform internal sanity check (database integrity and freshness).
        Default: 1800 (30 min)'),
                ),
            'Debug' => array(
                'title' => _TITLE2('Debug'),
                'info' => _HELPBOX2('Enable debug messages in libclamav.
        Default: disabled'),
                ),
            'LeaveTemporaryFiles' => array(
                'title' => _TITLE2('Leave Temporary Files'),
                'info' => _HELPBOX2('Do not remove temporary files (for debug purposes).
        Default: disabled'),
                ),
            'ScanPE' => array(
                'title' => _TITLE2('Scan PE'),
                'info' => _HELPBOX2('PE stands for Portable Executable - it\'s an executable file format used in all 32-bit versions of Windows operating systems. This option allows ClamAV to perform a deeper analysis of executable files and it\'s also required for decompression of popular executable packers such as UPX, FSG, and Petite.
        Default: enabled'),
                ),
            'DetectBrokenExecutables' => array(
                'title' => _TITLE2('Detect Broken Executables'),
                'info' => _HELPBOX2('With this option clamav will try to detect broken executables and mark them as Broken.Executable
        Default: disabled'),
                ),
            'ScanOLE2' => array(
                'title' => _TITLE2('Scan OLE2'),
                'info' => _HELPBOX2('This option enables scanning of Microsoft Office document macros.
        Default: enabled'),
                ),
            'ScanMail' => array(
                'title' => _TITLE2('Scan Mail'),
                'info' => _HELPBOX2('Enable internal e-mail scanner.
        Default: enabled'),
                ),
            'MailFollowURLs' => array(
                'title' => _TITLE2('Mail Follow URLs'),
                'info' => _HELPBOX2('If an email contains URLs ClamAV can download and scan them.
        WARNING: This option may open your system to a DoS attack.
        Never use it on loaded servers.
        Default: disabled'),
                ),
            'ScanHTML' => array(
                'title' => _TITLE2('Scan HTML'),
                'info' => _HELPBOX2('Perform HTML normalisation and decryption of MS Script Encoder code.
        Default: enabled'),
                ),
            'ScanArchive' => array(
                'title' => _TITLE2('Scan Archive'),
                'info' => _HELPBOX2('ClamAV can scan within archives and compressed files.
        Default: enabled'),
                ),
            'ScanRAR' => array(
                'title' => _TITLE2('Scan RAR'),
                'info' => _HELPBOX2('Due to license issues libclamav does not support RAR 3.0 archives (only the old 2.0 format is supported). Because some users report stability problems with unrarlib it\'s disabled by default and you must uncomment the directive below to enable RAR 2.0 support.
        Default: disabled'),
                ),
            'ArchiveMaxFileSize' => array(
                'title' => _TITLE2('Archive Max File Size'),
                'info' => _HELPBOX2('The options below protect your system against Denial of Service attacks using archive bombs.
        Files in archives larger than this limit won\'t be scanned.
        Value of 0 disables the limit.
        Default: 10M'),
                ),
            'ArchiveMaxRecursion' => array(
                'title' => _TITLE2('Archive Max Recursion'),
                'info' => _HELPBOX2('Nested archives are scanned recursively, e.g. if a Zip archive contains a RAR file, all files within it will also be scanned. This options specifies how deep the process should be continued.
        Value of 0 disables the limit.
        Default: 8'),
                ),
            'ArchiveMaxFiles' => array(
                'title' => _TITLE2('Archive Max Files'),
                'info' => _HELPBOX2('Number of files to be scanned within an archive.
        Value of 0 disables the limit.
        Default: 1000'),
                ),
            'ArchiveMaxCompressionRatio' => array(
                'title' => _TITLE2('Archive Max Compression Ratio'),
                'info' => _HELPBOX2('If a file in an archive is compressed more than ArchiveMaxCompressionRatio times it will be marked as a virus (Oversized.ArchiveType, e.g. Oversized.Zip)
        Value of 0 disables the limit.
        Default: 250'),
                ),
            'ArchiveLimitMemoryUsage' => array(
                'title' => _TITLE2('Archive Limit Memory Usage'),
                'info' => _HELPBOX2('Use slower but memory efficient decompression algorithm.
        Only affects the bzip2 decompressor.
        Default: disabled'),
                ),
            'ArchiveBlockEncrypted' => array(
                'title' => _TITLE2('Archive Block Encrypted'),
                'info' => _HELPBOX2('Mark encrypted archives as viruses (Encrypted.Zip, Encrypted.RAR).
        Default: disabled'),
                ),
            'ArchiveBlockMax' => array(
                'title' => _TITLE2('Archive Block Max'),
                'info' => _HELPBOX2('Mark archives as viruses (e.g. RAR.ExceededFileSize, Zip.ExceededFilesLimit) if ArchiveMaxFiles, ArchiveMaxFileSize, or ArchiveMaxRecursion limit is reached.
        Default: disabled'),
                ),
        );
    }
Member Data Documentation
Clamd::$Name = 'clamd'
Reimplemented from Model.
Definition at line 40 of file clamd.php.
Clamd::$User = '_clamav'
Reimplemented from Model.
Definition at line 41 of file clamd.php.
Clamd::$NVPS = '\h'
Reimplemented from Model.
Definition at line 43 of file clamd.php.
Clamd::$ConfFile = '/etc/clamd.conf'
Reimplemented from Model.
Definition at line 44 of file clamd.php.
Clamd::$LogFile = '/var/log/clamd.log'
Reimplemented from Model.
Definition at line 45 of file clamd.php.
Clamd::$VersionCmd = '/usr/local/sbin/clamd -V'
Reimplemented from Model.
Definition at line 47 of file clamd.php.
Clamd::$PidFile = '/var/run/clamav/clamd.pid'
Reimplemented from Model.
Definition at line 49 of file clamd.php.
Clamd::$Model = 'clamd'
Reimplemented from View.
Definition at line 41 of file include.clamd.php.
Clamd::$Layout = 'clamd'
Reimplemented from View.
Definition at line 43 of file include.clamd.php.
The documentation for this class was generated from the following files:
Model/clamd.php
View/clamav/include.clamd.php