ComixWall ISG Administration Interface: Session Class Reference
Session Class Reference
Public Member Functions
Session ()
getvars ()
getform ($name)
get ($n)
printoptions ($name, $options)
getformdefault ($name)
getformconstrained ($name, $value)
purge ()
_display ()
_test ()
Public Attributes
$vars
Detailed Description
Definition at line 48 of file class_session.inc.
Member Function Documentation
Session::Session ()
Definition at line 51 of file class_session.inc.
                       {
    $this->vars = new Vars();
    }
Session::getvars ()
Definition at line 55 of file class_session.inc.
                       {
    return $this->vars;
    }
Session::getform ($ name)
Definition at line 59 of file class_session.inc.
References $_SESSION, $Submenu, $symon, $View, getformconstrained(), and getformdefault().
Referenced by _test().
{
    global $symon, $View, $Submenu;
    if ($Submenu) {
        $session= &$_SESSION[$View->Model]['Graphs'][$Submenu];
    }
    else {
        $session= &$_SESSION[$View->Model]['Graphs'];
    }
    if (isset($_REQUEST[$name])) {
        $value = $_REQUEST[$name];
        // POSTed values have precedence over session vars
        $session[$name]= $value;
    }
    if (isset($session[$name])) {
        $value= $session[$name];
    }
    if (!isset($value)) {
        $value = $this->getformdefault($name);
    } else {
        $value = $this->getformconstrained($name, $value);
    }
    // Do not forget to save the new/default value to session var
    $session[$name]= $value;
    /* unroll items if named var selected */
    if ($symon['defaults'][$name]['type'] == 'named') {
        $s = $symon['defaults'][$name]['namedvalues'][$value];
        if (is_array($s)) {
        foreach ($s as $k => $v) {
            $this->vars->set($k, $v);
        }
        }
    }
    $this->vars->set($name, $value);
    return $value;
    }
Session::get ($ n)
Definition at line 102 of file class_session.inc.
                     {
    if ($this->vars->defp($n)) {
        return $this->vars->get($n);
    }
    }
Session::printoptions ($ name, $ options)
Definition at line 108 of file class_session.inc.
References print.
{
    foreach($options as $k => $v) {
        print '    <option ';
        if ($this->vars->defp($name) &&
        $this->vars->get($name) == $k) {
        print 'selected ';
        }
        print 'value="'.$k.'">'.$v."</option>\xa";
    }
    }
Session::getformdefault ($ name)
Definition at line 119 of file class_session.inc.
References $symon, and session.
Referenced by getform(), and getformconstrained().
{
    global $symon;
    if (!isset($symon['defaults'][$name]['default'])) {
        runtime_error('session: unknown variable "'.$name.'" requested');
    }
    $value = $symon['defaults'][$name]['default'];
    return $value;
    }
Session::getformconstrained ($ name, $ value)
Definition at line 131 of file class_session.inc.
References $symon, getformdefault(), and session.
Referenced by getform().
{
    global $symon;
    if (!isset($symon['defaults'][$name])) {
        runtime_error('session: unknown variable "'.$name.'" requested');
    }
    switch ($symon['defaults'][$name]['type']) {
    case 'named':
        if (!isset($symon['defaults'][$name]['namedvalues'][$value])) {
        $value = $this->getformdefault($name);
        }
        break;
    case 'integer':
        if ($value < $symon['defaults'][$name]['bounds']['min'] ||
        $value > $symon['defaults'][$name]['bounds']['max']) {
        $value = $this->getformdefault($name);
        }
        break;
    default:
        runtime_error('session: unknown variable type "'.$symon['defaults'][$name]['type'].'" requested');
        break;
    }
    return $value;
    }
Session::purge ()
Definition at line 158 of file class_session.inc.
References $vars.
                     {
    $vars = new Vars();
    }
Session::_display ()
Definition at line 162 of file class_session.inc.
{
    $this->vars->_display();
    }
Session::_test ()
Definition at line 166 of file class_session.inc.
References getform(), and layout.
                     {
    $this->getform('end');
    $this->getform('heigth');
    $this->getform('layout');
    $this->getform('size');
    $this->getform('start');
    $this->getform('timespan');
    $this->getform('width');
    $this->getform('layout');
    }
Member Data Documentation
Session::$vars
Definition at line 49 of file class_session.inc.
Referenced by purge().
The documentation for this class was generated from the following file:
View/symon/class_session.inc