ComixWall ISG Administration Interface: Dante Class Reference
Dante Class Reference
Public Member Functions
Dante ()
SetIfs ($lanif, $wanif)
SetIntnet ($net)
Dante ()
Public Attributes
$Name = 'dante'
$User = '_dante'
$ConfFile = '/etc/sockd.conf'
$LogFile = '/var/log/sockd.log'
$VersionCmd = '/usr/local/sbin/sockd -v'
$PidFile = '/var/run/sockd.pid'
$Model = 'dante'
$Layout = 'sockd'
Detailed Description
Definition at line 42 of file dante.php.
Member Function Documentation
Dante::Dante ()
Definition at line 53 of file dante.php.
References $TmpFile, Model, SetIfs(), and SetIntnet().
    {
        global $TmpFile;
        parent::Model();
        $this->Proc= 'sockd';
        $this->StartCmd= "/usr/local/sbin/sockd -D > $TmpFile 2>&1 &";
        $this->Commands= array_merge(
            $this->Commands,
            array(
                'SetIfs'    => array(
                    'argv'  => array(NAME, NAME),
                    'desc'  => _('Set ifs'),
                    ),
                'SetIntnet' => array(
                    'argv'  => array(IPRANGE),
                    'desc'  => _('Set ifs'),
                    ),
                )
            );
    }
Dante::SetIfs ($ lanif, $ wanif)
Definition at line 80 of file dante.php.
References Model::ReplaceRegexp().
Referenced by Dante().
    {
        $re= '/(\h*internal:\h*)(\w+\d+)(\h+.*external:\h*)(\w+\d+)(\s+)/ms';
        return $this->ReplaceRegexp($this->ConfFile, $re, '${1}'.$lanif.'${3}'.$wanif.'${5}');
    }
Dante::SetIntnet ($ net)
Definition at line 86 of file dante.php.
References $Re_Ip, $Re_Net, and Model::ReplaceRegexp().
Referenced by Dante().
    {
        global $Re_Ip, $Re_Net;
        $re= "/(\h*client\h+pass\h*\{\s*\h+from:\h+)($Re_Ip|$Re_Net)(\h+.*)/ms";
        return $this->ReplaceRegexp($this->ConfFile, $re, '${1}'.$net.'${3}');
    }
Dante::Dante ()
Definition at line 44 of file include.php.
References _HELPWINDOW().
    {
        $this->LogsHelpMsg= _HELPWINDOW('SOCKS proxy logs connection status and failures.');
    }
Member Data Documentation
Dante::$Name = 'dante'
Reimplemented from Model.
Definition at line 44 of file dante.php.
Dante::$User = '_dante'
Reimplemented from Model.
Definition at line 45 of file dante.php.
Dante::$ConfFile = '/etc/sockd.conf'
Reimplemented from Model.
Definition at line 47 of file dante.php.
Dante::$LogFile = '/var/log/sockd.log'
Reimplemented from Model.
Definition at line 48 of file dante.php.
Dante::$VersionCmd = '/usr/local/sbin/sockd -v'
Reimplemented from Model.
Definition at line 49 of file dante.php.
Dante::$PidFile = '/var/run/sockd.pid'
Reimplemented from Model.
Definition at line 51 of file dante.php.
Dante::$Model = 'dante'
Reimplemented from View.
Definition at line 41 of file include.php.
Dante::$Layout = 'sockd'
Reimplemented from View.
Definition at line 42 of file include.php.
The documentation for this class was generated from the following files:
Model/dante.php
View/dante/include.php