ComixWall ISG Administration Interface: Layout Class Reference
Layout Class Reference
Public Member Functions
Layout ($name= '')
_generate_default ()
_generate_host ($machine)
Public Attributes
$groups
$groupvars
Detailed Description
Definition at line 48 of file class_layout.inc.
Member Function Documentation
Layout::Layout ($ name = '')
Definition at line 52 of file class_layout.inc.
References $symon, _generate_default(), _generate_host(), and layout.
{
        global $symon;
        $this->_reset();
        if ($name != '') {
            if (!isset($symon["layout_dir"])) {
            config_error("layout_dir", "is not set");
            return 0;
            }
            if (!is_dir($symon["layout_dir"])) {
            config_error("layout_dir", "does not point to a directory");
            return 0;
            }
                if (isset($symon["isolate_hosts"]) &&
                    ($symon["isolate_hosts"] > 0) &&
                    is_dir($symon["host_tree"]."/".normalise_filename($name))) {
                    $this->_generate_host($name);
                } else {
                    $this->_load($name);
                }
        } else {
            $this->_generate_default();
        }
        if (!isset($this->groups)) {
            runtime_error('layout: no valid layout selected');
            return 0;
        }
    }
Layout::_generate_default ()
Definition at line 84 of file class_layout.inc.
References $symon, _generate_host(), and layout.
Referenced by Layout().
{
        global $symon;
        if (!is_dir($symon["host_tree"])) {
            config_error("host_tree", "does not point to a directory");
            return 0;
        }
        $root_dir = dir($symon["host_tree"]);
        while ($host = $root_dir->read()) {
                $this->_generate_host($host);
            }
        if (!isset($this->groups)) {
            runtime_error('layout: need $symon["host_tree"]/hostname/cpu0.rrd like files to generate the default layout - none found.');
            return 0;
        }
    }
Layout::_generate_host ($ machine)
Definition at line 103 of file class_layout.inc.
References $groupvars, and $symon.
Referenced by _generate_default(), and Layout().
{
        global $symon;
        if (!is_dir($symon["host_tree"])) {
            config_error("host_tree", "does not point to a directory");
            return 0;
        }
        if (is_file($symon["host_tree"]."/".$machine)) {
            runtime_error('$symon["host_tree"] should contain machine directories, not files. ($symon["host_tree"]/cpu0.rrd => $symon["host_tree"]/localhost/cpu0.rrd)');
        }
        if ($machine != '.' &&
            $machine != '..' &&
            is_dir($symon["host_tree"]."/".$machine)) {
            $groupvars = new Vars();
            $groupvars->set('host', $machine);
            $groupvars->set('dir', $symon["host_tree"].'/'.$machine);
            $groupvars->set('name', $machine);
            $this->_add_group($groupvars);
            /* get all graphs */
            $graph_dir = dir($symon["host_tree"].'/'.$machine);
            $files = array();
            while ($item = $graph_dir->read()) {
                if ($item != '.' &&
                    $item != '..' &&
                    preg_match("/.rrd$/", $item)) {
                    $files[] = $item;
                }
            }
            asort($files);
            /* get combined graphs */
            foreach ($symon['combine'] as $type => $enabled) {
                if ($enabled) {
                    $combine = array();
                    $newfiles = array();
                    foreach ($files as $key => $item) {
                        if (preg_match("/^".$type."[0-9_]/", $item)) {
                            $combine[] = $item;
                        } else {
                            $newfiles[] = $item;
                        }
                    }
                    $files = $newfiles;
                    if (count($combine)) {
                        $v = new Vars();
                        foreach ($combine as $key => $item) {
                            $v->set('rrdfile'.$key, $symon["host_tree"].'/'.$machine.'/'.$item);
                        }
                        $g = new Graph($groupvars);
                        $g->set_graph_vars($v);
                        $this->_add_item($machine, $g);
                    }
                }
            }
            foreach ($files as $key => $item) {
                $v = new Vars();
                $v->set('rrdfile', $symon["host_tree"].'/'.$machine.'/'.$item);
                $g = new Graph($groupvars);
                $g->set_graph_vars($v);
                $this->_add_item($machine, $g);
            }
        }
    }
Member Data Documentation
Layout::$groups
Definition at line 49 of file class_layout.inc.
Layout::$groupvars
Definition at line 50 of file class_layout.inc.
Referenced by _generate_host().
The documentation for this class was generated from the following file:
View/symon/class_layout.inc