ComixWall ISG Administration Interface: Snortips Class Reference
Snortips Class Reference
Public Member Functions
Snortips ()
Stop ()
Stops module process(es).
GetIP ($ip)
Searches for an IP or !IP.
GetInfo ()
DelIPFromList ($list, $ips)
Deletes a list of IPs from a list.
AddIPToList ($list, $ip)
Adds an IP to snortips white or black list.
UnblockAll ()
Unblock all.
UnblockIPs ($ips)
Unblock IPs.
BlockIP ($ip, $time= '')
Unblock IPs.
GetListIPs ($list)
Provides a list of IPs.
GetKeywords ()
Get keywords.
AddKeyword ($keyword)
Add a keyword.
DelKeyword ($keyword)
Delete a keyword.
ParseLogLine ($logline, &$cols)
Parses snortips IPS logs.
Snortips ()
PrintLogLine ($cols, $linenum)
Displays parsed log line.
PrintListedIPsForm ($list, $title, $helpmsg)
Displays white or black listed IPs form.
PrintBlockedIPsForm ()
Displays a list of blocked, blacklisted, or whitelisted IPs.
Public Attributes
$Name = 'snortips'
$User = 'root'
$NVPS = '\h'
$ConfFile = '/etc/snort/snortips.conf'
$LogFile = '/var/log/snortips.log'
$VersionCmd = 'unset LC_ALL; unset LANG; /usr/local/sbin/snortips -V'
$PidFile = '/var/run/snortips.pid'
$Model = 'snortips'
$Layout = 'snortips'
Detailed Description
Definition at line 38 of file snortips.php.
Member Function Documentation
Snortips::Snortips ()
Todo:
Is there any pattern or size for keywords?
Definition at line 53 of file snortips.php.
References $TmpFile, AddIPToList(), AddKeyword(), BlockIP(), DelIPFromList(), DelKeyword(), GetInfo(), GetKeywords(), GetListIPs(), Model, UnblockAll(), and UnblockIPs().
    {
        global $TmpFile;
        parent::Model();
        $this->StartCmd= "unset LC_ALL; unset LANG; /usr/local/sbin/snortips > $TmpFile 2>&1 &";
        $this->Commands= array_merge(
            $this->Commands,
            array(
                'AddIPToList'   => array(
                    'argv'  => array(NAME, IPADR|IPRANGE),
                    'desc'  => _('Add to IP list'),
                    ),
                'DelIPFromList' => array(
                    'argv'  => array(NAME, SERIALARRAY),
                    'desc'  => _('Delete IP from list'),
                    ),
                'UnblockAll'    => array(
                    'argv'  => array(),
                    'desc'  => _('Unblock all'),
                    ),
                'UnblockIPs'    => array(
                    'argv'  => array(SERIALARRAY),
                    'desc'  => _('Unblock IPs'),
                    ),
                'BlockIP'   => array(
                    'argv'  => array(IPADR|IPRANGE, NUM|EMPTYSTR),
                    'desc'  => _('Block IPs'),
                    ),
                'GetInfo'   => array(
                    'argv'  => array(),
                    'desc'  => _('Get IPS info'),
                    ),
                'GetListIPs'    => array(
                    'argv'  => array(NAME),
                    'desc'  => _('Get listed ips'),
                    ),
                'GetKeywords'   => array(
                    'argv'  => array(),
                    'desc'  => _('Get alert keywords'),
                    ),
                'AddKeyword'    => array(
                    'argv'  => array(STR),
                    'desc'  => _('Add alert keyword'),
                    ),
                'DelKeyword'    => array(
                    'argv'  => array(STR),
                    'desc'  => _('Delete alert keywords'),
                    ),
            )
        );
    }
Snortips::Stop ()
Stops module process(es).
Tries PROC_STAT_TIMEOUT times.
Returns:
boolean TRUE if the process killed successfully
Todo:
Actually should stop retrying on some error conditions?
Reimplemented from Model.
Definition at line 118 of file snortips.php.
References Model::Kill().
    {
        return $this->Kill();
    }
Snortips::GetIP ($ ip)
Searches for an IP or !IP.
Parameters:
[in] $ip Search string.
Returns:
Search string if successful.
Definition at line 128 of file snortips.php.
References Escape(), and Model::SearchFile().
Referenced by AddIPToList().
    {
        $ip= Escape($ip, '/.');
        return $this->SearchFile($this->ConfFile, "/^\h*($ip)\b\h*$/m");
    }
Snortips::GetInfo ()
Todo:
Use communication over shared memory (e.g. pipes) with SnortIPS instead
Definition at line 134 of file snortips.php.
References $Re_Ip, $Re_Net, Model::GetFile(), Model::IsRunning(), Model::PutFile(), and Model::RunShellCommand().
Referenced by PrintBlockedIPsForm(), and Snortips().
    {
        global $Re_Ip, $Re_Net;
        // Clear the file if this function spawns too fast (do not read the same contents again)
        $this->PutFile('/var/db/snortips', '');
        if ($this->IsRunning()) {
            $this->RunShellCommand('/bin/kill -INFO $(/bin/cat /var/run/snortips.pid)');
            $eof= FALSE;
            $count= 0;
            while ($count++ < self::PROC_STAT_TIMEOUT) {
                if ($items= $this->GetFile('/var/db/snortips')) {
                    // Check for EOF
                    if (preg_match("/^\.$/m", $items)) {
                        $eof= TRUE;
                        break;
                    }
                }
                exec('/bin/sleep .1');
            }
            if ($eof) {
                $info= array(
                    'Whitelisted' => array(),
                    'Blocked' => array(),
                    'Blacklisted' => array(),
                    );
                $items= explode("\n", $items);
                foreach ($items as $line) {
                    if (preg_match("/^($Re_Net|$Re_Ip) \((\d+)\)$/", $line, $match)) {
                        $host= $match[1];
                        $expires= $match[2];
                        $info['Blocked'][$host]= $expires.' ('. floor($expires / 60) .' '._('min').' '. $expires % 60 .' '._('sec').')';
                    }
                    else if (preg_match("/^!($Re_Net|$Re_Ip)/", $line, $match)) {
                        $info['Whitelisted'][]= $match[1];
                    }
                    else if (preg_match("/^($Re_Net|$Re_Ip)/", $line)) {
                        $info['Blacklisted'][]= $line;
                    }
                }
                return serialize($info);
            }
        }
        return FALSE;
    }
Snortips::DelIPFromList ($ list, $ ips)
Deletes a list of IPs from a list.
Does not allow system IPs to be deleted.
Parameters:
[in] $list string List name
[in] $ips array List of IPs to delete
Definition at line 192 of file snortips.php.
References $retval, Model::GetIpAddr(), Model::GetPhyIfs(), and ViewError().
Referenced by Snortips().
    {
        $systemips[]= '127.0.0.1';
        if ($list == 'whitelist') {
            $ifs= explode("\n", $this->GetPhyIfs());
            foreach ($ifs as $if) {
                if ($ifip= $this->GetIpAddr($if)) {
                    $systemips[]= $ifip;
                }
            }
        }
        $ips= unserialize($ips);
        $retval= TRUE;
        foreach ($ips as $ip) {
            if (!in_array($ip, $systemips)) {
                $method= $list == 'whitelist' ? 'DelAllowedIp' : 'DelRestrictedIp';
                $retval&= $this->$method($ip);
            }
            else {
                ViewError(_('You cannot delete system IP address').": $ip");
                $retval= FALSE;
            }
        }
        return $retval;
    }
Snortips::AddIPToList ($ list, $ ip)
Adds an IP to snortips white or black list.
Parameters:
[in] $list string List name
[in] $ip string IP or net
Check the IP in the complement list
Definition at line 224 of file snortips.php.
References $preIP, $preNet, $retval, GetIP(), Model::RunShellCommand(), and ViewError().
Referenced by Snortips().
    {
        global $preIP, $preNet;
        $compip= $list == 'whitelist' ? $ip : "!$ip";
        $output= $this->GetIP($compip);
        if ($output !== $compip) {
            $output= $this->RunShellCommand("/sbin/pfctl -nv -t snortips -T add $ip 2>&1");
            $output= explode("\n", $output);
            // 0/1 addresses added (dummy).
            if (preg_match('/^(\d+)\/\d+ addresses added \(dummy\)\.$/', $output[0], $match)) {
                if ($match[1] > 0) {
                    if (preg_match("/^A\s+($preIP|$preNet)$/", $output[1], $match)) {
                        $actualadded= $match[1];
                        // 192.168.1.1/32 and 192.168.1.1 are identical, but we miss it above
                        $compip= $list == 'whitelist' ? $actualadded : "!$actualadded";
                        $output= $this->GetIP($compip);
                        if ($output !== $compip) {
                            $method= $list == 'whitelist' ? 'AddAllowedIp' : 'AddRestrictedIp';
                            $retval= $this->$method($actualadded);
                            if ($actualadded == $ip) {
                                return $retval;
                            }
                            ViewError(_('IP or network address fixed').": $ip -> $actualadded");
                        }
                        else {
                            ViewError(_('White and black list entries should not be identical').": $actualadded");
                        }
                    }
                }
                else {
                    ViewError(_('Cannot add').": $ip\n$output[0]");
                }
            }
            else {
                ViewError(_('Pfctl output does not match').": $ip\n$output[0]");
            }
        }
        else {
            ViewError(_('White and black list entries should not be identical').": $ip");
        }
        return FALSE;
    }
Snortips::UnblockAll ()
Unblock all.
Definition at line 272 of file snortips.php.
References Model::RunShellCommand().
Referenced by Snortips().
    {
        return $this->RunShellCommand('/bin/kill -USR2 $(/bin/cat /var/run/snortips.pid)');
    }
Snortips::UnblockIPs ($ ips)
Unblock IPs.
Definition at line 279 of file snortips.php.
References Model::RunShellCommand().
Referenced by Snortips().
    {
        $ips= unserialize($ips);
        $contents= array();
        foreach ($ips as $ip) {
            $contents[]= "U $ip\n";
        }
        // file_put_contents() accepts array as data
        file_put_contents($this->sigMsgFile, $contents, LOCK_EX);
        return $this->RunShellCommand('/bin/kill -USR1 $(/bin/cat /var/run/snortips.pid)');
    }
Snortips::BlockIP ($ ip, $ time = '')
Unblock IPs.
Definition at line 293 of file snortips.php.
References Model::RunShellCommand().
Referenced by Snortips().
    {
        file_put_contents($this->sigMsgFile, rtrim("B $ip $time"), LOCK_EX);
        return $this->RunShellCommand('/bin/kill -USR1 $(/bin/cat /var/run/snortips.pid)');
    }
Snortips::GetListIPs ($ list)
Provides a list of IPs.
Definition at line 301 of file snortips.php.
References $Re_Ip, $Re_Net, and Model::SearchFileAll().
Referenced by Snortips().
    {
        global $Re_Ip, $Re_Net;
        return $this->SearchFileAll($this->LISTS[$list], "/^\h*($Re_Ip|$Re_Net)\h*$/m");
    }
Snortips::GetKeywords ()
Get keywords.
Definition at line 310 of file snortips.php.
References Model::SearchFileAll().
Referenced by Snortips().
    {
        return $this->SearchFileAll($this->ConfFile, "/^\h*Keyword\h+\"(.*)\"\h*$/m");
    }
Snortips::AddKeyword ($ keyword)
Add a keyword.
Definition at line 317 of file snortips.php.
References Model::AppendToFile(), and DelKeyword().
Referenced by Snortips().
    {
        $this->DelKeyword($keyword);
        return $this->AppendToFile($this->ConfFile, "Keyword \"$keyword\"");
    }
Snortips::DelKeyword ($ keyword)
Delete a keyword.
Definition at line 325 of file snortips.php.
References Escape(), and Model::ReplaceRegexp().
Referenced by AddKeyword(), and Snortips().
    {
        $keyword= Escape($keyword, '/');
        return $this->ReplaceRegexp($this->ConfFile, "/^(\h*Keyword\h+\"$keyword\"\s*)/m", '');
    }
Snortips::ParseLogLine ($ logline, &$ cols)
Parses snortips IPS logs.
Parameters:
[in] $logline Log line to parse.
[out] $cols Parser output, parsed fields.
Reimplemented from Model.
Definition at line 336 of file snortips.php.
References $Re_Ip, $Re_Net, and Model::ParseSyslogLine().
    {
        global $Re_Ip, $Re_Net;
        if ($this->ParseSyslogLine($logline, $cols)) {
            // Unblocking host 10.0.1.13
            $re= "/^Unblocking host ($Re_Ip|$Re_Net)$/";
            if (preg_match($re, $cols['Log'], $match)) {
                $cols['Unblocking']= $match[1];
            }
            else {
                // Blocking host $host as blacklisted
                $re= "/^Blocking host ($Re_Ip|$Re_Net) as blacklisted$/";
                if (preg_match($re, $cols['Log'], $match)) {
                    $cols['Blocked']= $match[1];
                }
                else {
                    // Host $host is already blocked; blocking as blacklisted
                    $re= "/^Host ($Re_Ip|$Re_Net) is already blocked; blocking as blacklisted$/";
                    if (preg_match($re, $cols['Log'], $match)) {
                        $cols['Blocked']= $match[1];
                    }
                    else {
                        // Blocking host 11.11.11.12 for 3600 ticks
                        $re= "/^Blocking host ($Re_Ip|$Re_Net) for (\d+) ticks$/";
                        if (preg_match($re, $cols['Log'], $match)) {
                            $cols['Blocked']= $match[1];
                            $cols['BlockedTime']= $match[2];
                        }
                        else {
                            // Host 11.11.11.11 is already blocked; extending amnesty to 7200 ticks
                            $re= "/^Host ($Re_Ip|$Re_Net) is already blocked; extending block duration by (\d+) ticks$/";
                            if (preg_match($re, $cols['Log'], $match)) {
                                $cols['Extended']= $match[1];
                                $cols['ExtendedTime']= $match[2];
                            }
                            else {
                                // Soft init requested, unblocking and zeroing all
                                $re= "/^Soft init requested, unblocking and zeroing all$/";
                                if (preg_match($re, $cols['Log'], $match)) {
                                    $cols['Softinit']= $cols['Date'].' - '.substr($cols['Time'], 0, 2)._('h');
                                }
                            }
                        }
                    }
                }
            }
            return TRUE;
        }
        return FALSE;
    }
Snortips::Snortips ()
Definition at line 44 of file include.php.
References _HELPBOX2(), _HELPWINDOW(), _TITLE2(), action, ConfHelpMsg, Config, and GraphHelpMsg.
    {
        $this->LogsHelpMsg= _HELPWINDOW("Here are the definitions of a few terms used in the logs:<ul class='nomargin'><li class='nomargin'>Blocking a host means adding it to IPS pf table as blocked</li><li class='nomargin'>Unblocking means deleting a blocked host from the table</li><li class='nomargin'>Deblocking means adding a whitelisted host to the table</li><li class='nomargin'>Undeblocking means deleting a whitelisted host from the table</li></ul>
        Failure to block a host does not necessarily indicate an error; the host may be in the table already.");
        $this->GraphHelpMsg= _HELPWINDOW('SnortIPS is a perl process. These graphs display data from all perl processes.');
        $this->ConfHelpMsg= _HELPWINDOW('The IDS produces many alerts. Some alerts may be more serious than others, hence most alerts have priorities. You can configure the IPS to block only alerts at a certain priority and up. Each alert also contains log and classification text. You can add keywords to match within such text. The IP in the matching alert is blocked. If the alert does not contain an IP address, no action is taken.');
        $this->Config = array(
            'Priority' => array(
                'title' => _TITLE2('Priority'),
                'info' => _HELPBOX2('This is the priority in the alerts. Alerts at this priority and up will be used to block IPs.'),
                ),
            'BlockDuration' => array(
                'title' => _TITLE2('Block Duration'),
                'info' => _HELPBOX2('Temporary block duration in seconds on each alert.'),
                ),
            'MaxBlockDuration' => array(
                'title' => _TITLE2('Max Block Duration'),
                'info' => _HELPBOX2('Total of block extensions cannot be higher than this value.'),
                ),
        );
    }
Snortips::PrintLogLine ($ cols, $ linenum)
Displays parsed log line.
Parameters:
[in] $cols Columns parsed.
[in] $linenum Line number to print as the first column.
Definition at line 74 of file include.php.
    {
        $this->PrintLogLineClass($cols['Log']);
        PrintLogCols($linenum, $cols);
        echo '</tr>';
    }
Snortips::PrintListedIPsForm ($ list, $ title, $ helpmsg)
Displays white or black listed IPs form.
Parameters:
[in] $list string Name: white or black list
[in] $title string Title to display
[in] $helpmsg string Help string
Attention:
The first invisible Add button is identical to the second to make Add the default form action, so that we save 3 html lines.
Definition at line 88 of file include.php.
References $Row, action, maxlength, method, and PrintHelpBox().
    {
        global $Row;
        $class= $Row++ % 2 == 0 ? 'evenline' : 'oddline';
        ?>
        <tr class="<?php echo $class ?>">
            <td class="title">
                <?php echo $title.':' ?>
            </td>
            <td>
                <?php
                $cmd= $list == 'whitelist' ? 'GetAllowedIps' : 'GetRestrictedIps';
                $this->Controller($ips, $cmd);
                ?>
                <form action="<?php echo $_SERVER['PHP_SELF'] ?>" method="post">
                    <input style="display:none;" type="submit" name="Add" value="<?php echo _CONTROL('Add') ?>"/>
                    <select name="IPs[]" multiple style="width: 200px; height: 100px;">
                        <?php
                        foreach ($ips as $ip) {
                            ?>
                            <option value="<?php echo $ip ?>"><?php echo $ip ?></option>
                            <?php
                        }
                        ?>
                    </select>
                    <input type="submit" name="Delete" value="<?php echo _CONTROL('Delete') ?>"/><br />
                    <input type="text" name="IPToAdd" style="width: 200px;" maxlength="18"/>
                    <input type="submit" name="Add" value="<?php echo _CONTROL('Add') ?>"/>
                    <input type="hidden" name="List" value="<?php echo $list ?>" />
                </form>
            </td>
            <td class="none">
                <?php
                PrintHelpBox($helpmsg);
                ?>
            </td>
        </tr>
        <?php
    }
Snortips::PrintBlockedIPsForm ()
Displays a list of blocked, blacklisted, or whitelisted IPs.
Also allows the user to add or delete blocked IPs.
Todo:
Do not run this command if SnortIPS is not running
Only admin can delete/add hosts
Only admin can delete/add hosts
Only admin can delete/add hosts
Definition at line 135 of file include.php.
References $_SESSION, $ADMIN, _TITLE(), _TITLE2(), action, GetInfo(), maxlength, and method.
    {
        global $ADMIN;
        ?>
        <td>
            <?php
            if ($this->Controller($output, 'GetInfo')) {
                $info= unserialize($output[0]);
                $blocked= count($info['Blocked']);
                $whitelisted= count($info['Whitelisted']);
                $blacklisted= count($info['Blacklisted']);
                $managed= $whitelisted + $blocked + $blacklisted;
                echo $managed.' '._TITLE2('managed').': '.$whitelisted.' '._TITLE2('whitelisted').', '.$blocked.' '._TITLE2('blocked').', '.$blacklisted.' '._TITLE2('blacklisted');
                ?>
                <table id="ipsmanaged">
                    <form action="<?php echo $_SERVER['PHP_SELF'] ?>" method="post">
                        <tr>
                            <th><?php echo _TITLE2('Host') ?></th>
                            <th><?php echo _TITLE2('Time to expire (secs)') ?></th>
                        </tr>
                        <?php
                        foreach ($info['Whitelisted'] as $host) {
                            ?>
                            <tr class="whitelisted">
                                <td>
                                    <?php echo $host ?>
                                </td>
                                <td>
                                    <?php echo _TITLE2('Whitelisted') ?>
                                </td>
                            </tr>
                            <?php
                        }
                        foreach ($info['Blacklisted'] as $host) {
                            ?>
                            <tr class="blacklisted">
                                <td>
                                    <?php echo $host ?>
                                </td>
                                <td>
                                    <?php echo _TITLE2('Blacklisted') ?>
                                </td>
                            </tr>
                            <?php
                        }
                        foreach ($info['Blocked'] as $host => $time) {
                            ?>
                            <tr class="blocked">
                                <td>
                                    <?php
                                    if (in_array($_SESSION['USER'], $ADMIN)) {
                                        ?>
                                        <input name="ItemsToDelete[]" type="checkbox" value="<?php echo $host ?>"/><?php echo $host ?>
                                        <?php
                                    }
                                    else {
                                        ?>
                                        <?php echo $host ?>
                                        <?php
                                    }
                                    ?>
                                </td>
                                <td>
                                    <?php echo $time ?>
                                </td>
                            </tr>
                            <?php
                        }
                        if (in_array($_SESSION['USER'], $ADMIN)) {
                            ?>
                            <tr>
                                <td>
                                    <input type="submit" name="Unblock" value="<?php echo _CONTROL('Unblock') ?>"/><br />
                                    <?php echo _TITLE2('Unblock selected') ?>
                                </td>
                                <td>
                                    <input type="submit" name="UnblockAll" value="<?php echo _CONTROL('Unblock All') ?>"/><br />
                                    <?php echo _TITLE2('Unblock all blocked entries') ?>
                                </td>
                            </tr>
                            <?php
                        }
                        ?>
                    </form>
                </table>
                <?php
                if (in_array($_SESSION['USER'], $ADMIN)) {
                    ?>
                    <br />
                    <form action="<?php echo $_SERVER['PHP_SELF'] ?>" method="post">
                        <?php echo _TITLE2('IP or Net').':' ?>
                        <input type="text" name="ItemToAdd" style="width: 100px;" maxlength="20"/>
                        <?php echo _TITLE2('Time to expire').':' ?>
                        <input type="text" name="TimeToAdd" style="width: 100px;" maxlength="20"/>
                        <?php echo _TITLE('secs') ?>
                        <input type="submit" name="Block" value="<?php echo _CONTROL('Block') ?>" />
                    </form>
                    <?php
                }
            }
            ?>
        </td>
        <?php
    }
Member Data Documentation
Snortips::$Name = 'snortips'
Reimplemented from Model.
Definition at line 40 of file snortips.php.
Snortips::$User = 'root'
Reimplemented from Model.
Definition at line 41 of file snortips.php.
Snortips::$NVPS = '\h'
Reimplemented from Model.
Definition at line 45 of file snortips.php.
Snortips::$ConfFile = '/etc/snort/snortips.conf'
Reimplemented from Model.
Definition at line 46 of file snortips.php.
Snortips::$LogFile = '/var/log/snortips.log'
Reimplemented from Model.
Definition at line 47 of file snortips.php.
Snortips::$VersionCmd = 'unset LC_ALL; unset LANG; /usr/local/sbin/snortips -V'
Reimplemented from Model.
Definition at line 49 of file snortips.php.
Snortips::$PidFile = '/var/run/snortips.pid'
Reimplemented from Model.
Definition at line 51 of file snortips.php.
Snortips::$Model = 'snortips'
Reimplemented from View.
Definition at line 41 of file include.php.
Snortips::$Layout = 'snortips'
Reimplemented from View.
Definition at line 42 of file include.php.
The documentation for this class was generated from the following files:
Model/snortips.php
View/snortips/include.php