ComixWall ISG Administration Interface: View/imspector/conf.acl.php File Reference
View » imspector
conf.acl.php File Reference
Functions
PrintAclForm ()
Displays Access Control List.
Variables
$CustomFunc = 'PrintAclForm'
Function Documentation
PrintAclForm ()
Displays Access Control List.
Definition at line 38 of file conf.acl.php.
References $Class, $selected, $View, _HELPBOX2(), _TITLE2(), action, example, maxlength, method, and PrintHelpBox().
{
    global $View, $Class;
    ?>
    <tr class="<?php echo $Class ?>">
        <td class="title">
            <?php echo _TITLE2('ACL').':' ?>
        </td>
        <td>
            <form action="<?php echo $_SERVER['PHP_SELF'] ?>" method="post">
                <input style="display:none;" type="submit" name="Add" value="<?php echo _CONTROL('Add') ?>"/>
                <select name="SelectedAcls[]" multiple style="width: 300px; height: 200px;">
                    <?php
                    if ($View->Controller($output, 'GetAcl')) {
                        foreach ($output as $acl) {
                            if ($_POST['SelectedAcls'] && in_array($acl, $_POST['SelectedAcls'])) {
                                $selected= ' selected';
                            }
                            else {
                                $selected= '';
                            }
                            ?>
                            <option value="<?php echo $acl ?>" title="<?php echo $acl ?>"<?php echo $selected ?>><?php echo $acl ?></option>
                            <?php
                        }
                    }
                    ?>
                </select>
                <br />
                <input type="submit" name="Delete" value="<?php echo _CONTROL('Delete') ?>"/>
                <input type="submit" name="MoveUp" value="<?php echo _CONTROL('Move Up') ?>"/>
                <input type="submit" name="MoveDown" value="<?php echo _CONTROL('Move Down') ?>"/><br />
                <br />
                <select name="Action" style="width: 100px;">
                    <option value="allow">allow</option>
                    <option value="deny">deny</option>
                </select>
                <input type="text" name="List" style="width: 200px;" maxlength="200"/>
                <input type="submit" name="Add" value="<?php echo _CONTROL('Add') ?>"/><br />
            </form>
        </td>
        <td class="none">
            <?php
            PrintHelpBox(_HELPBOX2('List format is:
allow|deny localid|all [groupchat|remoteid1 ... remoteidN]
Order of the access rules is important. For example, if deny all is the first rule, all access is effectively blocked, so make sure the deny all rule, if any, is at the bottom.'));
            ?>
        </td>
    </tr>
    <?php
}
Variable Documentation
$CustomFunc = 'PrintAclForm'
Definition at line 113 of file conf.acl.php.