ComixWall ISG Administration Interface: View/clamav/include.freshclam.php File Reference
View » clamav
include.freshclam.php File Reference
Classes
class Freshclam
Functions
PrintDatabaseMirrorsForm ()
Prints database mirrors.
Variables
$View = new Freshclam()
Function Documentation
PrintDatabaseMirrorsForm ()
Prints database mirrors.
Definition at line 111 of file include.freshclam.php.
References $Class, $View, _HELPBOX2(), _TITLE2(), action, maxlength, method, and PrintHelpBox().
{
    global $View, $Class;
    ?>
    <tr class="<?php echo $Class ?>">
        <td class="title">
            <?php echo _TITLE2('Database Mirrors').':' ?>
        </td>
        <td>
            <form action="<?php echo $_SERVER['PHP_SELF'] ?>" method="post">
                <input style="display:none;" type="submit" name="Add" value="<?php echo _CONTROL('Add') ?>"/>
                <select name="Mirrors[]" multiple style="width: 200px; height: 50px;">
                    <?php
                    if ($View->Controller($output, 'GetMirrors')) {
                        foreach ($output as $mirror) {
                            ?>
                            <option value="<?php echo $mirror ?>"><?php echo $mirror ?></option>
                            <?php
                        }
                    }
                    ?>
                </select>
                <input type="submit" name="Delete" value="<?php echo _CONTROL('Delete') ?>"/><br />
                <input type="text" name="MirrorToAdd" style="width: 200px;" maxlength="21"/>
                <input type="submit" name="Add" value="<?php echo _CONTROL('Add') ?>"/>
            </form>
        </td>
        <td class="none">
            <?php
            PrintHelpBox(_HELPBOX2("Here you can enter db.XY.clamav.net for a mirror close to you. Replace XY with your country code. See http://www.iana.org/cctld/cctld-whois.htm for the full list.
Not shown in this list is database.clamav.net, which is a round-robin record and points to ClamAV's most reliable mirrors. It is used as a fall back in case db.XY.clamav.net is not working."));
            ?>
        </td>
    </tr>
    <?php
}
Variable Documentation
$View = new Freshclam()
Definition at line 107 of file include.freshclam.php.