ComixWall ISG Administration Interface: View/lib/conf.php File Reference
View » lib
conf.php File Reference
Main configuration file included by all configuration pages.
Functions
PrintNVPForm ($values)
Displays an NVP configuration form, usually a textbox and buttons.
PrintReloadConfigForm ()
Variables
$Group = $_SESSION[$View->Model]['Group'] ? $_SESSION[$View->Model]['Group'] : 0
$Value = preg_replace('/\\\\"/', '"', $Value)
$Row = 1
Detailed Description
Main configuration file included by all configuration pages.
Definition in file conf.php.
Function Documentation
PrintNVPForm ($ values)
Displays an NVP configuration form, usually a textbox and buttons.
This function is used in all configuration pages to modify module parameters. Params can be enabled/disabled, and values can be changed.
Parameters:
[in] $values array All of the NVPs in $Config struct at once
Todo:
Is there a way to get browser's current font width to use here?
Definition at line 47 of file conf.php.
References $Row, $View, action, Config, maxlength, method, and PrintHelpBox().
{
    global $View, $Row;
    foreach ($values as $name => $valueconf) {
        // Model config may be different from View, View displays only this many config
        if (isset($View->Config[$name])) {
            $class= $Row++ % 2 == 0 ? 'evenline' : 'oddline';
            ?>
            <tr class="<?php echo $class ?>">
                <td class="title">
                    <?php
                    if (isset($View->Config[$name]['title'])) {
                        $title= $View->Config[$name]['title'];
                    }
                    else {
                        $title= $name;
                    }
                    echo $title.':';
                    ?>
                </td>
                <td>
                    <form action="<?php echo $_SERVER['PHP_SELF'] ?>" method="post">
                        <?php
                        define('CHAR_WIDTH', '5.75');
                        if ($valueconf['Enabled'] === TRUE) {
                            if (preg_match("|^$name=(.*)$|", $valueconf['Value'], $match)) {
                                // There are values like this: /usr/local/bin/send_sms 123456789 "VIRUS ALERT: %v"
                                $value= htmlentities($match[1], ENT_QUOTES);
                                ?>
                                <input type="text" name="ValueToChange" style="width: <?php echo strlen($value)*CHAR_WIDTH > 50 ? strlen($value)*CHAR_WIDTH : 50 ?>px;" maxlength="100" value="<?php echo $value ?>"/>
                                <input type="submit" name="Apply" value="<?php echo _CONTROL('Apply') ?>"/>
                                <?php
                            }
                            ?>
                            <input class="disablebutton" type="submit" name="Disable" value="<?php echo _CONTROL('Disable') ?>"/>
                            <?php
                        }
                        else if ($valueconf['Enabled'] === FALSE) {
                            if (preg_match("|^$name=(.*)$|", $valueconf['Value'], $match)) {
                                $value= htmlentities($match[1], ENT_QUOTES);
                                ?>
                                <input type="text" disabled name="ValueToChange" style="width: <?php echo strlen($value)*CHAR_WIDTH > 50 ? strlen($value)*CHAR_WIDTH : 50 ?>px;" maxlength="100" value="<?php echo $value ?>"/>
                                <?php
                            }
                            ?>
                            <input class="enablebutton" type="submit" name="Enable" value="<?php echo _CONTROL('Enable') ?>"/>
                            <?php
                        }
                        ?>
                        <input type="hidden" name="KeyToChange" value="<?php echo $name ?>" />
                    </form>
                </td>
                <td class="none">
                    <?php
                    if (isset($View->Config[$name]['info'])) {
                        PrintHelpBox($View->Config[$name]['info']);
                    }
                    ?>
                </td>
            </tr>
            <?php
        }
    }
}
PrintReloadConfigForm ()
Definition at line 115 of file conf.php.
References $Class, $ReloadConfig, _HELPBOX2(), _TITLE2(), action, method, and PrintHelpBox().
{
    global $ReloadConfig, $Class;
    ?>
    <tr class="<?php echo $Class ?>">
        <td class="title">
            <?php echo _TITLE2('Apply configuration').':' ?>
        </td>
        <td>
            <form action="<?php echo $_SERVER['PHP_SELF'] ?>" method="post">
                <input type="submit" name="Reload" value="<?php echo _CONTROL('Reload') ?>"/>
            </form>
        </td>
        <td class="none">
            <?php
            PrintHelpBox(_HELPBOX2('You can apply configuration changes without restarting currently running process.'));
            ?>
        </td>
    </tr>
    <?php
}
Variable Documentation
$Group = $_SESSION[$View->Model]['Group'] ? $_SESSION[$View->Model]['Group'] : 0
Definition at line 138 of file conf.php.
$Row = 1
Definition at line 180 of file conf.php.
$Value = preg_replace('/\\\\"/', '"', $Value)
Definition at line 144 of file conf.php.