ComixWall ISG Administration Interface: lib/lib.php File Reference
lib
lib.php File Reference
Project-wide common functions.
Functions
Escape ($str, $chars, $no_double_escapes=TRUE)
Escapes chars.
ViewError ($msg)
Sets or updates $ViewError with the given message.
_MENU ($str)
For classifying gettext strings into files.
_CONTROL ($str)
For classifying gettext strings into files.
_NOTICE ($str)
For classifying gettext strings into files.
_TITLE ($str)
For classifying gettext strings into files.
_STATS ($str)
For classifying gettext strings into files.
_HELPBOX ($str)
For classifying gettext strings into files.
_HELPWINDOW ($str)
For classifying gettext strings into files.
_TITLE2 ($str)
For classifying gettext strings into files.
_HELPBOX2 ($str)
For classifying gettext strings into files.
Detailed Description
Project-wide common functions.
Definition in file lib.php.
Function Documentation
_CONTROL ($ str)
For classifying gettext strings into files.
Definition at line 98 of file lib.php.
{
    return _($str);
}
_HELPBOX ($ str)
For classifying gettext strings into files.
Definition at line 122 of file lib.php.
Referenced by PrintAfterHoursForm(), PrintDateTimeForm(), PrintHostsForm(), PrintPrivIPsForm(), and PrintRestrictedIPsForm().
{
    return _($str);
}
_HELPBOX2 ($ str)
For classifying gettext strings into files.
Definition at line 140 of file lib.php.
Referenced by Apache::Apache(), Clamd::Clamd(), Freshclam::Freshclam(), Openssh::Openssh(), P3scan::P3scan(), PrintAclForm(), PrintConfSelectForm(), PrintConfStartStopForm(), PrintDatabaseMirrorsForm(), PrintDHCPInterfaceForm(), PrintDHCPOptionForm(), PrintDHCPRangeOptionForm(), Dansguardian::PrintFilterGroupForm(), PrintKeywordsForm(), PrintReloadConfigForm(), PrintSetLanguageForm(), PrintSiteCategorySearchForm(), PrintSquidIPPortForm(), Snortips::Snortips(), Spamassassin::Spamassassin(), and Squid::Squid().
{
    return _($str);
}
_HELPWINDOW ($ str)
For classifying gettext strings into files.
Definition at line 128 of file lib.php.
Referenced by Apache::Apache(), Apachelogs::Apachelogs(), Blacklists::Blacklists(), Clamd::Clamd(), Cwc::Cwc(), Cwwui::Cwwui(), Dansguardian::Dansguardian(), Dansguardianlogs::Dansguardianlogs(), Dante::Dante(), Dhcpd::Dhcpd(), Freshclam::Freshclam(), Ftpproxy::Ftpproxy(), Imspector::Imspector(), Monitoring::Monitoring(), Named::Named(), Openssh::Openssh(), Openvpn::Openvpn(), P3scan::P3scan(), Pf::Pf(), Smtpgated::Smtpgated(), Snort::Snort(), Snortalerts::Snortalerts(), Snortips::Snortips(), Spamassassin::Spamassassin(), Spamd::Spamd(), Squid::Squid(), and System::System().
{
    return _($str);
}
_MENU ($ str)
For classifying gettext strings into files.
Definition at line 92 of file lib.php.
Referenced by HTMLHeader().
{
    return _($str);
}
_NOTICE ($ str)
For classifying gettext strings into files.
Definition at line 104 of file lib.php.
Referenced by Openvpn::ConfSelectForm(), Openvpn::ConfStartStopForm(), PrintDateTimeForm(), and Dansguardian::SetSessionFilterGroup().
{
    return _($str);
}
_STATS ($ str)
For classifying gettext strings into files.
Definition at line 116 of file lib.php.
{
    return _($str);
}
_TITLE ($ str)
For classifying gettext strings into files.
Definition at line 110 of file lib.php.
Referenced by AuthHTMLFooter(), PrintAfterHoursForm(), Snortips::PrintBlockedIPsForm(), PrintDateTimeForm(), Dansguardian::PrintFilterGroupForm(), PrintHostsForm(), PrintPrivIPsForm(), PrintRestrictedIPsForm(), and PrintSiteCategorySearchForm().
{
    return _($str);
}
_TITLE2 ($ str)
For classifying gettext strings into files.
Definition at line 134 of file lib.php.
Referenced by Apache::Apache(), AuthHTMLFooter(), CheckPageActivation(), Clamd::Clamd(), Freshclam::Freshclam(), Openssh::Openssh(), P3scan::P3scan(), PrintAclForm(), PrintAfterHoursForm(), PrintBadwordsForm(), Snortips::PrintBlockedIPsForm(), PrintConfSelectForm(), PrintConfStartStopForm(), PrintDatabaseMirrorsForm(), PrintDHCPInterfaceForm(), PrintDHCPOptionForm(), PrintDHCPRangeOptionForm(), PrintFilterAuthIPForms(), PrintFilterCatForms(), PrintFilterConfForms(), PrintFilterExtMimeForm(), PrintFilterGroupIPsForms(), PrintKeywordsForm(), PrintReloadConfigForm(), PrintRulesForms(), PrintSetLanguageForm(), PrintSquidIPPortForm(), SetSubmenu(), Smtpgated::Smtpgated(), Snortips::Snortips(), Spamassassin::Spamassassin(), and Squid::Squid().
{
    return _($str);
}
Escape ($ str, $ chars, $ no_double_escapes = TRUE)
Escapes chars.
Prevents double escapes by default.
preg_quote() double escapes, thus is not suitable. It is not possible to make sure that strings contain no escapes, because this function is used over strings obtained from config files too, which we don't have any control over.
Example: $no_double_escapes as FALSE is used in the code to double escape $ char.
Parameters:
[in] $str string String to process.
[in] $chars string Chars to escape.
[in] $no_double_escapes boolean Whether to prevent double escapes.
Returns:
Escaped string.
First remove existing escapes
Definition at line 57 of file lib.php.
Referenced by Imspector::DelAcl(), Imspector::DelBadword(), Dansguardian::DelExt(), Dansguardian::DelIp(), Dansguardian::DelIpFilterGrp(), Squid::DelIpPort(), Snortips::DelKeyword(), Freshclam::DelMirror(), Dansguardian::DelSiteList(), Dansguardian::DelUrlList(), Dansguardian::DisableExt(), Dansguardian::EnableExt(), Snortips::GetIP(), Dansguardian::GetSiteList(), Dansguardian::GetUrlList(), Imspector::MoveAclDown(), Imspector::MoveAclUp(), Snort::MoveRuleDown(), Snort::MoveRuleUp(), and Model::SetNVP().
{
    if ($chars !== '') {
        $chars_array= str_split($chars);
        foreach ($chars_array as $char) {
            $esc_char= preg_quote($char, '/');
            if ($no_double_escapes) {
                $str= preg_replace("/\\\\$esc_char/", $char, $str);
            }
            $str= preg_replace("/$esc_char/", "\\\\$char", $str);
        }
    }
    return $str;
}
ViewError ($ msg)
Sets or updates $ViewError with the given message.
Error strings are accumulated in global $ViewError and returned to View.
Parameters:
[in] $msg string Error message.
Definition at line 79 of file lib.php.
Referenced by Snortips::AddIPToList(), System::AutoConfig(), Pf::CheckAfterHoursOverlap(), Dansguardian::CreateNewGroup(), Snortips::DelIPFromList(), Freshclam::DelMirror(), Pf::GetCrontab(), System::GetDynamicGateway(), Dansguardian::GetGroupFile(), Dansguardian::GetIpgroupsFilePath(), Dansguardian::GetListFilePath(), Pf::GetStateList(), System::InitGraphs(), Pf::InstallNewCrontab(), Openvpn::Restart(), Model::SetConfValue(), System::SetDateTime(), System::SetIf(), Snort::Start(), Pmacct::Start(), Snort::Stop(), and ValidateArgs().
{
    global $ViewError;
    if ($ViewError === '') {
        $ViewError= $msg;
    }
    else {
        $ViewError.= "\n".$msg;
    }
}