ComixWall ISG Administration Interface: View/pf/logsreport.php File Reference
View » pf
logsreport.php File Reference
Functions
parse_log ($log)
log_stats ($log_a)
get_host_by_address ($ip, $resolve=false)
get_service_by_port ($port, $proto="tcp", $resolve=false)
Variables
$pfhost = $_SESSION['pfhost']['connect']
$logs = parse_log(implode("\n", $Output))
$stats = log_stats($logs)
print $_GET ['reload']
$_SESSION ['dns_cache'] = $dns_cache
Function Documentation
get_host_by_address ($ ip, $ resolve = false)
Definition at line 121 of file logsreport.php.
{
  global $dns_cache;
  if ($resolve) {
    if (!isset($dns_cache["$ip"])) {
      $dns_cache["$ip"] = gethostbyaddr($ip);
    }
    return $dns_cache[$ip];
  } else {
    return $ip;
  }
}
get_service_by_port ($ port, $ proto = "tcp", $ resolve = false)
Definition at line 136 of file logsreport.php.
{
  global $service_cache;
  if ($resolve) {
    if (!isset($service_cache["$proto"]["$port"])) {
      $service = getservbyport($port, $proto);
      if ($service) {
        $service_cache["$proto"]["$port"] = $service;
      } else {
        $service_cache["$proto"]["$port"] = $port;
      }
    }
    return $service_cache["$proto"]["$port"];
  } else {
    return $port;
  }
}
log_stats ($ log_a)
Definition at line 87 of file logsreport.php.
References $stats.
{
  $stats = array();
  foreach ($log_a as $log_entry) {
    if ($log_entry['proto'] == "tcp" || $log_entry['proto'] == "udp") {
      $stats['sourceport'][$log_entry['sourceport']] += 1;
      $stats['destinationport'][$log_entry['destinationport']] += 1;
    }
    $stats['destination'][$log_entry['destination']] += 1;
    $stats['source'][$log_entry['source']] += 1;
    $stats['proto'][$log_entry['proto']] += 1;
    $stats['type'][$log_entry['type']] += 1;
  }
  if (count($stats['sourceport'])) {
    arsort($stats['sourceport']);
  }
  if (count($stats['destinationport'])) {
    arsort($stats['destinationport']);
  }
  if (count($stats['destination'])) {
    arsort($stats['destination']);
  }
  if (count($stats['source'])) {
    arsort($stats['source']);
  }
  if (count($stats['proto'])) {
    arsort($stats['proto']);
  }
  if (count($stats['type'])) {
    arsort($stats['type']);
  }
  return $stats;
}
parse_log ($ log)
Definition at line 38 of file logsreport.php.
{
  $log_a = array();
  foreach (preg_split("/\n/", $log, '-1', PREG_SPLIT_NO_EMPTY) as $rule_line) {
    $items_a = preg_split("/\s+/", $rule_line, '-1', PREG_SPLIT_NO_EMPTY);
    $data = array();
    $data['month'] = $items_a[0];
    $data['day'] = $items_a[1];
//     $data['time'] = $items_a[2];
    $fulltime= explode('.', $items_a[2]);
    $data['time'] = $fulltime[0];
    preg_match('/[\d]+/', $items_a[4], $match);
    $data['rule'] = $match[0];
    $data['type'] = $items_a[5];
    $data['direction'] = $items_a[6];
    $data['interface'] = substr($items_a[8], 0, -1);
    if (preg_match('/[A-Z.]/', substr($items_a[12], 0, 1))) {
      $data['proto'] = "tcp";
      $data['flags'] = $items_a[12];
    } else if ($items_a[12] == "udp" || preg_match('/[0-9]/', substr($items_a[12], 0, 1))) {
      $data['proto'] = "udp";
    } else {
      $data['proto'] = substr($items_a[12], 0, -1);
    }
    if ($data['proto'] == "igmp-") {
      $data['proto'] = 'igmp';
    }
    if ($data['proto'] == "tcp" || $data['proto'] == "udp" || $data['proto'] == "v") {
      $data['source'] = substr($items_a[9], 0, strrpos($items_a[9], "."));
      $data['sourceport'] = substr($items_a[9], strrpos($items_a[9], ".") + 1);
      $data['destination'] = substr($items_a[11], 0, strrpos($items_a[11], "."));
      $data['destinationport'] = substr($items_a[11], strrpos($items_a[11], ".") + 1, -1);
    } else {
      $data['source'] = $items_a[9];
      $data['destination'] = substr($items_a[11], 0, -1);
    }
    if ($data['proto'] == "icmp") {
      $data['flags'] = $items_a[13]. " ". $items_a[14];
    }
    $log_a[] = $data;
  }
  return array_reverse($log_a);
}
Variable Documentation
print $_GET['reload']
Definition at line 350 of file logsreport.php.
Referenced by AuthHTMLHeader(), reload(), and SetSubmenu().
$_SESSION['dns_cache'] = $dns_cache
Definition at line 413 of file logsreport.php.
$logs = parse_log(implode("\n", $Output))
Definition at line 171 of file logsreport.php.
Referenced by Spamassassin::GetLiveLogs(), Pf::GetLiveLogs(), Openssh::GetLiveLogs(), Spamassassin::GetLogs(), Pf::GetLogs(), and Openssh::GetLogs().
$pfhost = $_SESSION['pfhost']['connect']
Definition at line 167 of file logsreport.php.
$stats = log_stats($logs)
Definition at line 172 of file logsreport.php.
Referenced by Model::CollectDayStats(), Model::GetAllStats(), Model::GetSavedStats(), Model::GetStats(), Model::IncStats(), log_stats(), Model::SaveStats(), and Model::UpdateStats().