ComixWall ISG Administration Interface: View/openvpn/info.php File Reference
View » openvpn
info.php File Reference
Functions
PrintConfStartStopForm ()
Wrapper for ConfStartStopForm().
Function Documentation
PrintConfStartStopForm ()
Wrapper for ConfStartStopForm().
Only admin can start/stop the processes
Definition at line 40 of file info.php.
References $_SESSION, $ADMIN, $View, _HELPBOX2(), _TITLE2(), and PrintHelpBox().
{
    global $View, $ADMIN;
    if (in_array($_SESSION['USER'], $ADMIN)) {
        ?>
        <table id="ifselect">
            <tr>
                <td class="title">
                    <?php echo _TITLE2('Configuration').':' ?>
                </td>
                <td>
                    <?php
                    $View->ConfStartStopForm();
                    ?>
                </td>
                <td class="help">
                    <?php PrintHelpBox(_HELPBOX2('Here you should select configuration file(s) to start or stop the process with. Instance with the selected configuration is restarted if it is already running. Only the files with .conf extention are displayed.')) ?>
                </td>
            </tr>
        </table>
        <?php
    }
}