ComixWall ISG Administration Interface: View/openvpn/conf.php File Reference
View » openvpn
conf.php File Reference
Functions
PrintConfSelectForm ($module, $helpmsg= '')
Wrapper for ConfSelectForm().
Variables
$CustomFunc = 'PrintConfSelectForm'
$CustomFuncParam = $View->Model
Function Documentation
PrintConfSelectForm ($ module, $ helpmsg = '')
Wrapper for ConfSelectForm().
Parameters:
[in] $module string Module name passed to ConfSelectForm()
[in] $helpmsg string Extra help msg to append.
Definition at line 43 of file conf.php.
References $Class, $View, _HELPBOX2(), _TITLE2(), and PrintHelpBox().
{
    global $View, $Class;
    ?>
    <tr class="<?php echo $Class ?>">
        <td class="title">
            <?php echo _TITLE2('Configuration').':' ?>
        </td>
        <td>
            <?php
            $View->ConfSelectForm($module);
            ?>
        </td>
        <td class="none">
            <?php PrintHelpBox(_HELPBOX2('Here you can select the configuration file to view or modify. Also, you can delete the selected configuration file or copy it under another name. Only file names with .conf extention are displayed.').' '.$helpmsg) ?>
        </td>
    </tr>
    <?php
}
Variable Documentation
$CustomFunc = 'PrintConfSelectForm'
Definition at line 93 of file conf.php.
$CustomFuncParam = $View->Model
Definition at line 94 of file conf.php.