ComixWall ISG Administration Interface: View/p3scan/conf.php File Reference
View » p3scan
conf.php File Reference
Functions
PrintSetLanguageForm ()
Displays P3scan language file selector.
Variables
$CustomFunc = 'PrintSetLanguageForm'
Function Documentation
PrintSetLanguageForm ()
Displays P3scan language file selector.
Definition at line 40 of file conf.php.
References $Class, $selected, $View, _HELPBOX2(), _TITLE2(), action, method, and PrintHelpBox().
{
    global $View, $Class;
    $View->Controller($languages, 'GetLocales');
    if ($View->Controller($output, 'GetCurrentLocale')) {
        $currentlang= $output[0];
    }
    ?>
    <tr class="<?php echo $Class ?>">
        <td class="title">
            <?php echo _TITLE2('Report language').':' ?>
        </td>
        <td>
            <form action="<?php echo $_SERVER['PHP_SELF'] ?>" method="post">
                <select name="Language">
                    <?php
                    foreach ($languages as $lang) {
                        $selected= $currentlang === $lang ? 'selected' : '';
                        ?>
                        <option <?php echo $selected ?> value="<?php echo $lang ?>"><?php echo $lang ?></option>
                        <?php
                    }
                    ?>
                </select>
                <input type="submit" name="ApplyLanguage" value="<?php echo _CONTROL('Apply') ?>"/>
            </form>
        </td>
        <td class="none">
            <?php PrintHelpBox(_HELPBOX2('Here you can set the report language in emails sent to client, instead of infected e-mails.')) ?>
        </td>
    </tr>
    <?php
}
Variable Documentation
$CustomFunc = 'PrintSetLanguageForm'
Definition at line 79 of file conf.php.