ComixWall ISG Administration Interface: View/pf/graphs.php File Reference
View » pf
graphs.php File Reference
Variables
$Submenu = SetSubmenu('ifs')
break
case __pad0__
$View GraphHelpMsg = _HELPWINDOW('This graph shows the data transfer rate of packet filter. The transfer is between interfaces.')
case __pad1__
case __pad2__
case __pad3__
case host usage graphs are for
the last hour
case host usage graphs are for
the last last daily
case host usage graphs are for
the last last weekly
Variable Documentation
$Submenu = SetSubmenu('ifs')
Definition at line 38 of file graphs.php.
case __pad0__
Definition at line 47 of file graphs.php.
case __pad1__
Definition at line 52 of file graphs.php.
case __pad2__
Definition at line 57 of file graphs.php.
case __pad3__
Definition at line 62 of file graphs.php.
break
Definition at line 44 of file graphs.php.
case host usage graphs are for the last last daily
Definition at line 62 of file graphs.php.
View GraphHelpMsg = _HELPWINDOW('This graph shows the data transfer rate of packet filter. The transfer is between interfaces.')
Definition at line 48 of file graphs.php.
Referenced by Clamd::Clamd(), Snortips::Snortips(), and Spamassassin::Spamassassin().
case host usage graphs are for the last last hour
Definition at line 62 of file graphs.php.
Referenced by PrintDateTimeForm().
case host usage graphs are for the last last weekly
Definition at line 62 of file graphs.php.