ComixWall ISG Administration Interface: View/pf/conf.php File Reference
View » pf
conf.php File Reference
Basic PF configuration, pf enable/disable and After Hours settings.
Functions
PrintAfterHoursForm ()
Prints After Hour modification form.
PrintPrivIPsForm ()
Displays privileged IPs form.
PrintRestrictedIPsForm ()
Displays restricted IPs form.
Variables
$Row = 1
Detailed Description
Basic PF configuration, pf enable/disable and After Hours settings.
Definition in file conf.php.
Function Documentation
PrintAfterHoursForm ()
Prints After Hour modification form.
Sample After Hour lines in cron file:
30 19 * * 1,2,3,4,5,6 /sbin/pfctl -a AfterHours -f /etc/pf.conf.afterhours 0 9 * * 1,2,3,4,5,6 /sbin/pfctl -a AfterHours -Fr * * * * 7 /sbin/pfctl -a AfterHours -f /etc/pf.conf.afterhours
Warning:
Sunday is also 0, but should not be used in After Hours lines.
Definition at line 50 of file conf.php.
References $IMG_PATH, $Row, $View, _HELPBOX(), _TITLE(), _TITLE2(), action, example, maxlength, method, and PrintHelpBox().
{
    global $View, $IMG_PATH, $Row;
    $weekdays= array(
        //0 => _('Sun'),
        1 => _TITLE2('Mon'),
        2 => _TITLE2('Tue'),
        3 => _TITLE2('Wed'),
        4 => _TITLE2('Thu'),
        5 => _TITLE2('Fri'),
        6 => _TITLE2('Sat'),
        7 => _TITLE2('Sun'),
        );
    if ($View->Controller($output, 'GetAfterHours')) {
        list($businessdaysdisabled, $holidaysdisabled, $flushdisabled,
            $startmin, $starthour, $endmin, $endhour,
            $businessdays, $holidays, $flushdays)= unserialize($output[0]);
    }
    if ($View->Controller($output, 'GetAfterHoursPfRules')) {
        if (count($output) > 0) {
            $status= _TITLE('enabled');
            $button= 'Disable';
            $imgfile= 'run.png';
        }
        else {
            $status= _TITLE('disabled');
            $button= 'Enable';
            $imgfile= 'stop.png';
        }
    }
    $class= $Row++ % 2 == 0 ? 'evenline' : 'oddline';
    ?>
    <tr class="<?php echo $class ?>">
        <td class="title">
            <img src="<?php echo $IMG_PATH.$imgfile ?>" name="AfterHours" alt="AfterHours" border="0" align="absmiddle">
            <?php echo _TITLE2('After hours').' '.$status.':' ?>
        </td>
        <td>
            <form action="<?php echo $_SERVER['PHP_SELF'] ?>" method="post">
                <input type="submit" name="<?php echo $button ?>" value="<?php echo _($button) ?>"/>
            </form>
        </td>
        <td class="none">
            <?php PrintHelpBox(_HELPBOX('This button allows you to <b>manually</b> enable or disable after hours rules. Note that the rules are activated or deactivated immediately, irrespective of the after hours definitions below. For example, you can use this button to shutdown after hours rules in case of an emergency.')) ?>
        </td>
    </tr>
    <?php
    $class= $Row++ % 2 == 0 ? 'evenline' : 'oddline';
    ?>
    <form action="<?php echo $_SERVER['PHP_SELF'] ?>" method="post">
        <tr class="<?php echo $class ?>">
            <td class="titlegrouptop">
                <?php
                echo _TITLE('Business Days').':';
                ?>
            </td>
            <td>
                <table>
                    <tr>
                        <td class="pfafterhours">
                            <?php
                            foreach ($weekdays as $num => $day) {
                                $checked= in_array($num, $businessdays) ? 'checked' : '';
                                $checked= $businessdaysdisabled ? $checked.' disabled' : $checked;
                                ?>
                                <label><input name="BusinessDays[]" type="checkbox" <?php echo $checked ?> value="<?php echo $num ?>"><?php echo _($day) ?></label>
                                <?php
                            }
                            ?>
                        </td>
                        <td class="pfafterhoursbutton">
                            <?php
                            $button= $businessdaysdisabled ? 'Enable' : 'Disable';
                            ?>
                            <input type="submit" name="<?php echo $button.'BusinessDays' ?>" value="<?php echo _($button) ?>"/>
                        </td>
                    </tr>
                </table>
            </td>
            <td class="none" rowspan="3">
                <?php PrintHelpBox(_HELPBOX('Definition of after hours can be set here. If you modify any of these definitions, you should click the Apply button.
Note that when you enable Business Days or Holidays, the related rules will become active according to these definitions. If you don\'t want to use the after hours feature of ComixWall, make sure these definitions are disabled.
Business hours configuration is meaningful only for business days.')) ?>
            </td>
        </tr>
        <tr class="<?php echo $class ?>">
            <td class="titlegroupmiddle">
                <?php
                echo _TITLE('Holidays').':';
                ?>
            </td>
            <td>
                <table>
                    <tr>
                        <td class="pfafterhours">
                            <?php
                            foreach ($weekdays as $num => $day) {
                                $checked= in_array($num, $holidays) ? 'checked' : '';
                                $checked= $holidaysdisabled ? $checked.' disabled' : $checked;
                                ?>
                                <label><input name="Holidays[]" type="checkbox" <?php echo $checked ?> value="<?php echo $num ?>"><?php echo _($day) ?></label>
                                <?php
                            }
                            ?>
                        </td>
                        <td class="pfafterhoursbutton">
                            <?php
                            $button= $holidaysdisabled ? 'Enable' : 'Disable';
                            ?>
                            <input type="submit" name="<?php echo $button.'Holidays' ?>" value="<?php echo _($button) ?>"/>
                        </td>
                    </tr>
                </table>
            </td>
            <td class="none">
            </td>
        </tr>
        <tr class="<?php echo $class ?>">
            <td class="titlegroupbottom">
                <?php
                echo _TITLE('Business Hours').':';
                ?>
            </td>
            <td>
                <table>
                    <tr>
                        <td class="pfafterhours">
                            <?php
                            $disabled= $businessdaysdisabled ? 'disabled' : '';
                            echo _TITLE('From').':';
                            ?>
                            <input type="text" name="StartHour" <?php echo $disabled ?> style="width: 20px;" maxlength="2" value="<?php echo $starthour ?>" />
                            :
                            <input type="text" name="StartMin" <?php echo $disabled ?> style="width: 20px;" maxlength="2" value="<?php echo $startmin ?>" />
                            -
                            <?php
                            $disabled= $flushdisabled ? 'disabled' : '';
                            echo _TITLE('To').':';
                            ?>
                            <input type="text" name="EndHour" <?php echo $disabled ?> style="width: 20px;" maxlength="2" value="<?php echo $endhour ?>" />
                            :
                            <input type="text" name="EndMin" <?php echo $disabled ?> style="width: 20px;" maxlength="2" value="<?php echo $endmin ?>" />
                        </td>
                        <td class="pfafterhoursbutton">
                            <input type="submit" name="Apply" value="<?php echo _CONTROL('Apply') ?>"/>
                        </td>
                    </tr>
                </table>
            </td>
            <td class="none">
            </td>
        </tr>
    </form>
    <?php
}
PrintPrivIPsForm ()
Displays privileged IPs form.
This list is the !-prefixed IPs in pf.restrictedips.
Definition at line 217 of file conf.php.
References $Row, $View, _HELPBOX(), _TITLE(), action, maxlength, method, and PrintHelpBox().
{
    global $View, $Row;
    $class= $Row++ % 2 == 0 ? 'evenline' : 'oddline';
    ?>
    <tr class="<?php echo $class ?>">
        <td class="title">
            <?php echo _TITLE('Privileged IPs').':' ?>
        </td>
        <td>
            <form action="<?php echo $_SERVER['PHP_SELF'] ?>" method="post">
                <input style="display:none;" type="submit" name="Add" value="<?php echo _CONTROL('Add') ?>"/>
                <select name="PrivilegedIPs[]" multiple style="width: 200px; height: 100px;">
                    <?php
                    if ($View->Controller($ips, 'GetAllowedIps')) {
                        foreach ($ips as $ip) {
                            ?>
                            <option value="<?php echo $ip ?>"><?php echo $ip ?></option>
                            <?php
                        }
                    }
                    ?>
                </select>
                <input type="submit" name="Delete" value="<?php echo _CONTROL('Delete') ?>"/><br />
                <input type="text" name="PrivilegedIPToAdd" style="width: 200px;" maxlength="18"/>
                <input type="submit" name="Add" value="<?php echo _CONTROL('Add') ?>"/>
            </form>
        </td>
        <td class="none">
            <?php
            PrintHelpBox(_HELPBOX('Privileged IPs have access to more services than other IPs, such as instant messaging and file sharing. Normally, the ports of such services should remain blocked for users who do not need them.'));
            ?>
        </td>
    </tr>
    <?php
}
PrintRestrictedIPsForm ()
Displays restricted IPs form.
This list is the non-!-prefixed IPs in pf.restrictedips.
Definition at line 259 of file conf.php.
References $Row, $View, _HELPBOX(), _TITLE(), action, maxlength, method, and PrintHelpBox().
{
    global $View, $Row;
    $class= $Row++ % 2 == 0 ? 'evenline' : 'oddline';
    ?>
    <tr class="<?php echo $class ?>">
        <td class="title">
            <?php echo _TITLE('Restricted IPs').':' ?>
        </td>
        <td>
            <form action="<?php echo $_SERVER['PHP_SELF'] ?>" method="post">
                <input style="display:none;" type="submit" name="Add" value="<?php echo _CONTROL('Add') ?>"/>
                <select name="RestrictedIPs[]" multiple style="width: 200px; height: 100px;">
                    <?php
                    if ($View->Controller($ips, 'GetRestrictedIps')) {
                        foreach ($ips as $ip) {
                            ?>
                            <option value="<?php echo $ip ?>"><?php echo $ip ?></option>
                            <?php
                        }
                    }
                    ?>
                </select>
                <input type="submit" name="Delete" value="<?php echo _CONTROL('Delete') ?>"/><br />
                <input type="text" name="RestrictedIPToAdd" style="width: 200px;" maxlength="18"/>
                <input type="submit" name="Add" value="<?php echo _CONTROL('Add') ?>"/>
            </form>
        </td>
        <td class="none">
            <?php
            PrintHelpBox(_HELPBOX('This is the opposite of Privileged IPs. You can enter IP ranges as well, e.g. 192.168.1.0/24.'));
            ?>
        </td>
    </tr>
    <?php
}
Variable Documentation
$Row = 1
Definition at line 368 of file conf.php.