ComixWall ISG Administration Interface: View/pf/web/global_config/pfhostsedit.php File Reference
View » pf » web » global_config
pfhostsedit.php File Reference
Functions
set_pfhost_writeable ($name)
set_pfhost_nonwritable ($name)
Variables
$sql = "('". sqlite_escape_string($_POST['name']). "', '". sqlite_escape_string($_POST['connect']). "', "
$results = sqlite_query("select * from pfhosts where name='". sqlite_escape_string($_POST['name']) ."'", $db)
$pfhost = sqlite_fetch_array($results, SQLITE_ASSOC)
$db = sqlite_popen($database)
$active = "pfw"
$style
$result = implode("\n", $Output)
Function Documentation
set_pfhost_nonwritable ($ name)
Definition at line 55 of file pfhostsedit.php.
References $database, $db, and $results.
{
  global $database;
  $db  = sqlite_popen($database);
  $results = sqlite_query("select * from pfhosts where name='". sqlite_escape_string($name) ."'", $db);
  $pfhost_check = sqlite_fetch_array($results, SQLITE_ASSOC);
  if ($pfhost_check['can_connect'] == "true") {
    $results = sqlite_query("update pfhosts set can_connect='false' where name='". sqlite_escape_string($name) ."'", $db);
  }
  sqlite_close($db);
}
set_pfhost_writeable ($ name)
Definition at line 42 of file pfhostsedit.php.
References $database, $db, and $results.
{
  global $database;
  $db  = sqlite_popen($database);
  $results = sqlite_query("select * from pfhosts where name='". sqlite_escape_string($name) ."'", $db);
  $pfhost_check = sqlite_fetch_array($results, SQLITE_ASSOC);
  if ($pfhost_check['can_connect'] == "false") {
    $results = sqlite_query("update pfhosts set can_connect='true' where name='". sqlite_escape_string($name) ."'", $db);
  }
  sqlite_close($db);
}
Variable Documentation
$active = "pfw"
Definition at line 108 of file pfhostsedit.php.
$db = sqlite_popen($database)
Definition at line 101 of file pfhostsedit.php.
$pfhost = sqlite_fetch_array($results, SQLITE_ASSOC)
Definition at line 88 of file pfhostsedit.php.
$result = implode("\n", $Output)
Definition at line 163 of file pfhostsedit.php.
Referenced by Dansguardian::CreateNewGroup(), Dansguardian::GetExts(), and RRDTool::graph().
$results = sqlite_query("select * from pfhosts where name='". sqlite_escape_string($_POST['name']) ."'", $db)
Definition at line 87 of file pfhostsedit.php.
$sql = "('". sqlite_escape_string($_POST['name']). "', '". sqlite_escape_string($_POST['connect']). "', "
Definition at line 78 of file pfhostsedit.php.
$style
Initial value:
 <<<EOS
tr {text-align: left; }
.right {text-align: right; }
EOS
Definition at line 109 of file pfhostsedit.php.