ComixWall ISG Administration Interface: View/pf/web/global_config/pfhosts.php File Reference
View » pf » web » global_config
pfhosts.php File Reference
Variables
$db = sqlite_popen($database)
$results = sqlite_query("select * from pfhosts", $db)
$active = "pfw"
$style
print $pfhost ['id']
print $_SERVER['PHP_SELF'] del
Variable Documentation
$active = "pfw"
Definition at line 55 of file pfhosts.php.
$db = sqlite_popen($database)
Definition at line 47 of file pfhosts.php.
Referenced by set_pfhost_nonwritable(), and set_pfhost_writeable().
print $pfhost['id']
Definition at line 85 of file pfhosts.php.
$results = sqlite_query("select * from pfhosts", $db)
Definition at line 48 of file pfhosts.php.
Referenced by set_pfhost_nonwritable(), and set_pfhost_writeable().
$style
Initial value:
 <<<EOS
th {padding: 0 2em; }
EOS
Definition at line 56 of file pfhosts.php.
print $_SERVER ['PHP_SELF'] del
Initial value:
". $pfhost['id'];?>" onclick="return confirm('Are you sure you want to delete this pfhost?')">delete</a></td>
  </tr>
<?php }
Definition at line 86 of file pfhosts.php.