ComixWall ISG Administration Interface: View/snortips/conf.basic.php File Reference
View » snortips
conf.basic.php File Reference
Functions
PrintKeywordsForm ()
Displays alert keywords.
Variables
$CustomFunc = 'PrintKeywordsForm'
Function Documentation
PrintKeywordsForm ()
Displays alert keywords.
Definition at line 38 of file conf.basic.php.
References $Class, $View, _HELPBOX2(), _TITLE2(), action, maxlength, method, and PrintHelpBox().
{
    global $View, $Class;
    ?>
    <tr class="<?php echo $Class ?>">
        <td class="title">
            <?php echo _TITLE2('Keywords').':' ?>
        </td>
        <td>
            <?php
            $View->Controller($keywords, 'GetKeywords');
            ?>
            <form action="<?php echo $_SERVER['PHP_SELF'] ?>" method="post">
                <input style="display:none;" type="submit" name="Add" value="<?php echo _CONTROL('Add') ?>"/>
                <select name="Keywords[]" multiple style="width: 200px; height: 100px;">
                    <?php
                    foreach ($keywords as $key) {
                        ?>
                        <option value="<?php echo $key ?>"><?php echo $key ?></option>
                        <?php
                    }
                    ?>
                </select>
                <input type="submit" name="Delete" value="<?php echo _CONTROL('Delete') ?>"/><br />
                <input type="text" name="KeywordToAdd" style="width: 200px;" maxlength="50"/>
                <input type="submit" name="Add" value="<?php echo _CONTROL('Add') ?>"/>
            </form>
        </td>
        <td class="none">
            <?php
            PrintHelpBox(_HELPBOX2('These are keywords to match in alert messages. If alerts contain such words, the IP in that alert will be blocked.'));
            ?>
        </td>
    </tr>
    <?php
}
Variable Documentation
$CustomFunc = 'PrintKeywordsForm'
Definition at line 84 of file conf.basic.php.