ComixWall ISG Administration Interface: View/squid/conf.php File Reference
View » squid
conf.php File Reference
Functions
PrintSquidIPPortForm ()
Prints Squid interface change form as IP:Port and lets the user modify it.
Variables
$CustomFunc = 'PrintSquidIPPortForm'
Function Documentation
PrintSquidIPPortForm ()
Prints Squid interface change form as IP:Port and lets the user modify it.
Definition at line 40 of file conf.php.
References $Class, $View, _HELPBOX2(), _TITLE2(), action, maxlength, method, and PrintHelpBox().
{
    global $View, $Class;
    ?>
    <tr class="<?php echo $Class ?>">
        <td class="title">
            <?php echo _TITLE2('Proxy IP:Ports').':' ?>
        </td>
        <td>
            <form action="<?php echo $_SERVER['PHP_SELF'] ?>" method="post">
                <input style="display:none;" type="submit" name="Add" value="<?php echo _CONTROL('Add') ?>"/>
                <select name="Interfaces[]" multiple style="width: 200px; height: 50px;">
                    <?php
                    if ($View->Controller($ifs, 'GetIpPort')) {
                        foreach ($ifs as $if) {
                            ?>
                            <option value="<?php echo $if ?>"><?php echo $if ?></option>
                            <?php
                        }
                    }
                    ?>
                </select>
                <input type="submit" name="Delete" value="<?php echo _CONTROL('Delete') ?>"/><br />
                <input type="text" name="InterfaceToAdd" style="width: 200px;" maxlength="21"/>
                <input type="submit" name="Add" value="<?php echo _CONTROL('Add') ?>"/>
            </form>
        </td>
        <td class="none">
            <?php
            PrintHelpBox(_HELPBOX2('This is the IP and port over which the proxy accepts connections.'));
            ?>
        </td>
    </tr>
    <?php
}
Variable Documentation
$CustomFunc = 'PrintSquidIPPortForm'
Definition at line 85 of file conf.php.