ComixWall ISG Administration Interface: View/system/conf.basic.php File Reference
View » system
conf.basic.php File Reference
Basic system-wide configuration.
Functions
PrintDateTimeForm ($remotetime)
Displays a form to change system datetime.
Variables
$RemoteTime = implode("\n", $Output)
Detailed Description
Basic system-wide configuration.
Definition in file conf.basic.php.
Function Documentation
PrintDateTimeForm ($ remotetime)
Displays a form to change system datetime.
Definition at line 42 of file conf.basic.php.
References $_SESSION, $confirm, $TimeServer, _HELPBOX(), _NOTICE(), _TITLE(), action, hour, maxlength, method, and PrintHelpBox().
{
    global $TimeServer;
    if ($_SESSION['TimeServer']) {
        $TimeServer= $_SESSION['TimeServer'];
    }
    $day= date('d');
    $month= date('m');
    $year= date('y');
    $hour= date('H');
    $min= date('i');
    $confirm= _NOTICE('Are you sure you want to set the date?');
    ?>
    <tr class="oddline">
        <td class="title">
            <?php echo _TITLE('Time server').':' ?>
        </td>
        <td>
            <form action="<?php echo $_SERVER['PHP_SELF'] ?>" method="post">
                <input type="text" name="TimeServer" style="width: 200px;" maxlength="50" value="<?php echo $TimeServer ?>" />
                <input type="submit" name="Display" value="<?php echo _CONTROL('Display') ?>"/>
                <input type="submit" name="Apply" value="<?php echo _CONTROL('Apply') ?>" onclick="return confirm('<?php echo $confirm ?>')"/>
                <?php
                if (isset($remotetime)) {
                    echo '<br />'.$remotetime;
                }
                ?>
            </form>
        </td>
        <td class="none">
            <?php
            PrintHelpBox(_HELPBOX('Usually the network time daemon adjusts the system clock according to Internet time servers gradually. But if the clock is too out of sync with the time servers, you are advised to set the system clock to Internet time manually. You can use your own time server if you like.'));
            ?>
        </td>
    </tr>
    <tr class="evenline">
        <td class="title">
            <?php echo _TITLE('Date').':' ?>
        </td>
        <td>
            <form action="<?php echo $_SERVER['PHP_SELF'] ?>" method="post">
                <input type="text" name="Day" style="width: 20px;" maxlength="2" value="<?php echo $day ?>" />.
                <input type="text" name="Month" style="width: 20px;" maxlength="2" value="<?php echo $month ?>" />.
                <input type="text" name="Year" style="width: 20px;" maxlength="2" value="<?php echo $year ?>" /> -
                <input type="text" name="Hour" style="width: 20px;" maxlength="2" value="<?php echo $hour ?>" />:
                <input type="text" name="Minute" style="width: 20px;" maxlength="2" value="<?php echo $min ?>" />
                <input type="submit" name="Apply" value="<?php echo _CONTROL('Apply') ?>" onclick="return confirm('<?php echo $confirm ?>')"/>
            </form>
        </td>
        <td class="none">
            <?php
            PrintHelpBox(_HELPBOX('You can set the system clock here. Format is day.month.year-hour:minute.
<b>You must be very careful when setting the system clock, significant hops in system time may cause system malfunction.</b>'));
            ?>
        </td>
    </tr>
    <?php
}
Variable Documentation
$RemoteTime = implode("\n", $Output)
Definition at line 123 of file conf.basic.php.