ComixWall ISG Administration Interface: View/dansguardian/blacklists.php File Reference
View » dansguardian
blacklists.php File Reference
Classes
class Blacklists
Functions
PrintSiteCategorySearchForm ($site)
Displays a form to search sites/urls in black lists.
Variables
$View = new Blacklists()
$SearchSite = $_SESSION[$View->Model]['SearchSite']
Appends (prefixes) blacklist category descriptions table to cats page help boxes.
$LogSize = $Output[0]
$Logs = unserialize($Output[0])
$LineCount = $StartLine + 1
Function Documentation
PrintSiteCategorySearchForm ($ site)
Displays a form to search sites/urls in black lists.
Parameters:
[in] $site Search string.
Definition at line 61 of file blacklists.php.
References _HELPBOX2(), _TITLE(), action, maxlength, method, and PrintHelpBox().
{
    ?>
    <table>
        <tr>
            <td>
                <form action="<?php echo $_SERVER['PHP_SELF'] ?>" method="post">
                    <?php echo _TITLE('Search site').': ' ?>
                    <input type="text" name="SearchSite" style="width: 200px;" maxlength="100" value="<?php echo $site ?>"/>
                    <input type="submit" name="Search" value="<?php echo _CONTROL('Search') ?>"/>
                </form>
            </td>
            <td>
                <?php
                PrintHelpBox(_HELPBOX2('Here you can search sites and urls in category listings. Regexp below can help you further refine your search.'));
                ?>
            </td>
        </tr>
    </table>
    <?php
}
Variable Documentation
$LineCount = $StartLine + 1
Definition at line 199 of file blacklists.php.
$Logs = unserialize($Output[0])
Definition at line 197 of file blacklists.php.
$LogSize = $Output[0]
Definition at line 185 of file blacklists.php.
$SearchSite = $_SESSION[$View->Model]['SearchSite']
Appends (prefixes) blacklist category descriptions table to cats page help boxes.
Parameters:
[out] $msg Help box string to append to.
Definition at line 163 of file blacklists.php.
$View = new Blacklists()
Definition at line 55 of file blacklists.php.